### ISSUE TITLE
Compose options are not being obeyed

### ISSUE THREAD

**Issue by ProjectVRD** [pi-hole/docker-pi-hole#1000]
This is a: Bug

## Details

WEBPASSWORD and volumes entries in the docker compose script are not being implemented. No data is placed in to the existing directories that are entered as volume options as seen below, WEBPASSWORD entry is not being set as entered into option when the container has been created.

## Related Issues
- [ ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: DSM 7 
  * Hardware: Synology DS220+ 
  * Kernel Architecture: 
  * Docker Install Info and version: 
    - Software source: OS provided package 
    - Supplimentary Software: portainer - latest
  * Hardware architecture: 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

```yml
version: '3'

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp # Only required if you are using Pi-hole as your DHCP server
      - 34567:80/tcp
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
      - WEBPASSWORD=passwordplacedhere
    # Volumes store your data between container upgrades
    volumes:
      - /volume1/docker/pihole:/pihole
      - /volume1/docker/dnsmasq.d:/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
    restart: unless-stopped
```

3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
