### ISSUE TITLE
'sudo: unable to send audit message: Operation not permitted' with podman container

### ISSUE THREAD

**Issue by strzinek** [pi-hole/docker-pi-hole#1007]
This is a: Bug

## Details
When running pi-hole as a podman container, the host log gets filled up with this error message: 
"sudo: unable to send audit message: Operation not permitted"

## How to reproduce the issue 
I am running pi-hole container with podman-compose on fedora-server 35 using standard docker-compose.yml listed below.

1. Environment data
  * Operating System: Fedora 35
  * Hardware: PC
  * Kernel Architecture: x86/amd64
  * Podman Info: 
    - Software source: OS provided package

2. docker-compose.yml contents:
```
version: "3"

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "192.168.1.1:53:53/tcp"
      - "192.168.1.1:53:53/udp"
      - "192.168.1.1:80:80/tcp"
    environment:
      TZ: 'Europe/Prague'
      WEBPASSWORD: 'admin_pwd'
    volumes:
      - 'pihole-cfg:/etc/pihole'
      - 'pihole-dnsmasq:/etc/dnsmasq.d'
    restart: unless-stopped
```
