### ISSUE TITLE
While executing: attempt to write a readonly database Added 0 out of 1 domains

### ISSUE THREAD

**Issue by g0Idfinger** [pi-hole/docker-pi-hole#1012]
This is a: Run Issue 

## Details

<img width="234" alt="image" src="https://user-images.githubusercontent.com/60414807/156935933-130066b7-4f0f-41ea-bea2-3747f77d5aaa.png">
I am running the latest tag and receive the error above.
## Related Issues
- [ ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu 
  * Hardware: PC
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: Docker version 20.10.12, build e91ed57
    - Software source: official docker-ce 
    - Supplimentary Software: traefic, socket-proxy 
  * Hardware architecture: x86 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
version: "3.9"

networks:
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24

  traefik:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    container_name: traefik
    image: traefik:latest
    command: # CLI arguments
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=true
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
      # Allow these IPs to set the X-Forwarded-* headers - Cloudflare IPs: https://www.cloudflare.com/ips/
      - --entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22
      - --entryPoints.traefik.address=:8080
      - --api=true
      # - --api.insecure=true
      - --api.dashboard=true
      - --log=true
      - --log.level=WARN # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=false
      - --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      - --accessLog.filters.statusCodes=400-499
      - --providers.docker=true
      # - --providers.docker.endpoint=unix:///var/run/docker.sock # Use Docker Socket Proxy instead for improved security
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      # - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.$DOMAINNAME`)
      - --providers.docker.exposedByDefault=false
      # - --entrypoints.https.http.middlewares=chain-authelia@file
      - --entrypoints.https.http.tls.options=tls-opts@file
      # Add dns-cloudflare as default certresolver for all services. Also enables TLS and no need to specify on individual services
      - --entrypoints.https.http.tls.certresolver=dns-cloudflare
      - --entrypoints.https.http.tls.domains[0].main=$DOMAINNAME
      - --entrypoints.https.http.tls.domains[0].sans=*.$DOMAINNAME
      # - --entrypoints.https.http.tls.domains[1].main=$DOMAIN # Pulls main cert for second domain
      # - --entrypoints.https.http.tls.domains[1].sans=*.$DOMAIN # Pulls wildcard cert for second domain
      - --providers.docker.network=t2_proxy
      - --providers.docker.swarmMode=false
      - --providers.file.directory=/rules # Load dynamic configuration from one or more .toml or .yml files in a directory
      # - --providers.file.filename=/path/to/file # Load dynamic configuration from a file
      - --providers.file.watch=true # Only works on top level files in the rules folder
      # - --certificatesResolvers.dns-cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory # LetsEncrypt Staging Server - uncomment when testing
      - --certificatesResolvers.dns-cloudflare.acme.email=$CLOUDFLARE_EMAIL
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.delayBeforeCheck=90 # To delay DNS check and reduce LE hitrate
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.254 # You can specify a static IP
      socket_proxy:
    ports:
      # https://www.reddit.com/r/docker/comments/c1wrep/traefik_reverse_proxy_question_docker_overlay/
      - target: 80
        published: 80
        protocol: tcp
        mode: host
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - $DOCKERDIR/appdata/traefik2/rules:/rules # file provider directory
      # - /var/run/docker.sock:/var/run/docker.sock:ro # Use Docker Socket Proxy instead for improved security
      - $DOCKERDIR/appdata/traefik2/acme/acme.json:/acme.json # cert location - you must touch this file and change permissions to 600
      - $DOCKERDIR/appdata/traefik2/traefik.log:/traefik.log # for fail2ban - make sure to touch file before starting container
    environment:
      - CF_API_EMAIL_FILE=/run/secrets/cloudflare_email
      - CF_API_KEY_FILE=/run/secrets/cloudflare_api_key
    secrets:
      - cloudflare_email
      - cloudflare_api_key
      - htpasswd
    labels:
      - "traefik.enable=true"
      # HTTP-to-HTTPS Redirect
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # HTTP Routers
      - "traefik.http.routers.traefik-rtr.entrypoints=https"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.$DOMAINNAME`)"
      ## Services - API
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      ## Middlewares
      - "traefik.http.routers.traefik-rtr.middlewares=chain-authelia@file"

  pihole:
    #<<: *default-tz-puid-pgid
    container_name: pihole
    domainname: domain.local
    hostname: pihole
#    image: pihole/pihole:dev
    image: pihole/pihole:latest
    shm_size: '2g'
    depends_on:
      - dhcphelper
    networks:
      t2_proxy:
        ipv4_address: $PIHOLE_TRAEFIK_IP
    ports:
      - "$SERVER_IP:53:53/tcp"
      - "$SERVER_IP:53:53/udp"
    restart: always
    volumes:
      - $DOCKERDIR/appdata/pihole/pihole:/etc/pihole
      - $DOCKERDIR/appdata/pihole/pihole.log:/var/log/pihole.log
      - $DOCKERDIR/appdata/pihole/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    environment:
     # - FTLCONF_REPLY_ADDR4=$SERVER_IP
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=pihole.$DOMAINNAME
      - VIRTUAL_PORT=80
      - TZ=$TZ
      - WEBPASSWORD=
      - PIHOLE_DNS_=192.168.90.251#5054
      - WEBTHEME=default-dark
      - DNSMASQ_LISTENING=all
    labels:
      - "traefik.enable=true"
#      - "traefik.backend=pihole"
#      - "traefik.port=80"
     ## HTTP Routers
      - "traefik.http.routers.pihole-rtr.entrypoints=https"
      - "traefik.http.routers.pihole-rtr.rule=Host(`pihole.$DOMAINNAME`)"
      - "traefik.http.routers.pihole-rtr.tls=true"
#      - "traefik.frontend.rule=HostRegexp:pihole.$DOMAINNAME,{catchall:.*}"
#      - "traefik.frontend.priority=1"
      ## Middlewares
      - "traefik.http.routers.pihole-rtr.middlewares=chain-authelia@file,add-pihole"
      - "traefik.http.middlewares.add-pihole.addPrefix.prefix=/admin"
      # HTTP Services
      - "traefik.http.routers.pihole-rtr.service=pihole-svc"
      - "traefik.http.services.pihole-svc.loadbalancer.server.port=80"

  dhcphelper:
    build: ./dhcp-helper
    container_name: dhcp-helper
    restart: always
    network_mode: "host"
    command: -s $PIHOLE_TRAEFIK_IP
    cap_add:
      - NET_ADMIN

  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:latest
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.251

```

3. any additional info to help reproduce
If I run ```docker exec pihole chown -R www-data:pihole /etc/pihole``` then it works for a while if I force a gravity update, the error comes back.
screenshots of permissions during error:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/60414807/156936708-7d64d611-1050-482c-8957-81f7007cb062.png">
Screenshot of permissions the fix error after running the above command:
<img width="751" alt="image" src="https://user-images.githubusercontent.com/60414807/156936760-706809e7-2b02-473c-8f50-17831065b222.png">

## These common fixes didn't work for my issue

- [X ] I have tried removing/destroying my container, and re-creating a new container
- [ X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ X] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [!!!! ] I have tried running without my volume data mounts to eliminate volumes as the cause
This fixes it if I remove the ``` - $DOCKERDIR/appdata/pihole/pihole:/etc/pihole``` Volume
If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
