### ISSUE TITLE
Issue with using FTLCONF_{setting} empty environment variables

### ISSUE THREAD

**Issue by Apollorion** [pi-hole/docker-pi-hole#1018]
This is a: Bug

## Details

When I run the latest container using `FTLCONF_` environment variables a line gets added that the UI says it cannot parse.

For example, if I add `FTLCONF_BLOCKINGMODE=NODATA` then the `pihole-FTL.conf` file that gets generated looks like this:

```
#; Pi-hole FTL config file
#; Comments should start with #; to avoid issues with PHP and bash reading this file
declare=-x FTLCONF_BLOCKINGMODE=""
BLOCKINGMODE=NODATA
```

When I go into the UI and go to settings I see:

```
There was a problem applying your settings.
Debugging information:
PHP error (2): syntax error, unexpected '=' in /etc/pihole/pihole-FTL.conf on line 3 in /var/www/html/admin/scripts/pi-hole/php/FTL.php:23
```

I am using a helm chart, and I have verified it is not doing anything other than setting the FTLCONF environment variable because when I describe the pod I see:

```
    Environment:
      WEB_PORT:              80
      VIRTUAL_HOST:          pi.hole
      WEBPASSWORD:           <set to the key 'password' in secret 'pihole-password'>  Optional: false
      FTLCONF_BLOCKINGMODE:  NODATA
      FTLCONF_REPLY_ADDR4:   192.168.86.240
```

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu 21.04 
  * Hardware: PC
  * Kernel Architecture: x86
  * Docker Install Info and version: 
    - Software source: os provided package
    - Supplimentary Software: kubernetes 1.23
  * Hardware architecture: x86

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
I am using this helm chart: https://github.com/MoJo2600/pihole-kubernetes/
With the following values
```yaml
    DNS1: ~
    DNS2: ~

    podDnsConfig:
      enabled: false

    persistentVolumeClaim:
      enabled: true
      storageClass: "local-storage-pihole"

    serviceWeb:
      annotations:
          metallb.universe.tf/address-pool: default
          metallb.universe.tf/loadBalancerIPs: "192.168.86.240"
      type: LoadBalancer

    serviceDns:
      annotations:
        metallb.universe.tf/address-pool: default
        metallb.universe.tf/allow-shared-ip: "serviceDns"
        metallb.universe.tf/loadBalancerIPs: "192.168.86.250"
      type: LoadBalancer

    privileged: "true"

    extraEnvVars:
      FTLCONF_REPLY_ADDR4: 192.168.86.240
      FTLCONF_BLOCKINGMODE: "NODATA"

    resources:
      requests:
        cpu: "1000m"
        memory: "4Gi"
```
4. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
