### ISSUE TITLE
dnsmasq: process is missing required capability NET_ADMIN

### ISSUE THREAD

**Issue by balucio** [pi-hole/docker-pi-hole#1026]
The latest and 2022 pi-hole dockers images will exit reporting
`dnsmasq: process is missing required capability NET_ADMIN`
following the relevant configuration on `docker-compose`

```
 environment:
      TZ: "Europe/Rome"
      WEBPASSWORD: "***************"
      ServerIP: "192.168.1.248"
      TEMPERATUREUNIT: "c"
      DNS_FQDN_REQUIRED: "true"
      IPv6: "false"
      DHCP_IPv6: "false"
      DHCP_ACTIVE: "true"
      DHCP_START: "192.168.1.2"
      DHCP_END: "192.168.1.200"
      DHCP_ROUTER: "192.168.1.1"
      DHCP_LEASETIME: 3
      DHCP_rapid_commit: "true"
      DNSMASQ_LISTENING: "all"

    cap_add:
      - NET_ADMIN
```
This is a: Bug

## Details
The old docker image `pihole/pihole:2021.11` works well with the same docker-compose

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar _[938](https://github.com/pi-hole/docker-pi-hole/issues/938)_
