### ISSUE TITLE
Latest docker release (2022.04) breaks DNS resolution on armv7

### ISSUE THREAD

**Issue by Willsr71** [pi-hole/docker-pi-hole#1035]
This is a: Bug

The latest docker image does not correctly resolve queries. The Query log spits out errors for DNSSEC entries of `BOGUS (DNSSEC signature expired)` and `BOGUS (DNSSEC sig not yet valid)`. This is correlated by the log spitting out these two lines on a loop:
```
sudo: error initializing audit plugin sudoers_audit
sudo: unable to get time of day: Operation not permitted
```

Reverting to version 2022.02.1 fixes the issue.

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu 20.04
  * Hardware: Raspberry Pi 4b+
  * Kernel Architecture: armv7
  * Docker Install Info and version: 
    - Software source: official docker
    - Supplimentary Software: none
  * Hardware architecture: x86_64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
    pihole:
        image: pihole/pihole:2022.01.1
        #build: "./images/pihole-speedtest"
        hostname: "pihole"
        ports:
            - "53:53"
            - "53:53/udp"
            - "67:67/udp"
            - "80:80"
            - "443:443"
        volumes:
            - /home/pi/pihole/config:/etc/pihole
            - /home/pi/pihole/dnsmasq:/etc/dnsmasq.d
        cap_add:
            - NET_ADMIN
        dns:
            - 127.0.0.1
            - 1.1.1.1
        restart: "always"
        environment:
            TZ: "America/New_York"
```

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [X] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
