### ISSUE TITLE
2022.04 Image Fails on Docker

### ISSUE THREAD

**Issue by intersectRaven** [pi-hole/docker-pi-hole#1036]
This is a: Bug

## Details
Version 2022.04 image release fails on docker.
![image](https://user-images.githubusercontent.com/229447/161359998-58f5b3dc-f520-4892-acd9-dbde52c9fa2a.png)

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Arch Linux
  * Hardware: VPS
  * Kernel Architecture: x64
  * Docker Install Info and version: 
    - Software source: official arch
    - Supplimentary Software: 
  * Hardware architecture: x64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
pihole:
      image: pihole/pihole
      container_name: pihole
      environment:
         DNS1: '8.8.8.8'
         DNS2: '8.8.4.4'
         TZ: "Asia/Manila"
      ports:
         - 53:53/tcp
         - 53:53/udp
         - 8080:80/tcp
      restart: unless-stopped
```
4. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
