### ISSUE TITLE
2022.04.1 (Using image 334d46d0f4bd) not working on Raspbian Buster

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/docker-pi-hole#1043]
For me 2022.04.1 (Using image 334d46d0f4bd) does not fix anything.
I can produce this debug log when I revert to 036a3f19f8be https://tricorder.pi-hole.net/HxlHpPSE/ 
Note that I'm on armhf.

On docker host:
```
❯ uname -a
Linux raspberrypidocker 5.10.103-v8+ #1529 SMP PREEMPT Tue Mar 8 12:26:46 GMT 2022 aarch64 GNU/Linux
```

_Originally posted by @Mellbourn in https://github.com/pi-hole/docker-pi-hole/issues/1035#issuecomment-1086621033_

**Comment by Mellbourn** [comment]
Same behavior as before. Log ends with
```
pihole        | [services.d] done.
pihole        | sudo: unable to get time of day: Operation not permitted
pihole        | sudo: error initializing audit plugin sudoers_audit
pihole        | sudo: unable to get time of day: Operation not permitted
pihole        | sudo: error initializing audit plugin sudoers_audit
[repeated]
```

**Comment by PromoFaux** [comment]
<strike>opened a new issue as something is off in your debug log, and I think it is either a different issue or a misconfiguration:

```
[i] Core: v5.9 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
```

That should be showing v5.9.1</strike>

Just realised you said you reverted. I'm not able to match those digest hashes to anything on docker hub? Where are you getting that from?

What does your run command/compose file look like?

Also, what is the output of:
```
docker run -it --rm --name=pitest pihole/pihole:2022.04.1
```

**Comment by Mellbourn** [comment]
currently working `docker-compose`:

```yml
services:

  pihole:
    container_name: pihole
    image: pihole/pihole@sha256:60a9127372b0f7bb4b5eb09bc95e2735eb7b237999acf4bb079eb14b0f14632e
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Stockholm'
      WEBPASSWORD: 'not-my-real-password'
      # this is still needed to get pi.hole to work
      ServerIP: '192.168.211.11'
      DNSSEC: 'true'
    # this makes the name of the docker image not be a random hash. This name is recognized only in the docker host environment
    hostname: 'pi-hole-in-docker'
    # Volumes store your data between container upgrades
    volumes:
      - './pi-hole/etc-pihole/:/etc/pihole/'
      - './pi-hole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # these are supposedly needed, otherwise you will get 127.0.0.11 problems https://github.com/pi-hole/docker-pi-hole/issues/410#issuecomment-460515706 - still doesn't work
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```
