### ISSUE TITLE
`sudo: effective uid is not 0` error in logs, but filesystem containing `/var/lib/docker` is not mounted nosuid

### ISSUE THREAD

**Issue by duckpuppy** [pi-hole/docker-pi-hole#1069]
I've been struggling to get pihole working in docker. I think I've got everything working mostly, but I can't change or save any settings, and I get the `sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?` error in the logs when I attempt to change or save settings. I've tried running with `PIHOLE_UID` and `PIHOLE_GID` set to 0, `DNSMASQ_USER` set to `root`, nothing works. I'm running on a Debian 11 host.

`/var/lib/docker` is in the `/` filesystem mount, which is definitely not mounted with `nosuid`, and not an NFS mount. I am using the overlay2 filesystem driver for docker, if that makes a difference.

**Comment by duckpuppy** [comment]
A bit more info:
Docker server version: 20.10.13
PiHole docker image: 2022.04.2 (latest)

**Comment by rdwebdesign** [comment]
Another user had the same problem recently:
https://github.com/pi-hole/docker-pi-hole/issues/1012#issuecomment-1077982306

This means your filesystem was mounted using 'nosuid' option. You need to change this.

**Comment by duckpuppy** [comment]
It's not mounted nosuid. It's the root filesystem, and I actually have suid binaries that I use outside docker on the same filesystem.

**Comment by rdwebdesign** [comment]
I'm not sure what is different in your case, but this answer might help:

https://unix.stackexchange.com/questions/546822/why-does-sudo-fail-inside-docker-complaining-about-nosuid#546823

**Comment by duckpuppy** [comment]
That's still about nosuid mounted filesystems, which doesn't apply in this case.

**Comment by duckpuppy** [comment]
```
$ docker info | grep "Docker Root"
 Docker Root Dir: /var/lib/docker
$ df /var/lib/docker
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/sdb1      ext4  823G  313G  469G  41% /
$ mount | grep nosuid
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=8184452k,nr_inodes=2046113,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1640196k,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
/dev/sdc2 on /media/external type fuseblk (rw,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=1640192k,nr_inodes=410048,mode=700,uid=1000,gid=1000)
```

**Comment by dschaper** [comment]
What is your docker-compose.yml or docker run command for the container?

**Comment by duckpuppy** [comment]
```
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "54:53/tcp"
      - "54:53/udp"
    secrets:
      - pihole_password
    environment:
      TZ: $TZ
      WEBPASSWORD_FILE: /run/secrets/pihole_password
      PIHOLE_DNS_: unbound
      DNSSEC: 'false'
      WEBTHEME: default-dark
    volumes:
      - '/srv/etc/pihole/config:/etc/pihole/'
      - '/srv/etc/pihole/dnsmasq.d:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    networks:
      traefik:
    labels:
      diun.enable: true
      traefik.enable: true
      traefik.http.routers.pihole.entrypoints: web
      traefik.http.services.pihole.loadbalancer.server.port: 80
      traefik.http.services.pihole.loadbalancer.server.scheme: http
```

It's part of a MUCH larger stack, so I'm posting the pihole service snippet.

I'm binding the pihole DNS port to 54 on the host while I test (I have unbound running on 53 already, I'll stop it and change pihole to 53 if I get it working).
