### ISSUE TITLE
Release 2022.04.2 and up: Bash not found

### ISSUE THREAD

**Issue by d8v8b** [pi-hole/docker-pi-hole#1078]
Sorry, unable to provide versions or debug token due to nature of bug.

### Platform

- OS and version:  Artix 5.17.3-zen1-1-zen

- Platform:  Docker

### Expected behavior

The Pi-hole Docker container starts fully.

### Actual behavior / bug

The image bootloops because bash is not found.

### Steps to reproduce

1. Copy-paste the latest docker-compose.yml.example
2. docker-compose up
3. See error in log output

### Screenshots

`docker-compose up` log
![image](https://user-images.githubusercontent.com/95189311/164967847-305e089d-a171-4cab-8695-ea8033d3fd44.png)

`ls /bin`
![image](https://user-images.githubusercontent.com/95189311/164966794-9990e155-f333-476e-89d2-bcd4ac8f225a.png)

### Additional context

This bug occurs in releases 2022.04.2 to latest, and dev.
The bug does *not* occur in 2022.04.2beta and below, and nightly.

I was not able to use `ls` within the container. I used `docker cp pihole:/ pihole-contents`, and then did `ls pihole-contents/bin`.

The /var/log directory seems to only show the package install log from build time.

**Comment by dschaper** [comment]
Can you post your exact docker-compose.yaml please?

Bash is definitely in the image, and `2022.04.2` is the same image as `2022.04.2beta`. It was just retagged.

**Comment by d8v8b** [comment]
```yaml
version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "127.0.0.10:80:80/tcp"  # changed to avoid collision with reverse proxy
    environment:
      TZ: 'America/Chicago'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped # Recommended but not required (DHCP needs NET_ADMIN)
```
