### ISSUE TITLE
Password change through Docker env variable is ignored

### ISSUE THREAD

**Issue by shaderecker** [pi-hole/docker-pi-hole#1087]
This is a: **Bug**  

## Details

When I want to change pihole web password through the `WEBPASSWORD` env variable after the container was first created, this is currently not working as expected.
I can see that Docker picked up the change when I do a `docker inspect pihole` after the password env var change and a container restart:
```
"Env": [
                "WEBPASSWORD=newpassword",
```
However the webinterface of pihole is still working with the old password!

Looking into the container logs with `docker logs pihole` I can see this line:
`::: Pre existing WEBPASSWORD found`
So it seems that the existing `WEBPASSWORD` variable is found in the `/home/pi/pihole/pihole/setupVars.conf` config file and it uses that instead of applying the new password from the Docker container env variable.

I would expect that the new password gets picked up from the Docker env variable at container start.

As a workaround I can only delete the line with WEBPASSWORD from `/home/pi/pihole/pihole/setupVars.conf`.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Raspbian bullseye** 
  * Hardware: RasPi 3B+
  * Kernel Architecture: ArmV8 64bit
  * Docker Install Info and version: Docker version 20.10.15, build fd82621
    - Software source: official docker-ce
    - Supplimentary Software: 
  * Hardware architecture: ARMv8

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
Part of the Ansible playbook:
``` yaml
- name: Start/Update pihole container
  docker_container:
    name: pihole
    image: "pihole/pihole:2022.04.3"
    pull: yes
    restart_policy: unless-stopped
    env:
      TZ: "Europe/Berlin"
      FTLCONF_REPLY_ADDR4: "192.168.178.10"
      FTLCONF_REPLY_ADDR6: "fd00::10"
      WEBPASSWORD: "mysecretpassword"
      PIHOLE_DNS_: "1.1.1.1;2606:4700:4700::1111"
      DNSMASQ_LISTENING: "local"
      REV_SERVER: "true"
      REV_SERVER_DOMAIN: "fritz.box"
      REV_SERVER_TARGET: "192.168.178.1"
      REV_SERVER_CIDR: "192.168.178.0/24"
      FTLCONF_MAXDBDAYS: "180"
    dns_servers:
      - 127.0.0.1
      - "1.1.1.1"
    network_mode: host
    volumes:
      - "/home/{{ ansible_user }}/pihole/pihole/:/etc/pihole/"
      - "/home/{{ ansible_user }}/pihole/dnsmasq.d/:/etc/dnsmasq.d/"
    log_driver: json-file
    log_options:
      max-size: "10m"
      max-file: "5"

```
4. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
