### ISSUE TITLE
Broken Web UI (2022.04.3)

### ISSUE THREAD

**Issue by mrded** [pi-hole/docker-pi-hole#1093]
This is a: **Run Issue (running Pi-hole container failing) **  

## Details
I'm runing pi-hole on Raspberry pi 3 model b with docker-compose, and after updating an image from 2022.04.2 -> 2022.04.3 I noticed that Web UI stopped working correctly. (see screenshots)
![image](https://user-images.githubusercontent.com/347098/167663486-e68c027a-fee5-4243-8d16-c5e0e62f6270.png)
![image](https://user-images.githubusercontent.com/347098/167664681-c9ec7446-d8d5-46d1-85e4-eef7f83fb84f.png)
![image](https://user-images.githubusercontent.com/347098/167664845-7b87c32c-87f4-492d-bb1e-cca9cc1db4ee.png)

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

https://github.com/pi-hole/docker-pi-hole/issues/1046

## How to reproduce the issue 

1. Environment data
  * Operating System: Rasbian
  * Hardware: RasPi 3B
  * Kernel Architecture: armv7l
  * Docker Install Info and version: 
    - Software source: official docker-ce
    - Supplimentary Software: 
  * Hardware architecture: ARMv7

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2022.04.3
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/London'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

4. Run the thing
```
docker-compose pull
docker-compose up --force-recreate --build -d
```

5. If I roll back to `image: pihole/pihole:2022.04.2` web ui works just fine.

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
  - Old images work just fine.
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
