### ISSUE TITLE
Maximum number of concurrent DNS queries reached (max: 150)

### ISSUE THREAD

**Issue by Mellbourn** [pi-hole/docker-pi-hole#1098]
After upgrading to latest pi-holme docker today, it stopped working and, I keep getting this message in the logs:

`DNSMASQ_WARN Warning in dnsmasq core: Maximum number of concurrent DNS queries reached (max: 150)`

It seems to ignore the `RATE_LIMIT` setting in `docker-compose.yml`. I had already set it to `20000/60` and tried changing it to `0/0`. Neither seems to make any difference.

What is much worse, when I tried to go back to an earlier version, e.g. 2022.04.1, it remains in the same state, spamming the same `(max: 150)` message and not working. I have now got my network working again, by turning my router on and off again. When I turned off my router, the messages immediately stopped. So it is pretty obvious that it was the router that was doing there requests and being rate limited.

IMHO the whole rate limiting is a dangerous concept. What seems to happen for me, is that once my router happens to go over the rate limit, it gets blocked. But that just sends the router in a loop: it keeps requesting DNS and pi-hole keeps blocking it, making the network unusable.

This is a: Bug  

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Raspbian 
  * Hardware: RasPi 
  * Kernel Architecture: aaarch64 
  * Docker Install Info and version: 
    - Software source: 
    - Supplimentary Software: 
  * Hardware architecture: aarch64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

```yml
   pihole:
     container_name: pihole
     image: pihole/pihole:2022.04.1
     ports:
       - "53:53/tcp"
       - "53:53/udp"
       - "67:67/udp"
       - "80:80/tcp"
       - "443:443/tcp"
     environment:
       TZ: 'Europe/Stockholm'
       WEBPASSWORD: 'not-my-real-password'
       # this is still needed to get pi.hole to work
       ServerIP: '192.168.211.11'
       DNSSEC: 'true'
       RATE_LIMIT: '0/0'
     # this makes the name of the docker image not be a random hash. This name is recognized only in the docker host environment
     hostname: 'pi-hole-in-docker'
     # Volumes store your data between container upgrades
     volumes:
       - './pi-hole/etc-pihole/:/etc/pihole/'
       - './pi-hole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
     # these are supposedly needed, otherwise you will get 127.0.0.11 problems https://github.com/pi-hole/docker-pi-hole/issues/410#issuecomment-460515706 - still doesn't work
     dns:
       - 127.0.0.1
       - 1.1.1.1
     # Recommended but not required (DHCP needs NET_ADMIN)
     #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
     cap_add:
       - NET_ADMIN
     restart: unless-stopped
```

4. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
