### ISSUE TITLE
web gui not work on raspberry PI after 2022.01.1

### ISSUE THREAD

**Issue by jubilee2** [pi-hole/docker-pi-hole#1113]
the web ui not work since update to latest version 2022.05

This is a: Bug
<img width="1440" alt="Screen Shot 2022-06-07 at 2 03 53 PM" src="https://user-images.githubusercontent.com/5558405/172462859-79f2609f-a09a-4fc5-b2be-ace01ada55d2.png">

<img width="1440" alt="Screen Shot 2022-06-07 at 2 03 57 PM" src="https://user-images.githubusercontent.com/5558405/172462887-8f2397c2-ec86-4b6d-8c59-803da78d837c.png">

## Details
please see attachment when i update the docker image to latest version the web ui broken, i don't have more details,
i just changed the version in docker-compose.yml

## Related Issues
- [ ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: docker on Rasbian
  * Hardware: RasPi 4B
  * Kernel Architecture: ArmV7
  * Docker Install Info and version: 
    - Software source: official docker-ce
  * Hardware architecture: ARMv7

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2022.01.1
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8050:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'password'
      DNS1: 8.8.4.4

    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      # run `touch ./var-log/pihole.log` first unless you like errors
      - './var-log/pihole.log:/var/log/pihole.log'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)
```

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/

services:
  pihole:
    image: pihole/pihole:2022.05
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "8051:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'password'
      DNS1: 8.8.4.4

    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)
    restart: unless-stopped
```

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
