### ISSUE TITLE
Running PiHole on alternative web port does not work

### ISSUE THREAD

**Issue by MatejKovacic** [pi-hole/docker-pi-hole#1134]
This is a: **Bug**  

## Details
I have a Debian 11 server, running Nginx, Wireguard and OpenVPN. I have installed Pihole docker, however, I want that Pihole web interface is accessible on wg0 and tun0 interfaces only and on port 8080.

Here is my `docker-compose.yml` file:

```
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Ljubljana' #this is the time zone
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```
Web service is obviously running:

```
sudo netstat -pluton | grep docker
tcp        0      0 0.0.0.0:4430            0.0.0.0:*               LISTEN      1291/docker-proxy    off (0.00/0/0)
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1279/docker-proxy    off (0.00/0/0)
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      1317/docker-proxy    off (0.00/0/0)
udp        0      0 0.0.0.0:53              0.0.0.0:*                           1331/docker-proxy    off (0.00/0/0)
udp        0      0 0.0.0.0:67              0.0.0.0:*                           1303/docker-proxy    off (0.00/0/0)
```

But when I try to connect to this port, I get an error:
```
curl localhost:8080
curl: (56) Recv failure: Connection reset by peer
```

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Debian 11.3**
  * Hardware: PC (x86_64)
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: 
    - Software source: official docker-ce (docker-compose version 1.25.0; Docker version 20.10.5+dfsg1, build 55c4c88)
    - Supplimentary Software: /
  * Hardware architecture: 64-bit
  * 

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [X] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ X I have tried running without my volume data mounts to eliminate volumes as the cause
