### ISSUE TITLE
WEB_PORT not being applied?

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/docker-pi-hole#1139]
I'm actually experiencing something very similar. here's my docker-compose:
```yaml
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: proxy-dns
    restart: unless-stopped
    environment:
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query,https://9.9.9.9/dns-query,https://149.112.112.9/dns-query"

      # Listen on an unprivileged port
      - "TUNNEL_DNS_PORT=5053"

      # Listen on all interfaces
      - "TUNNEL_DNS_ADDRESS=0.0.0.0"
    ports:
      - "5053:5053/udp"
    networks:
       piholenet:
         ipv4_address: '172.19.0.3'

  pihole:
    container_name: pihole
    image: pihole/pihole:latest

    network_mode: host

    environment:
      TZ: 'America/Boise'
      WEB_PORT: 8081

    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
networks:
  piholenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
```

In this configuration, I'm forwarding through CloudFlared, I'm also running in host network mode because I'm doing DHCP and that was easiest.

I did create a static IP address through piholenet for CloudFlared, but pihole isn't using it, so I don't think it's related. WEB_PORT appears to be completely ignored, no matter what I set that value to, Pihole listens on port 80.

_Originally posted by @ryancastro in https://github.com/pi-hole/docker-pi-hole/issues/1134#issuecomment-1179623714_
