### ISSUE TITLE
pihole-FTL: no process found - With DNSMASQ_USER=root

### ISSUE THREAD

**Issue by marcosvrs** [pi-hole/docker-pi-hole#1146]
This is a: Bug

## Details

I tried to use DNSMASQ_USER=root, DNSMASQ_USER=myuser, and also PIHOLE_UID=0, PIHOLE_UID=1000.

All ends with the same log output:
```
pihole  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
pihole  | [s6-init] ensuring user provided files have correct perms...exited 0.
pihole  | [fix-attrs.d] applying ownership & permissions fixes...
pihole  | [fix-attrs.d] 01-resolver-resolv: applying... 
pihole  | [fix-attrs.d] 01-resolver-resolv: exited 0.
pihole  | [fix-attrs.d] done.
pihole  | [cont-init.d] executing container initialization scripts...
pihole  | [cont-init.d] 05-changer-uid-gid.sh: executing... 
pihole  | [cont-init.d] 05-changer-uid-gid.sh: exited 0.
pihole  | [cont-init.d] 20-start.sh: executing... 
pihole  |  ::: Starting docker specific checks & setup for docker pihole/pihole
pihole  | 
pihole  |   [i] Installing configs from /etc/.pihole...
pihole  |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
pihole  | Creating empty /etc/pihole/setupVars.conf file.
pihole  | Setting DNS servers based on PIHOLE_DNS_ variable
pihole  | Setting Web Theme based on WEBTHEME variable, using value default-auto
pihole  | Setting DHCP server
pihole  | ::: Assigning password defined by Environment Variable
pihole  |   [✓] New password set
pihole  |   [✓] Setting admin contact to pihole@marcosvr.com
pihole  | DNSMasq binding to default interface: eth0
pihole  | Added ENV to php:
pihole  |                       "TZ" => "Europe/Berlin",
pihole  |                       "PIHOLE_DOCKER_TAG" => "2022.07.1",
pihole  |                       "PHP_ERROR_LOG" => "/var/log/lighttpd/error-pihole.log",
pihole  |                       "ServerIP" => "0.0.0.0",
pihole  |                       "CORS_HOSTS" => "",
pihole  |                       "VIRTUAL_HOST" => "0.0.0.0",
pihole  | Using IPv4 and IPv6
pihole  | ::: setup_blocklists now setting default blocklists up: 
pihole  | ::: TIP: Use a docker volume for /etc/pihole/adlists.list if you want to customize for first boot
pihole  | ::: Blocklists (/etc/pihole/adlists.list) now set to:
pihole  | https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
pihole  | ::: Testing lighttpd config: Syntax OK
pihole  | ::: All config checks passed, cleared for startup ...
pihole  | ::: Enabling Query Logging
pihole  |   [i] Enabling logging...
  [✓] Logging has been enabled!
pihole  |  ::: Docker start setup complete
pihole  |   Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
pihole  |   Pi-hole version is v5.11.4 (Latest: v5.11.4)
pihole  |   AdminLTE version is v5.13 (Latest: v5.13)
pihole  |   FTL version is v5.16.1 (Latest: v5.16.1)
pihole  |   Container tag is: 2022.07.1
pihole  | [cont-init.d] 20-start.sh: exited 0.
pihole  | [cont-init.d] done.
pihole  | [services.d] starting services
pihole  | [services.d] done.
pihole  | Starting lighttpd
pihole  | Starting pihole-FTL (no-daemon) as root
pihole  | Starting crond
pihole  | Stopping pihole-FTL
pihole  | pihole-FTL: no process found
```

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

#241 #1019
https://github.com/pi-hole/docker-pi-hole/discussions/1021

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu 22.04 LTS 
  * Hardware: NUC7i5BNK 
  * Kernel Architecture: x86_64 
  * Docker Install Info and version: 
    - Software source: official docker-ce  - Docker version 20.10.17, build 100c701
    - Supplimentary Software: docker compose 
  * Hardware architecture:  64-bit 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```yaml
version: "3.8"

services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    network_mode: host
    environment:
      ADMIN_EMAIL: pihole@secret.email
      DHCP_ACTIVE: "true"
      DHCP_END: 192.168.0.254
      DHCP_IPv6: "true"
      DHCP_rapid_commit: "true"
      DHCP_ROUTER: 192.168.0.1
      DHCP_START: 192.168.0.3
      DNSMASQ_LISTENING: all
      DNSMASQ_USER: root
      DNSSEC: "true"
      PIHOLE_DNS_: 8.8.8.8;4.4.4.4
      # PIHOLE_UID: 0
      TZ: Europe/Berlin
      WEBPASSWORD: SuperSecretPass
      WEBTHEME: default-auto
    volumes:
      - ./.docker/pihole/dnsmasq.d:/etc/dnsmasq.d
      - ./.docker/pihole/etc:/etc/pihole
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
```

3. any additional info to help reproduce
## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [X] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
