### ISSUE TITLE
Cannot view API token due to x-frame-options: deny

### ISSUE THREAD

**Issue by danepowell** [pi-hole/docker-pi-hole#1163]
### Versions
Pi-hole version is v5.11.4 (Latest: v5.11.4)
AdminLTE version is v5.13 (Latest: v5.13)
FTL version is v5.16.1 (Latest: v5.16.1)

### Platform
pihole/pihole:latest docker image

### Expected behavior

When I click the "show api token" button in the API settings panel, I should see the API token.

### Actual behavior / bug

Firefox refuses to show the page in the modal, throwing an error due to x-frame-options being set to DENY

### Screenshots

![Screenshot 2022-08-03 073028](https://user-images.githubusercontent.com/1984514/182634315-676c61f0-9c97-48bf-bcec-2787bc98fedf.png)

### Additional context

I can see here that the x-frame-options should be SAMEORIGIN, not DENY. And I confirmed the same config exists in my Docker container. So perhaps the referrer is not being detected correctly?

https://github.com/pi-hole/pi-hole/blob/1be082a0e15fb7d12580db8b1f736fad4745b26a/advanced/lighttpd.conf.debian#L96

**Comment by dschaper** [comment]
Also please provide the docker-compose.yml or the docker run invocation commands you are using.

**Comment by danepowell** [comment]
Ah, now that I'm pasting my docker-compose.yml, I'm guessing this is actually caused by my Traefik reverse proxy.

Relevant section of docker-composer.yml:
```yaml
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    volumes:
    - ${CONFIGFOLDER}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    - ${CONFIGFOLDER}/pihole/etc-pihole/:/etc/pihole/
    networks:
    - web
    labels:
      traefik.enable: true
      traefik.http.routers.pihole.entrypoints: web-secure
      traefik.http.routers.pihole.middlewares: default@file
      traefik.http.routers.pihole.rule: Host(`pihole.${LOCALDOMAIN}`)
      traefik.http.routers.pihole.tls.certResolver: primary
      traefik.http.services.pihole.loadbalancer.server.port: 80
      traefik.tcp.routers.53-tcp.entrypoints: 53-tcp
      traefik.tcp.routers.53-tcp.rule: HostSNI(`*`)
      traefik.tcp.routers.53-tcp.service: pihole-53-tcp
      traefik.tcp.services.pihole-53-tcp.loadbalancer.server.port: 53
      traefik.udp.routers.53-udp.entrypoints: 53-udp
      traefik.udp.routers.53-udp.service: pihole-53-udp
      traefik.udp.services.pihole-53-udp.loadbalancer.server.port: 53
    env_file: .pihole.env
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    hostname: ${HOSTNAME}
    restart: ${RESTARTPOLICY}
```

Debug log: https://tricorder.pi-hole.net/uyTGdHvN/

Relevant traefik config:

```yaml
http:
  middlewares:
    default-security-headers:
      headers:
        browserXssFilter: true                            # X-XSS-Protection=1; mode=block
        contentTypeNosniff: true                          # X-Content-Type-Options=nosniff
        forceSTSHeader: true                              # Add the Strict-Transport-Security header even when the connection is HTTP
        frameDeny: true                                   # X-Frame-Options=deny
        referrerPolicy: "strict-origin-when-cross-origin"
        stsIncludeSubdomains: true                        # Add includeSubdomains to the Strict-Transport-Security header
        stsPreload: true                                  # Add preload flag appended to the Strict-Transport-Security header
        stsSeconds: 63072000                              # Set the max-age of the Strict-Transport-Security header (63072000 = 2 years)
```

frameDeny explains it, although I'm not quite sure how to fix it. I guess I'd want to only apply frameDeny if x-frame-options isn't already explicitly set...
