### ISSUE TITLE
unbound service not starting on docker image

### ISSUE THREAD

**Issue by sadpesant** [pi-hole/docker-pi-hole#1171]
This is a: Bug

## Details

I have followed the steps at [DNS/unbound guide](https://docs.pi-hole.net/guides/dns/unbound/#setting-up-pi-hole-as-a-recursive-dns-server-solution) and when I try the command:
`# sudo service unbound restart`
I get the message
`s6 service not found for unbound, exiting...`

I checked the path and the file exists: 
`/lib/systemd/system/unbound.service`

I also noticed the `root.hints` file is not created automatically using the package manager (don't think this is related though) as described in the guide. 

After googling a little bit I tried the `unbound-checkconf` command, and the output:
`unbound-checkconf[3301:0] fatal error: auto-trust-anchor-file: "/var/lib/unbound/root.key" does not exist`

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System:  Debian 11 Bullseye 
  * Hardware: Docker running on Mac mini M1 
  * Kernel Architecture: ArmV8 64bit 
  * Docker Install Info and version: 
    - Software source:   
    - Supplimentary Software: ubound 
  * Hardware architecture: arm 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
 `docker-compose up -d` with
 
```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2022.07
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: my-password
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #  - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
```
 
4. any additional info to help reproduce
After creating/running the container I executed the following commands:
`docker exec -it container-id /bin/bash`
`# apt update`
`# apt install unbound`

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

One thing I noticed after the installation of the unbound was the last lines of the output:

![image](https://user-images.githubusercontent.com/90574536/185810056-b24ed985-e98c-4ec5-a85d-58f16f77fb15.png)

I think this might be the reason. I did a research and found that a possibility would be:
`echo '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d`

If I run the command above before installing unbound the output changes to: 

![image](https://user-images.githubusercontent.com/90574536/185810209-264bad55-d04f-4bd4-8fe0-da352f74f6b5.png)
