### ISSUE TITLE
2022.08 S6 overlay bug

### ISSUE THREAD

**Issue by b-m-f** [pi-hole/docker-pi-hole#1176]
## Details

```
s6-overlay-suexec: fatal: can only run as pid 1
```
## How to reproduce the issue 

Pihole runs rootless with podman. 

```
HostUser=pihole
HostGroup=pihole

Environment="PIHOLE_UID=1000"
Environment="PIHOLE_GID=1000"
Environment="WEB_GID=1000"
Environment="WEB_UID=1000"
```

It has a supervisor running and this is the process hierarchy from `systemctl` in **2022.07.1**:

```
             ├─pihole.service …
             │ ├─supervisor
             │ │ └─1726889 /usr/bin/conmon --api-version 1 -c a_random_hash -u some_random_hash>
             │ └─container
             │   ├─1726894 /dev/init -- /s6-init
             │   ├─1726978 s6-svscan -t0 /var/run/s6/services
             │   ├─1727020 s6-supervise s6-fdholderd
             │   ├─1727521 s6-supervise lighttpd-access-log
             │   ├─1727522 s6-supervise lighttpd
             │   ├─1727523 s6-supervise pihole-FTL
             │   ├─1727525 s6-supervise lighttpd-error-log
             │   ├─1727526 s6-supervise cron
             │   ├─1727527 bash ./run
             │   ├─1727528 bash ./run
             │   ├─1727530 bash ./run
             │   ├─1727545 /usr/sbin/cron -f
             │   ├─1727563 lighttpd -D -f /etc/lighttpd/lighttpd.conf
             │   ├─1727593 /bin/bash -c /usr/bin/pihole-FTL no-daemon >/dev/null 2>&1
             │   ├─1727595 /usr/bin/pihole-FTL no-daemon
             │   ├─1727609 /usr/bin/php-cgi
             │   ├─1727641 /usr/bin/php-cgi
             │   ├─1727642 /usr/bin/php-cgi
             │   ├─1727643 /usr/bin/php-cgi
             │   └─1727644 /usr/bin/php-cgi
```

## Fix 

Revert to **2022.07.1** for now, as it runs fine here.

**Comment by PromoFaux** [comment]
Can we get a complete dump of your logs please? I've not really got a lot to go on here.

Given the following compose file, on my PC (docker, not rootless)

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      PIHOLE_UID: 1000
      PIHOLE_GID: 1000
      WEB_UID: 1000
      WEB_GID: 1000
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
```

I am running the container with no issue here:

```
adam@adam-pc:~/playground$ docker-compose up
Creating network "playground_default" with the default driver
Creating pihole ... done
Attaching to pihole
pihole    | s6-rc: info: service cron: starting
pihole    | s6-rc: info: service s6rc-oneshot-runner: starting
pihole    | s6-rc: info: service cron successfully started
pihole    | s6-rc: info: service s6rc-oneshot-runner successfully started
pihole    | s6-rc: info: service fix-attrs: starting
pihole    | s6-rc: info: service _startup: starting
pihole    | Starting crond
pihole    | fix-attrs: info: applying /etc/fix-attrs.d/01-resolver-resolv
pihole    | fix-attrs: warning: fix-attrs is deprecated, please fix volume permissions in your container manager instead
pihole    | s6-rc: info: service fix-attrs successfully started
pihole    | s6-rc: info: service legacy-cont-init: starting
pihole    | cont-init: info: running /etc/cont-init.d/05-changer-uid-gid.sh
pihole    | Changing ID for user: www-data (33 => 1000)
pihole    |  ::: Starting docker specific checks & setup for docker pihole/pihole
pihole    | 
pihole    |   [i] Installing configs from /etc/.pihole...
pihole    |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
pihole    | 
  [✓] Installing latest logrotate script
pihole    | Creating empty /etc/pihole/setupVars.conf file.
pihole    | Changing ID for group: www-data (33 => 1000)
pihole    | Changing ID for user: pihole (999 => 1000)
pihole    | cont-init: info: /etc/cont-init.d/05-changer-uid-gid.sh exited 0
pihole    | s6-rc: info: service legacy-cont-init successfully started
pihole    | Assigning random password: eLaZfZLr
pihole    |   [✓] New password set
pihole    | Added ENV to php:
pihole    |                     "TZ" => "America/Chicago",
pihole    |                     "PIHOLE_DOCKER_TAG" => "2022.08",
pihole    |                     "PHP_ERROR_LOG" => "/var/log/lighttpd/error-pihole.log",
pihole    |                     "CORS_HOSTS" => "",
pihole    |                     "VIRTUAL_HOST" => "0.0.0.0",
pihole    | Using IPv4 and IPv6
pihole    | ::: setup_blocklists now setting default blocklists up: 
pihole    | ::: TIP: Use a docker volume for /etc/pihole/adlists.list if you want to customize for first boot
pihole    | ::: Blocklists (/etc/pihole/adlists.list) now set to:
pihole    | https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
pihole    | Configuring default DNS servers: 8.8.8.8, 8.8.4.4
pihole    | Applying pihole-FTL.conf setting REPLY_ADDR4=0.0.0.0
pihole    | FTL binding to default interface: eth0
pihole    | ::: Enabling Query Logging
pihole    | ::: Testing lighttpd config: Syntax OK
pihole    | ::: All config checks passed, cleared for startup ...
pihole    | ::: Docker start setup complete
pihole    |   Pi-hole version is v5.11.4 (Latest: v5.11.4)
pihole    |   AdminLTE version is v5.13 (Latest: v5.13)
pihole    |   FTL version is v5.16.3 (Latest: v5.16.3)
pihole    |   Container tag is: 2022.08
pihole    | s6-rc: info: service _startup successfully started
pihole    | s6-rc: info: service pihole-FTL: starting
pihole    | s6-rc: info: service pihole-FTL successfully started
pihole    | s6-rc: info: service _gravityonboot: starting
pihole    | s6-rc: info: service lighttpd: starting
pihole    | s6-rc: info: service _gravityonboot successfully started
pihole    |   Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
pihole    | s6-rc: info: service lighttpd successfully started
pihole    | s6-rc: info: service legacy-services: starting
pihole    | Starting lighttpd
pihole    | s6-rc: info: service legacy-services successfully started
pihole    |   [i] Creating new gravity database
pihole    | Starting pihole-FTL (no-daemon) as pihole
pihole    |   [i] Migrating content of /etc/pihole/adlists.list into new database
pihole    |   [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range
pihole    | 
  [✓] Preparing new gravity database
pihole    |   [i] Using libz compression
pihole    | 
pihole    |   [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
pihole    |   [i] Analyzed 136495 domains
pihole    | 
  [✓] Creating new gravity databases
  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
pihole    |   [✓] The old database remains available.
pihole    |   [i] Number of gravity domains: 136495 (136495 unique domains)
pihole    |   [i] Number of exact blacklisted domains: 0
pihole    |   [i] Number of regex blacklist filters: 0
pihole    |   [i] Number of exact whitelisted domains: 0
pihole    |   [i] Number of regex whitelist filters: 0
  [✓] Cleaning up stray matter
pihole    | 
pihole    |   [✓] FTL is listening on port 53
pihole    |      [✓] UDP (IPv4)
pihole    |      [✓] TCP (IPv4)
pihole    |      [✓] UDP (IPv6)
pihole    |      [✓] TCP (IPv6)
pihole    | 
pihole    |   [i] Pi-hole blocking will be enabled
pihole    |   [i] Enabling blocking
  [✓] Pi-hole Enabled
```
