### ISSUE TITLE
s6: fatal timeout maybe due to bug in capabilities check

### ISSUE THREAD

**Issue by tommyknows** [pi-hole/docker-pi-hole#1189]
This is a: Bug / Run Issue

## Details

I'm running this Docker image in a pretty standard Kubernetes deployment and since upgrading to `2022.08.*`, my pod is crashlooping. Rolling back to `2022.07.1` resolves the issue.

Sadly, the log doesn't say too much (I think): 
<details>
  <summary>Output Log</summary>

```
s6-rc: info: service cron: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service cron successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service _startup: starting
Starting crond
fix-attrs: info: applying /etc/fix-attrs.d/01-resolver-resolv
fix-attrs: warning: fix-attrs is deprecated, please fix volume permissions in your container manager instead
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/05-changer-uid-gid.sh
cont-init: info: /etc/cont-init.d/05-changer-uid-gid.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
 ::: Starting docker specific checks & setup for docker pihole/pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service cron: stopping
Stopping cron
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service cron successfully stopped
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

</details>

And because the pod is crashlooping, I'd have a hard time to get the additional logs.

For reference, my deployment files: 
<details>
<summary>deployment manifests</summary>

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:2022.08.2
        resources:
          limits:
            memory: 100Mi
        env:
          - name: PIHOLE_DNS_
            value: "192.168.1.10"
          - name: FTLCONF_LOCAL_IPV4
            value: "192.168.1.11"
          - name: VIRTUAL_HOST
            value: "pihole.mydomain.com"
        ports:
        - name: webui
          containerPort: 80
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        volumeMounts:
          - mountPath: /etc/pihole
            name: pihole
          - mountPath: /etc/dnsmasq.d
            name: dnsmasq
      volumes:
        - name: pihole
          persistentVolumeClaim:
            claimName: pihole
        - name: dnsmasq
          persistentVolumeClaim:
            claimName: dnsmasq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnsmasq
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

```

</details>
I looked into the code a bit and believe to have found the issue though. 

The part that check for the capabilities is buggy. If any of the capability checks succeed, the built-up `CAP_STR` starts with a comma (e.g. `,CAP_CHOWN,...`).

`setcap` is not able to handle that, so it errors out:
```bash
$ setcap ",CAP_CHOWN+ep" "/usr/bin/pihole-FTL"
fatal error: Invalid argument
usage: setcap [-q] [-v] [-n <rootid>] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]

 Note <filename> must be a regular (non-symlink) file.
```

I'm not sure how confirm my suspicion though, so maybe it's also something else. In that case, is there any way to get more output in the logs?

If you think that my suspicion is correct, I'd be happy to submit a PR :-) 

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu 22.04
  * Hardware: PC 
  * Kernel Architecture: x86
  * Docker Install Info and version: not using Docker, just containerd. But with Kubernetes 1.24 / 1.25 (both work)
  * Hardware architecture: x86

3. any additional info to help reproduce
I'm not sure if this needs a Kubernetes environment to reproduce, as I don't have anything special in there. There's *NO* capabilities given to the container, it's not privileged....

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
