### ISSUE TITLE
Unable to see Dashboard without Login

### ISSUE THREAD

**Issue by mwatz1234** [pi-hole/docker-pi-hole#1199]
This is a: Run Issue (running Pi-hole container failing)

## Details

When using the latest docker image, I can no longer see the 'basic' dashboard, as it forces me to login.
## Related Issues
- [ ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Rasbian 
  * Hardware: RasPi 4B
  * Kernel Architecture: ArmV8 64bit
  * Docker Install Info and version: 
    - Software source: official docker-ce
    - Supplimentary Software: 
  * Hardware architecture: 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
version: '3.0'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: pihole.localdomain
    ports:
      - "443:443/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "853:853/tcp"
      - "853:853/udp"
    environment:
      - FTLCONF_LOCAL_IP4=192.168.2.117
      - TZ=America/Los_Angeles
      - WEBPASSWORD=Testing123
      - WEBTHEME=lcars
      - REV_SERVER=true
      - REV_SERVER_TARGET=192.168.2.1
      - REV_SERVER_DOMAIN=localdomain
      - REV_SERVER_CIDR=192.168.2.0/24
      - DNSSEC="true"
    volumes:
      - './etc/pihole:/etc/pihole/'
      - './etc/dnsmask:/etc/dnsmasq.d/'
      - './etc/config:/config/'
```      
3. any additional info to help reproduce
If i go back to version 2022.07.1, than I can see the 'basic' dashboard without login.

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ doc] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
