### ISSUE TITLE
"Stopping pihole-FTL" every hour in docker container running on openSUSE Leap 15.3

### ISSUE THREAD

**Issue by thomasmerz** [pi-hole/docker-pi-hole#1206]
This is a: **Bug**  

## Details
Every hour (exactly at 3 minutes past) I can see "Stopping pihole-FTL" messages on my Pi-hole (2022.09.02 - but even already some versions before) running in docker (docker-20.10.17_ce) on my openSUSE 15.3. But not on my Ubuntu 22.04 LTS.

> 2022-09-07T10:03:07.833302915Z Stopping pihole-FTL
2022-09-07T11:03:04.409706710Z Stopping pihole-FTL

There's also a corresponding message in FTL.log (my local time in germany is 2h plus London time):
> FTL.log:[2022-09-07 12:03:08.674 9170M] Error listening on Unix socket /run/pihole/FTL.sock: Cannot assign requested address (99)
FTL.log:[2022-09-07 13:03:05.197 22462M] Error listening on Unix socket /run/pihole/FTL.sock: Cannot assign requested address (99)

**What is causing this and why?
Can you advice how to get rid of this?**

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 
Starting/(re)creating pihole container, waiting until 3 minutes after a full hour and voila.
 
1. Environment data
  * Operating System: openSUSE 15.3
  * Hardware: PC
  * Kernel Architecture: x86/amd64,
  * Docker Install Info and version: 
    - Software source: OS provided package
    - Supplimentary Software: portainer/portainer-ce, netdata/netdata, ghcr.io/linuxserver/wireguard, henrywhitaker3/speedtest-tracker (containers) 
  * Hardware architecture: x86
 
2. docker-compose.yml contents:
```
version: "3"
services:
  pihole:
    hostname: 'pihole-merz-nimbus'
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    # https://github.com/pi-hole/docker-pi-hole/#environment-variables
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'secret'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # Enabling HTTPS for your Pi-hole Web Interface
      # https://discourse.pi-hole.net/t/enabling-https-for-your-pi-hole-web-interface/5771
      - './etc-lighttpd-external.conf:/etc/lighttpd/external.conf'
      - './etc-letsencrypt:/etc/letsencrypt/'
    cap_add:
      - NET_ADMIN
      - CAP_SYS_NICE
    ### restart: unless-stopped
    restart: always
```
My pi-hole containers running on Ubuntu use the same `docker-compose.yml` (with these changes: hostname, ports for web-gui)

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
