### ISSUE TITLE
FTL/dnsmasq port

### ISSUE THREAD

**Issue by brccabral** [pi-hole/docker-pi-hole#1221]
I have started pihole using this docker-compose.yml

```yml
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    network_mode: "host"
    environment:
      TZ: 'America/Los_Angeles'
      WEBPASSWORD: XXXXXX
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      - './var-log-pihole:/var/log/pihole'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

```

`FTL.log` shows many messages as 
```log
[2022-10-04 17:43:28.557 6828M] FATAL ERROR in dnsmasq core: failed to create listening socket for port 53: Address already in use
```

Only after editing `/etc/dnsmasq.conf` by adding another port FTL was able to start
```console
# cat /etc/dnsmasq.conf
conf-dir=/etc/dnsmasq.d

user=pihole

port=5353
```

What is the other process that is listening to port 53? Should this be configured by default?
