### ISSUE TITLE
Remove Web Password Option

### ISSUE THREAD

**Issue by cjlee89** [pi-hole/docker-pi-hole#1229]
I know `WEBPASSWORD` got implemented and I can remove the password all together by editing the setupVars file after docker creation. When updating the container, the `WEBPASSWORD` is put back. Is there a way we could get a `LEAVE_THE_FRONT_DOOR_OPEN` (or similar) variable to allow for permanent removal of the web password even after updates?

**Comment by PromoFaux** [comment]
Set `WEBPASSWORD` to be blank, i.e:

```yml
environment:      
      WEBPASSWORD:
      PIHOLE_DNS_:8.8.8.8;8.8.4.4
      #other variables
```
