### ISSUE TITLE
startup of docker container needs more than 1min

### ISSUE THREAD

**Issue by AlBundy33** [pi-hole/docker-pi-hole#1230]
since one of the latest updates the startup of the docker container (pihole:latest) needs more than one minute.
most of the time seems to be spend between this lines (output from docker logs)
```
[i] Installing latest logrotate script...
        [i] Existing logrotate file found. No changes made.
  [i] Custom WEB_PORT set to 3080
```

is it possible to speed this up?

**Comment by AlBundy33** [comment]
docker-compose.yml
```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    ports:
      - "192.168.1.111:53:53/tcp"
      - "192.168.1.111:53:53/udp"
      - "192.168.1.111:3080:3080/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: '´*************'
      PIHOLE_DNS_: '192.168.1.1;fd00::cece:1eff:fea8:6d0'
      #DNSMASQ_LISTENING: 'local'
      WEB_PORT: 3080
      DNS_BOGUS_PRIV: 'true'
      DNS_FQDN_REQUIRED: 'true'
      REV_SERVER: 'true'
      REV_SERVER_DOMAIN: 'fritz.box'
      REV_SERVER_TARGET: '192.168.1.1'
      REV_SERVER_CIDR: '192.168.1.0/24'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
```

if the container is started all is working as expected - its just the startup that takes some time and im pretty sure that some versions ago the container was ready after some seconds.
