### ISSUE TITLE
pi-hole + unbound : dig: parse of /etc/resolv.conf failed

### ISSUE THREAD

**Issue by MorgothSauron** [pi-hole/docker-pi-hole#1239]
I'm using the official pi-hole image (tag: 2022.11) with docker 20.10.20 on AlpineLinux 3.16.3 aarch64 (kernel 5.15.78-0-rpi4). I only use an unbound container as the upstream DNS (`127.0.0.1#5335`)

I noticed the following error in the container log (`docker logs pihole -f`) in the last few releases (2022.08, 2022.09, 2022.10, 2022.11): `dig: parse of /etc/resolv.conf failed`

This message seems to appear only when updating Gravity.

I executed a shell in the container (`docker exec -it pihole sh`) and the `dig` command fails with and without paramerter specified.

- `/etc/resolv.conf` on the host:
```
options timeout:15
search lan
nameserver 192.168.1.3
nameserver 2001:DB8::3
nameserver 192.168.1.1
```

- `/etc/resolv.conf` in the pihole containter
```
search lan
nameserver 127.0.0.1
nameserver 127.0.0.1#5335
options timeout:15
```

I tried the following changes in container's `resolv.conf`, without success:
- remove `options timeout:15` 
- remove `search lan`
- use alternate syntax: `[127.0.0.1]:5335`
- use alternate syntax: `127.0.0.1:5335`

The only working configuration is without the nameserver with a custom port specified
```
search lan
nameserver 127.0.0.1
options timeout:15
```

I didn't notice any problem with pihole functionalities and the dashboard do show that upstream DNS `127.0.0.1#5335` is being used. It is just that I'd like to have everything work without error.

**Comment by PromoFaux** [comment]
What does your compose/run script look like to start the container?

**Comment by MorgothSauron** [comment]
Here are the details for the compose config I use.

- `.env`:
```
IMAGE=pihole/pihole:2022.11
PIHOLE_DNS1=127.0.0.1#5335
PIHOLE_DNS2=127.0.0.1#5335
PIHOLE_SERVERIPV4=192.168.1.3
PIHOLE_WEBPASSWORD=
PIHOLE_TZ=Europe/Paris
PIHOLE_DNSMASQ_USER=pihole

# conditional forwarding
PIHOLE_REV_SERVER=true
PIHOLE_REV_SERVER_DOMAIN=lan
PIHOLE_REV_SERVER_TARGET=192.168.1.1
PIHOLE_REV_SERVER_CIDR=192.168.1.0/24

#
UNBOUND_PORT=5335
```

- `docker-compose.yml`:
```
version: "3.8"

services:
    srv:
        image: ${IMAGE}

        container_name: pihole

        depends_on:
            - dns

        hostname: pihole

        privileged: false

        environment:
            - TZ=${PIHOLE_TZ}
            - ServerIP=${PIHOLE_SERVERIPV4}
            - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
            - DNS1=${PIHOLE_DNS1}
            - DNS2=${PIHOLE_DNS2}
            - DNSMASQ_USER=${PIHOLE_DNSMASQ_USER}
            - REV_SERVER=${PIHOLE_REV_SERVER}
            - REV_SERVER_DOMAIN=${PIHOLE_REV_SERVER_DOMAIN}
            - REV_SERVER_TARGET=${PIHOLE_REV_SERVER_TARGET}
            - REV_SERVER_CIDR=${PIHOLE_REV_SERVER_CIDR}

        volumes:
            - config:/etc/pihole
            - dnsmasq:/etc/dnsmasq.d
            - log:/var/log

        network_mode: "host"

        dns:
            - 127.0.0.1
            - ${PIHOLE_DNS1}

        healthcheck:
            test: dig @127.0.0.1 pi.hole || exit 1
            interval: 2m00s
            timeout: 10s
            retries: 5
            start_period: 30s

        restart: 
            unless-stopped

    dns:
        build:
            context: ./unbound
            dockerfile: Dockerfile

        image: local/unbound

        container_name: unbound

        hostname: unbound

        privileged: true

        volumes:
            - dnsconf:/unbound/etc
            - dnslog:/unbound/log

        network_mode: "host"

        healthcheck:
            test: dig @127.0.0.1 -p ${UNBOUND_PORT} www.perdu.com || exit 1
            interval: 2m00s
            timeout: 10s
            retries: 5
            start_period: 30s

        restart: 
            unless-stopped

        devices:
            - "/dev/random:/dev/random"
            - "/dev/urandom:/dev/urandom"

volumes:
    dnsmasq:
    config:
    log:
    dnsconf:
    dnslog:
```

In case it matters, the `docker-compose` version:
```
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.8
OpenSSL version: OpenSSL 1.1.1s  1 Nov 2022
```
