### ISSUE TITLE
Pihole Synology macvlan

### ISSUE THREAD

**Issue by steff2632** [pi-hole/docker-pi-hole#1252]
Hi

I'm having trouble with using PiHole on synology using a macvlan network.

The network is created & my router even see's it and it has the right IP address matching the Mac address but I can't access the admin webpage

This is my compose

```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    cap_add:
      - NET_ADMIN
    networks:
      pihole_network:
        ipv4_address: 192.168.128.2   # <-- Update
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
     - 443:443/tcp
     - 53:53/udp
     - 67:67/udp
     - 80:80/tcp
    environment:
      ServerIP: 192.168.128.2         # <-- Update (match ipv4_address)
      WEBPASSWORD: "password"                   # <-- Add password (if required)
      FTLCONF_LOCAL_IPV4: 192.168.128.2
      TZ: 'Europe/London'
    volumes:
      - /volume1/docker/pihole:/etc/pihole
      - /volume1/docker/pihole/scripts/dnsmasq.conf:/etc/dnsmasq.d/02-network.conf
    restart: unless-stopped

networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: bond0
    ipam:
      config:
        - subnet: 192.168.128.0/24            # <-- Update
          gateway: 192.168.128.1              # <-- Update
          ip_range: 192.168.128.192/28        # <-- Update
```
unsure if its all needed e.g. 

- are port declarations needed if using macvlan since the macvlan has all ports?
- do I need to set my own dnsmasq declaration file?

These are the logs from the docker container 
[_pihole_logs-2.txt](https://github.com/pi-hole/docker-pi-hole/files/10178067/_pihole_logs-2.txt)

just trying to use the DNS features of PiHole not the DCHP features

**Comment by rdwebdesign** [comment]
Try replacing `192.168.128.2` with `192.168.128.200`.

Your `macvlan` is using `ip_range: 192.168.128.192/28`. 
This range starts with `192.168.128.192` and end at `192.168.128.207`.

**Comment by steff2632** [comment]
I set it to 201 because my router hands out address .100-199

its still unreachable
[_pihole_logs-2.txt](https://github.com/pi-hole/docker-pi-hole/files/10178315/_pihole_logs-2.txt)


connecting to the container I can ping websites but still can't access the admin panel

**Comment by buckaroogeek** [comment]
I have a working example of the docker compose yaml for a pihole container on a synology at https://github.com/buckaroogeek/unifi-pihole-doh-docker. You might find some additional tips in the readme. My example starts from the same source as yours. This compose file also starts several other containers but those can be ignored. The aux_address in the macvlan definition is the "shim" IP used by the synology network. There is also a shim.sh script file in the scripts folder that is run after the synology network is restarted. This allows the synology to actually "see" the docker macvlan IPs and container services.

**Comment by rdwebdesign** [comment]
@steff2632

I never created the macvlan network using the compose file. 
Since the macvlan is used to allow communication between docker containers and the Local network, I created a single macvlan and always reuse the same network.

A macvlan network by default are not able to ping or communicate with the host (and vice-versa). You need extra config to allow the communication.

There is a good post explaining macvlans and how to create them [on this link](https://blog.ivansmirnov.name/set-up-pihole-using-docker-macvlan-network/), but I'm afraid the website is offline at the moment. You can read [the post on WebArchive](https://web.archive.org/web/20220929225156/https://blog.ivansmirnov.name/set-up-pihole-using-docker-macvlan-network/).

Another post to help: https://gdevillele.github.io/engine/userguide/networking/get-started-macvlan/#/macvlan-bridge-mode-example-usage

Note:
I don't have a Synology device to test. Maybe the comment from **buckaroogeek** might help you.

**Comment by buckaroogeek** [comment]
@steff2632 -

My understanding is that the ```externalPort:containerPort``` syntax is not needed for macvlans since docker is not matching a port on the docker host (externalPort) to the container port.  I think docker just ignores that for macvlan but not sure.

The IP you set in the compose file for pihole is the one to use in the browser, i.e. http://http://192.168.110.201/admin/login.php should display the password authentication dialog.

**Comment by steff2632** [comment]
thank @rdwebdesign & @buckaroogeek 

it was the shim network that was needed. 

Do you know if its possible to create the shim network in docker/compose rather than an external script?

**Comment by rdwebdesign** [comment]
I don't think this is possible.
This is not a docker config. This is set at Operating System level.

**Comment by PromoFaux** [comment]
You need to do it separately. I used to have something set up on DSM6 that would autorun the script on boot - but since DSM7 that no longer works and I couldn't be bothered to look into it... I just have to remember to run the folloing `net-up.sh` (adjust to your own settings) script any time I reboot the Syno

```text
admin@syno:/volume1/docker$ cat net-up.sh
ip link add home-shim link eth0 type macvlan mode bridge
ip addr add 192.168.1.250 dev home-shim
ip link set home-shim up
ip route add 192.168.1.0/24 dev home-shim

admin@syno:/volume1/docker$ cat net-down.sh
ip route del 192.168.1.0/24 dev home-shim || true
ip link set home-shim down || true
ip addr del 192.168.1.250 dev home-shim || true
ip link del home-shim || true
```

**Comment by buckaroogeek** [comment]
> I don't think this is possible. This is not a docker config. This is set at Operating System level.

That is my understanding also.   I just run the shim.sh script manually after a synology reboot or network restart. To simplify ssh access a bit I added the following to ~/.ssh/config:

```
Host syn
  hostname quga.lan
  user bgsmith
  Port 2489
  IdentityFile ~/.ssh/id_ed25519
  ServerAliveInterval 60
  ServerAliveCountMax 240
```

and then ssh syn is all that is needed to access the command line on the synology.

**Comment by steff2632** [comment]
hmmm ok, this tutorial creates the bridge network in Synology Docker UI meaning it should be possible to create it with compose too

https://www.wundertech.net/how-to-use-docker-on-a-synology-nas/

**Comment by madnuttah** [comment]
I have done something similar, MCVLAN is working with an additional bridge to let the containers communicate with the host: [Pi-hole/Unbound MCVLAN example](https://github.com/madnuttah/unbound-docker/blob/main/unbound/examples/docker-compose.yaml%20(mcvlan)). It's all done in a compose file.

**Comment by steff2632** [comment]
> I have done something similar, MACVLAN is working with an additional bridge to let the containers communicate with the host: [Pi-hole/Unbound MACVLAN example](https://github.com/madnuttah/unbound-docker/blob/main/unbound/examples/docker-compose.yaml%20(mcvlan)). It's all done in a compose file.

This is what I was looking for, I was almost there but had the bridge trying to be in the same range (x.y.128.z) as the host because of the tutorial above. Yours appears to have it in a completely different one (x.y.127.z) can they still connect?


Doesn't seem to need it, docker/synology have made one up with the last two sections changed to the host system.
> Edit: shouldn't there be MAC Addresses to make MACVLAN work in your compose?

**Comment by madnuttah** [comment]
Yup, the container uses the bridge network to establish host/container communication. The host wasn't able to access the internet because Pi-hole's DNS resolution couldn't be reached within the MACVLAN network by the docker host. 

Anyway, this should get you started.

**Comment by steff2632** [comment]
so I get an error when trying this. I'm using portainer to create the docker compose and when creating the "stack" (docker compose up) it errors on the bridge network because port 443 is already in use

**Comment by madnuttah** [comment]
Show your current compose file please

**Comment by steff2632** [comment]
```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    networks:
      macvlan:
        ipv4_address: 192.168.128.201   # <-- Update
      bridge:
        ipv4_address: 192.168.127.201

    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
     - 443:443/tcp
     - 53:53/udp
     - 67:67/udp
     - 80:80/tcp
    environment:
      ServerIP: 192.168.128.201         # <-- Update (match ipv4_address)
      WEBPASSWORD: "password"                   # <-- Add password (if required)
      FTLCONF_LOCAL_IPV4: 192.168.128.201
      TZ: 'Europe/London'
      VIRTUAL_HOST: pihole.lan
      REV_SERVER: "true" #Use Conditional Forwarding
      REV_SERVER_TARGET: 192.168.128.1 #e.g. 192.168.1.1 or fd11:aa:1234:1234::11
      REV_SERVER_DOMAIN: 'steff.local'
      REV_SERVER_CIDR: 192.168.128.0/24 #e.g. 192.168.1.0/24 or fd11:bb:1234:1234::11


    volumes:
      - /volume1/docker/pihole:/etc/pihole
      - /volume1/docker/pihole/scripts/dnsmasq.conf:/etc/dnsmasq.d/02-network.conf
    restart: unless-stopped

networks:
  macvlan:

    driver: macvlan
    driver_opts:
      parent: bond0
    ipam:
      config:
        - subnet: 192.168.128.0/24            # <-- Update
          gateway: 192.168.128.1              # <-- Update
          ip_range: 192.168.128.200/30        # <-- Update
            
  bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.127.0/24            # <-- Update
```

**Comment by madnuttah** [comment]
The bridge subnet should be 192.168.127.0/16, other configs failed on my setup. You could try another ip range like 10.0.0.0/16 for testing.

Could you try just with plain docker-compose, not using portainer then please? I have it running here without complaining that the ports are in use. I think you need a MAC in a MACvlan still.

`docker-compose --profile=all -f YOURCOMPOSEFILE up -d`

**Comment by steff2632** [comment]
still getting the error inside portainer
`failed to deploy a stack: Network pihole_bridge Creating Network pihole_bridge Created Container pihole Recreate Container pihole Recreated Container pihole Starting Error response from daemon: driver failed programming external connectivity on endpoint pihole (acdac1ca4422b0a9eef06ab2376eeed1ed4c016b9a291a773fc76ebbf950f0f1): Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use`

is the full error from portainer and got the same error when using the CLI
<img width="1895" alt="Screenshot 2022-12-13 at 17 18 20" src="https://user-images.githubusercontent.com/3290735/207400642-f494be45-1da6-4560-9f1e-347bfd92d4d7.png">

**Comment by rdwebdesign** [comment]
There is another service or image using port 443 on your machine.

This is not a Pi-hole issue. It's a local config conflict.

**Comment by steff2632** [comment]
yes, sorry, thought that was known, Synology grabs most of the ports for itself (80 & 443 especially)

you did help me though @rdwebdesign because I thought docker would see that the macvlan network was created and push all traffic through it, I was wrong, so forwarded some ports and got the container to launch with the two networks however now my laptop (different machine) can't access the container on its macvlan address. 

compose and ifconfig output from the running container  if you're still interested 
```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    cap_add:
      - NET_ADMIN
    networks:
      macvlan:
        ipv4_address: 192.168.128.201   # <-- Update
      bridge:

    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
     - 54443:443/tcp
     - 5453:53/udp
     - 5467:67/udp
     - 5480:80/tcp
    environment:
      ServerIP: 192.168.128.201         # <-- Update (match ipv4_address)
      WEBPASSWORD: "password"                   # <-- Add password (if required)
      FTLCONF_LOCAL_IPV4: 192.168.128.201
      TZ: 'Europe/London'
      VIRTUAL_HOST: pihole.lan
      REV_SERVER: "true" #Use Conditional Forwarding
      REV_SERVER_TARGET: 192.168.128.1 #e.g. 192.168.1.1 or fd11:aa:1234:1234::11
      REV_SERVER_DOMAIN: 'steff.local'
      REV_SERVER_CIDR: 192.168.128.0/24 #e.g. 192.168.1.0/24 or fd11:bb:1234:1234::11


    volumes:
      - /volume1/docker/pihole:/etc/pihole
      - /volume1/docker/pihole/scripts/dnsmasq.conf:/etc/dnsmasq.d/02-network.conf
    restart: unless-stopped

networks:
  macvlan:

    driver: macvlan
    driver_opts:
      parent: bond0
    ipam:
      config:
        - subnet: 192.168.128.0/24            # <-- Update
          gateway: 192.168.128.1              # <-- Update
          ip_range: 192.168.128.200/30        # <-- Update
          aux_addresses:
              -host: 192.168.128.202
            
  bridge:
    driver: bridge

```

![Screenshot 2022-12-13 at 18 38 18](https://user-images.githubusercontent.com/3290735/207417689-e112ed8d-a3bf-4fd5-8855-df79d16b2575.png)

**Comment by rdwebdesign** [comment]
Actually, I never used a macvlan like this (maybe it will work).

I never included port forwarding for Pi-hole, because it's not necessary when using macvlan.

As I said on a previous comment, I create the macvlan network (and the bridge to the host) in a separate step, BEFORE the containers creation. This macvlan network is always there, even when I remove all containers.

**Comment by steff2632** [comment]
its working with the macvlan in the compose but needs the shim to allow local network (192.168.128.x) access. 

OT
Can you have multiple macvlan networks e.g. pihole and a http server, both will want port 80, or is it better to have one macvlan and then in the compose request the IP address and list the network as external

**Comment by rdwebdesign** [comment]
As I said, I never used macvlan this way, but I think you are mixing the ideas.

I think some of your containers are using bridge or host network. In this case port conflict is possible (and very likely).

Using macvlan each container will have its own IP.
There are no port conflicts even using 100 containers with port 80. Each container is accessed using a different IP like this: `192.168.0.200:80`, `192.168.0.201:80`, `192.168.0.202:80` ... (ports added just for clarification).

In simple words: each container is like a separate machine on your network. It's not possible to have a conflict.

**Comment by madnuttah** [comment]
I think you have a different problem than trying to create a bridge network for your container. This only would make sense if you need the host to get it's DNS resolution done by your Pi-hole. You just don't need it to access the Pi-hole webpage. What error message do you get when accessing your [Pi-hole admin panel](http://192.168.128.201:80/admin/login.php)?

**Comment by steff2632** [comment]
> As I said, I never used macvlan this way, but I think you are mixing the ideas.
> 
> I think some of your containers are using bridge or host network. In this case port conflict is possible (and very likely).
> 
> Using macvlan each container will have its own IP. There are no port conflicts even using 100 containers with port 80. Each container is accessed using a different IP like this: `192.168.0.200:80`, `192.168.0.201:80`, `192.168.0.202:80` ... (ports added just for clarification).
> 
> In simple words: each container is like a separate machine on your network. It's not possible to have a conflict.
> 
> **Note:** I don't know what is "better". I use the second option: one macvlan and use it as an external network.

Yes, this was a slightly different question, about macvlans in general. Is it better to have a macvlan network per container or one macvlan which you assign up addresses to  containers when creating them. You’ve said you do the second one.

**Comment by steff2632** [comment]
> I think you have a different problem than trying to create a bridge network for your container. This only would make sense if you need the host to get it's DNS resolution done by your Pi-hole. You just don't need it to access the Pi-hole webpage. What error message do you get when accessing your [Pi-hole admin panel](http://192.168.128.201:80/admin/login.php)?

Without the shim posted above, there’s no connection at all, even when using a different device to try to access the panel, with the shim it works like its a separate device on the network

**Comment by buckaroogeek** [comment]
> 
> Without the shim posted above, there’s no connection at all, even when using a different device to try to access the panel, with the shim it works like its a separate device on the network

With the docker macvlan I describe above, each container,as @rdwebdesign notes, basically functions as a separate machine on the local network. I can, for example, ping the pihole container from my workstation. Is the shim is *not* enabled, then there is no network connection from the synology IP to the IPs on the macvlan.  I cannot, for example, ping the pihole container from the Synology command line. 

The shim enables a network path from the synology to the containers so that a ping from the Synology command line works. The containers should be pingable and the web interface visible from other computers on the local network with or without the shim. At least that has been my experience. :)

As far as the number of distinct macvlans on a given docker instance, I personally do not see any benefit to have more than a single macvlan but that is just a personal perspective. Much less to manage. My approach is to set aside enough IPs on my home network for the macvlan (192.168.110.192/26 - xx.193 to xx.254) for the containers needed.

best regards

**Comment by steff2632** [comment]
Without the shim i get no connection to the macvlans from any of the IPs on my local network. I don’t think i need the synology to be able to connect to the PiHole, its controllable through docker/portainer. There’s no containers that need to talk to the PiHole, I don’t think

**Comment by buckaroogeek** [comment]
> Without the shim i get no connection to the macvlans from any of the IPs on my local network. I don’t think i need the synology to be able to connect to the PiHole, its controllable through docker/portainer. There’s no containers that need to talk to the PiHole, I don’t think

I admit to being puzzled about why the shim is needed to expose the containers to the local network. On my network, the synology uses the pihole as the preferred DNS server so the shim is very useful, but not strictly required as there is a fallback dns for the synology. Also several of the other containers either use the pihole or are used by the pihole. I have a DOH client in a container, for example, which is the upstream DNS for the pihole.

**Comment by rdwebdesign** [comment]
> I admit to being puzzled about why the shim is needed to expose the containers to the local network.

The best explanation I found was:
This is intentional. The traffic is explicitly filtered by the kernel modules themselves to offer additional provider isolation and security, but it's possible to create a macvlan bridge interface in the host to allow the communication between host and container.

Maybe you can find some explanation here:
- https://collabnix.com/2-minutes-to-docker-macvlan-networking-a-beginners-guide/
- https://hicu.be/bridge-vs-macvlan
- https://sreeninet.wordpress.com/2016/05/29/docker-macvlan-and-ipvlan-network-plugins/
- https://sreeninet.wordpress.com/2016/05/29/macvlan-and-ipvlan/

**Comment by steff2632** [comment]
Yeah I don’t get it either. It might be the synology/docker setup but from what I’ve experienced “host” means anything within either the same router haven’t tried putting them on different subnets (e.g. in my case 192.168.127.1)

**Comment by madnuttah** [comment]
> > As I said, I never used macvlan this way, but I think you are mixing the ideas.
> > I think some of your containers are using bridge or host network. In this case port conflict is possible (and very likely).
> > Using macvlan each container will have its own IP. There are no port conflicts even using 100 containers with port 80. Each container is accessed using a different IP like this: `192.168.0.200:80`, `192.168.0.201:80`, `192.168.0.202:80` ... (ports added just for clarification).
> > In simple words: each container is like a separate machine on your network. It's not possible to have a conflict.
> > **Note:** I don't know what is "better". I use the second option: one macvlan and use it as an external network.
> 
> Yes, this was a slightly different question, about macvlans in general. Is it better to have a macvlan network per container or one macvlan which you assign up addresses to containers when creating them. You’ve said you do the second one.

Yes, and it's working **out of the box**. I just use the bridge to make my docker host able to access Pi-hole's name resolution. 

So your initial problem is that you cannot access the webpage? May I ask again what you need the bridge for?

**Comment by madnuttah** [comment]
Would you try this please?

```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    mac_address: 00-A1-31-BA-BE-FF
    cap_add:
      - NET_ADMIN
    networks:
      dns-net:
        ipv4_address: 192.168.128.201   # <-- Update
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
     - 53:53/udp
     - 67:67/udp
     - 80:80/tcp
    environment:
      ServerIP: 192.168.128.201         # <-- Update (match ipv4_address)
      WEBPASSWORD: "password"                   # <-- Add password (if required)
      FTLCONF_LOCAL_IPV4: 192.168.128.4
      TZ: 'Europe/London'
      VIRTUAL_HOST: pihole.steff.local
      REV_SERVER: "true" #Use Conditional Forwarding
      REV_SERVER_TARGET: 192.168.128.1 #e.g. 192.168.1.1 or fd11:aa:1234:1234::11
      REV_SERVER_DOMAIN: 'steff.local'
      REV_SERVER_CIDR: 192.168.128.0/24 #e.g. 192.168.1.0/24 or fd11:bb:1234:1234::11


    volumes:
      - /volume1/docker/pihole:/etc/pihole
      - /volume1/docker/pihole/scripts/dnsmasq.conf:/etc/dnsmasq.d/02-network.conf
    restart: unless-stopped

networks:
  dns-net:

    driver: macvlan
    driver_opts:
      parent: bond0
    ipam:
      config:
        - subnet: 192.168.128.0/24            # <-- Update
          gateway: 192.168.128.1              # <-- Update
          ip_range: 192.168.128.200/30        # <-- Update
```

- The FTLCONF_LOCAL_IPV4 should be your docker host (IP of Synology NAS)
- The Virtual host is fixed (was pihole.lan not your current DNS domain)
- Changed the network name from macvlan to dns-net (just to make sure MCVLAN isn't a reserved term)

I'd suggest to change your home TLD from `.local` to `.arpa` or such to prevent issues with mDNS. 

It's a bit simplified but should work.
