### ISSUE TITLE
Unable to connect on port 443 with 2023.1.1 and 2023.01 also on port 80

### ISSUE THREAD

**Issue by thomasmerz** [pi-hole/docker-pi-hole#1274]
This is a: **Bug**  

## Details
Before 2023.1.1 my Pi-hole / lighttpd was listening and serving the Admin GUI via https, but with 2023.1.1 it's broken.
```
server.modules += ( "mod_openssl" )
$SERVER["socket"] == ":443" {
  ssl.engine  = "enable"
  ssl.pemfile = "/etc/letsencrypt/fullchain.pem"
  ssl.privkey = "/etc/letsencrypt/key.pem"
  ssl.openssl.ssl-conf-cmd = ("MinProtocol" => "TLSv1.3", "Options" => "-ServerPreference")
}
```

With 2023.01 it's also broken for http 😢 

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Ubuntu 22.04 LTS** as Guest-OS for docker
  * Hardware: PC/Docker
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: `Docker version 20.10.12, build 20.10.12-0ubuntu4`
  * Hardware architecture: x86
2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
  ```
services:
  pihole:
    hostname: 'pihole-nbg1-dc3'
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "33080:80/tcp"
      - "33443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - './etc-lighttpd-external.conf:/etc/lighttpd/external.conf'
      - './etc-letsencrypt:/etc/letsencrypt/'
    cap_add:
      - NET_ADMIN
      - CAP_SYS_NICE
    restart: unless-stopped
```
4. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
  Reverting to 2022.12.1 and everything is fine again.  
  Using 2023.1.1 shows http Admin GUI - that's ok in my home-network, but not for my cloud-servers
  Using 2023.01 no Admin-GUI at all!
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
