### ISSUE TITLE
BUG: lighttpd external.conf not working in 2023.01.10 after upgrade from 2022.12. (downgrading fixes it)

### ISSUE THREAD

**Issue by JvdMaat** [pi-hole/docker-pi-hole#1316]
This is a: Bug 

## Details

Upgrading from 2022.12 (through docker image cbcrowe/pihole-unbound), pihole is no longer responding to https requests.

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu 22.04.1 LTS
  * Hardware: HP Laptop 
  * Kernel Architecture: x86 
  * Docker Install Info and version: 
    - Software source: Official docker-ce
    - Supplementary Software: Chris Crowe pihole-unbound one-container bundle
  * Hardware architecture: x86

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
docker-compose:
  pihole:
    container_name: pihole
    image: cbcrowe/pihole-unbound:2023.01.10
    hostname: pihole-9
    shm_size: 128mb # 64mb is default. Got issues with the high query count (>1 million) during Comcast outage
    ports:
      - 192.168.9.9:53:53/tcp
      - 192.168.9.9:53:53/udp
      - 5343:443/tcp
    volumes:
      - /opt/pihole/pihole:/etc/pihole
      - /opt/pihole/lighttpd/external.conf:/etc/lighttpd/external.conf
      - /opt/pihole/dnsmasq.d:/etc/dnsmasq.d
      - /opt/swag/config/etc/letsencrypt:/ssl:ro
    #healthcheck: - Built-in! Jubilations
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBPASSWORD=redacted
      - WEBTHEME=default-dark
      - FTLCONF_LOCAL_IPV4=192.168.9.9
      - REV_SERVER=true
      - REV_SERVER_TARGET=192.168.9.1
      - REV_SERVER_DOMAIN=vandermaat.com
      - REV_SERVER_CIDR=192.168.0.0/16
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC=true
      - DNSMASQ_LISTENING=single
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.link.template=https://github.com/chriscrowe/docker-pihole-unbound/releases/tag/$${major}.$${minor}.$${patch}

```
```
external.conf file:
$HTTP["host"] == "dns.vandermaat.com" {
    setenv.add-environment = ("fqdn" => "true")

#Loading openssl
server.modules += ( "mod_openssl" )

$SERVER["socket"] == ":443" {
	ssl.engine  = "enable"
	ssl.pemfile = "/ssl/live/hass.vandermaat.com/priv-fullchain-bundle.pem"
	ssl.ca-file = "/ssl/live/hass.vandermaat.com/fullchain.pem"
    ssl.honor-cipher-order = "enable"
    ssl.cipher-list = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
#    ssl.use-sslv2 = "disable"
#    ssl.use-sslv3 = "disable"
	ssl.openssl.ssl-conf-cmd = ("MinProtocol" => "TLSv1.3", "Options" => "-ServerPreference")
}

$HTTP["url"] =~ "^/admin/" {
      # Allow using Pi-Hole admin in iframes (eg, for Home Assistant)
      setenv.set-response-header += (
         "X-Frame-Options" => "Allow"
      )
}

}
```

3. any additional info to help reproduce
Entering: /usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf gives no feedback (straight back to command prompt). In 2022.12 it would say:
2023-02-09 22:17:04: configfile-glue.c.298) DEPRECATED: do not set server options in conditionals, variable: server.modules
2023-02-09 22:17:04: configfile.c.255) Warning: please add "mod_openssl" to server.modules list in lighttpd.conf.  A future release of lighttpd 1.4.x *will not* automatically load mod_openssl and lighttpd *will not* use SSL/TLS where your lighttpd.conf contains ssl.* directives

I added 5380:80/tcp to the docker_compose ports, and HTTP works just fine.

Checking the /etc/lighttpd/lighttpd.conf file, it looks stock, and there is no lighttps.conf.orig file. (On the previous version it stated it was created by pihole and would get overwritten, this version does not have that). I double checked and loaded the pihole/pihole:2023.01.10 image directly, and it has the same issue (So this is not an issue in the cbcrowe docker container). 2023.01.10 lighttps.conf file starts as:
```
root@pihole-test:/etc/lighttpd# cat lighttpd.conf 
server.modules = (
        "mod_indexfile",
        "mod_access",
        "mod_alias",
        "mod_redirect",
)

server.document-root        = "/var/www/html"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80
```

2022.12 version started:
```
root@pihole-9:/etc/lighttpd# cat lighttpd.conf
# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Lighttpd config for Pi-hole
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.

###############################################################################
#     FILE AUTOMATICALLY OVERWRITTEN BY PI-HOLE INSTALL/UPDATE PROCEDURE.     #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#              CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE:              #
#                         /etc/lighttpd/external.conf                         #
###############################################################################

server.modules = (
    "mod_access",
    "mod_accesslog",
    "mod_auth",
    "mod_expire",
    "mod_redirect",
    "mod_setenv",
    "mod_rewrite"
)
```

I tried mounting the old lighttpd.conf from 2022.12 to the 2023.01.10 container, but that gave a bunch of lighttp errors.

## These common fixes didn't work for my issue

- [ ] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me) Works fine when reverting to 2022.12 (cbcrowe/pihole-unbound:2022.12)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause - Not tried as that wipes the HTTPS config

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
