### ISSUE TITLE
DNS resolution is currently unavailable

### ISSUE THREAD

**Issue by DarkCeptor44** [pi-hole/docker-pi-hole#1327]
I had PiHole running for a while and recently updated to the latest image/2023.02.2 and almost immediately after the container runs the DNS service stops working, the pages are still accessible by IP.

This is a: **Run Issue**  

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

#694 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Debian 11 headless from the board manufacturer** 
  * Hardware: **Orange Pi Zero 2 1GB** 
  * Kernel Architecture: **ArmV8 64bit** 
  * Docker Install Info and version: 
    - Software source: **OS provided package**
    - Supplimentary Software: 
  * Hardware architecture: **ARM64v8**

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```yaml
version: "3.3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pi.hole
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - 53:53/tcp
      - 53:53/udp
      #- 67:67/udp
      - 8080:80/tcp
    environment:
      - TZ=America/Sao_Paulo
      - WEBPASSWORD=123456
      - DNSMASQ_LISTENING=all
      - VIRTUAL_HOST=pi.hole
      - PROXY_LOCATION=pi.hole
      - FTLCONF_LOCAL_IPV4=127.0.0.1
    volumes:
      - /home/darkceptor44/docker/data/pihole/data:/etc/pihole
      - /home/darkceptor44/docker/data/pihole/dnsmasq.d:/etc/dnsmasq.d
    #cap_add:
    #  - NET_ADMIN
    restart: always
```
4. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

When running the image with a `docker run` command FTL didn't stop immediately but instead when I went into the DNS Records and added a domain there, then by using the extra environment variables in the docker-compose file it behaved the same way.
The first thing I did was to try an older image, I tried `2023.02.0` and `2023.01.10` (which was what I had before) while deleting the volumes in between and it didn't work.

Container logs:
```
02/18/2023 6:41:04 PM
s6-rc: info: service s6rc-oneshot-runner: starting
02/18/2023 6:41:04 PM
s6-rc: info: service s6rc-oneshot-runner successfully started
02/18/2023 6:41:04 PM
s6-rc: info: service fix-attrs: starting
02/18/2023 6:41:04 PM
s6-rc: info: service fix-attrs successfully started
02/18/2023 6:41:04 PM
s6-rc: info: service legacy-cont-init: starting
02/18/2023 6:41:04 PM
s6-rc: info: service legacy-cont-init successfully started
02/18/2023 6:41:04 PM
s6-rc: info: service cron: starting
02/18/2023 6:41:04 PM
s6-rc: info: service cron successfully started
02/18/2023 6:41:04 PM
s6-rc: info: service _uid-gid-changer: starting
02/18/2023 6:41:04 PM
s6-rc: info: service _uid-gid-changer successfully started
02/18/2023 6:41:04 PM
s6-rc: info: service _startup: starting
02/18/2023 6:41:04 PM
  [i] Starting docker specific checks & setup for docker pihole/pihole
02/18/2023 6:41:04 PM
  [i] Setting capabilities on pihole-FTL where possible
02/18/2023 6:41:04 PM
  [i] Applying the following caps to pihole-FTL:
02/18/2023 6:41:04 PM
        * CAP_CHOWN
02/18/2023 6:41:04 PM
        * CAP_NET_BIND_SERVICE
02/18/2023 6:41:04 PM
        * CAP_NET_RAW
02/18/2023 6:41:06 PM
  [i] Ensuring basic configuration by re-running select functions from basic-install.sh
02/18/2023 6:41:06 PM
02/18/2023 6:41:06 PM
  [i] Installing configs from /etc/.pihole...
02/18/2023 6:41:06 PM
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
02/18/2023 6:41:06 PM
  [i] Installing /etc/dnsmasq.d/01-pihole.conf...
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
02/18/2023 6:41:06 PM
  [i] Installing /etc/.pihole/advanced/06-rfc6761.conf...
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
02/18/2023 6:41:07 PM
02/18/2023 6:41:07 PM
  [i] Installing latest logrotate script...
  [✓] Installing latest logrotate script
02/18/2023 6:41:07 PM
  [i] Creating empty /etc/pihole/setupVars.conf file.
02/18/2023 6:41:07 PM
  [i] Assigning password defined by Environment Variable
02/18/2023 6:41:07 PM
  [✓] New password set
02/18/2023 6:41:07 PM
  [i] Added ENV to php:
02/18/2023 6:41:07 PM
                    "TZ" => "America/Sao_Paulo",
02/18/2023 6:41:07 PM
                    "PIHOLE_DOCKER_TAG" => "",
02/18/2023 6:41:07 PM
                    "PHP_ERROR_LOG" => "/var/log/lighttpd/error-pihole.log",
02/18/2023 6:41:07 PM
                    "CORS_HOSTS" => "",
02/18/2023 6:41:07 PM
                    "VIRTUAL_HOST" => "a933c23776be",
02/18/2023 6:41:07 PM
  [i] Using IPv4 and IPv6
02/18/2023 6:41:07 PM
  [i] setup_blocklists now setting default blocklists up: 
02/18/2023 6:41:07 PM
  [i] TIP: Use a docker volume for /etc/pihole/adlists.list if you want to customize for first boot
02/18/2023 6:41:07 PM
  [i] Blocklists (/etc/pihole/adlists.list) now set to:
02/18/2023 6:41:07 PM
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
02/18/2023 6:41:07 PM
  [i] Configuring default DNS servers: 8.8.8.8, 8.8.4.4
02/18/2023 6:41:07 PM
  [i] Applying pihole-FTL.conf setting LOCAL_IPV4=0.0.0.0
02/18/2023 6:41:07 PM
  [i] FTL binding to default interface: eth0
02/18/2023 6:41:07 PM
  [i] Enabling Query Logging
02/18/2023 6:41:08 PM
  [i] Testing lighttpd config: Syntax OK
02/18/2023 6:41:08 PM
  [i] All config checks passed, cleared for startup ...
02/18/2023 6:41:08 PM
  [i] Docker start setup complete
02/18/2023 6:41:08 PM
02/18/2023 6:41:08 PM
  [i] pihole-FTL (no-daemon) will be started as pihole
02/18/2023 6:41:08 PM
02/18/2023 6:41:08 PM
s6-rc: info: service _startup successfully started
02/18/2023 6:41:08 PM
s6-rc: info: service pihole-FTL: starting
02/18/2023 6:41:08 PM
s6-rc: info: service pihole-FTL successfully started
02/18/2023 6:41:08 PM
s6-rc: info: service lighttpd: starting
02/18/2023 6:41:08 PM
s6-rc: info: service lighttpd successfully started
02/18/2023 6:41:08 PM
s6-rc: info: service _postFTL: starting
02/18/2023 6:41:08 PM
s6-rc: info: service _postFTL successfully started
02/18/2023 6:41:08 PM
s6-rc: info: service legacy-services: starting
02/18/2023 6:41:08 PM
  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
02/18/2023 6:41:08 PM
s6-rc: info: service legacy-services successfully started
02/18/2023 6:41:08 PM
  [i] Creating new gravity database
02/18/2023 6:41:08 PM
  [i] Migrating content of /etc/pihole/adlists.list into new database
02/18/2023 6:41:17 PM
  [✗] DNS resolution is currently unavailable
02/18/2023 6:41:53 PM
  [i] Time until retry: 120
  [i] Time until retry: 120
  [i] Time until retry: 119
  [i] Time until retry: 118
  [i] Time until retry: 117
  [i] Time until retry: 116
  [i] Time until retry: 115
  [i] Time until retry: 114
  [i] Time until retry: 113
  [i] Time until retry: 112
  [i] Time until retry: 111
  [i] Time until retry: 110
  [i] Time until retry: 109
  [i] Time until retry: 108
  [i] Time until retry: 107
  [i] Time until retry: 106
  [i] Time until retry: 105
  [i] Time until retry: 104
  [i] Time until retry: 103Stopping pihole-FTL
```

Content of `setupVars.conf`:
```
INSTALL_WEB_INTERFACE=true
WEBPASSWORD=hashwashere
PIHOLE_INTERFACE=eth0
DNSMASQ_LISTENING=all
QUERY_LOGGING=true
BLOCKING_ENABLED=true
TEMPERATUREUNIT=C
PIHOLE_DNS_1=8.8.8.8
PIHOLE_DNS_2=1.1.1.1
PIHOLE_DNS_3=1.0.0.1
DNS_FQDN_REQUIRED=false
DNS_BOGUS_PRIV=false
DNSSEC=false
REV_SERVER=false
```

**Comment by alparo** [comment]
I have the same issue with the latest pihole image, debian and docker compose. DNS resolution is not available.

`s6-rc: info: service lighttpd: starting
s6-rc: info: service lighttpd successfully started
s6-rc: info: service _postFTL: starting
s6-rc: info: service _postFTL successfully started
  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
  [✗] DNS resolution is currently unavailable
  [✗] DNS resolution is not available
/opt/pihole/gravity.sh: line 362: echo: write error: Broken pipe
/opt/pihole/gravity.sh: line 362: echo: write error: Broken pipe
/opt/pihole/gravity.sh: line 362: echo: write error: Broken pipe
/opt/pihole/gravity.sh: line 362: echo: write error: Broken pipe
/opt/pihole/gravity.sh: line 362: echo: write error: Broken pipe
/opt/pihole/gravity.sh: line 362: echo: write error: Broken pipe`

**Comment by dschaper** [comment]
Do you have a `pihole-FTL.conf` file in your volume that contains data?

Your yaml has:
`      - FTLCONF_LOCAL_IPV4=10.4.0.10`
But the log output shows:
`  [i] Applying pihole-FTL.conf setting LOCAL_IPV4=0.0.0.0`

Did you actually type this line or did you change it for this paste?
`WEBPASSWORD=hashwouldgohere but i swapped to password file so it doesnt`

**Comment by DarkCeptor44** [comment]
> Do you have a pihole-FTL.conf file in your volume that contains data?

Yes:
```
#; Pi-hole FTL config file
#; Comments should start with #; to avoid issues with PHP and bash reading this file
MACVENDORDB=/macvendor.db
LOCAL_IPV4=10.4.0.10
RATE_LIMIT=1000/60
REPLY_ADDR4=10.4.0.10
```

> But the log output shows:

Sorry it's all a mess since I've deleted everything multiple times and tried different yaml/settings multiple times without updating certain things in here like the logs, [these](https://pastebin.com/kwpvbTVB) should be the latest ones.

> Did you actually type this line or did you change it for this paste?

Yeah the real value is just empty because it uses a separate file with the password now.

**Comment by dschaper** [comment]
> Yeah the real value is just empty because it uses a separate file with the password now.

And how did you set that up? I don't see a `WEBPASSWORD_FILE` environment variable, in fact I see a `WEBPASSWORD` env var set.

**Comment by dschaper** [comment]
Also note this may apply to you;
![image](https://user-images.githubusercontent.com/2782850/220012300-fd9b8ebb-7fb6-4348-a4ec-6fdc2ab5ed2b.png)

**Comment by DarkCeptor44** [comment]
> And how did you set that up? I don't see a `WEBPASSWORD_FILE` environment variable, in fact I see a `WEBPASSWORD` env var set.

Like I said some things I forgot to change in this post.

> Also note this may apply to you:

That did fix it, I could've sworn I tried that option before passing 1.1.1.1 as well and it didn't work at the time, for future reference this is the yaml now (with the password thing):
```yaml
version: "3.3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole.lab
    dns:
      - 127.0.0.1
    ports:
      - 53:53/tcp
      - 53:53/udp
      #- 67:67/udp
      - 8080:80/tcp
    environment:
      - TZ=America/Sao_Paulo
      - WEBPASSWORD=
      - WEBPASSWORD_FILE=password
      - DNSMASQ_LISTENING=all
      - VIRTUAL_HOST=pihole.lab
      - PROXY_LOCATION=pihole.lab
      - FTLCONF_LOCAL_IPV4=10.4.0.10
      - PIHOLE_DNS_=8.8.8.8;1.1.1.1
    volumes:
      - /home/darkceptor44/docker/data/pihole/data:/etc/pihole
      - /home/darkceptor44/docker/data/pihole/dnsmasq.d:/etc/dnsmasq.d
    #cap_add:
    #  - NET_ADMIN
    restart: always
```

I kind of want to get back to using `pi.hole` as the host but I'm scared of changing anything at this point, either way I'm closing this issue since it's fixed, sorry if it was a big waste of time, I am pretty new to Docker, Linux and self-hosting in general.
