### ISSUE TITLE
New themes with WEBTHEME variable

### ISSUE THREAD

**Issue by petcat30** [pi-hole/docker-pi-hole#1337]
This is a: Bug  

## Details

I am unable to set the web theme to 'High contrast dark' with the environment variable: WEBTHEME: 'high-contrast-dark'. Am I using the wrong name?
## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu 22.04 LTS
  * Hardware: Libre Computer Le Potato

2. docker-compose.yml 
```
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: lepotato
    ports:
      - "192.168.1.101:53:53/tcp"
      - "192.168.1.101:53:53/udp"
      - "192.168.1.101:80:80/tcp"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'piadmin'
      FTLCONF_LOCAL_IPV4: '192.168.1.101'
      PIHOLE_DNS_: '9.9.9.9;149.112.112.112'
      DNSMASQ_LISTENING: 'all'
      DNS_FQDN_REQUIRED: "true"
      DNS_BOGUS_PRIV: "true"
      WEBTHEME: 'high-contrast-dark'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
```

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
