### ISSUE TITLE
Default Pihole Docker-Image: read-only database

### ISSUE THREAD

**Issue by eals2019** [pi-hole/docker-pi-hole#1341]
This is a: Bug (Update Request for Docker Image) 

## Details

This is a known issue, but I wanted to specifically request that the docker image be updated so that this doesn't happen when pulling new docker Pihole images. Essentially, it seems the the /etc/pihole directory within the default Docker container image doesn't have the correct permissions assigned, so we are unable to write to the database. Instead, we get an error message warning us that we are attempting to write to a read-only database. In my situation, I was unable to add domains to the blacklist or enter additional adlists. The solution is simple and known; simply update the ownership of the file within the docker container using the following command:

** - docker exec pihole chown -R www-data:pihole /etc/pihole**

Hopefully this is helpful to someone. I wanted to report this an request that the docker image be updated if possible. It looks like the referenced Related Issues are from +1 year ago.

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

https://discourse.pi-hole.net/t/default-pi-image-read-only-database/61049
GitHub Issue https://github.com/pi-hole/docker-pi-hole/issues/860
- ![image](https://user-images.githubusercontent.com/126339760/228937627-b6ea43e6-dc91-4728-941d-27406f7f1bbc.png)

## How to reproduce the issue 

1. Environment data
  * Operating System: **Ubuntu** 
  * Hardware: Intel NUC 
  * Kernel Architecture: x86/amd64 
  * Docker Install Info and version: 
    - Software source: official docker-ce 
    - Supplimentary Software: Also making use of Nginx as proxy manager; should be irrelevant 
  * Hardware architecture: unknown

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
---
![image](https://user-images.githubusercontent.com/126339760/228936263-e4f733ea-06ff-42cb-8d69-414b75b41694.png)
```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      #- "81:80/tcp" #Switched to port 8080 while setting up Nginx
      #- "8080:80/tcp"
    environment:
      TZ: 'America/Chicago'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    networks:
      - network1

networks:
  network1:
    name: Websites
    external: true
```
---
4. any additional info to help reproduce
 - Simply pulled the latest docker container and ran the container using the previous docker-compose script.

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

 - As mentioned in the description, I believe the root cause of this issue is improperly set ownership of the /etc/pihole within the docker container. It was a simple adjustment to the container to fix this. However, it is possible that I am wrong, or that this is fix doesn't actually address a deeper root issue. Take it for what it's worth.
 **- docker exec pihole chown -R www-data:pihole /etc/pihole**
