### ISSUE TITLE
Double dir in /etc

### ISSUE THREAD

**Issue by pippo73** [pi-hole/docker-pi-hole#1346]
This is a: am I the only one who has a double dir in etc for pihole?

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System:
  *
``` # cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```
  * Hardware: 
  * Kernel Architecture: 
  * Docker Install Info and version: 
    - Software source: 
    - Supplimentary Software: 
  * Hardware architecture: 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

**portainer stack**

```
# https://github.com/pi-hole/docker-pi-hole/
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "81:80/tcp"
    environment:
      TZ: 'Europe/Rome'
      # WEBPASSWORD: 'set a secure password here or it will be random'
      WEBPASSWORD: p
    # Volumes store your data between container upgrades
    volumes:
      - /home/z-lmutt/PIHole/etc-pihole:/etc/pihole'
      - /home/z-lmutt/PIHole/etc-dnsmasq.d:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

```

3. any additional info to help reproduce

```
# ls -la /etc

<...>
drwxr-xr-x 3 root   root    4096 Mar 19 08:09  perl
drwxr-xr-x 3 root   root    4096 Mar 19 08:10  php
drwxrwxr-x 1 pihole pihole  4096 Apr 21 09:38  pihole                                       <-
drwxrwxr-x 3 pihole pihole  4096 Apr 20 18:58 "pihole'"                                    <- 
-rw-r--r-- 1 root   root     769 Apr 10  2021  profile
drwxr-xr-x 2 root   root    4096 Dec  9 20:15  profile.d
drwxr-xr-x 1 root   root    4096 Mar 25 20:20  rc0.d
drwxr-xr-x 1 root   root    4096 Mar 25 20:20  rc1.d
<...>
```
