### ISSUE TITLE
Blurry fonts in Total queries and Client activity graphs x axis

### ISSUE THREAD

**Issue by 56k-modem** [pi-hole/docker-pi-hole#1355]
This is a: Bug 

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Debian GNU/Linux 11 (bullseye)** 
  * Hardware: HP Compaq Elite 8300 
  * Kernel Architecture: x86_64 
  * Docker Install Info and version: 
    - Software source: official docker-ce 
    - Supplimentary Software: none 
  * Hardware architecture: x86_64 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

```
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: 'Europe/redacted'
      WEBPASSWORD: 'redacted'
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      DHCP_ACTIVE: "true"
      DHCP_START: 192.168.88.20
      DHCP_END: 192.168.88.254
      DHCP_ROUTER: 192.168.88.1
      DHCP_LEASETIME: 168
      PIHOLE_DOMAIN: lan
      INTERFACE: 'eno1'
      DNSMASQ_LISTENING: 'local'
      FTLCONF_LOCAL_IPV4: '192.168.88.8'
      FTLCONF_RATE_LIMIT: '1000/60'
      FTLCONF_REPLY_WHEN_BUSY: 'DROP'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

4. any additional info to help reproduce

Here is the problem:
![2023-05-29 15_31_18-Window](https://github.com/pi-hole/docker-pi-hole/assets/68462376/8cd3f34a-2705-49e5-b445-2e598c96da47)

The issue is present in Windows 10 under the latest Chrome browser upon visiting http://pi.hole/admin/ with font smoothing and ClearType turned off in the OS.

Cropped image: 
![2023-05-29 15_10_44-Window](https://github.com/pi-hole/docker-pi-hole/assets/68462376/e721ce90-65f2-46c4-a6c4-7298ddfb3a3d)

Note: Not all of the fonts are blurry, for example the left side of the axis is showing correctly:
![2023-05-29 15_24_44-Window](https://github.com/pi-hole/docker-pi-hole/assets/68462376/9e8bf4d8-ca32-4826-8091-f1aec28232b6)

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
