### ISSUE TITLE
"DNS resolution is currently unavailable" + "DNS resolution is not available" for GravityUpdate

### ISSUE THREAD

**Issue by thomasmerz** [pi-hole/docker-pi-hole#1364]
This is a: **Bug**  

## Details
When doing an update for Gravity DB by `docker exec -it pihole pihole -g` I get this error and nothing will/can't be updated at all:
```
🦎 thomas@merz-nimbus:~/dev [1/3888]
16:47 $ dig web.de @localhost
web.de.			3570	IN	A	82.165.229.138
web.de.			3570	IN	A	82.165.229.83

🦎 thomas@merz-nimbus:~/dev [1/3889]
16:47 $ docker exec -it pihole pihole -g
  [✗] DNS resolution is currently unavailable
  [✗] DNS resolution is not available

🦎 thomas@merz-nimbus:~/dev [1/3895]
16:52 $ dig pi.hole @localhost
pi.hole.		0	IN	A	0.0.0.0

🦎 thomas@merz-nimbus:~/dev [1/3896]
16:53 $ pgrep pihole-FTL
18701

🦎 thomas@merz-nimbus:~/dev/docker-your_spotify [1/3897]
16:53 $ docker exec -it pihole pgrep pihole-FTL
485
```

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

I think it might be related somehow to [these lines](https://github.com/pi-hole/pi-hole/blob/master/gravity.sh#L349-L369), but I didn't get it, WHY it's failing at my Pi-hole at home (and NOT on any of my other docker-pi-hole containers in my cloudservers that are configured identically)

## How to reproduce the issue 

1. Environment data
  * Operating System: **Docker** on OpenSUSE 15.4
  * Hardware: PC
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: Docker version 23.0.6-ce, build 9dbdbd4b6d76
    - Software source: offical OpenSUSE repo "Update repository with updates from SUSE Linux Enterprise 15"
  * Hardware architecture: x86

2. docker-compose.yml contents:
```
version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    hostname: 'pihole-merz-nimbus'
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # Enabling HTTPS for your Pi-hole Web Interface
      # https://discourse.pi-hole.net/t/enabling-https-for-your-pi-hole-web-interface/5771
      - './etc-lighttpd-external.conf:/etc/lighttpd/conf-enabled/20-external.conf'
      - './etc-letsencrypt:/etc/letsencrypt/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      ### As of `2022.04.01`, setting `CAP_NET_ADMIN` is only required if you are using Pi-hole as your DHCP server.
      ###- NET_ADMIN
      - CAP_SYS_NICE
```
## These common fixes didn't work for my issue

- [ ] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
