### ISSUE TITLE
Logrotate

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/docker-pi-hole#1387]
We need a mechanism to ensure logrotate is working

**Comment by edgd1er** [comment]
ideas:
* check if log is listed in var/lib/logrotate/status
* according to rotation (daily, weekly, monthly), log creation date is ok.
* 
https://serverfault.com/questions/189320/how-can-i-monitor-what-logrotate-is-doing

**Comment by buxm** [comment]
So I suppose mine is a known issue...
I've just realised my pihole.log is 8GB and my FTL.log is 70MB.
Both stopped rotating back in August 2022.
I'm running release 2024.02.0 on Synology DSM 7.1.1-42962 Update 6.

Here is what I've tried:
```
#docker exec -it pihole1 bash
root@pihole1:/# ls -lah /var/log/pihole
total 8.1G
drwx------ 1 www-data    999  290 Aug 25  2022 .
drwxr-xr-x 1 root     root    174 Feb 20 22:33 ..
-rw-r--r-- 1 www-data pihole  70M Feb 20 22:42 FTL.log
-rwx------ 1 root     root    14K Aug 25  2022 FTL.log.1
-rwx------ 1 root     root   2.5K Aug 24  2022 FTL.log.2.gz
-rwx------ 1 root     root    20K Aug 23  2022 FTL.log.3.gz
-rwx------ 1 root     root    19M Jul  9  2022 pihole-FTL.log
-rw-r--r-- 1 www-data pihole 8.0G Feb 20 22:49 pihole.log
-rwx------ 1 root     root   9.3M Aug 25  2022 pihole.log.1
-rwx------ 1 root     root   849K Aug 24  2022 pihole.log.2.gz
-rwx------ 1 root     root   703K Aug 23  2022 pihole.log.3.gz
-rwx------ 1 root     root   880K Aug 22  2022 pihole.log.4.gz
-rwx------ 1 www-data root   8.4K Feb 20 22:05 pihole_updateGravity.log
root@pihole1:/# pihole flush once
  [i] Flushing /var/log/pihole/pihole.log ...error: Ignoring /etc/pihole/logrotate because the file owner is wrong (should be root or user with uid 0).
  [✓] Flushed /var/log/pihole/pihole.log
  [✓] Deleted  queries from database
```
I've tried to force root ownership of the log files:
```
root@pihole1:/# chown root:root /var/log/pihole/pihole.log /var/log/pihole/pihole-FTL.log
root@pihole1:/# ls -lah /var/log/pihole
total 8.1G
drwx------ 1 www-data    999  290 Aug 25  2022 .
drwxr-xr-x 1 root     root    174 Feb 20 22:33 ..
-rw-r--r-- 1 www-data pihole  70M Feb 20 22:50 FTL.log
-rwx------ 1 root     root    14K Aug 25  2022 FTL.log.1
-rwx------ 1 root     root   2.5K Aug 24  2022 FTL.log.2.gz
-rwx------ 1 root     root    20K Aug 23  2022 FTL.log.3.gz
-rwx------ 1 root     root    19M Jul  9  2022 pihole-FTL.log
-rw-r--r-- 1 root     root   8.0G Feb 20 22:54 pihole.log
-rwx------ 1 root     root   9.3M Aug 25  2022 pihole.log.1
-rwx------ 1 root     root   849K Aug 24  2022 pihole.log.2.gz
-rwx------ 1 root     root   703K Aug 23  2022 pihole.log.3.gz
-rwx------ 1 root     root   880K Aug 22  2022 pihole.log.4.gz
-rwx------ 1 www-data root   8.4K Feb 20 22:05 pihole_updateGravity.log
root@pihole1:/# pihole flush once
  [i] Flushing /var/log/pihole/pihole.log ...error: Ignoring /etc/pihole/logrotate because the file owner is wrong (should be root or user with uid 0).
  [✓] Flushed /var/log/pihole/pihole.log
  [✓] Deleted  queries from database
```
If I restart the container, the ownership of the pihole.log is restored to the previous values:
```
#docker restart pihole1
pihole1
# docker exec -it pihole1 bash
root@pihole1:/# ls -lah /var/log/pihole
total 8.1G
drwx------ 1 www-data    999  290 Aug 25  2022 .
drwxr-xr-x 1 root     root    174 Feb 20 22:33 ..
-rw-r--r-- 1 www-data pihole  70M Feb 20 22:55 FTL.log
-rwx------ 1 root     root    14K Aug 25  2022 FTL.log.1
-rwx------ 1 root     root   2.5K Aug 24  2022 FTL.log.2.gz
-rwx------ 1 root     root    20K Aug 23  2022 FTL.log.3.gz
-rwx------ 1 root     root    19M Jul  9  2022 pihole-FTL.log
-rw-r--r-- 1 www-data pihole 8.0G Feb 20 22:55 pihole.log
-rwx------ 1 root     root   9.3M Aug 25  2022 pihole.log.1
-rwx------ 1 root     root   849K Aug 24  2022 pihole.log.2.gz
-rwx------ 1 root     root   703K Aug 23  2022 pihole.log.3.gz
-rwx------ 1 root     root   880K Aug 22  2022 pihole.log.4.gz
-rwx------ 1 www-data root   8.4K Feb 20 22:05 pihole_updateGravity.log
```

I'm running pihole using the following `docker-compose.yaml`
```
version: '3.7'

networks:
  
  # references externally defined network host_lan, see docker-create-host_lan.sh
  host_lan:
    external: true
  
services:
  pihole:
    container_name: ${PIHOLE_CONTAINER_NAME1}
    image: ${PIHOLE_IMG_NAME}:${TAG:-latest}
    hostname: ${PIHOLE_HOSTNAME1}
    domainname: ${DOMAIN_NAME}

    networks:
      # connect to host_lan with static IP address
      host_lan:
        ipv4_address: ${IPV4_PIHOLE1}
    
    # set DNS servers required by pihole
    dns:
      - 127.0.0.1
      - 8.8.8.8

    # set environment as required by pihole
    env_file: pihole.env
    environment:
      
      FTLCONF_LOCAL_IPV4: ${IPV4_PIHOLE1}
      
    volumes:
    # set volume binding as required by pihole
      - ${HOST_DOCKER_DIR}/${PIHOLE_CONTAINER_NAME1}/etc/pihole:/etc/pihole
      - ${HOST_DOCKER_DIR}/${PIHOLE_CONTAINER_NAME1}/etc/dnsmasq.d:/etc/dnsmasq.d
      - ${HOST_DOCKER_DIR}/${PIHOLE_CONTAINER_NAME1}/log/:/var/log/pihole
    
    restart: unless-stopped

    healthcheck:
      disable: true
```
and this is my `pihole.env`
```
WEBPASSWORD=xxxxxxx
TZ=Europe/Rome
VIRTUAL_HOST=pihole.mydomain.com
REV_SERVER=true
REV_SERVER_TARGET=192.168.1.80
REV_SERVER_DOMAIN=mydomain.com
REV_SERVER_CIDR=192.168.1.1/24
PIHOLE_DNS_=192.168.1.80
WEBTHEME=default-auto
PIHOLE_UID=1041
PIHOLE_GID=100
WEB_UID=1041
WEB_GID=100
```

**Comment by rdwebdesign** [comment]
Do you see the same behavior if you remove `WEB_UID` and `WEB_GID` variables?

**Comment by buxm** [comment]
@rdwebdesign yes, even if I remove those variables and recreate the container, I see the same behaviour.

**Comment by iamdoubz** [comment]
I went to "mirror" my PiHole to another server and I saw that my `pihole.log` was over 11GB!

There is a `logrotate` file in my "pihole" storage directory and it contains the right data to logrotate, but doesn't appear to run. There are 6 files in the `/etc/logrotate.d` directory: alternatives, apt, btmp, dpkg, lighttpd, wtmp. But no pihole. I copied the contents of these files, created a new directory to store these files, copied the files there, then also copied the `logrotate` file.

Initially, I got an error, but it wanted the files to be "root" created so I did that.

Then I tested logrotate with command `logrotate -d /etc/logrotate.d/logrotate`. It appeared to work!

Hope this helps someone...

**Comment by PromoFaux** [comment]
Have just checked my running v6 container and logrotate certainly appears to be working correctly here:

```
dev-v6:/# ls -lah /var/log/pihole
total 9.0M
drwxr-xr-x 1 pihole pihole  348 Mar 29 00:00 .
drwxr-xr-x 1 root   root     60 Mar 15 21:30 ..
-rw-r----- 1 pihole pihole  14K Mar 29 21:57 FTL.log
-rw-r----- 1 pihole pihole  15K Mar 29 00:00 FTL.log.1
-rw-r----- 1 pihole pihole 1.4K Mar 28 00:00 FTL.log.2.gz
-rw-r----- 1 pihole pihole 1.3K Mar 27 00:00 FTL.log.3.gz
-rw-r----- 1 pihole pihole 4.8M Mar 29 21:57 pihole.log
-rw-r----- 1 pihole pihole 3.1M Mar 29 00:00 pihole.log.1
-rw-r----- 1 pihole pihole 413K Mar 28 00:00 pihole.log.2.gz
-rw-r----- 1 pihole pihole 286K Mar 27 00:00 pihole.log.3.gz
-rw-r----- 1 pihole pihole 236K Mar 26 00:00 pihole.log.4.gz
-rw-r----- 1 pihole pihole 205K Mar 25 00:00 pihole.log.5.gz
-rw-r--r-- 1 root   root   1.2K Mar 23 03:25 pihole_updateGravity.log
-rw-r----- 1 pihole pihole    0 Mar 16 00:00 webserver.log
-rw-r----- 1 pihole pihole  424 Mar 16 00:00 webserver.log.1
```

Which is fired nightly by `cron`

```
dev-v6:/# cat /etc/crontabs/root 
25 3 * * 6 PATH="$PATH:/usr/sbin:/usr/local/bin/" pihole updateGravity >/var/log/pihole/pihole_updateGravity.log || cat /var/log/pihole/pihole_updateGravity.log
00 00 * * * PATH="$PATH:/usr/sbin:/usr/local/bin/" pihole flush once quiet
3 19 * * * PATH="$PATH:/usr/sbin:/usr/local/bin/" pihole updatechecker
```

Looking at the command that is run (`pihole flush once quiet`) we see this code:

![image](https://github.com/pi-hole/docker-pi-hole/assets/1998970/d71999e6-f6c7-4f1e-a956-ca205402269f)


And the same in my v5 container:

```
root@docker-pihole-pi4:/# ls -lah /var/log/pihole
total 158M
drwxr-xr-x 1 root   root   4.0K Mar 29 21:55 .
drwxr-xr-x 1 root   root   4.0K Mar  1 06:44 ..
-rw-r--r-- 1 pihole pihole 216K Mar 29 21:58 FTL.log
-rw-r--r-- 1 pihole pihole  99M Mar 29 21:55 FTL.log.1
-rw-r--r-- 1 pihole pihole 7.5M Mar 29 00:00 FTL.log.2.gz
-rw-r--r-- 1 pihole pihole 8.8M Mar 28 00:00 FTL.log.3.gz
-rw-r--r-- 1 pihole pihole  75K Mar 29 21:58 pihole.log
-rw-r--r-- 1 pihole pihole  33M Mar 29 21:55 pihole.log.1
-rw-r--r-- 1 pihole pihole 2.2M Mar 29 00:00 pihole.log.2.gz
-rw-r--r-- 1 pihole pihole 2.5M Mar 28 00:00 pihole.log.3.gz
-rw-r--r-- 1 pihole pihole 2.9M Mar 27 00:00 pihole.log.4.gz
-rw-r--r-- 1 pihole pihole 2.9M Mar 26 00:00 pihole.log.5.gz
-rw-r----- 1 root   pihole  34K Jan  3 17:46 pihole_debug.log
-rw-r--r-- 1 root   root   1.2K Mar 24 04:33 pihole_updateGravity.log
```

**Comment by PromoFaux** [comment]
Does anyone in this thread still have problems with the logs not being rotated?

**Comment by buxm** [comment]
@PromoFaux yes, the problems I reported earlier are still there:
```
$ sudo docker exec -it pihole1 bash
root@pihole1:/# pihole flush once
  [i] Flushing /var/log/pihole/pihole.log ...error: Ignoring /etc/pihole/logrotate because the file owner is wrong (should be root or user with uid 0).
  [✓] Flushed /var/log/pihole/pihole.log
  [✓] Deleted  queries from database
root@pihole1:/#
exit
$ ls -lah /volume1/docker/pihole1/log/
total 9.6G
drwxrwxrwx+ 1 pihole synopkgs  290 Aug 25  2022 .
drwxrwxrwx+ 1 pihole users      12 Jan 26  2020 ..
-rw-r--r--  1 pihole     1000  96M May  8 22:34 FTL.log
-rwxrwxrwx+ 1 root   root      14K Aug 25  2022 FTL.log.1
-rwxrwxrwx+ 1 root   root     2.5K Aug 24  2022 FTL.log.2.gz
-rwxrwxrwx+ 1 root   root      20K Aug 23  2022 FTL.log.3.gz
-rwxrwxrwx+ 1 root   root      19M Jul  9  2022 pihole-FTL.log
-rw-r--r--  1 pihole     1000 9.5G May  8 22:34 pihole.log
-rwxrwxrwx+ 1 root   root     9.3M Aug 25  2022 pihole.log.1
-rwxrwxrwx+ 1 root   root     849K Aug 24  2022 pihole.log.2.gz
-rwxrwxrwx+ 1 root   root     703K Aug 23  2022 pihole.log.3.gz
-rwxrwxrwx+ 1 root   root     880K Aug 22  2022 pihole.log.4.gz
-rwxrwxrwx+ 1 pihole root     7.5K May  5 03:42 pihole_updateGravity.log
```

**Comment by buxm** [comment]
my compose file:
```
version: '3.7'

networks:
  
  # references externally defined network host_lan, see docker-create-host_lan.sh
  host_lan:
    external: true
  
services:
  pihole:
    container_name: ${PIHOLE_CONTAINER_NAME1}
    image: ${PIHOLE_IMG_NAME}:${TAG:-latest}
    hostname: ${PIHOLE_HOSTNAME1}
    domainname: ${DOMAIN_NAME}

    networks:
      # connect to host_lan with static IP address
      host_lan:
        ipv4_address: ${IPV4_PIHOLE1}
    
    # set DNS servers required by pihole
    dns:
      - 127.0.0.1
      - 8.8.8.8

    # set environment as required by pihole
    env_file: pihole.env
    environment:
      
      FTLCONF_LOCAL_IPV4: ${IPV4_PIHOLE1}
      
    volumes:
    # set volume binding as required by pihole
      - ${HOST_DOCKER_DIR}/${PIHOLE_CONTAINER_NAME1}/etc/pihole:/etc/pihole
      - ${HOST_DOCKER_DIR}/${PIHOLE_CONTAINER_NAME1}/etc/dnsmasq.d:/etc/dnsmasq.d
      - ${HOST_DOCKER_DIR}/${PIHOLE_CONTAINER_NAME1}/log/:/var/log/pihole
    
    restart: unless-stopped

    healthcheck:
      disable: true
```

my `pihole.env`:
```
WEBPASSWORD=xxxxxxx
TZ=Europe/Rome
VIRTUAL_HOST=pihole.mydomain.com
REV_SERVER=true
REV_SERVER_TARGET=192.168.1.80
REV_SERVER_DOMAIN=mydomain.com
REV_SERVER_CIDR=192.168.1.1/24
PIHOLE_DNS_=192.168.1.80
WEBTHEME=default-auto
PIHOLE_UID=1041
PIHOLE_GID=100
WEB_UID=1041
WEB_GID=100
```

No, I haven't tried the beta v6 image.
