### ISSUE TITLE
Can't fix:  Stopping pihole-FTL pihole-FTL: no process found

### ISSUE THREAD

**Issue by aronmgv** [pi-hole/docker-pi-hole#1414]
Like a week ago my pihole container started to be unreliable. I have noticed many logs of:
```
Stopping pihole-FTL
pihole-FTL: no process found
```
This happens sooner or later.. Now I cant get rid of this behavior. You notice that my setup is using Bind as the only upstream DNS forwarder, which then is using something public like Cloudflare. I ruled out issues with Bind using Couldflare servers directly..

Things I tried in order:
1) deleted `pihole-FTL.db`
2) deleted `pihole-FTL.conf` to force its default config
3) deleted whole pihole volume and configured it from scratch
    - added local entries into: `custom.list`

## How to reproduce the issue 

1. Environment data
  * Operating System: **Linux edoras 5.10.0-23-amd64 SMP Debian 5.10.179-2 (2023-07-14) x86_64 GNU/Linux**
  * Hardware: PC
  * Kernel Architecture: x86_64 
  * Docker Install Info and version: Docker version 24.0.4, build 3713ee1
    - Software source: docker-ce
    - Supplimentary Software: no
  * Hardware architecture: x86_64 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```yml
version: "3.7"

services:
  pihole:
    container_name: default.dns.pihole
    image: pihole/pihole:latest
    restart: always
    hostname: pihole
    networks:
      static-network:
        ipv4_address: 172.31.1.102
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 50009:80/tcp
    cap_add:
      - NET_ADMIN
    volumes:
      - $PWD/pihole/etc-pihole/:/etc/pihole/
      - $PWD/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
      - $PWD/resolv.conf:/etc/resolv.conf
    environment:
      - TZ=${TZ}
      - DNSMASQ_USER=root
      - VIRTUAL_HOST=pihole.example.com/admin/
      - WEBPASSWORD=***
      - DNS1=172.31.1.101#53
      - DNS2=no

  bind:
    container_name: default.dns.bind
    build: ./bind
    restart: always
    hostname: bind
    networks:
      static-network:
        ipv4_address: 172.31.1.101
    expose:
      - 53/tcp
      - 53/udp
    volumes:
      - $PWD/bind/config/:/etc/bind/
    environment:
      - TZ=${TZ}

networks:
  static-network:
    name: default.dns.pihole
    ipam:
      config:
        - subnet: 172.31.1.0/24
```

3. any additional info to help reproduce
```
default.dns.pihole  | s6-rc: info: service s6rc-oneshot-runner: starting
default.dns.pihole  | s6-rc: info: service s6rc-oneshot-runner successfully started
default.dns.pihole  | s6-rc: info: service fix-attrs: starting
default.dns.pihole  | s6-rc: info: service fix-attrs successfully started
default.dns.pihole  | s6-rc: info: service legacy-cont-init: starting
default.dns.pihole  | s6-rc: info: service legacy-cont-init successfully started
default.dns.pihole  | s6-rc: info: service cron: starting
default.dns.pihole  | s6-rc: info: service cron successfully started
default.dns.pihole  | s6-rc: info: service _uid-gid-changer: starting
default.dns.pihole  | s6-rc: info: service _uid-gid-changer successfully started
default.dns.pihole  | s6-rc: info: service _startup: starting
default.dns.pihole  |   [i] Starting docker specific checks & setup for docker pihole/pihole
default.dns.pihole  |   [i] Setting capabilities on pihole-FTL where possible
default.dns.pihole  |   [i] Applying the following caps to pihole-FTL:
default.dns.pihole  |         * CAP_CHOWN
default.dns.pihole  |         * CAP_NET_BIND_SERVICE
default.dns.pihole  |         * CAP_NET_RAW
default.dns.pihole  |         * CAP_NET_ADMIN
default.dns.pihole  |   [i] Ensuring basic configuration by re-running select functions from basic-install.sh
default.dns.pihole  |
default.dns.pihole  |   [i] Installing configs from /etc/.pihole...
default.dns.pihole  |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
default.dns.pihole  |
default.dns.pihole  |   [i] Installing latest logrotate script...
default.dns.pihole  |   [i] Existing logrotate file found. No changes made.
default.dns.pihole  |   [i] Assigning password defined by Environment Variable
default.dns.pihole  |   [✓] New password set
default.dns.pihole  |   [i] Added ENV to php:
default.dns.pihole  |                     "TZ" => "Europe/Prague",
default.dns.pihole  |                     "PIHOLE_DOCKER_TAG" => "",
default.dns.pihole  |                     "PHP_ERROR_LOG" => "/var/log/lighttpd/error-pihole.log",
default.dns.pihole  |                     "CORS_HOSTS" => "",
default.dns.pihole  |                     "VIRTUAL_HOST" => "pihole.example.com/admin/",
default.dns.pihole  |   [i] Using IPv4 and IPv6
default.dns.pihole  |
  [✓] Installing latest Cron script
default.dns.pihole  |   [i] Preexisting ad list /etc/pihole/adlists.list detected (exiting setup_blocklists early)
default.dns.pihole  |   [i] Converting DNS1 to PIHOLE_DNS_
default.dns.pihole  |   [i] Setting DNS servers based on PIHOLE_DNS_ variable
default.dns.pihole  |   [i] Applying pihole-FTL.conf setting LOCAL_IPV4=0.0.0.0
default.dns.pihole  |   [i] FTL binding to default interface: eth0
default.dns.pihole  |   [i] Enabling Query Logging
default.dns.pihole  |   [i] Testing lighttpd config: Syntax OK
default.dns.pihole  |   [i] All config checks passed, cleared for startup ...
default.dns.pihole  |   [i] Docker start setup complete
default.dns.pihole  |
default.dns.pihole  |   [i] pihole-FTL (no-daemon) will be started as root
default.dns.pihole  |
default.dns.pihole  | s6-rc: info: service _startup successfully started
default.dns.pihole  | s6-rc: info: service pihole-FTL: starting
default.dns.pihole  | s6-rc: info: service pihole-FTL successfully started
default.dns.pihole  | s6-rc: info: service lighttpd: starting
default.dns.pihole  | s6-rc: info: service lighttpd successfully started
default.dns.pihole  | s6-rc: info: service _postFTL: starting
default.dns.pihole  | s6-rc: info: service _postFTL successfully started
default.dns.pihole  | s6-rc: info: service legacy-services: starting
default.dns.pihole  |   Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
default.dns.pihole  | s6-rc: info: service legacy-services successfully started
default.dns.pihole  |   [✗] DNS resolution is currently unavailable
  [✓] DNS resolution is now available
default.dns.pihole  |
default.dns.pihole  |   [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range
default.dns.pihole  |
  [✓] Preparing new gravity database
  [✓] Creating new gravity databases
default.dns.pihole  |   [i] Using libz compression
default.dns.pihole  |
default.dns.pihole  |   [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [✓] Parsed 207330 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
default.dns.pihole  |       Sample of non-domain entries:
default.dns.pihole  |         - "0.0.0.0"
default.dns.pihole  |
default.dns.pihole  |   [i] List stayed unchanged
default.dns.pihole  |
  [✓] Building tree
  [✓] Swapping databases
default.dns.pihole  |   [✓] The old database remains available
default.dns.pihole  |   [i] Number of gravity domains: 207330 (207330 unique domains)
default.dns.pihole  |   [i] Number of exact blacklisted domains: 0
default.dns.pihole  |   [i] Number of regex blacklist filters: 0
default.dns.pihole  |   [i] Number of exact whitelisted domains: 0
default.dns.pihole  |   [i] Number of regex whitelist filters: 0
  [✓] Cleaning up stray matter
default.dns.pihole  |
default.dns.pihole  |   [✓] FTL is listening on port 53
default.dns.pihole  |      [✓] UDP (IPv4)
default.dns.pihole  |      [✓] TCP (IPv4)
default.dns.pihole  |      [✓] UDP (IPv6)
default.dns.pihole  |      [✓] TCP (IPv6)
default.dns.pihole  |
default.dns.pihole  |   [✓] Pi-hole blocking is enabled
default.dns.pihole  |
default.dns.pihole  | Stopping pihole-FTL
default.dns.pihole  | pihole-FTL: no process found
default.dns.pihole  | fatal: unable to access 'https://github.com/pi-hole/pi-hole/': Could not resolve host: github.com
default.dns.pihole  | fatal: unable to access 'https://github.com/pi-hole/AdminLTE/': Could not resolve host: github.com
default.dns.pihole  | fatal: unable to access 'https://github.com/pi-hole/FTL/': Could not resolve host: github.com
default.dns.pihole  |   Pi-hole version is v5.17.1 (Latest: N/A)
default.dns.pihole  |   AdminLTE version is v5.20.1 (Latest: N/A)
default.dns.pihole  |   FTL version is v5.23 (Latest: N/A)
default.dns.pihole  |   Container tag is: 2023.05.2
default.dns.pihole  |
default.dns.pihole  | Stopping pihole-FTL
default.dns.pihole  | pihole-FTL: no process found
default.dns.pihole  | Stopping pihole-FTL
default.dns.pihole  | pihole-FTL: no process found
default.dns.pihole  | Stopping pihole-FTL
default.dns.pihole  | pihole-FTL: no process found
```

## These common fixes didn't work for my issue
- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

**Comment by aronmgv** [comment]
Just tried to replicate from scratch without custom config I had before and still it will start failing after approximately 10-12 hours of running without issues. Does anybody have any clue? My setup was running okay for over a year and suddenly `pihole-FTL` process starts crashing..

```yml
version: "3.7"

services:
  pihole:
    container_name: default.dns.pihole
    image: pihole/pihole:latest
    restart: always
    hostname: pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 50009:80/tcp
    cap_add:
      - NET_ADMIN
    volumes:
      - $PWD/pihole/etc-pihole/:/etc/pihole/
      - $PWD/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
      - $PWD/custom.list:/etc/pihole/custom.list
      - $PWD/resolv.conf:/etc/resolv.conf
    environment:
      - TZ=${TZ}
      - DNSMASQ_USER=root
      - WEBPASSWORD=*
      - DNS1=1.1.1.1
      - DNS2=no
```

```
default.dns.pihole  | s6-rc: info: service s6rc-oneshot-runner: starting
default.dns.pihole  | s6-rc: info: service s6rc-oneshot-runner successfully started
default.dns.pihole  | s6-rc: info: service fix-attrs: starting
default.dns.pihole  | s6-rc: info: service fix-attrs successfully started
default.dns.pihole  | s6-rc: info: service legacy-cont-init: starting
default.dns.pihole  | s6-rc: info: service legacy-cont-init successfully started
default.dns.pihole  | s6-rc: info: service cron: starting
default.dns.pihole  | s6-rc: info: service cron successfully started
default.dns.pihole  | s6-rc: info: service _uid-gid-changer: starting
default.dns.pihole  | s6-rc: info: service _uid-gid-changer successfully started
default.dns.pihole  | s6-rc: info: service _startup: starting
default.dns.pihole  |   [i] Starting docker specific checks & setup for docker pihole/pihole
default.dns.pihole  |   [i] Setting capabilities on pihole-FTL where possible
default.dns.pihole  |   [i] Applying the following caps to pihole-FTL:
default.dns.pihole  |         * CAP_CHOWN
default.dns.pihole  |         * CAP_NET_BIND_SERVICE
default.dns.pihole  |         * CAP_NET_RAW
default.dns.pihole  |         * CAP_NET_ADMIN
default.dns.pihole  |   [i] Ensuring basic configuration by re-running select functions from basic-install.sh
default.dns.pihole  |
default.dns.pihole  |   [i] Installing configs from /etc/.pihole...
default.dns.pihole  |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
default.dns.pihole  |
default.dns.pihole  |   [i] Installing latest logrotate script...
default.dns.pihole  |   [i] Existing logrotate file found. No changes made.
default.dns.pihole  |   [i] Assigning password defined by Environment Variable
default.dns.pihole  |   [✓] New password set
default.dns.pihole  |   [i] Added ENV to php:
default.dns.pihole  |                     "TZ" => "Europe/Prague",
default.dns.pihole  |                     "PIHOLE_DOCKER_TAG" => "",
default.dns.pihole  |                     "PHP_ERROR_LOG" => "/var/log/lighttpd/error-pihole.log",
default.dns.pihole  |                     "CORS_HOSTS" => "",
default.dns.pihole  |                     "VIRTUAL_HOST" => "pihole",
default.dns.pihole  |   [i] Using IPv4 and IPv6
default.dns.pihole  |
  [✓] Installing latest Cron script
default.dns.pihole  |   [i] Preexisting ad list /etc/pihole/adlists.list detected (exiting setup_blocklists early)
default.dns.pihole  |   [i] Converting DNS1 to PIHOLE_DNS_
default.dns.pihole  |   [i] Setting DNS servers based on PIHOLE_DNS_ variable
default.dns.pihole  |   [i] Applying pihole-FTL.conf setting LOCAL_IPV4=0.0.0.0
default.dns.pihole  |   [i] FTL binding to default interface: eth0
default.dns.pihole  |   [i] Enabling Query Logging
default.dns.pihole  |   [i] Testing lighttpd config: Syntax OK
default.dns.pihole  |   [i] All config checks passed, cleared for startup ...
default.dns.pihole  |   [i] Docker start setup complete
default.dns.pihole  |
default.dns.pihole  |   [i] pihole-FTL (no-daemon) will be started as root
default.dns.pihole  |
default.dns.pihole  | s6-rc: info: service _startup successfully started
default.dns.pihole  | s6-rc: info: service pihole-FTL: starting
default.dns.pihole  | s6-rc: info: service pihole-FTL successfully started
default.dns.pihole  | s6-rc: info: service lighttpd: starting
default.dns.pihole  | s6-rc: info: service lighttpd successfully started
default.dns.pihole  | s6-rc: info: service _postFTL: starting
default.dns.pihole  | s6-rc: info: service _postFTL successfully started
default.dns.pihole  | s6-rc: info: service legacy-services: starting
default.dns.pihole  |   Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
default.dns.pihole  | s6-rc: info: service legacy-services successfully started
default.dns.pihole  |   [✗] DNS resolution is currently unavailable
  [i] Time until retry: 98Stopping pihole-FTL
default.dns.pihole  | pihole-FTL: no process found
  [i] Time until retry: 71Stopping pihole-FTL
default.dns.pihole  | pihole-FTL: no process found
  [i] Time until retry: 45Stopping pihole-FTL
default.dns.pihole  | pihole-FTL: no process found
  [i] Time until retry: 18Stopping pihole-FTL
default.dns.pihole  | pihole-FTL: no process found
  [✗] DNS resolution is not available
default.dns.pihole  | Stopping pihole-FTL
default.dns.pihole  | pihole-FTL: no process found
default.dns.pihole  | Stopping pihole-FTL
default.dns.pihole  | pihole-FTL: no process found
default.dns.pihole  | Stopping pihole-FTL
default.dns.pihole  | pihole-FTL: no process found
default.dns.pihole  | Stopping pihole-FTL
default.dns.pihole  | pihole-FTL: no process found
default.dns.pihole  | Stopping pihole-FTL
default.dns.pihole  | pihole-FTL: no process found
default.dns.pihole  | Stopping pihole-FTL
default.dns.pihole  | pihole-FTL: no process found
default.dns.pihole  | Stopping pihole-FTL
```
