### ISSUE TITLE
Stopping pihole-FTL pihole-FTL: no process found (Fresh installation from docker-compose example; Mac M2)

### ISSUE THREAD

**Issue by deimjons** [pi-hole/docker-pi-hole#1420]
Stopping pihole-FTL pihole-FTL: no process found

This is a: Run Issue (running Pi-hole container failing)

## Details

Hello. I have fresh installation dirrectly by example of docker-compose. When I try to access localhost:80  

I recive 403 Forbidden. In logs Stopping pihole-FTL pihole-FTL: no process found. 

## How to reproduce the issue 

1. Environment data
  * Operating System: Mac OS Ventura 13.5.1 (22G90) 
  * Hardware: Macbook air 15 M2 
  * Kernel Architecture: ARM V? 
  * Docker Install Info and version:  Docker Desktop 4.22.1 (118664)
    - Software source: 
    - Supplimentary Software: 
  * Hardware architecture: 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

```
version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped # Recommended but not required (DHCP needs NET_ADMIN)  
```

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by deimjons** [comment]
Hello again. For more than a week I played with Pihole and still no results.. Someone please help. I have a few updates, maybe it helps somehow:

I tried to login inside the container and run pihole-FTL process manually. In result I have received error: 

```
root@67a68c9df105:/# pihole-FTL

dnsmasq: cannot access /etc/dnsmasq.d/sedtAwl3w: No such file or directory
```

Then I tried to check what going on with permissions there: 

```
root@67a68c9df105:/# cd /etc/dnsmasq.d 
root@67a68c9df105:/etc/dnsmasq.d# ls -la
ls: cannot access 'sedtAwl3w': No such file or directory
total 16
drwxr-xr-x  6 root root  192 Sep  4 14:37 .
drwxr-xr-x  1 root root 4096 Sep  4 14:37 ..
-rw-r--r--  1 root root    0 Aug 28 16:04 .gitkeep
-rw-r--r--+ 1 root root 1334 Sep  4 14:37 01-pihole.conf
-rw-r--r--+ 1 root root 2190 Sep  4 14:37 06-rfc6761.conf
-?????????? ? ?    ?       ?            ? sedtAwl3w
```

If I just remove file sedtAwl3w from volume and reload container - error "pihole-FTL pihole-FTL: no process found" - disappears. 
But I have another error in logs of container: 

```
youruser@yourmachine compose % docker logs pihole --tail 50 -f
        - "# title: stevenblack/hosts"
        - "#"
        - "# this hosts file is a merged collection of hosts from reputable sources,"
        - "# with a dash of crowd sourcing via github"
        - "# date: 28 august 2023 22:49:47 (utc)"

  [i] List stayed unchanged

  [✓] Building tree
  [✓] Swapping databases
  [✓] The old database remains available
  [i] Number of gravity domains: 0 (0 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Cleaning up stray matter

  [✓] FTL is listening on port 53
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [i] Pi-hole blocking will be enabled
  [i] Enabling blocking
  [✓] Pi-hole Enabled

sed: couldn't open temporary file /etc/pihole/sedJQBaqa: Permission denied
sed: couldn't open temporary file /etc/pihole/sedBMzRhv: Permission denied
sed: couldn't open temporary file /etc/pihole/sedOcK59R: Permission denied
sed: couldn't open temporary file /etc/pihole/sedpobRnp: Permission denied
sed: couldn't open temporary file /etc/pihole/sedAzLTl6: Permission denied
sed: couldn't open temporary file /etc/pihole/sedF6hB5t: Permission denied
sed: couldn't open temporary file /etc/pihole/sedWcxoIP: Permission denied
sed: couldn't open temporary file /etc/pihole/sedoBRi0f: Permission denied
sed: couldn't open temporary file /etc/pihole/sedh599kJ: Permission denied
sed: couldn't open temporary file /etc/pihole/sedSTpN5s: Permission denied
sed: couldn't open temporary file /etc/pihole/sedfXmm9J: Permission denied
sed: couldn't open temporary file /etc/pihole/sedwVtCC3: Permission denied
sed: couldn't open temporary file /etc/pihole/sedpL5eEl: Permission denied
sed: couldn't open temporary file /etc/pihole/sed5G8afR: Permission denied
sed: couldn't open temporary file /etc/pihole/sedRf8CqA: Permission denied
sed: couldn't open temporary file /etc/pihole/sedZTaiQL: Permission denied
sed: couldn't open temporary file /etc/pihole/sedkUKpDj: Permission denied
  Pi-hole version is v5.17.1 (Latest: v5.17.1)
  AdminLTE version is v5.20.1 (Latest: v5.20.1)
  FTL version is v5.23 (Latest: v5.23)
  Container tag is: 2023.05.2
```

If I tried to access web panel of pihole I receive same error:  403 Forbidden

I tried to remove this files and reload container again but pihole creates this files again and I have this error again. 

If login into container and make la -la in /etc/pihole situation looks similar with file from /etc/dnsmasq.d/

```
root@0d2b4fb011f8:/# ls -la /etc//pihole/
ls: cannot access '/etc//pihole/sedxK83eb': No such file or directory
ls: cannot access '/etc//pihole/sedB8twrw': No such file or directory
ls: cannot access '/etc//pihole/sedUUg9Ap': No such file or directory
ls: cannot access '/etc//pihole/sedYiJKT6': No such file or directory
ls: cannot access '/etc//pihole/sedX4RI6L': No such file or directory
ls: cannot access '/etc//pihole/sed0huMwG': No such file or directory
ls: cannot access '/etc//pihole/sediddwQK': No such file or directory
ls: cannot access '/etc//pihole/sedcL2GTr': No such file or directory
ls: cannot access '/etc//pihole/seddrP4sF': No such file or directory
ls: cannot access '/etc//pihole/sedErIc24': No such file or directory
ls: cannot access '/etc//pihole/sed2yiW7t': No such file or directory
ls: cannot access '/etc//pihole/sed30yKht': No such file or directory
ls: cannot access '/etc//pihole/sedj7aSiF': No such file or directory
ls: cannot access '/etc//pihole/sedg7Wp7D': No such file or directory
ls: cannot access '/etc//pihole/sedjIAveP': No such file or directory
ls: cannot access '/etc//pihole/sedVi8mCL': No such file or directory
ls: cannot access '/etc//pihole/sedAfgGWm': No such file or directory
ls: cannot access '/etc//pihole/sedQR6KSa': No such file or directory
ls: cannot access '/etc//pihole/sedkI7b93': No such file or directory
ls: cannot access '/etc//pihole/sedysrmua': No such file or directory
ls: cannot access '/etc//pihole/sed2b3MIj': No such file or directory
ls: cannot access '/etc//pihole/sed2QXewj': No such file or directory
ls: cannot access '/etc//pihole/sedGmZlTZ': No such file or directory
ls: cannot access '/etc//pihole/sed26L18b': No such file or directory
ls: cannot access '/etc//pihole/sedbyXpUd': No such file or directory
ls: cannot access '/etc//pihole/sedwaWJhz': No such file or directory
ls: cannot access '/etc//pihole/sedtJ1DkQ': No such file or directory
ls: cannot access '/etc//pihole/sedPlj8NW': No such file or directory
ls: cannot access '/etc//pihole/sedirUtUK': No such file or directory
ls: cannot access '/etc//pihole/sedYeyoHZ': No such file or directory
ls: cannot access '/etc//pihole/sedLLQMXo': No such file or directory
ls: cannot access '/etc//pihole/sed98rmcZ': No such file or directory
ls: cannot access '/etc//pihole/sedLZJoPl': No such file or directory
ls: cannot access '/etc//pihole/sedG0O6QX': No such file or directory
ls: cannot access '/etc//pihole/sedIMDWEn': No such file or directory
ls: cannot access '/etc//pihole/sedyZriUb': No such file or directory
total 7544
drwxrwxr-x  53 pihole pihole    1696 Sep  4 14:47 .
drwxr-xr-x   1 root   root      4096 Sep  4 14:46 ..
-rw-r--r--+  1 root   pihole       0 Sep  4 14:37 custom.list
-rw-r--r--+  1 pihole pihole       0 Sep  4 14:37 dhcp.leases
-rw-r--r--   1 root   root       651 Sep  4 14:46 dns-servers.conf
-rw-rw-r--   1 pihole pihole   98304 Sep  4 14:46 gravity.db
-rw-rw-r--   1 pihole pihole   98304 Sep  4 14:43 gravity_old.db
-rw-r--r--   1 root   root   6885720 Sep  4 14:46 list.1.raw.githubusercontent.com.domains
-rw-r--r--   1 root   root        95 Sep  4 14:37 list.1.raw.githubusercontent.com.domains.sha1
-rw-r--r--   1 pihole pihole      65 Sep  4 14:46 local.list
-rw-r--r--+  1 root   root       229 Sep  4 14:37 logrotate
drwxr-xr-x   3 root   root        96 Sep  4 14:37 migration_backup
-rw-rw-r--+  1 pihole root       157 Sep  4 14:46 pihole-FTL.conf
-rw-rw-r--   1 pihole pihole   81920 Sep  4 14:47 pihole-FTL.db
-??????????  ? ?      ?            ?            ? sed0huMwG
-??????????  ? ?      ?            ?            ? sed26L18b
-??????????  ? ?      ?            ?            ? sed2QXewj
-??????????  ? ?      ?            ?            ? sed2b3MIj
-??????????  ? ?      ?            ?            ? sed2yiW7t
-??????????  ? ?      ?            ?            ? sed30yKht
-??????????  ? ?      ?            ?            ? sed98rmcZ
-??????????  ? ?      ?            ?            ? sedAfgGWm
-??????????  ? ?      ?            ?            ? sedB8twrw
-??????????  ? ?      ?            ?            ? sedErIc24
-??????????  ? ?      ?            ?            ? sedG0O6QX
-??????????  ? ?      ?            ?            ? sedGmZlTZ
-??????????  ? ?      ?            ?            ? sedIMDWEn
-??????????  ? ?      ?            ?            ? sedLLQMXo
-??????????  ? ?      ?            ?            ? sedLZJoPl
-??????????  ? ?      ?            ?            ? sedPlj8NW
-??????????  ? ?      ?            ?            ? sedQR6KSa
-??????????  ? ?      ?            ?            ? sedUUg9Ap
-??????????  ? ?      ?            ?            ? sedVi8mCL
-??????????  ? ?      ?            ?            ? sedX4RI6L
-??????????  ? ?      ?            ?            ? sedYeyoHZ
-??????????  ? ?      ?            ?            ? sedYiJKT6
-??????????  ? ?      ?            ?            ? sedbyXpUd
-??????????  ? ?      ?            ?            ? sedcL2GTr
-??????????  ? ?      ?            ?            ? seddrP4sF
-??????????  ? ?      ?            ?            ? sedg7Wp7D
-??????????  ? ?      ?            ?            ? sediddwQK
-??????????  ? ?      ?            ?            ? sedirUtUK
-??????????  ? ?      ?            ?            ? sedj7aSiF
-??????????  ? ?      ?            ?            ? sedjIAveP
-??????????  ? ?      ?            ?            ? sedkI7b93
-??????????  ? ?      ?            ?            ? sedtJ1DkQ
-??????????  ? ?      ?            ?            ? sedwaWJhz
-??????????  ? ?      ?            ?            ? sedxK83eb
-??????????  ? ?      ?            ?            ? sedyZriUb
-??????????  ? ?      ?            ?            ? sedysrmua
-rw-r--r--+  1 pihole pihole     209 Sep  4 14:43 setupVars.conf
-rw-r--r--   1 root   root       209 Sep  4 14:46 setupVars.conf.update.bak
-rw-r--r--   1 root   root       382 Sep  4 14:47 versions
root@0d2b4fb011f8:/# 
```

**Comment by edgd1er** [comment]
it looks like a right permissions problem, container's user cannot write to the mounted volumes.
from the container, you may try to create file as root and as pihole and see if the file is created and editable.

have a look to vars like PIHOLE_UID, PIHOLE_GID, WEB_UID, WEB_GID

**Comment by deimjons** [comment]
volumes before the test it is just empty folders. Container successfully writes all files except temporary files sed******. 

I read the documentation about  PIHOLE_UID, PIHOLE_GID, WEB_UID, WEB_GID. 
1) As I understand if I setup  DNSMASQ_USER: root I should make PIHOLE_UID the same id as root in my mac??? or root in linux VM what Mac runs for the docker?  Or it should be not root user, it should me my user?
2) Which group id I should setup for PIHOLE_GID? on my host machine I haven't pihole group. 
3) In documentation written that WEB_UID, WEB_GID should be not the same as PIHOLE_UID, PIHOLE_GID? which user id and group id I should use fort WEB_UID, WEB_GID? On my mac I haven't group and user www-data.

**Comment by SneWs** [comment]
The only way to get PiHole to properly work on macOS lately from what I've found out is to make sure to not map your volumes directly to disk, but rather to create a named volume. This will make sure that you don't have to fiddle around with FS level permissions etc.

Here is an example PiHole docker-compose that works on my M1 Mac Studio that you can use as a starting point.

```
version: "3"

volumes:
  web_data:
    name: pihole-data

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8001:80/tcp"
    environment:
      TZ: 'Europe/Stockholm'
      WEBPASSWORD: 'SET_A_STRONG_PWD_HERE'
    # Volumes store your data between container upgrades
    volumes:
      - 'web_data:/data/etc-pihole:/etc/pihole'
      - 'web_data:/data/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      #- NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
      - CAP_NET_BIND_SERVICE
      - CAP_SYS_NICE
      - CAP_CHOWN
    restart: always

```

Take note of the volume mapping
```
# This creates a named volume
volumes:
  web_data:
    name: pihole-data

... 

# And here we make use of the named volume instead of mapping it into a location on the physical FS
    volumes:
      - 'web_data:/data/etc-pihole:/etc/pihole'
      - 'web_data:/data/etc-dnsmasq.d:/etc/dnsmasq.d'
```

This will then show up as a Volume in Docker Desktop UI as well if you're using that
<img width="1253" alt="image" src="https://github.com/pi-hole/docker-pi-hole/assets/57133/53da4260-3e94-4e2f-8cc9-c4ca16cbc2d8">

Good luck!
