### ISSUE TITLE
Weird version behavior with Pihole on docker

### ISSUE THREAD

**Issue by Karbust** [pi-hole/docker-pi-hole#1421]
This is a: **Bug**  

## Details

This is the `version` file after I upgrade the image:
```
CORE_VERSION=v5.17.1
CORE_BRANCH=master
CORE_HASH=6a45c6a8
GITHUB_CORE_VERSION=v5.17.1
GITHUB_CORE_HASH=8495565a
WEB_VERSION=v5.20.1
WEB_BRANCH=master
WEB_HASH=3a11976e
GITHUB_WEB_VERSION=v5.20.1
GITHUB_WEB_HASH=41682f17
FTL_VERSION=v5.23
FTL_BRANCH=master
FTL_HASH=d201776e
GITHUB_FTL_VERSION=v5.23
GITHUB_FTL_HASH=1a114133
DOCKER_VERSION=2023.05.2
GITHUB_DOCKER_VERSION=2023.05.2
```

This is the `version` file after a few hours of upgrading the image:
```
CORE_VERSION=v5.16.2
CORE_BRANCH=master
CORE_HASH=d885e926
GITHUB_CORE_VERSION=v5.17.1
GITHUB_CORE_HASH=8495565a
WEB_VERSION=v5.19
WEB_BRANCH=master
WEB_HASH=d7f18428
GITHUB_WEB_VERSION=v5.20.1
GITHUB_WEB_HASH=41682f17
FTL_VERSION=v5.22
FTL_BRANCH=master
FTL_HASH=eb197891
GITHUB_FTL_VERSION=v5.23
GITHUB_FTL_HASH=1a114133
DOCKER_VERSION=2023.03.1
GITHUB_DOCKER_VERSION=2023.05.2
```

I even deleted the version file before trying again and it created with newer versions, but after a few hours it's like it rolls back...

After the upgrade the Web UI says `Docker Tag 2023.05.2`, but after a few hours goes back to `Docker Tag 2023.03.1 · Update available!`

What I used to use to upgrade the docker image:
```bash
sudo docker compose down
sudo docker image rm pihole/pihole:latest
sudo docker pull pihole/pihole:latest
sudo docker compose up -d
```
But, since it didn't work I just created the container manually on Portainer with all the env variables, the issue keeps happening.

This bug is not recent, has been happening for a while (practically since I upgraded to the new version when it came out).

Another thing I found weird was that on the last week (from 21 to 25) I had another weird issue were all my ad-lists disappeared, good thing was that I had a backup and was easy to add everything again (manually through the UI, the backup was for the previous installation I had on barebones on another computer).

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Debian GNU/Linux 11 (bullseye)** (downloaded from RaspberryPi's website)
  * Hardware: RaspberryPi 4B
  * Kernel Architecture: aarch64
  * Docker Install Info and version: 
    - Software source: official docker-ce
    - Supplimentary Software: portainer (also happens without using portainer)
  * Hardware architecture: aarch64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
docker-compose.yml:
```yaml
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: 'host'
    environment:
      WEB_BIND_ADDR: '0.0.0.0'
      TZ: 'Europe/Lisbon'
      WEBPASSWORD: '<password>'
      WEB_PORT: '3123'
      INTERFACE: 'eth0'
      DNSMASQ_LISTENING: 'all'
      ServerIP: '192.168.1.150'
      IPv6: 'false'
      DHCP_ACTIVE: 'true'
      DHCP_START: '192.168.1.5'
      DHCP_END: '192.168.1.60'
      DHCP_ROUTER: '192.168.1.254'
      DHCP_rapid_commit: 'true'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

Container on portainer:
![portainer](https://cdn.karbust.com/BedO8/wabUtuna60.png/raw)

3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
 * Stopped and removed the container, deleted the version file and created it again, the newer version file was created but after a while it was like before.
