### ISSUE TITLE
Permission denied when initializing configs

### ISSUE THREAD

**Issue by theJian** [pi-hole/docker-pi-hole#1432]
This is a: **Run Issue**  

## Details

I'm running Fedora 38 Silverblue, after copying `docker-compose.yml` and starting it by this command `podman-compose up -d`,  pihole failed to start.
I checked the logs and the directory created by pihole container, and it seemed the container created a read-only `/etc/pihole`, creating files in it will fail then.
Here is the log: `podman logs pihole`

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service cron: starting
s6-rc: info: service cron successfully started
s6-rc: info: service _uid-gid-changer: starting
s6-rc: info: service _uid-gid-changer successfully started
s6-rc: info: service _startup: starting
  [i] Starting docker specific checks & setup for docker pihole/pihole
  [i] Setting capabilities on pihole-FTL where possible
  [i] Applying the following caps to pihole-FTL:
        * CAP_CHOWN
        * CAP_NET_BIND_SERVICE
        * CAP_NET_ADMIN
  [i] Ensuring basic configuration by re-running select functions from basic-install.sh

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
/etc/.pihole/automated install/basic-install.sh: line 1362: /etc/pihole/dns-servers.conf: Permission denied
s6-rc: info: service _startup successfully started
s6-rc: info: service pihole-FTL: starting
s6-rc: info: service pihole-FTL successfully started
s6-rc: info: service lighttpd: starting
s6-rc: info: service lighttpd successfully started
s6-rc: info: service _postFTL: starting
s6-rc: info: service _postFTL successfully started
s6-rc: info: service legacy-services: starting
  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
s6-rc: info: service legacy-services successfully started
install: cannot create regular file '/etc/pihole/dhcp.leases': Permission denied
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
chown: changing ownership of '/etc/pihole': Permission denied
  Installation Failure: /etc/pihole/setupVars.conf does not exist!
  Please run 'pihole -r', and choose the 'reconfigure' option to fix.
chmod: cannot access '/etc/pihole/dhcp.leases': No such file or directory
```

## How to reproduce the issue 

1. Environment data
  * Operating System: **Fedora 38 Silverblue** 
  * Hardware: PC
  * Kernel Architecture: x86_64
  * Docker Install Info and version: 
    - Software source: Podman
  * Hardware architecture: x86

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

docker-compose.yml
```yml
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Asia/Dubai'
      WEBPASSWORD: 'elohip'
      FTLCONF_LOCAL_IPV4: '192.168.1.64'
      PIHOLE_DNS_: '1.1.1.1;1.0.0.1'
    volumes:
      - './etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```
