### ISSUE TITLE
Cannot use in bridge mode when userland proxy is disabled

### ISSUE THREAD

**Issue by UlyssesZh** [pi-hole/docker-pi-hole#1462]
This is a: Run Issue

## Details

Write `{"userland-proxy": false}` in `/etc/docker/daemon.json` and restart docker daemon. Then, pihole-FTL can start but does not work. It also uses a lot of CPU.

<details><summary>Log</summary>
<pre>pihole  | s6-rc: info: service s6rc-oneshot-runner: starting                                                                                                                                  
pihole  | s6-rc: info: service s6rc-oneshot-runner successfully started                                                                                                                       
pihole  | s6-rc: info: service fix-attrs: starting                                                                                                                                            
pihole  | s6-rc: info: service fix-attrs successfully started                                                                                                                                 
pihole  | s6-rc: info: service legacy-cont-init: starting                                                                                                                                     
pihole  | s6-rc: info: service legacy-cont-init successfully started                                                                                                                          
pihole  | s6-rc: info: service cron: starting                                                                                                                                                 
pihole  | s6-rc: info: service cron successfully started                                                                                                                                      
pihole  | s6-rc: info: service _uid-gid-changer: starting                                                                                                                                     
pihole  | s6-rc: info: service _uid-gid-changer successfully started                                                                                                                          
pihole  | s6-rc: info: service _startup: starting                                                                                                                                             
pihole  |   [i] Starting docker specific checks & setup for docker pihole/pihole                                                                                                              
pihole  |   [i] Setting capabilities on pihole-FTL where possible                                                                                                                             
pihole  |   [i] Applying the following caps to pihole-FTL:                                                                                                                                    
pihole  |         * CAP_CHOWN                                                                                                                                                                 
pihole  |         * CAP_NET_BIND_SERVICE                                                                                                                                                      
pihole  |         * CAP_NET_RAW                                                                                                                                                               
pihole  |         * CAP_NET_ADMIN                                                                                                                                                             
pihole  |   [i] Ensuring basic configuration by re-running select functions from basic-install.sh                                                                                             
pihole  |                                                                                                                                                                                     
pihole  |   [i] Installing configs from /etc/.pihole...                                                                                                                                       
pihole  |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!                                                                                                       
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf                                                                                                                                                 
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
pihole  | 
pihole  |   [i] Installing latest logrotate script...
pihole  |       [i] Existing logrotate file found. No changes made.
pihole  |   [i] Assigning password defined by Environment Variable
pihole  |   [✓] New password set
pihole  |   [i] Added ENV to php:
pihole  |                     "TZ" => "America/Los_Angeles",
pihole  |                     "PIHOLE_DOCKER_TAG" => "",
pihole  |                     "PHP_ERROR_LOG" => "/var/log/lighttpd/error-pihole.log",
pihole  |                     "CORS_HOSTS" => "",
pihole  |                     "VIRTUAL_HOST" => "pihole.025500.xyz",
pihole  |   [i] Using IPv4 and IPv6
pihole  | 
  [✓] Installing latest Cron script
pihole  |   [i] Preexisting ad list /etc/pihole/adlists.list detected (exiting setup_blocklists early)
pihole  |   [i] Existing DNS servers detected in setupVars.conf. Leaving them alone
pihole  |   [i] Applying pihole-FTL.conf setting LOCAL_IPV4=192.168.1.5
pihole  |   [i] Applying pihole-FTL.conf setting RATE_LIMIT=2000/60
pihole  |   [i] FTL binding to default interface: eth0
pihole  |   [i] Enabling Query Logging
pihole  |   [i] Testing lighttpd config: Syntax OK
pihole  |   [i] All config checks passed, cleared for startup ...
pihole  |   [i] Docker start setup complete
pihole  | 
pihole  |   [i] pihole-FTL (no-daemon) will be started as root
pihole  | 
pihole  | s6-rc: info: service _startup successfully started
pihole  | s6-rc: info: service pihole-FTL: starting
pihole  | s6-rc: info: service pihole-FTL successfully started
pihole  | s6-rc: info: service lighttpd: starting
pihole  | s6-rc: info: service lighttpd successfully started
pihole  | s6-rc: info: service _postFTL: starting
pihole  | s6-rc: info: service _postFTL successfully started
pihole  | s6-rc: info: service legacy-services: starting
pihole  |   Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
pihole  | s6-rc: info: service legacy-services successfully started
pihole  |   [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range
pihole  | 
  [✓] Preparing new gravity database
  [✓] Creating new gravity databases
pihole  |   [i] Using libz compression
pihole  | 
pihole  |   [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [✓] Parsed 148940 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
pihole  |       Sample of non-domain entries:
pihole  |         - "0.0.0.0"
pihole  | 
pihole  |   [i] List stayed unchanged
pihole  | 
  [✓] Building tree
  [✓] Swapping databases
pihole  |   [✓] The old database remains available
pihole  |   [i] Number of gravity domains: 148940 (148940 unique domains)
pihole  |   [i] Number of exact blacklisted domains: 0
pihole  |   [i] Number of regex blacklist filters: 0
pihole  |   [i] Number of exact whitelisted domains: 0
pihole  |   [i] Number of regex whitelist filters: 0
pihole  | /bin/bash: line 1:   267 Hangup                  /usr/bin/pihole-FTL no-daemon > /dev/null 2>&1
pihole  |   [i] Cleaning up stray matter...Stopping pihole-FTL
  [✓] Cleaning up stray matter
pihole  | pihole-FTL: no process found
pihole  | 
pihole  |   [✓] FTL is listening on port 
pihole  |      [✓] UDP (IPv4)
pihole  |      [✓] TCP (IPv4)
pihole  |      [✗] UDP (IPv6)
pihole  |      [✓] TCP (IPv6)
pihole  | 
pihole  |   [✓] Pi-hole blocking is enabled
pihole  | 
pihole  |   Pi-hole version is v5.17.2 (Latest: v5.17.2)
pihole  |   web version is v5.20.2 (Latest: v5.20.2)
pihole  |   FTL version is v5.23 (Latest: v5.23)
pihole  |   Container tag is: 2023.10.0
pihole  | </pre>
</details>
## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

#1240

## How to reproduce the issue 

1. Environment data
  * Operating System: Arch 
  * Hardware: Laptop (Lenovo Legion)
  * Kernel Architecture: x86_64
  * Docker Install Info and version: 
    - Software source: From Arch packages, installed using pacman 
    - Supplimentary Software: None 
  * Hardware architecture: x86 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

```yml
version: "3" 
 
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - net-admin
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8099:80/tcp"
    environment:
      FTLCONF_LOCAL_IPV4: 192.168.1.5
      FTLCONF_RATE_LIMIT: 2000/60
      TZ: 'America/Los_Angeles'
      WEBPASSWORD: filtered
      DNSMASQ_LISTENING: all
      VIRTUAL_HOST: pihole.025500.xyz
      VIRTUAL_PORT: 443
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

networks:
  net-admin:
    external: true
```

4. any additional info to help reproduce

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [X] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
