### ISSUE TITLE
unable to resolve host address

### ISSUE THREAD

**Issue by firyx** [pi-hole/docker-pi-hole#1484]
This is a: **Bug**  

## Details

* I get `unable to resolve host address` error when accessing internet through pihole docker container

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Docker on MX Linux 23 (Debian based Linux) 
  * Hardware: PC
  * Kernel Architecture: x86/amd64 
  * Docker Install Info and version: 
    - Software source: official docker-ce 
    - Supplimentary Software: docker-compose 
  * Hardware architecture: x86/amd64 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
  * docker-compose.yml:
  ```yml
version: '3.9'

services:
    archivebox:
        image: ${DOCKER_IMAGE:-archivebox/archivebox:dev}
        command: server --quick-init 0.0.0.0:8000
        ports:
            - 127.0.0.1:8000:8000
        volumes:
            - ./data:/data
            # - ./etc/crontabs:/var/spool/cron/crontabs  # uncomment this and archivebox_scheduler below to set up automatic recurring archive jobs
            # - ./archivebox:/app/archivebox             # uncomment this to mount the ArchiveBox source code at runtime (for developers working on archivebox)
        # build: .                                       # uncomment this to build the image from source code at buildtime (for developers working on archivebox)
        dns:                                           # uncomment this and pihole container below for ad-blocking during archiving
            - pihole
        environment:
            - ALLOWED_HOSTS=*                   # restrict this to only accept incoming traffic via specific domain name

    
    
    ### Example: To run pihole in order to block ad/tracker requests during archiving,
    # uncomment this block and set up pihole using its admin interface

    pihole:
      image: pihole/pihole:latest
      ports:
        - 8090:80       # uncomment to access the admin HTTP interface on http://localhost:8090
        - 53:53/tcp
        - 53:53/udp
      environment:
        - WEBPASSWORD=some-password
        - DNSMASQ_LISTENING=all
      volumes:
        - ./etc/pihole:/etc/pihole
        - ./etc/dnsmasq:/etc/dnsmasq.d
  ```

  * `docker compose run archivebox init --setup`
  * `docker compose up`
  * `docker exec archivebox-archivebox-1 wget https://abc.com`
  * error:
  ```logs
$ docker exec archivebox-archivebox-1 wget https://abc.com
--2023-11-06 07:46:33--  https://abc.com/
Resolving abc.com (abc.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘abc.com’
  ```
  * when I try to archive any link with Archivebox, I get DNS errors

3. any additional info to help reproduce

* When I perform `docker exec archivebox-pihole-1 curl -L https://abc.com` => it seems internet is working, the page is downloaded
* When I perform `docker exec archivebox-archivebox-1 wget pihole/admin` => it seems pihole is working, the admin page is downloaded
* I can access both Archivebox admin web interface (`127.0.0.1:8000`) and Pihole admin interface (`127.0.0.1:8090`)
* When I disable pihole by commenting `services.archivebox.dns` and `services.pihole...` in the `docker-compose.yml` file, then Archivebox works correctly, the links are downloaded, there are no DNS errors.

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by firyx** [comment]
This made it working:

```yml
version: '3.9'

services:
  archivebox:
    image: ${DOCKER_IMAGE:-archivebox/archivebox:dev}
    command: server --quick-init 0.0.0.0:8000
    ports:
    - 127.0.0.1:8000:8000
    volumes:
    - ./data:/data
    depends_on:
    - pihole
    dns:                                           # uncomment this and pihole container below for ad-blocking during archiving
    - 172.20.0.53
    networks:
      archiveboxnet:
        ipv4_address: 172.20.0.6
    environment:
    - ALLOWED_HOSTS=*                   # restrict this to only accept incoming traffic via specific domain name

  ### Example: To run pihole in order to block ad/tracker requests during archiving,
  # uncomment this block and set up pihole using its admin interface

  pihole:
    image: pihole/pihole:latest
    ports:
    - 127.0.0.1:8090:80       # uncomment to access the admin HTTP interface on http://localhost:8090
    - 127.0.0.1:53:53/tcp
    - 127.0.0.1:53:53/udp
    environment:
    - WEBPASSWORD=...
    - DNSMASQ_LISTENING=all
    volumes:
    - ./etc/pihole:/etc/pihole
    - ./etc/dnsmasq:/etc/dnsmasq.d
    dns:
    - 127.0.0.1
    - 1.1.1.1
    - 1.0.0.1
    networks:
      archiveboxnet:
        ipv4_address: 172.20.0.53

networks:
  archiveboxnet:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
```
