### ISSUE TITLE
PiHole Web Interface keeps going back to an older version

### ISSUE THREAD

**Issue by gh0sti** [pi-hole/docker-pi-hole#1522]
This is a: Run Issue  

## Details

Web Interface will revert to an older version of 5.18 when the latest web interface is 5.21. I am using docker build 2023.11.0. I have to consistently run update checker to have the web interface update to show the latest version when signing in.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **root@raspberrypi:/home/pi# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
** 
  * Hardware: Raspberry Pi 4
  * Kernel Architecture: Arm 32bit
  * Docker Install Info and version: 
    - Software source: 2023.11.0 Official Docker Github
    - Supplimentary Software: Portainer 2.19.4
  * Hardware architecture: 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

```yml
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: homepi  
    ports:  
     - "54:53/tcp"  
     - "54:53/udp"    
     - "85:80/tcp"    
    volumes:  
     - './etc-pihole:/etc/pihole'  
     - './etc-dnsmasq.d:/etc/dnsmasq.d'  
```
    
4. any additional info to help reproduce
<img width="425" alt="pihole" src="https://github.com/pi-hole/docker-pi-hole/assets/4202657/79c45111-9dd3-41bf-9001-dbf8ab5bf2da">

## These common fixes didn't work for my issue

- [ ] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
