### ISSUE TITLE
s6-overlay-suexec: Exec format error

### ISSUE THREAD

**Issue by ngn13** [pi-hole/docker-pi-hole#1524]
Hello, it seems like the `linux/386` image for version 2023.05.0 and above is broken.

This is a: **Run Issue or bug idk**  

## Details
I copied over the example docker-compose file, made few edits and after running it, I realized that the web server is down. So I checked the logs
and this was what I got:
```
/s6-init: 37: exec: s6-overlay-suexec: Exec format error
``` 
After downgrading couple of times, I found out that the issue occurs in version 2023.05.0 and above

## How to reproduce the issue 

1. Environment data
  * Operating System: **Debian GNU/Linux 11 (bullseye)** 
  * Hardware: **PC**
  * Kernel Architecture: 32bit
  * Docker Install Info and version: 
     - official image version 2023.05.0 (and above) 
     - docker-compose version 1.25.0 
     - docker version 20.10.5+dfsg1
  * Hardware architecture: x86

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```yaml
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2023.03.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "127.0.0.1:8080:80/tcp"
    environment:
      TZ: 'Europe/Istanbul'
      WEBPASSWORD: 'verysecureandrealpasswordthatidefinitelyforgottoremove'
    volumes:
      - './pihole:/etc/pihole'
      - './dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
```

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
