### ISSUE TITLE
Unable to run as non-root user

### ISSUE THREAD

**Issue by ReK42** [pi-hole/docker-pi-hole#1533]
This is a: Bug 

## Details
I'm trying to run this container via docker-compose and have the volumes point to an NFS location. To handle the UID/GID mapping, I need the container to run with UID 9000 and GID 9000. I've used the `PIHOLE_UID` and `PIHOLE_GID` environment variables to do this, however it still breaks. It appears the file `/etc/pihole/custom.list` is forced to be owned by root, which then breaks everything. Additionally, there appears to be no error checking in the `ensure_basic_configuration` function to see whether or not the `installConfigs` call failed.

https://github.com/pi-hole/pi-hole/blob/19bfa08b83026611fef664caff506c272b61d35e/automated%20install/basic-install.sh#L1376

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Debian 12
  * Hardware: Virtual Machine
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: 
    - Software source: official docker-ce
    - Supplimentary Software: portainer, nfs
  * Hardware architecture: x86
  * NFS share mounted to `/nfs` with a folder, `/nfs/docker`, owned by 9000:9000

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
---
version: "3.8"
services:
  app:
    image: pihole/pihole:latest
    restart: unless-stopped
    container_name: pihole
    environment:
      - TZ=Etc/UTC
      - PIHOLE_UID=9000
      - PIHOLE_GID=9000
      - VIRTUAL_HOST=dns.example.com
      - PROXY_LOCATION=dns.example.com
      - FTLCONF_LOCAL_IPV4=192.0.2.1
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "53:53/udp"    # DNS
      - "53:53/tcp"    # DNS
      - "443:443/tcp"  # DNS-over-HTTPS
      - "853:853/tcp"  # DNS-over-TLS
      - "853:853/udp"  # DNS-over-QUIC
      - "3000:80/tcp"  # Admin
    volumes:
      - /nfs/docker/pihole_config:/etc/pihole
      - /nfs/docker/pihole_dnsmasq_config:/etc/dnsmasq.d
```

3. Container Log Output
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service cron: starting
s6-rc: info: service cron successfully started
s6-rc: info: service _uid-gid-changer: starting
  [i] Changing ID for user: pihole (999 => 9000)
  [i] Changing ID for group: pihole (1000 => 9000)
s6-rc: info: service _uid-gid-changer successfully started
s6-rc: info: service _startup: starting
  [i] Starting docker specific checks & setup for docker pihole/pihole
  [i] Setting capabilities on pihole-FTL where possible
  [i] Applying the following caps to pihole-FTL:
        * CAP_CHOWN
        * CAP_NET_BIND_SERVICE
        * CAP_NET_RAW
  [i] Ensuring basic configuration by re-running select functions from basic-install.sh
  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [i] Installing /etc/dnsmasq.d/01-pihole.conf...
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [i] Installing /etc/.pihole/advanced/06-rfc6761.conf...
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
   Error: Unable to initialize configuration file /etc/pihole/custom.list
s6-rc: info: service _startup successfully started
s6-rc: info: service pihole-FTL: starting
s6-rc: info: service pihole-FTL successfully started
s6-rc: info: service lighttpd: starting
s6-rc: info: service lighttpd successfully started
s6-rc: info: service _postFTL: starting
s6-rc: info: service _postFTL successfully started
s6-rc: info: service legacy-services: starting
  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
s6-rc: info: service legacy-services successfully started
  Installation Failure: /etc/pihole/setupVars.conf does not exist! 
  Please run 'pihole -r', and choose the 'reconfigure' option to fix.
```

4. Docker host `pihole_config` volume
You can see the `custom.list` file is owned by root.
```
root@docker-a:~# ls -ln /nfs/docker/pihole_config/
total 31
-rw------- 1    0 9000     0 Jan 28 07:50 custom.list
-rw-r--r-- 1 9000 9000     0 Jan 28 07:50 dhcp.leases
-rw-r--r-- 1 9000 9000   651 Jan 28 07:50 dns-servers.conf
-rw-rw-r-- 1 9000 9000   112 Jan 28 07:50 pihole-FTL.conf
-rw-rw-r-- 1 9000 9000 81920 Jan 28 08:06 pihole-FTL.db
-rw-r--r-- 1 9000 9000   274 Jan 28 07:51 versions

root@docker-a:~# ls -ln /nfs/docker/pihole_dnsmasq_config/
total 9
-rw-r--r-- 1 9000 9000 1334 Jan 28 07:50 01-pihole.conf
-rw-r--r-- 1 9000 9000 2190 Jan 28 07:50 06-rfc6761.conf
```

## These common fixes didn't work for my issue
- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
