### ISSUE TITLE
s6-rc-compile: fatal: invalid /etc/s6-overlay/s6-rc.d/_postFTL/type: must be oneshot, longrun, or bundle

### ISSUE THREAD

**Issue by Dialgatrainer02** [pi-hole/docker-pi-hole#1547]
This is a: run issue

## Details

docker logs

```
s6-rc-compile: fatal: invalid /etc/s6-overlay/s6-rc.d/_postFTL/type: must be oneshot, longrun, or bundle
```

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: alpine
  * Hardware: virtulised with proxmox has 3 gb ram and 1 core given to alpine vm running docker
  * Kernel Architecture: x86_64
  * Docker Install Info and version: 
    - Software source: alpine repo
    - Supplimentary Software: heimdall
  * Hardware architecture: x86_64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

```
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "88:80/tcp"
    environment:
      TZ: "${TZ}"  # Adjust to your timezone
      WEBPASSWORD: ${PASSWORD}  # Set a secure password
    restart: always
    volumes:
      - '${DOCKER_DIR}/pihole/etc-pihole:/etc/pihole'
      - '${DOCKER_DIR}/pihole/dnsmasq.d:/etc/dnsmasq.d'
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    hostname: heimdall
    container_name: heimdall
    environment:
      - TZ="${TZ}"
    volumes:
      - ${DOCKER_DIR}/heimdall/config:/config
    ports:
      - 8080:80
      - 7443:443
    restart: always
```
4. any additional info to help reproduce

fresh install done today i whent to log in and i saw it was unheathy and not 

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
