### ISSUE TITLE
Conditionnal forwarding broken after teleporter import

### ISSUE THREAD

**Issue by t4nki** [pi-hole/docker-pi-hole#1550]
Hi,

I've been setting up my podman ansible playbooks for future v6 update.
I have imported a v5 teleporter backup, and everything seems fine, but, after importing my backup and running gravity update, the reverse server is not working anymore, I had to restart my container for it to work again.

This is a: Bug

## Details

setup a new pihole instance with ansible and podman
import teleporter backup through ui
reverse servers are not used anymore
update gravity
reverse servers still not used
restart container (systemctl restart pihole_container)
reverse servers are back 

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Debian 
  * Hardware: Raspi 4
  * Kernel Architecture: aarch64
  * Podman Install Info and version: 
    - Software source: Debian bookworm repos v4.3.1
    - Supplimentary Software: cloudflared in same podman pod
  * Hardware architecture: aarch64

2. ansible module : 
```
- name: Déploiement de PiHole
  containers.podman.podman_container:
    name: pihole
    image: docker.io/pihole/pihole:development-v6
    label:
      io.containers.autoupdate=registry
      PODMAN_SYSTEMD_UNIT=pod_infra.service
      diun.enable=true
    env:
      TZ: 'Europe/Paris'
      FTLCONF_dns_piholePTR: 'NONE'
      FTLCONF_dns_upstreams: 127.0.0.1#5054
      FTLCONF_dns_ignoreLocalhost: true
      FTLCONF_dns_domain: 'lan'
      FTLCONF_dns_dnssec: true
      FTLCONF_dns_reply_host_force4: true
      FTLCONF_dns_reply_host_IPv4: '{{ ansible_default_ipv4.address }}'
      FTLCONF_dns_listeningMode: 'SINGLE'
      FTLCONF_dns_revServers: "true,{{ ansible_default_ipv4.address.split('.')[0:2] | join('.') }}.0.0/16,{{ ansible_default_ipv4.gateway }},{{ ansible_domain }}"
      FTLCONF_resolver_resolveIPv6: false
      FTLCONF_webserver_api_password: '{{ vault_pihole_passwd }}'
      FTLCONF_webserver_tls_rev_proxy: true
      FTLCONF_webserver_port: 8053
    volumes:
      - /srv/pihole:/etc/pihole
      - /srv/home/home.html:/var/www/html/admin/home.html
      - /srv/ssl/ca.crt:/var/www/html/admin/ca.crt
    state: present
    restart_policy: "no"
    pod: "infra"
    log_driver: json-file
    log_opt: path=/var/log/containers/pihole.json
    healthcheck_start_period: 1m
    healthcheck_interval: 2m
    healthcheck_retries: 5
    healthcheck_timeout: 1m
    dns: 1.1.1.1
```
3. any additional info to help reproduce : 
make a pihole v5x backup with teleporter
start pihole v6
import teleporter backup
reverse servers not seen or used

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [X] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
