### ISSUE TITLE
Unable start container with tag 2024.06.01

### ISSUE THREAD

**Issue by corasaniti** [pi-hole/docker-pi-hole#1603]
With the arm v7 and v8 architecture everything seems to work with the 2024.06.01 tag but with the x64 architecture the container remains in starting for a long time and then in the "unhealth" state.
I am unable to start the container and end up getting an Internal Server error.
Something broke with last update 2024.06.01

I haven't tried the x86 architecture but there is probably the same problem. I downgraded to version 2024.05.0 and everything works fine again

Thank you

  * Operating System: Debian
  * Hardware: PC
  * Kernel Architecture: amd64
  * Docker Install Info and version:  latest Docker 

Thanks

**Comment by PromoFaux** [comment]
Can you please try the `dev` tag?

**Comment by PromoFaux** [comment]
Can you please try the `dev` tag?

**Comment by corasaniti** [comment]
@PromoFaux 
I just tried the `dev `tag and it seems to work fine
Same problem, the container remains in "`unhealth`" state and I get a server error, here is my log
[_pihole_logs.txt](https://github.com/user-attachments/files/15862038/_pihole_logs.txt)

**Comment by PromoFaux** [comment]
Ok, thanks - was half expecting that, but hoping it was just a glitch between builds as there are no differences between the two tags.

Interesting, though. Will look into it ASAP - I cannot quite see why the latest change would cause this. In theory, nothing has changed for x86_64 since the previous tag

**Comment by PromoFaux** [comment]
Testing with a very basic `docker run --rm -it pihole/pihole:latest` the container appears to be working OK on my Synology Nas:

```
adam@syno:/$ sudo docker ps -a
CONTAINER ID   IMAGE                           COMMAND                  CREATED         STATUS                        PORTS                                            NAMES
8a7f10c56e78   pihole/pihole:latest            "/s6-init"               2 minutes ago   Up About a minute (healthy)   53/udp, 53/tcp, 80/tcp, 67/udp                   relaxed_morse
```

And it's showing the correct `x86_64` arch.

```
adam@syno:/$ sudo docker exec -it relaxed_morse bash
root@8a7f10c56e78:/# arch
x86_64
root@8a7f10c56e78:/# dpkg --print-architecture
amd64
```

Your log shows the following:

```
/opt/pihole/gravity.sh: line 316:   271 Bus error               timeout 4 dig +short "${lookupDomain}" &> /dev/null
  [✗] DNS resolution is currently unavailable
  [i] Time until retry: 120
  [✓] DNS resolution is now available
```

What does your compose/docker run command look like?

**Comment by corasaniti** [comment]
@PromoFaux 
Hi this is my docker-compose.

```
version: "2"
services:
  pihole:
    container_name: pihole
    hostname: debian11
    image: pihole/pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Rome'
    volumes:
      - '/home/corasaniti/docker/pihole/etc-pihole/:/etc/pihole/'
      - '/home/corasaniti/docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 8.8.8.8
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```
