### ISSUE TITLE
Unable to Set WEBPASSWORD Value in Docker Compose or Using PiHole Command

### ISSUE THREAD

**Issue by highball8** [pi-hole/docker-pi-hole#1650]
I am running Pi-hole on a Raspberry Pi using Docker Compose. When I set a value for the web interface password using the WEBPASSWORD variable, that password is not accepted. Same result when I use the `sudo pihole -a -p` command. In both cases I get a **Wrong password!** error on the web interface log in.

I believe this is a bug. I have not seen any similar issues reporting this problem.

I can find the password in /<docker>/pi-hole/etc-pihole/setupVars.conf, and that password works but it is a hexidecimal string that I did not set.

I'm trying to understand why I cannot set a password in the docker-compose.yml.

I'm getting inconsistent results when setting the password using the `sudo pihole -a -p` command inside the container or the `docker exec -it pihole pihole -a -p` command from outside the container. Sometimes the web interface will accept that password, sometimes it will not. But that password is still not reflected in 

* Host: Linux 6.8.0-1012-raspi # 13-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep  2 11:13:41 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
* Docker version 27.3.1, build ce12230
* Docker packages: 
    * docker-buildx-plugin/noble,now 0.17.1-1\~ubuntu.24.04~noble arm64 [installed,automatic]
    * docker-ce-cli/noble,now 5:27.3.1-1\~ubuntu.24.04~noble arm64 [installed]
    * docker-ce-rootless-extras/noble,now 5:27.3.1-1\~ubuntu.24.04~noble arm64 [installed,automatic]
    * docker-ce/noble,now 5:27.3.1-1\~ubuntu.24.04~noble arm64 [installed]
    * docker-compose-plugin/noble,now 2.29.7-1\~ubuntu.24.04~noble arm64 [installed,automatic]
* Docker Image: pihole:latest (78de8a1eefcf)

I've tried everything to resolve this, from changing the password I am trying to set, to restarting the container, removing and pulling the image again, and I have also jsut completely reinstalled the host OS and reinstalled Docker.

**Comment by highball8** [comment]
@rdwebdesign - Thank you for your reply. I was previously using special characters, including `$`. I also altered my use of quotes around the password in the Compose file, but I still had the same issue. 

After reading your reply, this worked for me: No special characters in `WEBPASSWORD` and enclosing `WEBPASSWORD` in single quotes (`'`).

Note: I copied the Compose file from GitHub directly into Vim so the only thing I changed with it was the use of the `WEBPASSWORD` variable.

Thanks again.

**Comment by rdwebdesign** [comment]
Looks like this is the docker version of [this similar issue](https://github.com/pi-hole/pi-hole/issues/5771).

If you set a string containing the character `$` without quotes (or inside double quotes `""`), the compose file will consider the text after the `$` as a variable name.

Examples:

```yml
WEBPASSWORD: $PASS    # this will set WEBPASSWORD as the value of the variable $PASS  

WEBPASSWORD: abc$de    # this will set WEBPASSWORD as "abc" followed by the value of $de
                       # If there is no variable called "de", the password will be just "abc"

WEBPASSWORD: "abc$de"    # same as above. Variables inside double quotes are expanded.

WEBPASSWORD: 'abc$de'    # this will set WEBPASSWORD as "abc$de" literally. Values inside single quotes are strings. No expansion.
```

From [_compose file_ docs](https://docs.docker.com/reference/compose-file/interpolation/):

> Values in a Compose file can be set by variables and interpolated at runtime. Compose files use a Bash-like syntax `${VARIABLE}`. Both `$VARIABLE` and `${VARIABLE}` syntax is supported.
