### ISSUE TITLE
DEBUG_ANY dnsmasq received signal 17

### ISSUE THREAD

**Issue by PatricioooAG** [pi-hole/docker-pi-hole#1667]
This is a: Run issue

## Details

Im using the nightly image, the problem are with the latest releases of Docker Desktop, after a minutes I get the log : DEBUG_ANY dnsmasq received signal 17 and the webs are not loading. I have in the compose to make a local folder PiHole and dnsmasq, but dnsmasq folder is always empty and I don't know if is normal.  The problem is the same with "latest" image, I try too the different virtualization modes in Docker. It's my second time writing for help, but the dnsmasq log is new. The latest Docker Desktop working are 4.17 maybe to 4.19, newer don't. Thanks.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: MacOs 
  * Hardware: MacBook Pro M3
  * Kernel Architecture: 
  * Docker Install Info and version: 
    - Software source: 
    - Supplimentary Software: 
  * Hardware architecture: 

2. docker-compose.yml 
```yml
version: '3'
services:
  pihole:
    image: pihole/pihole:nightly
    container_name: pihole
    environment:
      - ServerIP=10.0.0.18
      - TZ=Europe/Madrid
      - DNS1=10.0.0.18:5053  # Apuntamos al servidor DoH en 10.0.0.18:5053
    ports:
      - "8082:80"
      - "10.0.0.18:53:53/tcp"
      - "10.0.0.18:53:53/udp"
      - "448:443"  # Puerto HTTPS para la interfaz web
    volumes:
      - ./pihole:/etc/pihole    # Persistencia de configuración de Pi-hole
      - ./dnsmasq:/etc/dnsmasq.d # Persistencia de configuración de dnsmasq
    dns:
      - 1.1.1.1               # DNS de Docker para la resolución interna
    restart: unless-stopped   # Reiniciar el contenedor en caso de fallo
    cap_add:
      - SYS_TIME
    depends_on:
      - cloudflared

  cloudflared:
    image: crazymax/cloudflared:latest
    container_name: cloudflared
    ports:
      - '5053:5053/udp'
      - '5053:5053/tcp'
    environment:
      - "TZ=Europe/Madrid"
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"
    restart: always

volumes:
  pihole:
  dnsmasq:
```

4. any additional info to help reproduce
wait some time. 
## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
