### ISSUE TITLE
DHCP Lua Script Not Executing

### ISSUE THREAD

**Issue by balucio** [pi-hole/docker-pi-hole#1672]
This is a: **BUG**

## Details
I'm encountering an issue with the Docker Pi-hole setup where Lua scripts are not being executed.

I created a simple Lua script with `lease` function. This script seems not called by Pi-Hole.

```ini
root@pihole:~# cat /etc/dnsmasq.d/03-dnsmasq-script.conf 
script-on-renewal
dhcp-scriptuser=root
dhcp-luascript=/etc/dnsmasq.d/scripts/dhcp-leases-events.lua
```

this is the `lua` script
```lua
function init()
   print("INIT")
end

-- Handling Dnsmasq Lease events
function lease(event, data)
   print("Lease" .. event)
end

-- Called when dnsmasq exit
function shutdown()
    print("Shutting down...")
end
```

## How to reproduce the issue 

1. Environment data
  * Operating System: **Debian**
  * Hardware: Intel(R) N95 (Container)
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: 
    - Software source: Docker version 27.4.0, build bde2b89
    - Supplimentary Software: none
  * Hardware architecture: x86_64

2. docker-compose.yml contents:
```
name: pihole-dns
services:
  pihole:
    cap_add:
      - NET_ADMIN
    container_name: pihole
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      DHCP_ACTIVE: "true"
      DHCP_END: 192.168.1.140
      DHCP_IPv6: "true"
      DHCP_LEASETIME: "1"
      DHCP_ROUTER: 192.168.1.1
      DHCP_START: 192.168.1.10
      DHCP_rapid_commit: "true"
      DNS_BOGUS_PRIV: "true"
      DNS_FQDN_REQUIRED: "true"
      DNSMASQ_LISTENING: all
      DNSSEC: "false"
      PIHOLE_DNS_: 1.1.1.1;8.8.8.8;8.8.4.4"
      PIHOLE_DOMAIN: sapacasa.it
      QUERY_LOGGING: "true"
      TEMPERATUREUNIT: c
      TZ: Europe/Rome
      VIRTUAL_HOST: dns.sapacasa.it
      WEBPASSWORD: ****************
      WEBUIBOXEDLAYOUT: boxed
    expose:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    hostname: pihole
    image: pihole/pihole:latest
    labels:
        **OMITTED TRAEFIK LABELS**
    networks:
      internal:
      services:
        ipv4_address: 192.168.1.248
    restart: always
    volumes:
      - type: bind
        source: /home/user/docker-pihole/etc-pihole
        target: /etc/pihole
        bind:
          create_host_path: true
      - type: bind
        source: /home/user/docker-pihole/etc-dnsmasq.d
        target: /etc/dnsmasq.d
        bind:
          create_host_path: true
networks:
  internal:
    external: true
  services:
    external: true
```

6. Bash scripts appear to execute correctly. When modifying the Pi-hole configuration to run Bash scripts, they are executed as expected, and the output is correctly logged to the `pihole.log` file.
