### ISSUE TITLE
Once DHCP is enabled through environment variables, it can't be disabled

### ISSUE THREAD

**Issue by hugoduraes** [pi-hole/docker-pi-hole#1688]
This is a: **Bug**  

## Details

Once DHCP is enabled through environment variables, it can't be disabled. This happens because the DHCP setup is only executed when the `DHCP_ACTIVE` environment variable is set to `true`. Source code:
```bash
[[ -n "${DHCP_ACTIVE}" && ${DHCP_ACTIVE} == "true" ]] && echo "Setting DHCP server" && setup_FTL_dhcp
```

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Raspbian**
  * Hardware: RasPi 4B
  * Kernel Architecture: 
  * Docker Install Info and version: 
    - Software source: official docker-ce
    - Supplimentary Software: 
  * Hardware architecture: 

2. docker-compose.yml
```yaml
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: "Europe/Lisbon"
      WEBPASSWORD: "** REDACTED **"
      FTLCONF_LOCAL_IPV4: "192.168.10.4"
      FTLCONF_PRIVACYLEVEL: 0
      FTLCONF_MAXDBDAYS: 90
      FTLCONF_BLOCK_ICLOUD_PR: "false"
      PIHOLE_DNS_: "1.1.1.2;1.0.0.2;2606:4700:4700::1112;2606:4700:4700::1002"
      DNSSEC: "true"
      DNS_BOGUS_PRIV: "true"
      DNS_FQDN_REQUIRED: "true"
      DHCP_ACTIVE: "false"
      DHCP_START: ""
      DHCP_END: ""
      DHCP_ROUTER: ""
      DHCP_LEASETIME: 6
      PIHOLE_DOMAIN: "home"
      DNSMASQ_LISTENING: "all"
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    network_mode: "host"
``` 
4. any additional info to help reproduce

Edit `docker-compose.yml` and enable DHCP by setting DHCP_ACTIVE to `true` and `DHCP_START`, `DHCP_END` and `DHCP_ROUTER` with the necessary values; run `docker compose up -d`. The Pi-hole UI should show that DHCP is enabled.
Then, edit `docker-compose.yml` again and disable DHCP by setting DHCP_ACTIVE to `false`; run `docker compose up -d`. The Pi-hole UI still shows that DHCP is enabled.

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
