### ISSUE TITLE
Not responding to DNS queries (from local network)

### ISSUE THREAD

**Issue by zambrinf** [pi-hole/docker-pi-hole#1695]
### Versions

Core version is v6.0 (Latest: v6.0)
Web version is v6.0 (Latest: v6.0)
FTL version is vDev-eaa7dbb (Latest: v6.0)

### Platform

- OS and version:  Debian GNU/Linux 12

- Platform:  raspberry pi

### Expected behavior

Dns queries working in my local network

### Actual behavior / bug

Being blocked by pihole as if it was non-local

### Steps to reproduce

- Had docker running version 2024.07.0
- Updated to latest
- try `nslookup google.com <masked ip>` from another machine (local)

```
DNS request timed out.
    timeout was 2 seconds.
Servidor:  UnKnown
Address:  <masked ip>

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** O tempo limite da solicitação para UnKnown expirou
```

Debug:
https://tricorder.pi-hole.net/OOL8jTA6/
```

*** [ DIAGNOSING ]: Pi-hole diagnosis messages
   count   last timestamp       type                  message                                                       blob1                 blob2                 blob3                 blob4                 blob5

   ------  -------------------  --------------------  ------------------------------------------------------------  --------------------  --------------------  --------------------  --------------------  --------------------
   1       2025-02-18 18:48:08  DNSMASQ_WARN          ignoring query from non-local network <masked ip>(logged

                                                       only once)

```

**Comment by rdwebdesign** [comment]
Please, provide a Debug Token.

**Comment by zambrinf** [comment]
@rdwebdesign 
https://tricorder.pi-hole.net/OOL8jTA6/

**Comment by PromoFaux** [comment]
@zambrinf - what does your docker run/compose look like please?

**Comment by zambrinf** [comment]
@PromoFaux 
```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - "80/tcp"
    environment:
      TZ: 'America/Sao_Paulo'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    networks:
      - homelab1

networks:
  homelab1:
    name: homelab
    external: true
```
That network is a bridge one
