### ISSUE TITLE
V6 : custom dnsmasq no longer work

### ISSUE THREAD

**Issue by fabiencharrasse** [pi-hole/docker-pi-hole#1711]
This is a: **Bug**  

## Details

I use pihole to redirect all my *.dev.myname subdomain website to a local ip address with a dnsmasq custom file in **/etc/dnsmasq.d/02-dev.myname.conf**:

`address=/dev.myname/192.168.1.84`

This worked fine since v6 update. Now when i request example.dev.myname, pihole.log gave me : 

`cached example.dev.myname is NXDOMAIN `

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Ubuntu** 
  * Hardware: PC
  * Kernel Architecture: x86
  * Docker Install Info and version: 
    - Software source: OS provided package
    - Supplimentary Software: portainer
  * Hardware architecture: x86

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "192.168.1.107:53:53/tcp"
      - "192.168.1.107:53:53/udp"
      - "1080:80/tcp"
    environment:
      TZ: 'Europe/Paris'
      # WEBPASSWORD: 'set a secure password here or it will be random'
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'3
      FTLCONF_dns_listeningMode: 'all'
    # Volumes store your data between container upgrades
    volumes:
      - '/home/myname/docker/pihole/etc-pihole:/etc/pihole'
      - '/home/myname/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
```
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
