### ISSUE TITLE
Pihole does not allow an empty password

### ISSUE THREAD

**Issue by Shagon94** [pi-hole/docker-pi-hole#1713]
### Versions

pihole:/# pihole -v
Core version is v6.0 (Latest: v6.0.1)
Web version is v6.0 (Latest: v6.0)
FTL version is v6.0 (Latest: v6.0)

pihole/pihole:latest

### Platform

- OS and version:  Debian 12

- Platform:  Raspberry pi

### Expected behavior

Setting an empty password causes pihole to reset to a random one.

### Actual behavior / bug

`FTLCONF_webserver_api_password=""` does not disable the authentication

### Steps to reproduce

1. Set `FTLCONF_webserver_api_password=""` for the docker container
2. Observe that the password is random on every restart, even after changing it manually.

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
Thanks for the report. We'll fix this

**Comment by yubiuser** [comment]
Mhh.. this might fall into FTL's realm

```
pihole  |   [i] Starting FTL configuration
pihole  |   [i] Assigning password defined by Environment Variable

pihole  | 2025-02-19 19:42:17.739 UTC [179M] WARNING: Environment variable FTLCONF_webserver_api_password has no value, substituting with empty string
pihole  | 2025-02-19 19:42:17.740 UTC [179M] INFO: 2 FTLCONF environment variables found (2 used, 0 invalid, 0 ignored)
pihole  | 2025-02-19 19:42:17.740 UTC [179M] INFO:    [✓] FTLCONF_webserver_api_password is used

```

@DL6ER Does FTL treat the empty string as "disable password" or does it generate a hash from the empty string?

**Comment by DL6ER** [comment]
I very much assume the latter because environment variables will always be defined. I don't even know if this is a bug?

**Comment by yubiuser** [comment]
It should as we use `${var+x}` to check for unset vars, not empty

https://github.com/pi-hole/docker-pi-hole/blob/66b79aa6c3b6f38d07c5679b43cbb7475e5e679e/src/bash_functions.sh#L191-L218

**Comment by DL6ER** [comment]
For what does this bash code exist in the first place? Only for generating a random password for you in case there is none? I'm asking because `FTLCONF_webserver_api_password` is valid for FTL as `webserver.api.password` exists and FTL very likely parses this independently from whatever the shell script is doing.

**Comment by yubiuser** [comment]
> Only for generating a random password for you in case there is none?

Yes. To set some default password if users did not. We also did this in v5 container.

**Comment by Shagon94** [comment]
Some users (such as myself) have authelia in front of everything to provide authentication, as such I remove authentication from the apps themselves. I'd like to remove the password (this worked in v5) so I can just login through authelia once.

**Comment by rdwebdesign** [comment]
How did you set the variable to the container?

Can you please post the compose file?

**Comment by Shagon94** [comment]
```yaml
# Pihole
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      - HOST_CONTAINERNAME=pihole
      - IPv6=False
      - DNSMASQ_LISTENING=all
      - WEBUIBOXEDLAYOUT=boxed
      - WEBTHEME=default-dark
      - PIHOLE_DNS_=cloudflared#5053
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3001:80/tcp
    volumes:
      - pihole_data:/etc/pihole/
      - pihole_dnsmasq:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: always
    hostname: pihole

volumes:
  pihole_data:
  pihole_dnsmasq:
```

**Comment by yubiuser** [comment]
This file is missing the `FTLCONF_webserver_api_password`

**Comment by Shagon94** [comment]
That is correct, yes. I can re-test with `FTLCONF_webserver_api_password` if needed.

**Comment by yubiuser** [comment]
Please do so. Our internal test allowed to disable authentication with `FTLCONF_webserver_api_password=""`

**Comment by Shagon94** [comment]
```
❯ docker container logs pihole | grep password
  [i] Assigning password defined by Environment Variable
2025-02-19 22:06:24.353 CET [57M] INFO:    [✓] FTLCONF_webserver_api_password is used
```

going to the admin page redirects to the `/admin/login` page

**Comment by rdwebdesign** [comment]
There is no password variable in your compose file above.

---

I think I know what is causing the "issue".
There are more than one way to set environment variables in a compose file.

You are using `- VAR=VALUE`, but there is also another format: `VAR: "value"`.

I tested assigning an empty password using different formats and this is the result:
```yml
    environment:
      - FTLCONF_webserver_api_password=          ### empty password is set
      - FTLCONF_webserver_api_password=""        ### password will be ("") - 2 double quotes
      - FTLCONF_webserver_api_password=''        ### password will be ('') - 2 single quotes


      FTLCONF_webserver_api_password:            ### variable is not set and a random password is created
      FTLCONF_webserver_api_password: ""        ### empty password is set
      FTLCONF_webserver_api_password: ''        ### empty password is set
```

If you want to set an empty password using format you are already using, you need to set it like this:

```yml
    environment:
      - FTLCONF_webserver_api_password=          ### do not add quotes here
```

If you use the format used in our example, use quotes to represent an empty string:
```yml
    environment:
      FTLCONF_webserver_api_password: ""
```
