### ISSUE TITLE
Fresh deployment = Cannot open config file /etc/pihole/pihole.toml in exclusive mode (r): Bad file descriptor

### ISSUE THREAD

**Issue by virtualex-itv** [pi-hole/docker-pi-hole#1715]
This is a: Bug 

## Details

spinning up a new instance of pihole v6 today in docker and using the newer env vars.  however, when i spin up the container I am seeing the following error in the logs:
```
Cannot open config file /etc/pihole/pihole.toml in exclusive mode (r): Bad file descriptor
```
therefore, none of the settings i am trying to configure are getting applied.

**Note: This seems to happen only if/when using a persistent volume on an external device (NFS in my case).**

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Ubuntu** 
  * VMware VMs & RasPi 4B: 
  * Kernel Architecture:x86 & Arm 64bit 
  * Docker Install Info and version: 
    - Software source: official docker-ce
    - Supplimentary Software: portainer
  * Hardware architecture: x86 & ARMv7

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

```
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    security_opt:
      - no-new-privileges:false
    hostname: pi.hole
    environment:
      # recommended
      - TZ=${TZ}
      - FTLCONF_webserver_api_password=${SECRET}
      # optional
      - FTLCONF_dns_upstreams=1.1.1.1;9.9.9.9
      - FTLCONF_dns_dnssec=true
      - FTLCONF_dns_bogusPriv=true
      - FTLCONF_dns_domainNeeded=true
      - FTLCONF_webserver_interface_theme=auto
      # advanced
      - FTLCONF_dns_specialDomains_iCloudPrivateRelay=false
    volumes:
      - ${DOCKER_DIR}/appdata/pihole/pihole:/etc/pihole
      - ${DOCKER_DIR}/appdata/pihole/dnsmasq.d:/etc/dnsmasq.d
    networks:
      proxy:
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 1080:80/tcp
      - 1443:443/tcp
    dns:
      - 127.0.0.1
      - 1.1.1.1

networks:
  proxy:
    external: true
```

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
