### ISSUE TITLE
Brand new deployment - [✗] DNS resolution is currently unavailable

### ISSUE THREAD

**Issue by mill1000** [pi-hole/docker-pi-hole#1743]
Using the example Docker compose file in the README.md doesn't bring up a functional Pi-Hole instance.

The final log is "[✗] DNS resolution is currently unavailable" and the web interface is unavailable.

The output of the container on first start
```
Attaching to pihole-test
pihole-test  |   [i] Setting up user & group for the pihole user
pihole-test  |   [i] PIHOLE_UID not set in environment, using default (1000)
pihole-test  |   [i] PIHOLE_GID not set in environment, using default (1000)
pihole-test  | 
pihole-test  |   [i] Starting FTL configuration
pihole-test  |   [i] No DNS upstream set in environment or config file, defaulting to Google DNS
pihole-test  |   [i] Assigning password defined by Environment Variable
pihole-test  |   [i] Starting crond for scheduled scripts. Randomizing times for gravity and update checker
pihole-test  | 
pihole-test  |   [i] Ensuring logrotate script exists in /etc/pihole
pihole-test  | 
pihole-test  |   [i] Gravity migration checks
pihole-test  |   [i] No adlist file found, creating one with a default blocklist
pihole-test  |   [i] /etc/pihole/gravity.db does not exist (Likely due to a fresh volume). This is a required file for Pi-hole to operate.
pihole-test  |   [i] Gravity will now be run to create the database
  [✗] Migrating the list's cache directory to new location
pihole-test  | sed: /etc/pihole/listsCache/*.sha1: No such file or directory
pihole-test  |   [i] Creating new gravity database
pihole-test  |   [i] Migrating content of /etc/pihole/adlists.list into new database
pihole-test  |   [✗] DNS resolution is currently unavailable
```

This is a bug 

## Details

Subsequent starts of the container also fail, but this time with SQL errors.
```
Attaching to pihole-test
pihole-test  |   [i] Setting up user & group for the pihole user
pihole-test  |   [i] PIHOLE_UID not set in environment, using default (1000)
pihole-test  |   [i] PIHOLE_GID not set in environment, using default (1000)
pihole-test  | 
pihole-test  |   [i] Starting FTL configuration
pihole-test  |   [i] Assigning password defined by Environment Variable
pihole-test  |   [i] Starting crond for scheduled scripts. Randomizing times for gravity and update checker
pihole-test  | 
pihole-test  |   [i] Ensuring logrotate script exists in /etc/pihole
pihole-test  | 
pihole-test  |   [i] Gravity migration checks
pihole-test  |   [i] No adlist file found, creating one with a default blocklist
pihole-test  |   [i] Existing gravity database found - schema will be upgraded if necessary
pihole-test  |      
pihole-test  | 
pihole-test  |   [i] pihole-FTL pre-start checks
pihole-test  |   [i] Setting capabilities on pihole-FTL where possible
pihole-test  |   [i] Applying the following caps to pihole-FTL:
pihole-test  |         * CAP_CHOWN
pihole-test  |         * CAP_NET_BIND_SERVICE
pihole-test  |         * CAP_NET_RAW
pihole-test  |         * CAP_NET_ADMIN
pihole-test  |         * CAP_SYS_NICE
pihole-test  |         * CAP_SYS_TIME
pihole-test  | 
pihole-test  |   [i] Starting pihole-FTL (no-daemon) as pihole
pihole-test  | 
pihole-test  |   [i] Version info:
pihole-test  |       Core version is v6.0.3 (Latest: v6.0.3)
pihole-test  |       Web version is v6.0.1 (Latest: v6.0.1)
pihole-test  |       FTL version is v6.0.2 (Latest: v6.0.2)
pihole-test  | 
pihole-test  | 2025-02-22 21:41:26.963 GMT [54M] INFO: ########## FTL started on 6dd45fb71353! ##########
pihole-test  | 2025-02-22 21:41:26.964 GMT [54M] INFO: FTL branch: master
pihole-test  | 2025-02-22 21:41:26.964 GMT [54M] INFO: FTL version: v6.0.2
pihole-test  | 2025-02-22 21:41:26.964 GMT [54M] INFO: FTL commit: ac500d5f
pihole-test  | 2025-02-22 21:41:26.964 GMT [54M] INFO: FTL date: 2025-02-21 21:48:20 +0000
pihole-test  | 2025-02-22 21:41:26.964 GMT [54M] INFO: FTL user: pihole
pihole-test  | 2025-02-22 21:41:26.964 GMT [54M] INFO: Compiled for linux/amd64 (compiled on CI) using cc (Alpine 14.2.0) 14.2.0
pihole-test  | 2025-02-22 21:41:27.093 GMT [54M] INFO: 1 FTLCONF environment variable found (1 used, 0 invalid, 0 ignored)
pihole-test  | 2025-02-22 21:41:27.093 GMT [54M] INFO:    [✓] FTLCONF_webserver_api_password is used
pihole-test  | 2025-02-22 21:41:27.095 GMT [54M] INFO: Wrote config file:
pihole-test  | 2025-02-22 21:41:27.095 GMT [54M] INFO:  - 152 total entries
pihole-test  | 2025-02-22 21:41:27.095 GMT [54M] INFO:  - 149 entries are default
pihole-test  | 2025-02-22 21:41:27.095 GMT [54M] INFO:  - 3 entries are modified
pihole-test  | 2025-02-22 21:41:27.095 GMT [54M] INFO:  - 0 entries are forced through environment
pihole-test  | 2025-02-22 21:41:27.097 GMT [54M] INFO: Parsed config file /etc/pihole/pihole.toml successfully
pihole-test  | 2025-02-22 21:41:27.097 GMT [54M] INFO: PID file does not exist or not readable
pihole-test  | 2025-02-22 21:41:27.097 GMT [54M] INFO: No other running FTL process found.
pihole-test  | 2025-02-22 21:41:27.101 GMT [54M] INFO: PID of FTL process: 54
pihole-test  | 2025-02-22 21:41:27.102 GMT [54M] INFO: listening on 0.0.0.0 port 53
pihole-test  | 2025-02-22 21:41:27.102 GMT [54M] INFO: listening on :: port 53
pihole-test  | 2025-02-22 21:41:27.104 GMT [54M] INFO: PID of FTL process: 54
pihole-test  | 2025-02-22 21:41:27.104 GMT [54M] WARNING: No database file found, creating new (empty) database
pihole-test  | 2025-02-22 21:41:27.130 GMT [54M] INFO: Database version is 1
pihole-test  | 2025-02-22 21:41:27.130 GMT [54M] INFO: Updating long-term database to version 2
pihole-test  | 2025-02-22 21:41:27.135 GMT [54M] INFO: Updating long-term database to version 3
pihole-test  | 2025-02-22 21:41:27.140 GMT [54M] INFO: Updating long-term database to version 4
pihole-test  | 2025-02-22 21:41:27.144 GMT [54M] INFO: Updating long-term database to version 5
pihole-test  | 2025-02-22 21:41:27.153 GMT [54M] INFO: Updating long-term database to version 6
pihole-test  | 2025-02-22 21:41:27.158 GMT [54M] INFO: Updating long-term database to version 7
pihole-test  | 2025-02-22 21:41:27.162 GMT [54M] INFO: Updating long-term database to version 8
pihole-test  | 2025-02-22 21:41:27.172 GMT [54M] INFO: Updating long-term database to version 9
pihole-test  | 2025-02-22 21:41:27.176 GMT [54M] INFO: Updating long-term database to version 10
pihole-test  | 2025-02-22 21:41:27.186 GMT [54M] INFO: Updating long-term database to version 11
pihole-test  | 2025-02-22 21:41:27.193 GMT [54M] INFO: Updating long-term database to version 12
pihole-test  | 2025-02-22 21:41:27.199 GMT [54M] INFO: Updating long-term database to version 13
pihole-test  | 2025-02-22 21:41:27.204 GMT [54M] INFO: Updating long-term database to version 14
pihole-test  | 2025-02-22 21:41:27.209 GMT [54M] INFO: Updating long-term database to version 15
pihole-test  | 2025-02-22 21:41:27.215 GMT [54M] INFO: Updating long-term database to version 16
pihole-test  | 2025-02-22 21:41:27.219 GMT [54M] INFO: Updating long-term database to version 17
pihole-test  | 2025-02-22 21:41:27.225 GMT [54M] INFO: Updating long-term database to version 18
pihole-test  | 2025-02-22 21:41:27.230 GMT [54M] INFO: Updating long-term database to version 19
pihole-test  | 2025-02-22 21:41:27.234 GMT [54M] INFO: Updating long-term database to version 20
pihole-test  | 2025-02-22 21:41:27.242 GMT [54M] INFO: Updating long-term database to version 21
pihole-test  | 2025-02-22 21:41:27.247 GMT [54M] INFO: Database successfully initialized
pihole-test  | 2025-02-22 21:41:27.258 GMT [54M] INFO: Imported 0 queries from the on-disk database (it has 0 rows)
pihole-test  | 2025-02-22 21:41:27.258 GMT [54M] INFO: Parsing queries in database
pihole-test  | 2025-02-22 21:41:27.258 GMT [54M] INFO: Imported 0 queries from the long-term database
pihole-test  | 2025-02-22 21:41:27.258 GMT [54M] INFO:  -> Total DNS queries: 0
pihole-test  | 2025-02-22 21:41:27.258 GMT [54M] INFO:  -> Cached DNS queries: 0
pihole-test  | 2025-02-22 21:41:27.258 GMT [54M] INFO:  -> Forwarded DNS queries: 0
pihole-test  | 2025-02-22 21:41:27.258 GMT [54M] INFO:  -> Blocked DNS queries: 0
pihole-test  | 2025-02-22 21:41:27.258 GMT [54M] INFO:  -> Unknown DNS queries: 0
pihole-test  | 2025-02-22 21:41:27.258 GMT [54M] INFO:  -> Unique domains: 0
pihole-test  | 2025-02-22 21:41:27.258 GMT [54M] INFO:  -> Unique clients: 0
pihole-test  | 2025-02-22 21:41:27.258 GMT [54M] INFO:  -> DNS cache records: 0
pihole-test  | 2025-02-22 21:41:27.258 GMT [54M] INFO:  -> Known forward destinations: 0
pihole-test  | 2025-02-22 21:41:27.337 GMT [54M] INFO: FTL is running as user pihole (UID 1000)
pihole-test  | 2025-02-22 21:41:27.342 GMT [54M] INFO: Created SSL/TLS certificate for pi.hole at /etc/pihole/tls.pem
pihole-test  | 2025-02-22 21:41:27.342 GMT [54M] INFO: Reading certificate from /etc/pihole/tls.pem ...
pihole-test  | 2025-02-22 21:41:27.343 GMT [54M] INFO: Using SSL/TLS certificate file /etc/pihole/tls.pem
pihole-test  | 2025-02-22 21:41:27.343 GMT [54M] INFO: Web server ports:
pihole-test  | 2025-02-22 21:41:27.343 GMT [54M] INFO:   - 80 (HTTP, IPv4, optional)
pihole-test  | 2025-02-22 21:41:27.343 GMT [54M] INFO:   - 443 (HTTPS, IPv4, optional)
pihole-test  | 2025-02-22 21:41:27.343 GMT [54M] INFO:   - 80 (HTTP, IPv6, optional)
pihole-test  | 2025-02-22 21:41:27.343 GMT [54M] INFO:   - 443 (HTTPS, IPv6, optional)
pihole-test  | 2025-02-22 21:41:27.344 GMT [54M] INFO: Restored 0 API sessions from the database
pihole-test  | 2025-02-22 21:41:27.347 GMT [54M] INFO: Blocking status is enabled
pihole-test  | 2025-02-22 21:41:27.439 GMT [54/T57] ERROR: gravityDB_count(SELECT value FROM info WHERE property = 'gravity_count';) - SQL error step no more rows available
pihole-test  | 2025-02-22 21:41:27.439 GMT [54/T57] WARNING: Count of gravity domains not available. Please run pihole -g
pihole-test  | 2025-02-22 21:41:27.441 GMT [54/T57] INFO: Compiled 0 allow and 0 deny regex for 1 client in 0.2 msec
pihole-test  | 2025-02-22 21:41:28.046 GMT [54/T57] ERROR: gravity_updated(): SELECT value FROM info WHERE property = 'updated'; - SQL error step: no more rows available
pihole-test  | 2025-02-22 21:41:28.106 GMT [54M] WARNING: WARNING in dnsmasq core: ignoring query from non-local network 10.100.1.194 (logged only once)
pihole-test  | 2025-02-22 21:41:29.052 GMT [54/T57] ERROR: gravity_updated(): SELECT value FROM info WHERE property = 'updated'; - SQL error step: no more rows available
pihole-test  | 2025-02-22 21:41:30.064 GMT [54/T57] ERROR: gravity_updated(): SELECT value FROM info WHERE property = 'updated'; - SQL error step: no more rows available
pihole-test  | 2025-02-22 21:41:31.070 GMT [54/T57] ERROR: gravity_updated(): SELECT value FROM info WHERE property = 'updated'; - SQL error step: no more rows available
pihole-test  | 2025-02-22 21:41:31.649 GMT [54/T56] INFO: Received 8/8 valid NTP replies from pool.ntp.org
pihole-test  | 2025-02-22 21:41:31.649 GMT [54/T56] INFO: Time offset: 3.775060e+00 ms (excluded 0 outliers)
pihole-test  | 2025-02-22 21:41:31.650 GMT [54/T56] INFO: Round-trip delay: 3.635454e+01 ms (excluded 0 outliers)
pihole-test  | 2025-02-22 21:41:31.650 GMT [54/T160] INFO: NTP server listening on 0.0.0.0:123 (IPv4)
pihole-test  | 2025-02-22 21:41:31.650 GMT [54/T161] INFO: NTP server listening on :::123 (IPv6)
pihole-test  | 2025-02-22 21:41:32.075 GMT [54/T57] ERROR: gravity_updated(): SELECT value FROM info WHERE property = 'updated'; - SQL error step: no more rows available
```

The only changes to the example docker-compose were the container name and the host ports
```
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole-test
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "8080:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "4430:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: 'Europe/London'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: 'correct horse battery staple'
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - './etc-pihole:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
```

I checked the image with `docker image inspect` and the version is reported as  `"org.opencontainers.image.version": "2025.02.4"`

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Debian 12 - 6.1.0-28-amd64
  * Hardware: Dell Thin Client
  * Kernel Architecture: amd64
  * Docker Install Info and version: 
    - Software source: Official Docker CE
    - Supplimentary Software: N/A
  * Hardware architecture: x86
  *
## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
