### ISSUE TITLE
Suggested dns_listeningMode settings incorrect

### ISSUE THREAD

**Issue by bmbenson** [pi-hole/docker-pi-hole#1744]
This is a: Documentation Bug  

## Details
When using the suggested value on the project readme:
https://github.com/pi-hole/docker-pi-hole/#running-pi-hole-docker
Suggestion:
```
If using Docker's default bridge network setting, set the environment variable FTLCONF_dns_listeningMode to all.
```

But when starting up with the latest, I get the error:
```
2025-02-22 16:42:08.399 PST [56M] WARNING: ENV FTLCONF_dns_listeningMode is not an allowed option, allowed options are: Pi-hole interface listening modes
2025-02-22 16:42:08.590 PST [56M] INFO: 3 FTLCONF environment variables found (1 used, 1 invalid, 1 ignored)
2025-02-22 16:42:08.590 PST [56M] ERROR:   [✗] FTLCONF_dns_listeningMode is invalid (not an allowed option, allowed options are: Pi-hole interface listening modes)
```

I corrected the issue by providing these settings:
```
      FTLCONF_dns_listeningMode: 'SINGLE'
      FTLCONF_dns_interface: 'eth0'
```

I would open a PR to correct the readme, but I want to be sure I'm not missing something.

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu
  * Hardware: intel x86 desktop
  * Kernel Architecture: x86_64
  * Docker Install Info and version: 
    - Software source: docker official repo
  * Hardware architecture: x86_64
  * Kernel uname -a: Linux linux-MS-7885 6.8.0-52-generic #53~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jan 15 19:18:46 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

Working config:
cat pihole.compose.yaml 
```
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: 'America/Los_Angeles'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: 'REDACTED'
      FTLCONF_dns_listeningMode: 'SINGLE'
      FTLCONF_dns_interface: 'eth0'
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - './etc-pihole:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
```
Using it:
` docker compose -f ./pihole.compose.yaml up -d`

**Comment by yubiuser** [comment]
Please post your docker-compose file when it is not working.

**Comment by bmbenson** [comment]
Compose that throws the error mentioned: (due to FTLCONF_dns_listeningMode: 'any')
```
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: 'America/Los_Angeles'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: 'REDACTED'
      FTLCONF_dns_listeningMode: 'any'
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - './etc-pihole:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stoppe
```

**Comment by yubiuser** [comment]
> FTLCONF_dns_listeningMode: 'all'

Could you, even if it's unlikely to fix it, try with upper case. FTLCONF_dns_listeningMode: 'ALL'

**Comment by bmbenson** [comment]
That did the trick!  The pihole suggested values message "...allowed options are: <...>" sent me on a path thinking the 'all' option was deprecated in v6.  Makes sense it's case sensitive! Thank you!

```
2025-02-23 12:00:11.870 PST [56M] INFO: 2 FTLCONF environment variables found (2 used, 0 invalid, 0 ignored)
2025-02-23 12:00:11.870 PST [56M] INFO:    [✓] FTLCONF_dns_listeningMode is used
2025-02-23 12:00:11.870 PST [56M] INFO:    [✓] FTLCONF_webserver_api_password is used
```

**Comment by bmbenson** [comment]
Full working config for others that may come along and find it:

```
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: 'America/Los_Angeles'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: 'REDACTED'
      FTLCONF_dns_listeningMode: 'ALL'
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - './etc-pihole:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
```
