### ISSUE TITLE
Docker restart, wrong queries counts

### ISSUE THREAD

**Issue by manilx** [pi-hole/docker-pi-hole#1761]
Latest Docker piholev6 installed.

```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 443:443/tcp
    environment:
      TZ: Europe/Lisbon
      FTLCONF_webserver_api_password: password
      FTLCONF_dns_listeningMode: all
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
networks: {}

```

When I stop and restart pihole, the Total_Queries and Queries_Blocked values are not the last ones before the stop. But from some time back.
They should be saved  between restarts....?
