### ISSUE TITLE
After updating to v6, after every container version update, unable to log in using existing cookies/password

### ISSUE THREAD

**Issue by evulhotdog** [pi-hole/docker-pi-hole#1769]
This is a: **Bug**  

## Details

Every time that the container is updated, after trying to reauthenticate with pihole or using existing cookies it fails to log me in. I am required to clear cookies for some reason. This did not occur in v5.

<img width="695" alt="Image" src="https://github.com/user-attachments/assets/8a2895cb-a252-4a90-b912-f94277c29d14" />

If I manually remove the cookies from my browser for the ip:port of pihole, it works fine. 

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **docker** 
  * Hardware: virtual machine
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: 
    - Software source: ghcr.io/pi-hole/pihole:2025.02.4
    - Supplimentary Software: 
  * Hardware architecture: x86

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: default
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: ghcr.io/pi-hole/pihole:2025.02.4
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add: ["SYS_NICE"]

        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /admin/
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

        resources:
          requests:
            memory: 100Mi
            cpu: "10m"

        env:
        - name: TZ
          value: "America/New_York"
        - name: FTLCONF_webserver_api_password
          valueFrom:
           secretKeyRef:
             name: pihole
             key: password

        # Sets upstream DNS servers
        - name: FTLCONF_dns_upstreams
          value: 10.0.10.1

        # Disable rate limiter
        - name: FTLCONF_dns_rateLimit_count
          value: "0"
        - name: FTLCONF_dns_rateLimit_interval
          value: "0"

        # Allows more than just the local subnet to use the resolver.
        - name: FTLCONF_dns_listeningMode
          value: "all"

        ports:
        - containerPort: 80

        volumeMounts:
        - name: etc-pihole
          mountPath: /etc/pihole
        - name: etc-dnsmasq-d
          mountPath: /etc/dnsmasq.d
        - name: dshm
          mountPath: /dev/shm

      volumes:
        - name: etc-pihole
          persistentVolumeClaim:
            claimName: pvc-pihole-etc-pihole
        - name: etc-dnsmasq-d
          persistentVolumeClaim:
            claimName: pvc-pihole-etc-dnsmasq-d
# Pi-hole runs into some limit on the default image.
# https://www.reddit.com/r/pihole/comments/zgm48b/pihole_reporting_ram_shortage_when_there_is/
# Fix: https://stackoverflow.com/questions/43373463/how-to-increase-shm-size-of-a-kubernetes-container-shm-size-equivalent-of-doc
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 500Mi

```
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by ivanjx** [comment]
i already set the pihole password to empty. however, i am always logged out and cant login anymore on each container recreate.

i always have to run `pihole setpassword` to login now.

**Comment by rdwebdesign** [comment]
> i already set the pihole password to empty

How did you set it? Can you please post the compose file lines where you set the empty password?

**Comment by ivanjx** [comment]
@rdwebdesign `pihole setpassword` in the container.

but honestly i have had enough of many issues surrounding this v6 release. i just revert back to v5 and will never update ever again.

**Comment by PromoFaux** [comment]
@ivanjx - please don't hijack other people's issues. 

Please read the manual, if describes how to set an empty password in docker. 

![Screenshot_20250301-093830.png](https://github.com/user-attachments/assets/56fd522b-464c-4c94-b68f-abdd76612e78)

**Comment by PromoFaux** [comment]
@evulhotdog - will try to look at this later - though I am unable to reproduce your issue, I have seen someone else on our forums mention something similar

**Comment by rdwebdesign** [comment]
@evulhotdog 

Does the issue happen if you try to set the password directly on the compose file, like this?

```yml
      env:
        TZ: "America/New_York"
        FTLCONF_webserver_api_password: "my_secret_password"
```
