### ISSUE TITLE
Upgrade from 2024.07.0 to 2025.02.07 failed

### ISSUE THREAD

**Issue by jimmywan** [pi-hole/docker-pi-hole#1774]
After upgrading from 2024.07.0 to 2025.02.07, the UI eventually starts up but complains that it's unable to connect to local DNS (cloudflared running in the same portainer stack). Clicking around in the interface, a few of the screens don't work (clients, groups, etc). Most notably, DNS is **NOT** working. Local testing of cloudflared indicates that it appears to be working fine.
```
 dig @192.168.1.4 -p 5053 google.com

; <<>> DiG 9.18.30-0ubuntu0.24.04.2-Ubuntu <<>> @192.168.1.4 -p 5053 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20839
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: a704732a048cdcaf (echoed)
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             298     IN      A       142.251.116.138
google.com.             298     IN      A       142.251.116.139
google.com.             298     IN      A       142.251.116.113
google.com.             298     IN      A       142.251.116.100
google.com.             298     IN      A       142.251.116.101
google.com.             298     IN      A       142.251.116.102

;; Query time: 0 msec
;; SERVER: 192.168.1.4#5053(192.168.1.4) (UDP)
;; WHEN: Mon Mar 03 14:34:50 CST 2025
;; MSG SIZE  rcvd: 207
```

After reverting to 2024.07.0 which had been working, it complains about unexpected DB changes (understandable), as this ends up in my logs:
``` [i] Creating new gravity databases...

  [✗] Unable to copy data from /etc/pihole/gravity.db to /etc/pihole/gravity.db_temp

  Parse error near line 18: table adlist has 10 columns but 12 values were supplied

Runtime error near line 20: FOREIGN KEY constraint failed (19)

   [✗] Unable to create gravity database. Please try again later. If the problem persists, please contact support.
```

Bug

## Related Issues
- [ ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: DSM 7.2.2-72806 Update 3
  * Hardware: Synology DS 1019+
  * Kernel Architecture: 
  * Docker Install Info and version: 
    - Software source: Sy
    - Supplimentary Software: portainer 2.21.2
  * Hardware architecture: x86

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
version: "3.6"

services:
  cloudflared:
    container_name: cloudflared
    restart: unless-stopped
    image: cloudflare/cloudflared:2024.12.1
    command: proxy-dns
    environment:
      - "TUNNEL_DNS_UPSTREAM=https://9.9.9.11/dns-query,https://149.112.112.112/dns-query,https://[2620:fe::11]/dns-query,https://[2620:fe::fe:11]/dns-query"
      - "TUNNEL_METRICS=0.0.0.0:49312"
      - "TUNNEL_DNS_ADDRESS=0.0.0.0"
      - "TUNNEL_DNS_PORT=5053"
    # sysctls:
    #   - net.ipv4.ip_unprivileged_port_start=53
    networks:
      pihole_lan:
        ipv4_address: 192.168.1.4
      pihole_bridge:
        ipv4_address: 192.168.10.4
      
  pihole:
    cap_add:
      - NET_ADMIN # required if you are using Pi-hole as your DHCP server
    container_name: pihole
    restart: unless-stopped
    image: pihole/pihole:2025.02.7
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp # required if you are using Pi-hole as your DHCP server
      - 80/tcp      
    networks:
      pihole_lan:
        ipv4_address: 192.168.1.5
      pihole_bridge:
        ipv4_address: 192.168.10.2

    environment:
      - "TZ=America/Chicago"
      - "DNS1=192.168.1.4#5053"
      - "DNS2=no"
      - "DNSMASQ_LISTENING=all"
      - "DNSMASQ_USER=xxxx"
      - "WEBPASSWORD=xxxx"
    volumes:
      - '/volume1/docker/pihole/pihole/:/etc/pihole/'
      - '/volume1/docker/pihole/dnsmasq.d/:/etc/dnsmasq.d/'

networks:
  pihole_lan:
    external: true
    name: dns
  pihole_bridge:
    external: true
    name: dns_bridge
```
4. any additional info to help reproduce
I was really hoping to not have to nuke all of my historical data and configuration. I see that the old configs were backed up, but it looks like it doesn't auto backup the DBs.

## These common fixes didn't work for my issue

- [ ] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
