### ISSUE TITLE
Unable login into admin panel

### ISSUE THREAD

**Issue by agentsas** [pi-hole/docker-pi-hole#1785]
This is a: Run Issue (running Pi-hole container failing), 

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu 
  * Hardware: Rock 5b
  * Kernel Architecture: ArmV8 64bit
  * Docker Install Info and version: 
    - Software source: official docker-ce
  * Hardware architecture: aarch64

2. docker-compose.yml contents
```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "533:53/tcp"
      - "533:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      # Set the appropriate timezone for your location from
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: 'Europe/Kaliningrad'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - './data:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
```
3. on login form submit getting this response
```
{
    "session": {
        "valid": false,
        "totp": false,
        "sid": null,
        "validity": -1,
        "message": "no SID provided"
    },
    "took": 2.47955322265625e-05
}
```

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by crispybegs** [comment]
`      # Set a password to access the web interface. Not setting one will result in a random password being assigned
`

shouldn't you have a password in your compose?

```
environment:
      TZ: 'Europe/Kaliningrad'
      FTLCONF_webserver_api_password: 'your_password_here'
      FTLCONF_dns_listeningMode: 'all'
```
