### ISSUE TITLE
Password problem

### ISSUE THREAD

**Issue by dogukansahil** [pi-hole/docker-pi-hole#1819]
After upgrading to 2025.02.0 (Pi-hole v6) on Raspberry Pi using CasaOS (Docker), I can no longer log in to the admin panel—even after resetting the password with pihole -a -p. This issue did not exist in 2024s.

Related Issues
 I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar

How to reproduce the issue
Environment data

Operating System: Raspberry Pi OS (64-bit), via CasaOS

Hardware: Raspberry Pi 5

Kernel Architecture: ARMv8 64-bit

Docker Install Info and version:

Software source: Docker CE via CasaOS

Supplimentary Software: CasaOS UI

Hardware architecture: ARM64

**Comment by yubiuser** [comment]
> I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar

Sure? We had quite some issues regarding this with V6.

Also, please don't ignore the help template and post all the requested information.

**Comment by dogukansahil** [comment]
> > I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar
> 
> Sure? We had quite some issues regarding this with V6.
> 
> Also, please don't ignore the help template and post all the requested information.

Thanks for the response. I'm running Pi-hole v6 (2025.03.0) via Docker on Raspberry Pi 5, deployed through CasaOS. Initially, both WEBPASSWORD and FTLCONF_webserver_api_password were set (the former added automatically by CasaOS). I removed WEBPASSWORD and left only FTLCONF_webserver_api_password=dogukan2025!, and logs clearly confirm it's being used: "Assigning password defined by Environment Variable" and "[✓] FTLCONF_webserver_api_password is used". Despite this, I still can't log in to the admin interface at http://<IP>:8801/admin — I've tried incognito mode, different browsers, typing the password manually, and even setting the env variable empty to disable authentication. Running pihole setpassword also fails with the expected message about the env variable taking precedence. At this point, the container boots cleanly, the logs show no errors, the password is applied via env var, but login always fails. I'm stuck unless there's something subtle I'm missing or a bug in the authentication layer for v6 in Docker/CasaOS setups.

**Comment by rdwebdesign** [comment]
Did you try to add single quotes around your password?

```ini
FTLCONF_webserver_api_password='dogukan2025!'
```

**Comment by dogukansahil** [comment]
> Did you try to add single quotes around your password?
> 
> FTLCONF_webserver_api_password='dogukan2025!'

Yes I tried it and even added it as a variable with casaos.

**Comment by rdwebdesign** [comment]
Please post your compose file.

**Comment by dogukansahil** [comment]
> Please post your compose file.
For example, when I do it like this, the quotation marks are also included in the password, but I tried every way.

```
name: pihole
services:
  pihole:
    cpu_shares: 90
    command: []
    container_name: pihole
    deploy:
      resources:
        limits:
          memory: 4045M
        reservations:
          memory: "67108864"
    environment:
      - FTLCONF_webserver_api_password='dogukan2025!'
      - PROXY_LOCATION=pi.hole
      - TZ=Europe/Istanbul
      - VIRTUAL_HOST=pi.hole
    hostname: pihole
    image: pihole/pihole:2025.03.0
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Pihole/icon.png
    ports:
      - target: 80
        published: "8801"
        protocol: tcp
      - target: 54
        published: "54"
        protocol: tcp
      - target: 54
        published: "54"
        protocol: udp
      - target: 67
        published: "67"
        protocol: udp
      - target: 547
        published: "547"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/pihole/etc/pihole/
        target: /etc/pihole
      - type: bind
        source: /DATA/AppData/pihole/etc/dnsmasq.d/
        target: /etc/dnsmasq.d
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
            zh_cn: 时区
        - container: WEBPASSWORD
          description:
            en_us: Pi-hole admin password
            zh_cn: Pi-hole 管理密码
        - container: VIRTUAL_HOST
          description:
            en_us: Pi-hole Custom Hostname
            zh_cn: Pi-hole 自定义域名
        - container: PROXY_LOCATION
          description:
            en_us: Pi-hole PROXY_LOCATION
      ports:
        - container: "80"
          description:
            en_us: WebUI HTTP Port
            zh_cn: WebUI HTTP 端口
        - container: "53"
          description:
            en_us: Pihole DNS port
            zh_cn: Pihole DNS 端口
        - container: "53"
          description:
            en_us: Pihole DNS port
            zh_cn: Pihole DNS 端口
          protocol: udp
        - container: "67"
          description:
            en_us: Pihole DHCP IPv4 port
            zh_cn: Pihole DHCP IPv4 端口
          protocol: udp
        - container: "547"
          description:
            en_us: Pihole DHCP IPv6 port
            zh_cn: Pihole DHCP IPv6 端口
          protocol: udp
      volumes:
        - container: /etc/pihole
          description:
            en_us: Pi-hole /etc/pihole directory.
            zh_cn: Pi-hole /etc/pihole 目录
        - container: /etc/dnsmasq.d
          description:
            en_us: Pi-hole /etc/dnsmasq.d directory.
            zh_cn: Pi-hole /etc/dnsmasq.d 目录
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm64
    - "386"
    - arm
  author: CasaOS Team
  category: Network
  description:
    ar_sa: تحكم محلي وخصوصية أولاً. مدعوم من مجتمع عالمي من المخترعين والمحبين لل
      DIY. مثالي للتشغيل على Raspberry Pi أو خادم محلي.
    de_de: Open-Source-Heimautomatisierung, die die lokale Steuerung und
      Privatsphäre zuerst berücksichtigt. Unterstützt von einer weltweiten
      Gemeinschaft von Bastlern und DIY-Enthusiasten. Perfekt zum Ausführen auf
      einem Raspberry Pi oder einem lokalen Server.
    en_us: Open source home automation that puts local control and privacy first.
      Powered by a worldwide community of tinkerers and DIY enthusiasts. Perfect
      to run on a Raspberry Pi or a local server.
    es_es: Automatización doméstica de código abierto que pone el control local y la
      privacidad en primer lugar. Impulsado por una comunidad mundial de
      entusiastas del bricolaje y los entusiastas del bricolaje. Perfecto para
      ejecutar en una Raspberry Pi o un servidor local.
    fr_fr: Automatisation domestique open source qui met le contrôle local et la vie
      privée en premier. Propulsé par une communauté mondiale de bricoleurs et
      d'enthusiastes DIY. Parfait pour fonctionner sur un Raspberry Pi ou un
      serveur local.
    hu_hu: Nyílt forrású otthoni automatizálás, amely először a helyi vezérlésre és
      a magánéletre helyezi a hangsúlyt. A világ minden tájáról érkező
      tinkererek és DIY rajongók közössége támogatja. Tökéletesen működik egy
      Raspberry Pi-n vagy egy helyi szerveren.
    it_it: Automazione domestica open source che mette il controllo locale e la
      privacy in primo piano. Alimentato da una comunità mondiale di tinkerers e
      appassionati di DIY. Perfetto per eseguire su una Raspberry Pi o un server
      locale.
    pl_pl: Otwartoźródłowa automatyzacja domowa, która umieszcza kontrolę lokalną i
      prywatność na pierwszym miejscu. Napędzane przez międzynarodową
      społeczność tinkerów i entuzjastów DIY. Idealne do uruchamiania na
      Raspberry Pi lub lokalnym serwerze.
    pt_br: Automação residencial de código aberto que coloca o controle local e a
      privacidade em primeiro lugar. Alimentado por uma comunidade mundial de
      tinkerers e entusiastas DIY. Perfeito para executar em uma Raspberry Pi ou
      um servidor local.
    ru_ru: Open source home automation that puts local control and privacy first.
      Powered by a worldwide community of tinkerers and DIY enthusiasts. Perfect
      to run on a Raspberry Pi or a local server.
    sv_se: Öppen källkods hemautomation som sätter lokal kontroll och integritet i
      första hand. Drivs av en global gemenskap av tinkerers och
      DIY-entusiaster. Perfekt att köra på en Raspberry Pi eller en lokal
      server.
    uk_ua: Open source home automation that puts local control and privacy first.
      Powered by a worldwide community of tinkerers and DIY enthusiasts. Perfect
      to run on a Raspberry Pi or a local server.
    zh_cn: 开源家庭自动化系统，将本地控制和隐私放在首位。由全球 DIY 爱好者和 DIY 爱好者组成的社区提供支持。适合在树莓派或本地服务器上运行。
  developer: Pi-hole
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Pihole/icon.png
  index: /admin
  is_uncontrolled: false
  main: pihole
  port_map: "8801"
  scheme: http
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Pihole/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Pihole/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Pihole/screenshot-3.jpg
  store_app_id: pihole
  tagline:
    ar_sa: حظر الإعلانات على نطاق الشبكة
    de_de: Netzwerkweite Werbeblockierung
    en_us: Network-wide Ad Blocking
    es_es: Bloqueo de anuncios a nivel de red
    fr_fr: Blocage des publicités sur tout le réseau
    hu_hu: Hálózati hirdetések blokkolása
    it_it: Blocco pubblicità a livello di rete
    pl_pl: Blokowanie reklam na całej sieci
    pt_br: Bloqueio de anúncios em toda a rede
    ru_ru: Блокировка рекламы на всей сети
    sv_se: Blockera annonser över hela nätverket
    uk_ua: Блокування реклами на всій мережі
    zh_cn: 网络广告拦截
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Pihole/thumbnail.jpg
  tips:
    before_install:
      en_us: |
        Default password: `casaos`
      zh_cn: |
        默认密码：`casaos`
  title:
    custom: ""
    en_us: Pi-hole

```

**Comment by rdwebdesign** [comment]
Can you try using a different format for the environment section?

Like this:
```yml
    environment:
      FTLCONF_webserver_api_password: 'dogukan2025!'  # You probably don't need the quotes here,
      PROXY_LOCATION: pi.hole                         #     but you can add it, just in case
      TZ: Europe/Istanbul
      VIRTUAL_HOST: pi.hole
```
