### ISSUE TITLE
FTLCONF_webserver_api_password does not work on http webui. It works on https webui only.

### ISSUE THREAD

**Issue by janusn** [pi-hole/docker-pi-hole#1821]
This is a: Bug

For a docker container, the environment variable `FTLCONF_webserver_api_password` does not work as intended when connecting with http port. A blank password works but anything else does not. The env. variable works fine while connecting through HTTPS port.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu 24.04.2 LTS Server 
  * Hardware: Intel NUC13 Core 1340P 
  * Kernel Architecture: amd64 
  * Docker Install Info and version: 
    - Software source: official docker-ce 
    - Supplimentary Software: 
  * Hardware architecture: amd64 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
$ cat compose.yaml
---
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4480:80/tcp"
      - "4443:443/tcp"
    env_file:
      - ./secrets.env
    environment:
      PIHOLE_UID: 1004
      PIHOLE_GID: 1004
      TZ: 'Europe/London'
      FTLCONF_dns_listeningMode: all
      FTLCONF_misc_etc_dnsmasq_d: true
    volumes:
      - './config/etc/pihole:/etc/pihole'
      - './config/etc/dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - CAP_SYS_NICE
    restart: unless-stopped
```
3. connect to the webui with a browser with a URL like `http://pihole.example.com:4480/admin/`
4. filling the password set to environment variable `FTLCONF_webserver_api_password`

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by casperklein** [comment]
I cannot confirm this. With the below example from the [README.md](https://github.com/pi-hole/docker-pi-hole/blob/master/README.md), I can access Pi-hole via HTTP using the password `correct horse battery staple` just fine:

```
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: 'Europe/London'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: 'correct horse battery staple'
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - './etc-pihole:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
```
