### ISSUE TITLE
Bug: Docker container unhealthy: Error relocating /usr/lib/libisc-9.20.9.so

### ISSUE THREAD

**Issue by jplegat** [pi-hole/docker-pi-hole#1845]
This is a: Bug  

Details

## Related Issues

- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar
  
  
  

## How to reproduce the issue

1. Environment data
  
  - Operating System: Ubuntu
  - Hardware: Milk-V Mars
  - Kernel Architecture: riscv64
  - Docker Install Info and version:
    
    ```
    Client:
     Version:           27.5.1
     API version:       1.47
     Go version:        go1.22.8
     Git commit:        27.5.1-0ubuntu3~24.10.1
     Built:             Tue Apr  1 14:07:21 2025
     OS/Arch:           linux/riscv64
     Context:           default
    
    Server:
     Engine:
      Version:          27.5.1
      API version:      1.47 (minimum version 1.24)
      Go version:       go1.22.8
      Git commit:       27.5.1-0ubuntu3~24.10.1
      Built:            Tue Apr  1 14:07:21 2025
      OS/Arch:          linux/riscv64
      Experimental:     false
     containerd:
      Version:          2.0.5
      GitCommit:        
     runc:
      Version:          1.2.5-0ubuntu1~24.10.1
      GitCommit:        
     docker-init:
      Version:          0.19.0
      GitCommit:        
    ```
    
    - Software source: Official docker image
    - Supplimentary Software: 
  - Hardware architecture: riscv64
2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here:
  
  ```
  services:
    pihole:
      container_name: pihole
    # image: pihole/pihole:2025.04.0
      image: pihole/pihole:latest
      ports:
        # DNS Ports
        - "53:53/tcp"
        - "53:53/udp"
        # Default HTTP Port
        - "80:80/tcp"
        # Default HTTPs Port. FTL will generate a self-signed certificate
        - "443:443/tcp"
        # Uncomment the below if using Pi-hole as your DHCP Server
        #- "67:67/udp"
      environment:
        # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
        TZ: 'America/Los_Angeles'
        # Set a password to access the web interface. Not setting one will result in a random password being assigned
        FTLCONF_webserver_api_password: 'zzzzz'
        FTLCONF_dns_upstreams: 172.30.200.3
        FTLCONF_dns_listeningMode: 'ALL'
      # Volumes store your data between container upgrades
      volumes:
        # For persisting Pi-hole's databases and common configuration file
        - '/home/ubuntu/docker/pihole/etc-pihole:/etc/pihole'
        # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards
        #- './etc-dnsmasq.d:/etc/dnsmasq.d'
      cap_add:
        # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
        # Required if you are using Pi-hole as your DHCP server, else not needed
        - NET_ADMIN
      restart: unless-stopped
      depends_on:
        - bind9
      networks:
        pihole_network:
          ipv4_address: 172.30.200.2 # <-- use this ip as dns when connected to pihole_network: (i.e. within a docker network)
    bind9:
      container_name: bind9
      # image: ghcr.io/jplegat/bind9.18:riscv64
      image: ghcr.io/jplegat/bind9_debian:riscv64
      hostname: bind9.local
      restart: unless-stopped
      ports:
        - 5335:53/tcp
        - 5335:53/udp
      networks:
        pihole_network:
          ipv4_address: 172.30.200.3 # <-- Pi-hole as upstream DNS
  networks:
    # Define a custom subnet for Pi-hole so that Bind can be an upstream DNS on port 53
    pihole_network:
      name: pihole_network
      ipam:
        driver: default
        config:
          - subnet: 172.30.200.0/24
            gateway: 172.30.200.1
            ip_range: 172.30.200.0/24
  ```
  
3. Start the containter with `docker compose`. Monitor the status until it changes to 'unhealthy'. Run `docker inspect`:
  

`docker inspect --format='{{json .State.Health}}' pihole | jq`

The output should be similar to:

```
{
  "Status": "unhealthy",
  "FailingStreak": 4,
  "Log": [
    {
      "Start": "2025-06-11T17:48:20.777122854-07:00",
      "End": "2025-06-11T17:48:21.944748064-07:00",
      "ExitCode": 1,
      "Output": "Error relocating /usr/lib/libisc-9.20.9.so: EVP_MD_CTX_get_size_ex: symbol not found\nError relocating /usr/lib/libisc-9.20.9.so: EVP_MD_CTX_get_size_ex: symbol not found\n"
    },
    {
      "Start": "2025-06-11T17:48:51.947620749-07:00",
      "End": "2025-06-11T17:48:53.110542794-07:00",
      "ExitCode": 1,
      "Output": "Error relocating /usr/lib/libisc-9.20.9.so: EVP_MD_CTX_get_size_ex: symbol not found\nError relocating /usr/lib/libisc-9.20.9.so: EVP_MD_CTX_get_size_ex: symbol not found\n"
    },
    {
      "Start": "2025-06-11T17:49:23.113425964-07:00",
      "End": "2025-06-11T17:49:24.265667919-07:00",
      "ExitCode": 1,
      "Output": "Error relocating /usr/lib/libisc-9.20.9.so: EVP_MD_CTX_get_size_ex: symbol not found\nError relocating /usr/lib/libisc-9.20.9.so: EVP_MD_CTX_get_size_ex: symbol not found\n"
    },
    {
      "Start": "2025-06-11T17:49:54.268124696-07:00",
      "End": "2025-06-11T17:49:55.419462395-07:00",
      "ExitCode": 1,
      "Output": "Error relocating /usr/lib/libisc-9.20.9.so: EVP_MD_CTX_get_size_ex: symbol not found\nError relocating /usr/lib/libisc-9.20.9.so: EVP_MD_CTX_get_size_ex: symbol not found\n"
    }
  ]
}
```

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
