### ISSUE TITLE
Comments break FTLCONF_dns_hosts in compose.yaml

### ISSUE THREAD

**Issue by coreyasmith** [pi-hole/docker-pi-hole#1850]
This is a: Bug

## Details

Pi-hole will not load any DNS hosts from `compose.yaml` if one of the hosts under `FTLCONF_dns_hosts` is commented out. I would expect the commented host to just be ignored, but other hosts to load as usual.

```yml
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      FTLCONF_dns_hosts: |
        192.168.1.2 foo.domain.com
        192.168.1.3 bar.domain.com
        #192.168.1.4 baz.domain.com
```

Remove the comment or commented line and DNS hosts load as expected.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Debian GNU/Linux 12 (bookworm) 
  * Hardware: Raspberry Pi 4 Model B 
  * Kernel Architecture: aarch64 
  * Docker Install Info and version: 
    - Software source: official docker-ce 
    - Supplimentary Software: N/A 
  * Hardware architecture: ARMv8 

2. See details above.

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
