### ISSUE TITLE
need a way to persist extra /etc/hosts entry to enable dnsmasq cnames (?)

### ISSUE THREAD

**Issue by jamesmanning** [pi-hole/docker-pi-hole#260]
I can volume-mount dnsmasq.d and get some cname mappings added but dnsmasq appears to require the cname targets be in /etc/hosts and I'm having to append them to /etc/hosts on each start of the container.

This is a... 

- [x] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

I want to provide some cname's for youtube/google/bing in order to enforce restricted search/viewing for my kids' devices.  I'm currently using the instructions from this post on the pi-hole discourse:

https://discourse.pi-hole.net/t/use-dns-to-force-youtube-into-restricted-mode-and-pi-hole/1996/15

I have dnsmasq.d volume-mounted and have a 05-restrict.conf, but as the instructions in that post indicate, the cnames don't take effect unless they are mapped to IP addresses in the /etc/hosts file.

The /etc/hosts file gets recreated on each start of the container, so each time I have to append to the /etc/hosts file

![image](https://user-images.githubusercontent.com/225626/38643477-36c6600c-3dab-11e8-8d89-348ed185c5e5.png)

Ideally I'd like a way to either persist the entries that need to be included in /etc/hosts or have a place to put a script that can append the entries before dnsmasq is started (or restart dnsmasq after the entries are added) since the entries appear to need to be present in the /etc/hosts at the time of dnsmasq starting up (writing them later isn't sufficient until dnsmasq is restarted).

I have to admit, having the /etc/hosts entries feels really unfortunate and I would have  hoped that dnsmasq could support just the cname step and get the A record resolutions from upstream instead of needing it locally, but I guess that's a dnsmasq restriction.

## Expected Behavior

Some way of persisting additional /etc/hosts or a programmatic place to append entries before dnsmasq starts

## Actual Behavior

Having to append to /etc/hosts and  restart dnsmasq each time the container starts

## Possible Fix

don't  know

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. docker run -d --name pihole -p 53:53/tcp -p 53:53/udp -p 80:80 -p 443:443 -v "/c/Users/james/Documents/pi-hole-config/pihole/:/etc/pihole/" -v "/c/Users/james/Documents/pi-hole-config/dnsmasq.d/:/etc/dnsmasq.d/" -e ServerIP="192.168.0.170" --restart=unless-stopped diginc/pi-hole:latest
2. follow instructions in post at https://discourse.pi-hole.net/t/use-dns-to-force-youtube-into-restricted-mode-and-pi-hole/1996/15

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Context and extra information

trying to add cnames to implement restrictions to youtube/google/bing via dns

## Your Environment 

* Docker Host Operating System and OS Version: Windows 10 Version 1709 build 16299.371
* Docker Version: 18.03.0-ce-win59 (16762)
* Hardware architecture:  x86

![image](https://user-images.githubusercontent.com/225626/38643950-ee98654e-3dac-11e8-842f-351f2b5cc3ca.png)

**Comment by diginc** [comment]
docker controls /etc/hosts typically, you have to tell it you want extra hosts at run time:

- for docker run: https://docs.docker.com/engine/reference/commandline/run/#add-entries-to-container-hosts-file---add-host
- for docker-compose: https://docs.docker.com/compose/compose-file/#extra_hosts

I have examples of this in the docker-compose files but I think it's worth a README change for better exposure since it ties in to customizing pihole

**Comment by jamesmanning** [comment]
@diginc Thank you so much! It didn't even dawn on me to see if this was something docker itself supported, my apologies for filing the issue.  You're absolutely right about the example compose files, I see the extra_hosts entry now. That's perfect!

**Comment by nickbreen** [comment]
You can also use dnsmasq's `--addn-hosts` option to specify an _additional_ hosts file to read.

E.g. in `/etc/dnsmasq.d/50-extra-hosts.conf` add
```
addn-hosts /etc/hosts.extra
```
Add you extra hosts to the `/etc/hosts.extra` file.

You'll probably want to fiddle around with docker volumes to persist the files.

**Comment by sebkouba** [comment]
This helped me figure out what my compose file should look like. This works for me, finally:

```
version: "3"
 
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'password123'
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    extra_hosts:
      - "ipad:192.168.2.2q6"
      - "mac:192.168.2.78"
      - "lifx:192.168.2.138"
      - "oneplus3:192.168.2.83"
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

I had added the names to hosts on the docker host which doesn't work and editing the hosts file inside the container doesn't work because docker overwrites it. Had to compose down and up rather than just restart for the changes to go live. Maybe this will help others...
