### ISSUE TITLE
Cannot deploy on Docker Swarm (RPi 3) using "docker stack deploy"

### ISSUE THREAD

**Issue by codestation** [pi-hole/docker-pi-hole#299]
Cannot deploy pi-hole on docker swarm using a docker-compose.yml. Fails with `no suitable node (unsupported platform on 3 nodes)`

This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

The image is using the wrong architecture so docker swarm fails to deploy a stack with this image.
```
docker run --rm mplatform/mquery diginc/pi-hole-multiarch:debian_armhf
Image: diginc/pi-hole-multiarch:debian_armhf
 * Manifest List: No
 * Supports: amd64/linux
```
A workaround is to create a service with --no-resolve-image, but then you cannot use the parameters on the yaml and have to start the service by hand.

## Expected Behavior

The service should be deployed and run.
## Actual Behavior

The service task fails with  `no suitable node (unsupported platform on 3 nodes)`
## Possible Fix

Use `manifest-tool` and upload a manifest with the correct mapping of image/architecture. An upside for using manifest-tool is that all users can reference the same image `diginc/pi-hole` and docker will download the correct image for their architecture.
## Steps to Reproduce and debugging done

1. Create `docker-compose.yml`
``` yml
version: '3.5'

services:
  pihole:
    image: diginc/pi-hole-multiarch:debian_armhf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - pihole-data:/etc/pihole
      - dnsmasq-data:/etc/dnsmasq.d
    environment:
      - TZ=UTC
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  pihole-data: {}
  dnsmasq-data: {}
```
2. `docker stack deploy -c docker-compose.yml pihole`

## Context and extra information

https://github.com/moby/moby/issues/35158
https://github.com/StefanScherer/whoami/blob/d5ca7e92bb9b9de03588cb7fdba13d5307fb8938/travis-deploy.sh#L56-L66

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version: 18.06.0-ce
* Hardware architecture: ARMv7 (Raspberry Pi 3B+)
