### ISSUE TITLE
No random password

### ISSUE THREAD

**Issue by StefanSchoof** [pi-hole/docker-pi-hole#309]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
I have no `WEBPASSWORD` environment variable set. I updated from the 3.3 image to the 4.0 version and now there is no login for the web required.

## Expected Behavior
After the update pi.hole still require a password.

## Actual Behavior
No password is required. My `pihole/setupVars.conf.update.bak` contains a line with 

```
WEBPASSWORD=<longAlphanumeric>
```

My `pihole/setupVars.conf` contains

```
WEBPASSWORD=
```

A `docker logs pihole | grep random` show nothing.

Running without a mapped `/etc/pihole` folder results also in a unprotected admin site.

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Hypriot
* Docker Version: 18.06.0-ce, build 0ffa825
* Hardware architecture:  Armv7 (rpi3)

**Comment by fsegouin** [comment]
Can confirm. I was about to post it as well.

**Comment by Haxy89** [comment]
Could you show your docker run command?

**Comment by StefanSchoof** [comment]
I use docker-compose with a `.env` file

```
pihole:
  restart: unless-stopped
  container_name: pihole
  image: pihole/pihole:v4.0_armhf
  volumes:
    - "./pihole/:/etc/pihole/"
    - "./dnsmasq.d/:/etc/dnsmasq.d/"
  environment:
    - ServerIP=${IP}
    - ServerIPv6=${IPv6}
    - DNS1=${DNS1}
    - DNS2=${DNS2}
    - TZ=Europe/Berlin
  ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "80:80"
```

I generate the `.env` file with a script:

```
IP_LOOKUP="$(ip route get 8.8.8.8 | awk '{ print $NF; exit }')" # May not work for VPN / tun0
IPv6_LOOKUP="$(ifconfig wlan0 | grep inet6 | cut -f 10 -d " " | grep '^fd00:')" # use ipv6 with the fd00 prefix, because it does not change

IP="${IP:-$IP_LOOKUP}" # use $IP, if set, otherwise IP_LOOKUP
IPv6="${IPv6:-$IPv6_LOOKUP}" # use $IPv6, if set, otherwise IP_LOOKUP
DNS1="${IP%.*}.1"
DNS2="$(dig +noall +additional -x ${DNS1} | cut -f 6 | grep '^fd00:')" # get ipv6 of dns1
cat > .env <<EOL
IP=${IP}
IPv6=${IPv6}
DNS1=${DNS1}
DNS2=${DNS2}
EOL
```
