### ISSUE TITLE
DHCP not working in bridged mode

### ISSUE THREAD

**Issue by DerFetzer** [pi-hole/docker-pi-hole#320]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
I was running the docker image all the time with `net=host`. I read in issue #292 that it should be possible with exposing port 67 in bridge mode.
I am trying for a while now to get it to work but it does not.
DNS and all other Pihole stuff (blocking page, blocking ads, admin page...) is functional but DHCP ist not working.

## Steps to Reproduce and debugging done
I run Pihole as well as two stubby containers with docker-compose:
```
version: "3"
services:
  pihole:
    image: pihole/pihole:v4.0_armhf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    restart: always
    cap_add:
        - NET_ADMIN
    environment:
      ServerIP: 192.168.x.x
      DNS1: 172.20.0.100#8053
      DNS2: 172.20.0.101#8053
      TZ: MEZ
    volumes:
      - '/home/xxx/docker/pihole/pihole/:/etc/pihole/'
      - '/home/xxx/docker/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
    depends_on:
      - stubby1
      - stubby2
    networks:
      - backend

  stubby1:
    build: ./stubby
    restart: always
    networks:
      backend:
        ipv4_address: '172.20.0.100'
    
  stubby2:
    build: ./stubby
    restart: always
    networks:
      backend:
        ipv4_address: '172.20.0.101'

networks:
  backend:
    ipam:
      config:
        - subnet: 172.20.0.0/16
```

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

I already tried all different combinations of `INTERFACE` and `DNSMASQ_LISTENING` environment variables (by the way: I see no location where `DNSMASQ_LISTENING` is used in this repository. How is it working?).

## Your Environment 

* Docker Host Operating System and OS Version: 4.4.50-hypriotos-v7+
* Docker Version: 18.02.0-ce
* Hardware architecture: RaspberryPi 3

Does anyone have an idea @diginc @alazare619?
Thanks in advance!
