### ISSUE TITLE
Provide a manifest to resolve image according to architecture - ARM, x86

### ISSUE THREAD

**Issue by bltavares** [pi-hole/docker-pi-hole#344]
It would be nice if people using the dockerized pi-hole image could simply run `docker run pihole/pihole` and have the correct architecture chosen for them instead of selecting manually which tag to pick.

This is a... 

- [x] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

I've recently learned that Docker now supports multi-architecture images for the same tag. There was [an announcement](https://blog.docker.com/2017/11/multi-arch-all-the-things/) latter last year about it (which I have missed).

Taking an example from Ubuntu or Debian, someone may just run `docker run ubuntu` from RPI or Linux and have the correct image downloaded.

For example, running the following we see that `ubuntu` provides multiple arch:

```
$ docker run --rm mplatform/mquery ubuntu
Image: ubuntu
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v7
   - linux/arm64
   - linux/386
   - linux/ppc64le
   - linux/s390x
```

Runing for pihole we see that the `manifest` is not configured.

```
$ docker run --rm mplatform/mquery pihole/pihole
Image: pihole/pihole
 * Manifest List: No
 * Supports: amd64/linux
```

## Expected Behavior

I would expect that running `docker run pihole/pihole` on any raspberry pi would work automatically.

## Actual Behavior

The execution fails as I didn't specify the correct architecture tag to download the image

## Possible Fix

Integrating with [manifest-tool](https://github.com/estesp/manifest-tool#createpush) it would be possible to create a `.yaml` and push the manifest to point to the correct tags. No need to recreate the pipeline or change how the tags are layared.

Creating a `latest-manifest.yml` similar to:

```yml
image: pihole/pihole:latest
manifests:
  -
    image: pihole/pihole:v4.0_armhf
    platform:
      architecture: arm
      variant: v7
      os: linux
  -
    image: pihole/pihole:v4.0_aarch64
    platform:
      architecture: arm64
      os: linux
  -
    image: pihole/pihole:v4.0_amd64
    platform:
      architecture: amd64
      os: linux
```

Then calling `./manifest-tool push from-spec latest-manifest.yml` should do the trick.
I've tested locally and, for obvious reasons, got unauthorized.

It would also be possible to create a `development` manifest to do the same for the development tag.
