### ISSUE TITLE
Web password is regenerated every time the container is recreated

### ISSUE THREAD

**Issue by ericparton** [pi-hole/docker-pi-hole#364]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
I'm using docker compose to manage an installation of pihole, but every time the container needs to be recreated as the result of an update to the container or a configuration change, the web password is set to a new random value. Per the documentation, I'm mounting a persistent volume at /etc/pihole, which does save the rest of my settings, but just not the web password.

## Expected Behavior
The web password is stored in somewhere in /etc/pihole and persisted with the rest of the configuration if a volume is mounted there.

## Actual Behavior
The web password is not persisted with the rest of the configuration and is always regenerated when a new container is created, even if the container is reusing the configuration from a mounted volume.

## Steps to Reproduce and debugging done

1. Create a container using the instructions in the readme
2. Stop that container, then create a new container with the same volumes
3. Observe that the web passwords are not the same

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Context and extra information
There is a workaround by setting the WEBPASSWORD variable, but you have to then hard code a password somewhere.

## Your Environment 

* Docker Host Operating System and OS Version: Ubuntu 18.0.4
* Docker Version: 18.09
* Hardware architecture: x86

**Comment by nxadm** [comment]
You can set the password in something like docker-compose?

```
# cat docker-compose.yml 
version: '2'
services:
  pihole:
    build:
      context: /opt/docker/_upstream/docker-pi-hole
      dockerfile: Dockerfile_amd64
    environment:
      - TZ='Europe/Brussels'
      - ServerIP=192.168.1.2
      - WEBPASSWORD=FooBar
      - DNS1=8.8.8.8
      - DNS2=8.8.4.4
      - IPv6=False
    ports:
      - "192.168.1.2:53:53"
      - "192.168.1.2:53:53/udp"
      - "192.168.1.2:80:80"
      - "192.168.1.2:443:443"
    volumes:
      - /opt/docker/pihole/rw/pihole:/etc/pihole
      - /opt/docker/pihole/rw/dnsmasq.d:/etc/dnsmasq.d
#    init: true    
    restart: always
#    network_mode: "host"
```
