### ISSUE TITLE
Pihole adds its' private docker network IP address to /etc/hosts overriding docker-compose extra_hosts variable

### ISSUE THREAD

**Issue by Eyeless77** [pi-hole/docker-pi-hole#367]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

I try to run PiHole in my docker environment using docker-compose and Traefik as a reverse proxy. I can manage static DNS entries on PiHole using `02-lan.conf` with `addn-hosts=/etc/pihole/lan.list` line. Lan.list files contains my static entries:

```
192.168.100.121	portainer.home.local	portainer
192.168.100.121	traefik.home.local	traefik
192.168.100.121	pihole.home.local	pihole
192.168.100.121	grafana.home.local	grafana
```

## Expected Behavior

All subdomains should be resolved to corresponding IP addresses.

## Actual Behavior

All subdomains are resolved correctly except PiHole itself. PiHole responds with an IP from docker private network, which is created on `docker-compose up`.

```
$ host portainer.home.local
portainer.home.local has address 192.168.100.121
$ host traefik.home.local
traefik.home.local has address 192.168.100.121
$ host pihole.home.local
pihole.home.local has address 172.19.0.2
```

## Possible Fix

I tried to add hosts entry manually using the following setting in docker-compose.
```
    extra_hosts:
      - 'pihole.home.local:192.168.100.121'
```

When I run `cat /etc/hosts` command inside the container, I get the following:
```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
192.168.100.121	pihole.home.local
172.19.0.2	pihole.home.local pihole
```

If I manually remove the line `172.19.0.2	pihole.home.local pihole` inside the container, everything works fine.

```
$ host pihole.home.local
pihole.home.local has address 192.168.100.121
```

## Steps to Reproduce and debugging done

My docker-compose file.

```
version: "3.6"
services:
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKERDIR}/traefik:/etc/traefik
      - ${DOCKERDIR}/shared:/shared
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERDIR}/portainer/data:/data
    environment:
      - TZ=${TZ}
  pihole:
    container_name: pihole
    domainname: ${DOMAINNAME}
    hostname: pihole
    image: pihole/pihole:latest
    networks:
      - traefik_proxy
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '8182:80'
      - '8183:443'
    restart: always
    volumes:
      - ${DOCKERDIR}/pihole/:/etc/pihole/
      - ${DOCKERDIR}/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    environment:
      - ServerIP=${SERVER_IP}
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=pihole.${DOMAINNAME}
      - VIRTUAL_PORT=80
      - TZ={TZ}
      - WEBPASSWORD=PASSWORD
      - DNS1=172.17.0.1#54
      - DNS2=172.17.0.1#54
    extra_hosts:
      - 'pihole.home.local:192.168.100.121'
    labels:
      - "traefik.enable=true"
      - "traefik.backend=pihole"
      - "traefik.port=80"
      - "traefik.frontend.rule=HostRegexp:pihole.${DOMAINNAME},{catchall:.*}"
      - "traefik.frontend.priority=1"
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
```

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Ubuntu 18.04.1 LTS 4.15.0-39-generic
* Docker Version: 18.06.1-ce, build e68fc7a
* Hardware architecture: x86/64
