### ISSUE TITLE
Support Cloudflare DNS-over-HTTPS 

### ISSUE THREAD

**Issue by carlos-sarmiento** [pi-hole/docker-pi-hole#378]
This is a... 

- [x] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
In order to provide more security to my DNS activities, I wanted to use cloudflare's DNS over HTTPS provider (cloudflared). I know I could run it from another docker container but I think it would be great if we could have a build of this image that includes it directly. 

## Expected Behavior
Cloudflared is included in a version of this image.

## Actual Behavior
Cloudflared is not included
## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1.
2. 
3. 
4. 

## Debug steps I have tried

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture:

**Comment by DL6ER** [comment]
My opinion: I wouldn't want to run Cloudflare's DoH and don't think it should be included in the Pi-hole container as it would unnecessarily increase its size.

I run my own recursive resolver (based on `unbound`) at home and - as such - don't have to trust Cloudflare. Although my DNS traffic is not encrypted, it is secured by DNSSEC, i.e., any alterations on the transmissions can be detected and rejected. As you're asking for security, not confidentiality, this seems to be what you're for, as well. See also the introduction of [this guide](https://docs.pi-hole.net/guides/unbound/).

**Comment by dschaper** [comment]
I concur. If there is a need for an included binary I would vote for a provider agnostic one like Stubby. https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Daemon+-+Stubby 

Though preferred would be to not have it in the same image as Pi-hole and instead in a Compose.

**Comment by carlos-sarmiento** [comment]
Good points all around. I guess my request makes no sense within the pihole docker image

**Comment by cjk** [comment]
@carlos-sarmiento You may take a look at [this](https://github.com/visibilityspots/dockerfile-cloudflared) where Clouflared's service has it's own docker-container and is combined with Pi-hole as it's (only) resolver.
This combines the benefit of both solutions - all traffic is encrypted and Pi-hole is used for blocking / DHCP / DNS.

**Comment by crazy-max** [comment]
I have created a [multi-platform Docker image](https://github.com/crazy-max/docker-cloudflared) for those who want to play with it and pihole.

```
$ docker run --rm mplatform/mquery crazymax/cloudflared:latest
Image: crazymax/cloudflared:latest
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v6
   - linux/arm/v7
   - linux/arm64
   - linux/386
   - linux/ppc64le
   - linux/s390x
```

```yml
version: "3.5"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - "TZ=America/Chicago"
    volumes:
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    dns:
      - "cloudflared#5053"
      - "1.1.1.1" # fallback
    restart: unless-stopped

  cloudflared:
    image: crazymax/cloudflared:latest
    container_name: cloudflared
    networks:
      - pihole
    environment:
      - "TZ=America/Chicago"
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"
    restart: unless-stopped

networks:
  pihole:
    name: pihole
```
