### ISSUE TITLE
New 4.1.1 update result in stopped DNS service

### ISSUE THREAD

**Issue by Martinvdm** [pi-hole/docker-pi-hole#391]
This is a... 

- [ ] Request for a new or modified feature
- [X] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
Docker image is updated to 4.1.1, after this it does not start the FTL service
````
  [✗] DNS service is NOT running,
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec],
[cont-init.d] 20-start.sh: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
Starting lighttpd,
Starting pihole-FTL (no-daemon),
Starting crond,
[services.d] done.,
Stopping pihole-FTL,
F4.11,
Starting pihole-FTL (no-daemon),
Stopping pihole-FTL,
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
````

## Expected Behavior
Should start

## Actual Behavior
Error starting

## Possible Fix
No idea

## Steps to Reproduce and debugging done
Did not done debugging, roll back to 4.1 solve the issue

## Debug steps I have tried

- [X] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 
roll back to 4.1 solve the issue

## Your Environment 

* Docker Host Operating System and OS Version: Ubuntu 18.04.1
* Docker Version: 17.12.1-ce
* Hardware architecture: Intel NUC
````
  pihole:
    container_name: pihole
    domainname: 123.local
    image: pihole/pihole:4.1
    restart: always
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - 'x.x.x.x:53:53/tcp'
      - 'x.x.x.x:53:53/udp'
      - '0.0.0.0:8053:80/tcp'
    volumes:
      - /home/docker/pihole/log/pihole.log:/var/log/pihole.log
      - /home/docker/pihole/etc-pihole/:/etc/pihole/
      - /home/docker/pihole/etc-dnsmasqd/:/etc/dnsmasq.d/
    environment:
      ServerIP: x.x.x.x
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: x.x.x.x:8053
      VIRTUAL_PORT: 8053
      TZ: 'Europe/Amsterdam'
      WEBPASSWORD: xxxxxx
````
