### ISSUE TITLE
Docker dnsmasq[4235] FAILED to start up

### ISSUE THREAD

**Issue by ghost** [pi-hole/docker-pi-hole#397]
Hey ALL

After removing my working container and image for update the pihole container i have an issue 
the pihole DNS won't start i looking in the

 DNS log

Jan 18 14:36:44 dnsmasq[9797]: setting capabilities failed: Operation not permitted
Jan 18 14:36:44 dnsmasq[9797]: FAILED to start up
Jan 18 14:36:45 dnsmasq[9811]: setting capabilities failed: Operation not permitted
Jan 18 14:36:45 dnsmasq[9811]: FAILED to start up
Jan 18 14:36:46 dnsmasq[9825]: setting capabilities failed: Operation not permitted
Jan 18 14:36:46 dnsmasq[9825]: FAILED to start up

pihole-FTL.log

FTL branch: master
[2019-01-18 14:39:16.684] FTL version: v4.1.2
[2019-01-18 14:39:16.684] FTL commit: b06eedf
[2019-01-18 14:39:16.684] FTL date: 2018-12-21 14:43:34 -0600
[2019-01-18 14:39:16.684] FTL user: root
[2019-01-18 14:39:16.684] WARNING: Starting pihole-FTL as user root is not recommended
[2019-01-18 14:39:16.684] Starting config file parsing (/etc/pihole/pihole-FTL.conf)
[2019-01-18 14:39:16.684]    SOCKET_LISTENING: only local
[2019-01-18 14:39:16.684]    AAAA_QUERY_ANALYSIS: Show AAAA queries
[2019-01-18 14:39:16.684]    MAXDBDAYS: max age for stored queries is 365 days
[2019-01-18 14:39:16.684]    RESOLVE_IPV6: Resolve IPv6 addresses
[2019-01-18 14:39:16.684]    RESOLVE_IPV4: Resolve IPv4 addresses
[2019-01-18 14:39:16.684]    DBINTERVAL: saving to DB file every minute
[2019-01-18 14:39:16.684]    DBFILE: Using /etc/pihole/pihole-FTL.db
[2019-01-18 14:39:16.684]    MAXLOGAGE: Importing up to 24.0 hours of log data
[2019-01-18 14:39:16.684]    PRIVACYLEVEL: Set to 0
[2019-01-18 14:39:16.684]    IGNORE_LOCALHOST: Show queries from localhost
[2019-01-18 14:39:16.684]    BLOCKINGMODE: Null IPs for blocked domains
[2019-01-18 14:39:16.684]    REGEX_DEBUGMODE: Inactive
[2019-01-18 14:39:16.684]    ANALYZE_ONLY_A_AND_AAAA: Disabled. Analyzing all queries
[2019-01-18 14:39:16.684]    DBIMPORT: Importing history from database
[2019-01-18 14:39:16.684]    PIDFILE: Using /var/run/pihole-FTL.pid
[2019-01-18 14:39:16.684]    PORTFILE: Using /var/run/pihole-FTL.port
[2019-01-18 14:39:16.684]    SOCKETFILE: Using /var/run/pihole/FTL.sock
[2019-01-18 14:39:16.684]    WHITELISTFILE: Using /etc/pihole/whitelist.txt
[2019-01-18 14:39:16.684]    BLACKLISTFILE: Using /etc/pihole/black.list
[2019-01-18 14:39:16.685]    GRAVITYFILE: Using /etc/pihole/gravity.list
[2019-01-18 14:39:16.685]    REGEXLISTFILE: Using /etc/pihole/regex.list
[2019-01-18 14:39:16.685]    SETUPVARSFILE: Using /etc/pihole/setupVars.conf
[2019-01-18 14:39:16.685]    AUDITLISTFILE: Using /etc/pihole/auditlog.list
[2019-01-18 14:39:16.685] Finished config file parsing
[2019-01-18 14:39:16.685] INFO: No whitelist file found
[2019-01-18 14:39:16.685] Compiled 0 Regex filters and 0 whitelisted domains in 0.1 msec (0 errors)
[2019-01-18 14:39:16.685] Database successfully initialized
[2019-01-18 14:39:16.686] Imported 0 queries from the long-term database
[2019-01-18 14:39:16.686]  -> Total DNS queries: 0
[2019-01-18 14:39:16.686]  -> Cached DNS queries: 0
[2019-01-18 14:39:16.686]  -> Forwarded DNS queries: 0
[2019-01-18 14:39:16.686]  -> Exactly blocked DNS queries: 0
[2019-01-18 14:39:16.686]  -> Unknown DNS queries: 0
[2019-01-18 14:39:16.686]  -> Unique domains: 0
[2019-01-18 14:39:16.686]  -> Unique clients: 0
[2019-01-18 14:39:16.686]  -> Known forward destinations: 0
[2019-01-18 14:39:16.686] Successfully accessed setupVars.conf
[2019-01-18 14:39:17.087] PID of FTL process: 12019
[2019-01-18 14:39:17.087] Listening on port 4711 for incoming IPv4 telnet connections
[2019-01-18 14:39:17.087] Listening on port 4711 for incoming IPv6 telnet connections
[2019-01-18 14:39:17.087] Listening on Unix socket
[2019-01-18 14:39:17.685] Using log file /var/log/pihole-FTL.log

my running command for starting my pihole container is

sudo docker run -d --name "pihole" -p 53:53/tcp -p 53:53/udp -p 67:67/udp -p 80:80 -p 443:443 -v "/home/docker/pihole/piholednsmasq.d/:/etc/piholednsmasq.d/" -v "/etc/localtime:/etc/localtime:ro" -v "/home/docker/pihole/pihole/:/etc/pihole/" -v "/home/docker/pihole/pihole-script/:/etc/pihole-script/" -v "/home/docker/pihole/dnsmasq.d/:/etc/dnsmasq.d/" -e ServerIP="10.0.30.23" --restart=always pihole/pihole:latest 

Pleas i don't see the issue to get my container working

**Comment by diginc** [comment]
Your run command seems to be missing the new required args https://github.com/pi-hole/docker-pi-hole#docker-pi-hole-v411-important-upgrade-notes

**Comment by OliElli** [comment]
Same issue here using docker-compose:
```
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    volumes:
      - /home/oli/docker/data/pihole/etc:/etc/pihole
      - /home/oli/docker/data/pihole/dnsmasq.d:/etc/dnsmasq.d
      - /var/log/pihole.log:/var/log/pihole.log
    environment:
      - ServerIP=192.168.0.20
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=pihole.lan
      - VIRTUAL_PORT=80
      - TZ=Europe/London
      - PUID=1002
      - PGID=1002
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
    extra_hosts:
      - plex.lan:192.168.0.20
      - radarr.lan:192.168.0.20
      - sonarr.lan:192.168.0.20
      - nzbget.lan:192.168.0.20
      - plexpy.lan:192.168.0.20
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
```

Even after adding the two noted requirements
```
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
```

I just get logs full of
```
Jan 19 21:33:29 dnsmasq[329]: setting capabilities failed: Operation not permitted
Jan 19 21:33:29 dnsmasq[329]: FAILED to start up
```

Reverting to v4.0.0.1 resolves the issue.

**Comment by gen2fish** [comment]
Same issue.

Here is my docker-compose
````
 pihole:
    container_name: pihole
    domainname: docker
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '30004:80'
        #- 'YYYY:443'
    restart: unless-stopped
    volumes:
      - /tank/pihole/pihole:/etc/pihole
      - /tank/pihole/pihole.log:/var/log/pihole.log
      - /tank/pihole/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      - ServerIP=10.28.5.10
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=pihole.fish.local
      - VIRTUAL_PORT=80
      - TZ=Americas/Denver
      - WEBPASSWORD=PIHOLEWEBPASSWORD

```

Reverting to 4.0.0-1 was my fix as well.
