### ISSUE TITLE
Imposible change 80 Web Port on docker with NETWORK HOST

### ISSUE THREAD

**Issue by Nitrosito** [pi-hole/docker-pi-hole#404]
Hello

If you run Pi-Hole on Docker, with network in mode host
It is impossible to change port 80 from lighttpd to another port.

this file allways be modified to port 80 when you instance the image...
The only way to change it is executing docker exec..., changing lighttpd.conf and restarting the service. But when you stop and start the container.. same problem.. at start, lighttpd.conf set to port 80.

Is there any other way?

(I like run container in network=host, to log the real ip from clients...) if you run the container in bridge mode, the IP of clients allways be the ip of docker gateway network 

a greeting

**Comment by diginc** [comment]
Does `-e WEB_PORT=999` work?

**Comment by Nitrosito** [comment]
Hi @diginc , i try it Monday in the office.. 
I suspect thats -e WEB_PORT only work in bridge network mode, but i try

Thanks

**Comment by Bierchermuesli** [comment]
WEB_PORT works for me. like:
```
pihole:
    image: pihole/pihole:latest
 ...
    network_mode: "host"
    # ports:   -> conflicts with host mode!
    #   - "xx:xx/tcp"
    cap_add:
      - NET_ADMIN
    environment:
      ServerIP: 192.168.88.99
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.${DOMAINNAME}
      WEB_PORT: 5089
     ...
```
a catchall:80 on traefik redirects to port 5089
