### ISSUE TITLE
[Feature Request]: Use Docker container names as upstream DNS-Sevrers instead of IP only

### ISSUE THREAD

**Issue by Ichnafi** [pi-hole/docker-pi-hole#425]
This is a... 

- [x] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
You can set manually two custom DNS server IPs in the GUI. This have to be valid IPv4/IPv6 adresses.
If you use a DNS proxy (i.e. Stubby) in another docker container as upstream DNS server for Pi-Hole, you can not enter the container name into those fields and use the docker internal DNS, so pi-hole can forward request to the DNS-proxy. Hence you have to give the DNS-proxy container a static IP-Address, which is not an optimal use of the docker infrastructure.

## Expected Behavior
One can use either a valid IPv4/IPv6 address as an upstream server, or a docker container name making use of docker's internal DNS to resolve the upstream dns's IP in the docker virtual network.

## Actual Behavior
One can only enter valid IPv4/IPv6  into the GUI as custom upstream servers. If you don't there is a error message

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1.
2. 
3. 
4. 

## Debug steps I have tried

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Raspbian Stretch
* Docker Version: 18.09.2
* Hardware architecture: ARMv7

**Comment by yegle** [comment]
This is especially useful for people running pihole in docker. Otherwise people have to manually configure network and allocate IP addresses.

As a workaround here's what I'm doing:

First create a network to put all your containers that requires access to pihole:
```
$ docker network create --subnet 172.29.0.0/16 infra
```
Then use the following docker compose file:
```
version: '2'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
    environment:
      - TZ=America/Los_Angeles
      - DNS1=172.29.1.2  # this is the stubby container IP address
      - DNS2=no
      - VIRTUAL_HOST=pihole.apkay.com
    volumes:
      - /opt/pihole/:/etc/pihole/
      - /opt/dnsmasq.d/:/etc/dnsmasq.d/
    dns: 127.0.0.1
    depends_on:
      - stubby
    networks:
        default:
            ipv4_address: 172.29.1.1  # Use IP address in 172.29.1.0/24 to avoid conflict with other containers
  stubby:
    image: yegle/stubby-dns:latest
    container_name: stubby
    dns: 127.0.0.1
    restart: unless-stopped
    volumes:
      - /opt/stubby/etc:/usr/local/etc/stubby
    networks:
        default:
            ipv4_address: 172.29.1.2  # Use IP address in 172.29.1.0/24 to avoid conflict with other containers
networks:
    default:  # references the infra network you created. The "default" network does not have IP management support, so you have to use a different network. By setting "infra" as your default network, you don't need to repeat network setting for all the containers in this file.
        external:
            name: infra
```

Then for each container that you want to specify Pihole as DNS server, you need to specify `dns: 172.29.1.1`.

**Comment by mrdoug47** [comment]
+1 for this feature request.

**Comment by derekhendrickx** [comment]
I would love to see this implemented. I tried to use a container name with my pihole container and it didn't work.

**Comment by CourtneySherman** [comment]
+1 for this request.  Thanks.

**Comment by jol64** [comment]
I commented in another issue, but see this is related.
https://github.com/pi-hole/docker-pi-hole/issues/486#issuecomment-744231989
Actually I would not care about whether I can enter this in the UI as I was expecting to put this into my environment settings. Then a script resolving it to an IP would be sufficient.

**Comment by oywino** [comment]
> Then use the following docker compose file:
> 
> ```
> version: '2'
> services:
>   pihole:
>     container_name: pihole
>     image: pihole/pihole:latest
>     restart: unless-stopped
>     ports:
>       - 53:53/tcp
>       - 53:53/udp
>       - 67:67/udp
>     environment:
>       - TZ=America/Los_Angeles
>       - DNS1=172.29.1.2  # this is the stubby container IP address
>       - DNS2=no
>       - VIRTUAL_HOST=pihole.apkay.com
>     volumes:
>       - /opt/pihole/:/etc/pihole/
>       - /opt/dnsmasq.d/:/etc/dnsmasq.d/
>     dns: 127.0.0.1
>     depends_on:
>       - stubby
>     networks:
>         default:
>             ipv4_address: 172.29.1.1  # Use IP address in 172.29.1.0/24 to avoid conflict with other containers
>   stubby:
>     image: yegle/stubby-dns:latest
>     container_name: stubby
>     dns: 127.0.0.1
>     restart: unless-stopped
>     volumes:
>       - /opt/stubby/etc:/usr/local/etc/stubby
>     networks:
>         default:
>             ipv4_address: 172.29.1.2  # Use IP address in 172.29.1.0/24 to avoid conflict with other containers
> networks:
>     default:  # references the infra network you created. The "default" network does not have IP management support, so you have to use a different network. By setting "infra" as your default network, you don't need to repeat network setting for all the containers in this file.
>         external:
>             name: infra
> ```

I tried this and it works - except for one thing: Ports settings are ignored !
Here's what I'm doing:

```
version: '3'

services:
  npm:
    image: jc21/nginx-proxy-manager:2.9.19
    restart: "no"

    ports:
      - 8380:80
      - 8443:443
      - 8481:81

    environment:
      LANG: nb_NO.UTF-8
      TZ: Europe/Oslo

    volumes:
      - /share/Web/nginx:/data
      - /share/Web/nginx/LE:/etc/letsencrypt

    networks:
      default:
          ipv4_address: 192.168.1.126

networks:
  default:
    external:
      name:  qnet-static-eth0-79e6cc

```

The ports mapping section is completely ignored.
What am I doing wrong?
