### ISSUE TITLE
Unable to run pi-hole with network mode "host" on a Raspberry 

### ISSUE THREAD

**Issue by nikoskip** [pi-hole/docker-pi-hole#443]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
Pi-hole is unable to start due a httpd port bind issue.

## Expected Behavior
Start Pi-hole normally

## Actual Behavior
After running `docker-compose up` I'm getting this message on screen:

```
pihole    | 2019-04-18 20:28:26: (network.c.464) can't bind to port: 127.0.0.1 80 Address already in use
pihole    | Stopping lighttpd
pihole    | lighttpd: no process found
pihole    | Starting lighttpd
pihole    | 2019-04-18 20:28:27: (network.c.464) can't bind to port: 127.0.0.1 80 Address already in use
pihole    | Stopping lighttpd
pihole    | lighttpd: no process found
pihole    | Starting lighttpd
pihole    | 2019-04-18 20:28:28: (network.c.464) can't bind to port: 127.0.0.1 80 Address already in use
pihole    | Stopping lighttpd
pihole    | lighttpd: no process found
pihole    | Starting lighttpd
pihole    | 2019-04-18 20:28:29: (network.c.464) can't bind to port: 127.0.0.1 80 Address already in use
pihole    | Stopping lighttpd
```

This only happens using **host** as network mode on Docker, and I would like to use the host mode because I need the DHCP functionality.

## Possible Fix
I don't know 😢 

## Steps to Reproduce and debugging done
Use this `docker-compose.yml` and try to run it on a Raspberry Pi:

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'America/Santiago'
      WEBPASSWORD: 'xxxx'
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    network_mode: host
```

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 
- [x] **I have checked if any program is really using port 80 on my host**

## Your Environment 

* Docker Host Operating System and OS Version: Raspbian 9
* Docker Version: 18.09.0 build 4d60db4
* Hardware architecture: ARMv7
