### ISSUE TITLE
Host filesystem boot device becomes read-only after pi-hole container runs for a few days.

### ISSUE THREAD

**Issue by asimpson** [pi-hole/docker-pi-hole#448]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

I run several docker services on my NAS, e.g. plex, unifi etc. When I add pi-hole to my docker-compose it will run just fine for 24 hours to a week before the host system filesystem gets locked as read-only. My only alternative at that point is to run `e2fsck -f /dev/xxxx` and fix various inode errors. When I don't run pi-hole the system runs smoothly without intervention.

## Expected Behavior

Pi-hole should run without the host system becoming read-only.
## Actual Behavior

Pi-hole runs but eventually the host system becomes read-only.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
### docker-compose config
```
 pihole:
    image: "pihole/pihole:latest"
    volumes:
      - /mnt/crate/pihole-storage/pihole:/etc/pihole
      - /mnt/crate/pihole-storage/pihole-dnsmasq:/etc/dnsmasq.d
    ports:
      - "192.168.1.96:53:53/tcp"
      - "192.168.1.96:53:53/udp"
      - "192.168.1.96:80:80/tcp"
      - "192.168.1.96:443:443/tcp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: 'unless-stopped'
    environment:
      ServerIP: 192.168.1.96
      WEBPASSWORD: 'xxxx'
      PUID: 1000
      PGID: 999
```

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 
- [x] I have mounted my shared volumes on a different filesystem (`zfs` instead of `ext4`).

## Context and extra information

I created a virtual network interface (192.168.1.96) just for pi-hole to segment it away from the rest of the services on the NAS. Here is the netplan config (Ubuntu 18.04):

```
network:
    ethernets:
        enp2s0:
            addresses: [192.168.1.96/24]
            dhcp4: true
            gateway4: 192.168.1.1
```

## Your Environment 

* Docker Host Operating System and OS Version: `Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-47-generic x86_64)`
* Docker Version: `Docker version 18.09.4, build d14af54266`
* Hardware architecture: `x86`
`uname -a` output: `Linux nas 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
