### ISSUE TITLE
4.3.1-1 ignores WEB_PORT when there are files under /etc/pihole

### ISSUE THREAD

**Issue by globus243** [pi-hole/docker-pi-hole#471]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

When deploying the newest tag 4.3.1-1 with data on a volume mounted at /etc/pihole/ the WEB_PORT gets ignored and Lighttp tries to bind on port 80.
Only if I scrap the volume an make a fresh install, pihole uses the WEB_PORT.
using persistend data is not possible this way.

## Expected Behavior

When WEB_PORT ist set in docker-compose.yml, Lighttpd should use this port

## Actual Behavior

Lighttpd uses Port 80

## Possible Fix

- (not really a fix) delete everything in /etc/pihole/

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1.  docker-compose.yml

```
version: "3"

services:
  pihole:
    image: pihole/pihole:4.3.1-1 # or :latest
    network_mode: host
    environment:
      TZ: 'Europe/Berlin'
      ServerIP: 'x.x.x.x'
      WEB_PORT: 8081
      DNS1: '1.1.1.1'
      DNS2: '8.8.8.8'
      WEBPASSWORD: 'xxxxxxxxx'
      DNSMASQ_LISTENING: 'local'
      DNSMASQ_USER: 'root'
      IPv6: 'false'
    # Volumes store your data between container upgrades
    volumes:
       - 'xxxx:/etc/pihole/'
       - 'xxxx:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```
2. docker-compose up -d
3. Log says `(network.c.464) can't bind to port:  80 Address already in use `

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Synology DSM 6.2.2
* Docker version 17.05.0-ce, build 371caef-synology
* docker-compose version 1.14.0
* Hardware architecture: x64
