### ISSUE TITLE
After Pihole Container Restart, Web Server dies

### ISSUE THREAD

**Issue by XxAcielxX** [pi-hole/docker-pi-hole#477]
After adding blocklist from https://v.firebog.net/hosts/lists.php?type=all I restart the Pihole Container by doing either OS reboot/shutdown, `docker restart pihole` or combination of `docker stop pihole` then `docker start pihole`, everything restarts except lighttpd server which provides the web access. 

This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Expected Behavior

Everything should restart including Web server
## Actual Behavior

Everything restarts, but Web server never does
## Possible Fix

Domains more than approx 850k in Blacklist, is causing this issue for me.

Only this https://v.firebog.net/hosts/lists.php?type=tick worked.

## Steps to Reproduce and debugging done

My `docker-compose.yml`
```
version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    network_mode: host
#    ports:
#      - "53:53/tcp"
#      - "53:53/udp"
#      - "67:67/udp"
#      - "80:80/tcp"
#      - "443:443/tcp"
    environment:
#      INTERFACE: 'eth0'
      ServerIP: '192.168.1.31'
      TZ: 'Asia/Karachi'
      WEBPASSWORD: 'xxxx'
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # run `touch ./var-log/pihole.log` first unless you like errors
       - './var-log/pihole.log:/var/log/pihole.log'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```
1. After the initial install, added https://v.firebog.net/hosts/lists.php?type=all blocklist 
2. Restart Pihole Container to to see if everything works
3.  Web server dies

## Debug steps I have tried

- Restarted Docker Service
- Restarted the whole OS
- Checked `ss -tlnu` to see if anything else is running on port 80
- Removed all custom blocklists I added

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Arch Linux ARM
* Docker Version: 18.09.6-ce
* Hardware architecture: ARMv7
