### ISSUE TITLE
Using only one DNS in docker compose - second appears always

### ISSUE THREAD

**Issue by eflemingtra** [pi-hole/docker-pi-hole#485]
This is a... 

- [X] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Using docker compose, the examples indicate putting in two DNS servers, the first being 127.0.0.1. That's fine as I use Unbound for DNS and it's what I want to use. However, I don't want a second DNS server as I have a second pi-Hole running on a separate machine. My router is set up to use both pi-holes.

However, whenever i leave the second DNS server entry out, it seems to default to using 8.8.4.4 as per the DNS settings page on the admin portal. While I can deselect this and save to just use 127.0.0.1, it will come back each time I have to recreate the container.

## Expected Behavior

Allow the input of only one DNS server in the container, and not have a second one chosen by default.

## Steps to Reproduce and debugging done

My docker compose:

```
pihole:
    container_name: pihole
    domainname: docker
    hostname: pihole
    image: pihole/pihole:latest
    links:
      - unbound
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      # - '67:67/udp'
      - '80:80'
      - '443:443'
      - 85:80/tcp
    restart: always
    volumes:
      - /home/user/docker/pihole/pihole:/etc/pihole
      - /home/user/docker/pihole/pihole.log:/var/log/pihole.log
      - /home/user/docker/pihole/dnsmasq.d:/etc/dnsmasq.d
    environment:
      - TZ=Australia/Sydney
      - WEBPASSWORD=${WEBPASSWORD}
      - DNS1=127.0.0.1#5354 
```

## Debug steps I have tried

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture:
