### ISSUE TITLE
Pi-Hole 4.3.2 doesn't respect the ServerIP parameter

### ISSUE THREAD

**Issue by canoben** [pi-hole/docker-pi-hole#514]
After updating my Pi-Hole docker image I could not login to the admin interface using the usual address I've been using for months. I quickly found put that the address had been changed from 192.168.0.199 to 192.168.0.192.

I attributed this to a random glitch, but when I updated Pi-Hole on a second site that I manage, the exact same thing happened (and the address had not been changef to any other random address but again to .192).

The line "ServerIP" => "192.168.0.199" does appear on the log, so I am specifying the desired address (I'm updating a docker container, so the old paramters should be used anyway).

I could now change the address in my gateway, but I'd like not having to do that every time I update Pi-Hole.

Does anybody have any idea what's going on here? Also, I just noticed there is a pi-hole-docker image. Should I use that one instead of the defautl one when using with Docker (the default one has been working just fine for me)?

**Comment by diginc** [comment]
In order to fix reported problems we need to be able to replicate the problem.

Please provide more info, such as:
- How you ran your docker exactly (the entire docker-compose or docker run)
- Customization you may have made (web UI tweaks, or config file changes)

Does your docker host computer have a static IP of 192.168.0.199?

**Comment by simao** [comment]
I am getting the same problem when running pihole using docker+docker-compose

I see on the logs:

```
pihole    | Added ENV to php:
pihole    | 			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
pihole    | 			"ServerIP" => "0.0.0.0",
pihole    | 			"VIRTUAL_HOST" => "0.0.0.0",
```

When running using docker-run it works:

```
Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "192.168.1.104",
			"VIRTUAL_HOST" => "192.168.1.104",
```

My docker-compose file:

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      ServerIp: "192.168.1.104"
      TZ: 'Europe/Berlin'
    volumes:
      - '/home/pi/etc-pihole/:/etc/pihole/'
      - '/home/pi/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
```

Any ideas?
