### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by parwana786** [pi-hole/docker-pi-hole#519]
This is a... 

- [ ] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ x] Issue trying to build / test / develop the docker image

## Description
Can't build the container with the docker-compose.yml

## Expected Behavior
Build and run container

## Actual Behavior
standard_init_linux.go:211: exec user process caused "exec format error"

## Possible Fix
reason: Maybe it cant map the architecture.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
 ```
$ docker-compose
standard_init_linux.go:211: exec user process caused "exec format error"
```

## Debug steps I have tried

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ x] I have searched this repository for existing issues and pull requests that look similar 
https://github.com/pi-hole/docker-pi-hole/issues/361
https://github.com/pi-hole/docker-pi-hole/issues/178
https://github.com/pi-hole/docker-pi-hole/issues/131

## Your Environment 

* Docker Host Operating System and OS Version:
 `Linux raspberrypi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux`
* Docker Version:
```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.75-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 3.814GiB
 Name: raspberrypi
 ID: 7V7O:QW22:BLVB:UO6U:2OLQ:JECI:YXUI:DEY2:OJQV:WCMU:PI23:FWL4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

```
* Hardware architecture: ARMv7, Raspberry pi 4 - 4GB

docker-compose.yml

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: xxxxx
      DNS1: 8.8.8.8
      VIRTUAL_HOST: pihole
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN
    restart: unless-stopped
```
