### ISSUE TITLE
effective uid is not zero errors and pihole fails to save any settings when running with userns enabled, bypassing userns_mode=host fails with permission errors on sudo libs

### ISSUE THREAD

**Issue by tprasadtp** [pi-hole/docker-pi-hole#536]
When Running with docker settings fail to save because of the error mentioned(See logs from compose below)
- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Fails to save any settings from WEB UI with errors
`pihole    | sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
`

```
 docker-compose up
Creating volume "temp_pihole_vol" with default driver
Creating volume "temp_pihole_vol_dnsmasq" with default driver
Recreating pihole ... done
Attaching to pihole
pihole    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
pihole    | [s6-init] ensuring user provided files have correct perms...exited 0.
pihole    | [fix-attrs.d] applying ownership & permissions fixes...
pihole    | [fix-attrs.d] 01-resolver-resolv: applying... 
pihole    | [fix-attrs.d] 01-resolver-resolv: exited 0.
pihole    | [fix-attrs.d] done.
pihole    | [cont-init.d] executing container initialization scripts...
pihole    | [cont-init.d] 20-start.sh: executing... 
pihole    |  ::: Starting docker specific checks & setup for docker pihole/pihole
pihole    | WARNING Misconfigured DNS in /etc/resolv.conf: Two DNS servers are recommended, 127.0.0.1 and any backup server
pihole    | WARNING Misconfigured DNS in /etc/resolv.conf: Primary DNS should be 127.0.0.1 (found 127.0.0.11)
pihole    | 
pihole    | nameserver 127.0.0.11
pihole    | options ndots:0
pihole    |   [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u5
pihole    | 
pihole    |   [i] Installing configs from /etc/.pihole...
pihole    |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
pihole    | chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
pihole    | + pihole -a -p '"password"' '"password"'
pihole    | Setting password: "password"
pihole    |   [✓] New password set
pihole    | Using custom DNS servers: "1.1.1.1" & "1.0.0.1"
pihole    | DNSMasq binding to default interface: eth0
pihole    | Added ENV to php:
pihole    | 			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
pihole    | 			"ServerIP" => "0.0.0.0",
pihole    | 			"VIRTUAL_HOST" => "0.0.0.0",
pihole    | Using IPv4
pihole    | ::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
pihole    | https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
pihole    | https://mirror1.malwaredomains.com/files/justdomains
pihole    | http://sysctl.org/cameleon/hosts
pihole    | https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
pihole    | https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
pihole    | https://hosts-file.net/ad_servers.txt
pihole    | ::: Testing pihole-FTL DNS: FTL started!
pihole    | ::: Testing lighttpd config: Syntax OK
pihole    | ::: All config checks passed, cleared for startup ...
pihole    |  ::: Docker start setup complete
pihole    |   [i] Pi-hole blocking is enabled
pihole    |   [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range
pihole    | 
pihole    |   [i] Target: raw.githubusercontent.com (hosts)
  [✓] Status: Retrieval successful
pihole    | 
pihole    |   [i] Target: mirror1.malwaredomains.com (justdomains)
  [✓] Status: Retrieval successful
pihole    | 
pihole    |   [i] Target: sysctl.org (hosts)
  [✓] Status: No changes detected
pihole    | 
pihole    |   [i] Target: s3.amazonaws.com (simple_tracking.txt)
  [✓] Status: No changes detected
pihole    | 
pihole    |   [i] Target: s3.amazonaws.com (simple_ad.txt)
  [✓] Status: No changes detected
pihole    | 
pihole    |   [i] Target: hosts-file.net (ad_servers.txt)
  [✓] Status: Retrieval successful
pihole    | 
  [✓] Consolidating blocklists
  [✓] Extracting domains from blocklists
pihole    |   [i] Number of domains being pulled in by gravity: 138742
  [✓] Removing duplicate domains
pihole    |   [i] Number of unique domains trapped in the Event Horizon: 116533
pihole    |   [i] Nothing to whitelist!
pihole    |   [i] Number of regex filters: 0
  [✓] Parsing domains into hosts format
  [✓] Cleaning up stray matter
pihole    | 
pihole    |   [✓] DNS service is running
pihole    |   [i] Pi-hole blocking will be enabled
pihole    |   [i] Enabling blocking
  [✓] Pi-hole Enabled
pihole    | [cont-init.d] 20-start.sh: exited 0.
pihole    | [cont-init.d] done.
pihole    | [services.d] starting services
pihole    | Starting lighttpd
pihole    | Starting crond
pihole    | Starting pihole-FTL (no-daemon) as root
pihole    | [services.d] done.
pihole    | sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
pihole    | sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
pihole    | sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
pihole    | sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
pihole    | sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
^CGracefully stopping... (press Ctrl+C again to force)
Stopping pihole   ... done

```

### docker-compose file

```yaml
$ cat docker-compose.yml 
version: "3.3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole.lan.domain.tld
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.lan.domain.tld`)"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=le"
      - "traefik.http.routers.pihole.entrypoints=websecure"
    networks:
      - web
      - pihole
    # DNS Ports
    ports:
      - target: 53
        published: 53
        protocol: tcp
      - target: 53
        published: 53
        protocol: udp
    environment:
      - TZ="Europe/Berlin"
      - CONDITIONAL_FORWARDING_DOMAIN="lan.domain.tld"
      - CONDITIONAL_FORWARDING_IP="192.168.1.1"
      - CONDITIONAL_FORWARDING_REVERSE="1.168.192.in-addr.arpa"
      - WEBPASSWORD=password
      - DNS1="1.1.1.1"
      - DNS2="1.0.0.1"
      - IPv6="False"
    # Volumes store your data between container upgrades
    volumes:
      - pihole:/etc/pihole/:rw
      - pihole_vol_dnsmasq:/etc/dnsmasq.d/:rw
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
volumes:
  pihole:
  pihole_vol_dnsmasq:

networks:
  pihole:
  web:
    external: true

```

#### with userns=host

```
docker-compose up
Recreating pihole ... done
Attaching to pihole
pihole    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
pihole    | [s6-init] ensuring user provided files have correct perms...exited 0.
pihole    | [fix-attrs.d] applying ownership & permissions fixes...
pihole    | [fix-attrs.d] 01-resolver-resolv: applying... 
pihole    | [fix-attrs.d] 01-resolver-resolv: exited 0.
pihole    | [fix-attrs.d] done.
pihole    | [cont-init.d] executing container initialization scripts...
pihole    | [cont-init.d] 20-start.sh: executing... 
pihole    |  ::: Starting docker specific checks & setup for docker pihole/pihole
pihole    | WARNING Misconfigured DNS in /etc/resolv.conf: Two DNS servers are recommended, 127.0.0.1 and any backup server
pihole    | WARNING Misconfigured DNS in /etc/resolv.conf: Primary DNS should be 127.0.0.1 (found 127.0.0.11)
pihole    | 
pihole    | nameserver 127.0.0.11
pihole    | options ndots:0
pihole    |   [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u5
pihole    | 
pihole    |   [i] Installing configs from /etc/.pihole...
pihole    |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
pihole    | chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
pihole    | ::: Pre existing WEBPASSWORD found
pihole    | Using custom DNS servers: "1.1.1.1" & "1.0.0.1"
pihole    | DNSMasq binding to default interface: eth0
pihole    | Added ENV to php:
pihole    | 			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
pihole    | 			"ServerIP" => "0.0.0.0",
pihole    | 			"VIRTUAL_HOST" => "0.0.0.0",
pihole    | Using IPv4
pihole    | ::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
pihole    | https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
pihole    | https://mirror1.malwaredomains.com/files/justdomains
pihole    | http://sysctl.org/cameleon/hosts
pihole    | https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
pihole    | https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
pihole    | https://hosts-file.net/ad_servers.txt
pihole    | ::: Testing pihole-FTL DNS: sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
pihole    | sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
pihole    | sudo: fatal error, unable to load plugins
pihole    | [cont-init.d] 20-start.sh: exited 1.
pihole    | [cont-finish.d] executing container finish scripts...
pihole    | [cont-finish.d] done.
pihole    | [s6-finish] syncing disks.
pihole    | [s6-finish] sending all processes the TERM signal.
pihole    | [s6-finish] sending all processes the KILL signal and exiting.


```

## Actual Behavior
Settings are not saved!! and if userns_mode is set to host the dowcker compose fails with error above.

## Debug steps I have tried

I have tried recreating the volumes mounted at  `/etc/pihole` and dhcp configs.

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar

## Your Environment 
* Docker Host Operating System and OS Version:

## `etc/os-release`
```
$ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
  
## `docker info`
```
docker info
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
  userns
 Kernel Version: 4.19.75-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 3.863GiB
 Name: pi-alpha
 ID: ####UUID####
 Docker Root Dir: /var/lib/docker/100000.100000
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

  ```
* Docker Version: 19.03.5
* Hardware : Raspberry Pi 4

**Comment by tprasadtp** [comment]
spoke too soon. I guess it is caused by 
```json
{
  "userns-remap": "default",
  "no-new-privileges": true
}
```
`--security-opt=no-new-privileges:false` should fix this.I am guessing this will be eliminated completely once the new API server/FTL and web interface is in place. In the meantime, shouldn't this be added in FAQ or in notes or even as comment in docker-compose file?

**Comment by erictt** [comment]
I have a very similar configuration and have the same error. not sure how to fix it.

FYI, the `security-opt=no-new-privileges:false` doesn't help.

**Comment by systemofapwne** [comment]
I'm suffering from the same issue. I use userns-remap and added no-new-privileges to my container. This is by design and I do not want to change this. I really would anticipate a fix.
Right now, I simply change the config by hand.

**Comment by Rotzbua** [comment]
I had the same issue. My config uses `"no-new-privileges": true` so the uid and guid used by container must be available on host. Workaround is to create all missing users and groups.

The used uid and guid are:
https://github.com/pi-hole/docker-pi-hole/issues/328#issuecomment-424062892

A fix with changeable ids is still in progress:
https://github.com/pi-hole/docker-pi-hole/issues/328

**Comment by c0m3d1an** [comment]
I solved this problem (finally) after running the container with --cap-add=setuid --cap-add=setgid

**Comment by talhajunaidd** [comment]
I had the same problem because I was using a separate partition for docker-data and in the mount options of the data partition `nosuid` was set.
I removed that and it solved the issue.

**Comment by Klarstein** [comment]
Is this issue getting any love on the pihole side? All proposed workarounds in this issue will degrade security in some way.

**Comment by KillrOfLife** [comment]
Issue still persists on the current latest build. removed all folders from pihole on the host so standard permissions would be used.

```yml
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 82:80/tcp
    environment:
      TZ: ${TZ}
      DNSSEC: "true"
      WEBPASSWORD: ${pass}
    volumes:
      - ${ConfigPath}/pihole/pihole:/etc/pihole
      - ${ConfigPath}/pihole/dnsmasq:/etc/dnsmasq.d
```
