### ISSUE TITLE
unable to change mode / permission denied 

### ISSUE THREAD

**Issue by uselpa** [pi-hole/docker-pi-hole#549]
Container does not start up because of chown errors (permission denied).

This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "192.168.178.34:53:53/tcp"
      - "192.168.178.34:53:53/udp"
      - "192.168.178.34:67:67/udp"
      - "192.168.178.34:81:80/tcp"
    environment:
      TZ: 'Europe/Luxembourg'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - '/root/pihole/etc-pihole/:/etc/pihole/'
      - '/root/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 192.168.178.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

## Actual Behavior

```
root@snap1:~/d_pihole# docker-compose up
Creating pihole ... done
Attaching to pihole
pihole    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
pihole    | [s6-init] ensuring user provided files have correct perms...s6-chown: fatal: unable to chown /var/run/s6/etc/fix-attrs.d/01-resolver-resolv: Permission denied
pihole    | s6-chmod: fatal: unable to change mode of /var/run/s6/etc/fix-attrs.d/01-resolver-resolv: Permission denied
pihole    | s6-chown: fatal: unable to chown /var/run/s6/etc/cont-init.d/20-start.sh: Permission denied
pihole    | s6-chmod: fatal: unable to change mode of /var/run/s6/etc/cont-init.d/20-start.sh: Permission denied
pihole    | s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/lighttpd/run: Permission denied
pihole    | s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/pihole-FTL/run: Permission denied
pihole    | s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/cron/run: Permission denied
pihole    | s6-chmod: fatal: unable to change mode of /var/run/s6/etc/services.d/lighttpd/run: Permission denied
pihole    | s6-chmod: fatal: unable to change mode of /var/run/s6/etc/services.d/cron/run: Permission denied
pihole    | s6-chmod: fatal: unable to change mode of /var/run/s6/etc/services.d/pihole-FTL/run: Permission denied
pihole    | s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/lighttpd/finish: Permission denied
pihole    | s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/pihole-FTL/finish: Permission denied
pihole    | s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/cron/finish: Permission denied
pihole    | s6-chmod: fatal: unable to change mode of /var/run/s6/etc/services.d/cron/finish: Permission denied
pihole    | s6-chmod: fatal: unable to change mode of /var/run/s6/etc/services.d/lighttpd/finish: Permission denied
pihole    | s6-chmod: fatal: unable to change mode of /var/run/s6/etc/services.d/pihole-FTL/finish: Permission denied
pihole    | exited 0.
pihole    | [fix-attrs.d] applying ownership & permissions fixes...
pihole    | [fix-attrs.d] 01-resolver-resolv: applying...
pihole    | [fix-attrs.d] 01-resolver-resolv: exited 0.
pihole    | [fix-attrs.d] done.
pihole    | [cont-init.d] executing container initialization scripts...
pihole    | [cont-init.d] 20-start.sh: executing...
pihole    | foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/20-start.sh: Permission denied
pihole    | foreground: fatal: unable to wait for /var/run/s6/etc/cont-init.d/20-start.sh: No child process
pihole    | [cont-finish.d] executing container finish scripts...
pihole    | [cont-finish.d] done.
pihole    | [s6-finish] syncing disks.
pihole    | [s6-finish] sending all processes the TERM signal.
pihole    | [s6-finish] sending all processes the KILL signal and exiting.
```

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1.
2. 
3. 
4. 

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Ubuntu Core 18
* Docker Version: 18.09.9
* Hardware architecture:  x86-64

``
