### ISSUE TITLE
Support for Docker Secrets

### ISSUE THREAD

**Issue by nicedevil007** [pi-hole/docker-pi-hole#556]
Hey guys,

I'm using your docker pihole deployment with a docker swarm environment.
I setup a docker secret with a webpassword "test1234".

Then I added everything as described in docker guides to use this docker secret and the service starts without any error. Unfortunately the webpassword isn't the same as I entered in this secret.
The WebGUI always tells me that the password is wrong. I guess there is no support for it right now.

So this should be understood as an improvement/enhancement <3

Thank you all in advance.

EDIT: forgot to post my docker-compose.yml

```
version: '3.1'

services:

  pihole:
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 443:443/tcp
      - 80:80/tcp
    network_mode: 'host'
    environment:
      TZ: 'Europe/Berlin'
      IPv6: 'False'
      DNSMASQ_USER: 'pihole'
      WEBPASSWORD: /run/secrets/pihole_webpw
    secrets:
       - pihole_webpw
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
      - theme:/var/www/html/admin/style/vendor
    dns:
      - 127.0.0.1
      - 192.168.1.1
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

volumes:
  pihole:
  dnsmasq:
  theme:
  
secrets:
  pihole_webpw:
    external: true
```

![grafik](https://user-images.githubusercontent.com/17103076/72412296-4530a400-376d-11ea-959a-0d0852727a02.png)
