### ISSUE TITLE
404 on ServerIP

### ISSUE THREAD

**Issue by kaihendry** [pi-hole/docker-pi-hole#559]
- [x] Issue trying to run the docker image

## Description

```
[hendry@t480s ~]$ curl http://192.168.1.4/admin/
404 page not found
[hendry@t480s ~]$ ssh pi@192.168.1.4
Last login: Wed Jan 29 13:37:13 2020 from 192.168.1.25
pi@four:~$  curl http://192.168.1.4/admin/
404 page not found
pi@four:~$  curl -I http://localhost/admin/
HTTP/1.1 200 OK
X-Pi-hole: The Pi-hole Web interface is working!
X-Frame-Options: DENY
Set-Cookie: PHPSESSID=et4rkegfsq14m6h24gq0imu8h6; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-type: text/html; charset=UTF-8
Date: Wed, 29 Jan 2020 13:38:03 GMT
Server: lighttpd/1.4.45
```

One day http://192.168.1.4/admin/ stopped working. How can I get it working again? I'm running the latest image.

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - TZ=Asia/Singapore
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
```

**Comment by NazarKosteckij** [comment]
This should help you

```
environment:
      - TZ=Asia/Singapore
      - ServerIP=192.168.1.4
```

**Comment by kaihendry** [comment]
Thanks, but it doesn't appear to work: https://s.natalian.org/2020-02-05/pihole.txt

**Comment by NazarKosteckij** [comment]
This `docker-compose.yml` config **definetly works** 
```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - TZ=Asia/Singapore
      - ServerIP=172.27.131.141
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
```

![image](https://user-images.githubusercontent.com/7646850/73839548-eebffe00-481e-11ea-98a9-14632d9a9391.png)

**Comment by hstr0100** [comment]
I have the same issue here, running on a raspberry pi 4 on docker.
I spent hours trying to debug this thinking it was an issue with my network configuration but no dice.
It stopped working out of nowhere after restarting the container a few days ago. it used to work.

lsof -n -i shows that lighttpd is not listening to any ports whatsoever
`root@PiHoleNetwork:/# lsof -n -i
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
pihole-FT 503 root    4u  IPv4  91164      0t0  UDP *:53
pihole-FT 503 root    5u  IPv4  91165      0t0  TCP *:53 (LISTEN)
pihole-FT 503 root    6u  IPv6  91166      0t0  UDP *:53
pihole-FT 503 root    7u  IPv6  91167      0t0  TCP *:53 (LISTEN)
pihole-FT 503 root   10u  IPv4  91171      0t0  TCP 127.0.0.1:4711 (LISTEN)`

Yet no errors are shown in any log files
`root@PiHoleNetwork:/var/log/lighttpd# cat *
2020-02-09 17:08:45: (log.c.217) server started
2020-02-09 17:14:51: (log.c.217) server started`
`root@PiHoleNetwork:/var/log# /etc/init.d/lighttpd status
[ ok ] lighttpd is running.`

This is really driving me nuts, at this point I tried everything I could to bring the web interface back up, and tried many different network setups in docker.

**Comment by PromoFaux** [comment]
@kaihendry Saw your comment on HN.. is this still an issue with the v5.0 container?

I've been running my main Pi-hole install under docker for some time now and have not seen this issue myself. FWIW, my compose file:

```
version: '3.5'
services:

  pihole:
    container_name: pihole
    depends_on:
      - unbound
    image: pihole/pihole:v5.0
    environment:
      - TZ=Europe/London
      - ServerIP=192.168.1.253
      - DNS1=192.168.1.254#53
      - DNS2=no
      - HOST_IP=192.168.1.253
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./pihole/resolv.conf:/etc/resolv.conf
      - ./pihole/configs/pihole/:/etc/pihole/
      - ./pihole/configs/dnsmasq.d:/etc/dnsmasq.d/
    ports:
      - "53:53/tcp"
      - "67:67/udp" # Uncomment if you want to use Pi-Hole for DHCP
      - "53:53/udp"
    expose:
      - "80"
    mac_address: d0:ca:ab:cd:ef:fe
    networks:
      home:
        ipv4_address: 192.168.1.253
    dns:
      - 127.0.0.1
    cap_add:
      - NET_ADMIN
    restart: always
```
