### ISSUE TITLE
Request for documentation on how to run docker image with IPv6 (and IPv4)

### ISSUE THREAD

**Issue by adworacz** [pi-hole/docker-pi-hole#560]
This is a... 

- [x] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Please provide documentation on how to setup our docker environments such that IPv6 blocking works. It is well known that IPv6 is disabled by default for docker installs, and there's some documentation for updating the daemon.json file sprinkled around the internet, but I honestly can't find proper documentation that works anywhere.

I'm willing to help out/contribute via pull request/wiki, but I don't have a working solution for myself yet. This would include how to forward DNS requests using DHCPv6 options from a router (I run Openwrt, and already do this for IPv4, but realized there's a whole for IPv6). I can help with that documentation, once we get docker + IPv6 working.

I had Pihole enabled via DHCP options on my router (the classic "6,192.168.1.112" DHCP option), but I realized that some of my traffic was still being served directly from my router, and looking at the output of `drill`, it was always served by the IPv6 representation of my router. So, I was leaking due to direct IPv6 requests.

## Expected Behavior

IPv6 DNS serving to work.

## Actual Behavior

IPv4 DNS serving is the only thing that works. IPv6 is disabled by default.

## Possible Fix

Update /etc/docker/daemon.json, update docker compose files to provide an IPv6 address somehow?

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
N/A

## Debug steps I have tried

- [X] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [X] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause
- [X] I have searched this repository for existing issues and pull requests that look similar 

## Context and extra information

Related issue: https://github.com/pi-hole/docker-pi-hole/issues/250

## Your Environment 

* Docker Host Operating System and OS Version: Debian 10 (Buster)
* Docker Version: Docker version 19.03.5, build 633a0ea838
* Hardware architecture: x86_64

**Comment by zottelbeyer** [comment]
here's some documentation on how I got ipv6 to work in my home env: https://gist.github.com/zottelbeyer/c47b1a48b9c5c69796a712466e7fb71f

The biggest lack of documentation (or my understanding of it) IMO is in the prerequisites for even getting IPv6 to work in docker.

anyways, hope this helps and maybe someone is willing to put it in a nicer form for the wiki.

**Comment by tntwist** [comment]
@nathang21 

I got the pi.hole with cloudflared for DNS over HTTPS and IPv6 working.
Here is my docker-compose file:

https://gist.github.com/tntwist/a6183bbf736d7d652d1fc01a32c9c19a

Hope it can help you.

**Comment by Sijisu** [comment]
I used an NGINX reverse proxy to get IPv6 working. I'm running the following config on the Nginx:

```
# PiHole config
stream {
    upstream dns_servers {
        server 127.0.0.1:6953;
    }

    server {
        listen 53  udp;
        listen 53; #tcp
        listen [::]:53 udp;
        listen [::]:53;
        proxy_pass dns_servers;
    }
}
```
And then standard docker-compose.yml, but with changed ports.
```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "127.0.0.1:6953:53/tcp"
      - "127.0.0.1:6953:53/udp"
      - "127.0.0.1:6969:80/tcp"
      - "127.0.0.1:6970:443/tcp"
    environment:
      TZ: 'YOU-TIMEZONE'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 8.8.8.8
    cap_add:
      - NET_ADMIN
    network_mode: "bridge"
    restart: unless-stopped
```
Not the greatest solution in the world but it works for my use case.
```
$ nslookup duckduckgo.com 2a00:aaaa:aa:aaaa::cafe
Server:         2a00:aaaa:aa:aaaa::cafe
Address:        2a00:aaaa:aa:aaaa::cafe#53

Non-authoritative answer:
Name:   duckduckgo.com
Address: 40.114.177.156
```
