### ISSUE TITLE
docker upgrade FORCES re-add of Google DNS and removes OpenDNS!

### ISSUE THREAD

**Issue by fermulator** [pi-hole/docker-pi-hole#585]
Yikes!  I just went through the simple upgrade process (pull latest, rm docker image, re-compose)
To my horror, my upstream DNS settings for "Cloudfare" and "OpenDNS" were CHANGED to "Cloudfare" and "Google"!! this is bad
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
My settings were set in the UI, and I have the proper persistent volumes setup.
Configured for OpenDNS and Cloudflare.  After a docker upgrade, I get Google and Cloudflare. :(

## Expected Behavior
Google DNS shouldn't be re-added as the default here.

## Actual Behavior

```
fermulator@docker:/srv$ egrep server=[0-9] pihole/etc/dnsmasq.d/01-pihole.conf
server=208.67.222.222
server=208.67.220.220
server=1.1.1.1
server=1.0.0.1
```

After I run the upgrade
```
fermulator@docker:/srv/pihole$ cat upgrade.sh 
docker pull pihole/pihole
docker rm -f pihole
docker-compose up -d pihole
```
compose file:
```
fermulator@docker:/srv$ cat pihole/docker-compose.yml 
version: "3.5"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
        #- "67:67/udp" ; don't need DHCP
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Toronto'
      #WEBPASSWORD: SNIP
    # Volumes store your data between container upgrades
    volumes:
        #- '/srv/pihole/etc/:/etc/'
      - '/srv/pihole/etc/pihole/:/etc/pihole/'
      - '/srv/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/'
      - '/srv/pihole/tmp/:/tmp/docker-host/'
      - '/srv/pihole/etc/lighttpd/:/etc/lighttpd/'
        #- '/srv/pihole/logs/:/var/log'
    dns:
      - 127.0.0.1
      - 208.67.222.222
      - 208.67.220.220
      - 1.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN
    restart: unless-stopped
    shm_size: '2gb'
```

After the upgrade
```
fermulator@docker:/srv$ git diff pihole/etc/dnsmasq.d/01-pihole.conf
diff --git a/pihole/etc/dnsmasq.d/01-pihole.conf b/pihole/etc/dnsmasq.d/01-pihole.conf
index fa9e9ed..d2bf122 100644
--- a/pihole/etc/dnsmasq.d/01-pihole.conf
+++ b/pihole/etc/dnsmasq.d/01-pihole.conf
@@ -38,8 +38,8 @@ log-facility=/var/log/pihole.log
 local-ttl=2
 
 log-async
-server=208.67.222.222
-server=208.67.220.220
+server=8.8.8.8
+server=8.8.4.4
 server=1.1.1.1
 server=1.0.0.1
 domain-needed
```
, confirming this in the GUI too :(

## Possible Fix
at first I noticed my `--dns` settings in the compose weren't right, but they were fixed and the same issue

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 
(hard to find "Google DNS" too many results)

## Your Environment 

* Docker Host Operating System and OS Version: `Ubuntu 18.04`
* Docker Version: `5:19.03.6~3-0~ubuntu-bionic`
* Hardware architecture: `x86-64`
