### ISSUE TITLE
Stopped blocking after upgrade [arm64/aarch64 raspbian]

### ISSUE THREAD

**Issue by Mellbourn** [pi-hole/docker-pi-hole#587]
After upgrading to v4.4 my pi  hole stopped blocking ads.

This is a... 

- [ ] Request for a new or modified feature
- [x ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

I have been using docker-pi-hole without issue for months. Recently I did an upgrade (using `docker-compose pull && docker-compose up -d`, which upgraded to v4.4
After this upgrade, the pi-hole seems to be up and running, the web interface is working, but after running for several days:
* "Percent Blocked" shows as 0.0%
* "Domains on Blocklist" shows as -2
* It does not seem to block ads anymore
* In the Query log, only Status green is listed, nothing blocked.
* In the `pihole-FTL.log` file, 
** it states `ravityDB_open(): /etc/pihole/gravity.db does not exist`
** further down all rows says `Gravity database not available`! e.g. `domain_in_list(discord.co): Gravity database not available`

I'm a bit surprised at the FTL Version, it says  `vDev (development, vDev-7dea0f0)`
![Screenshot 2020-02-28 at 14 58 30](https://user-images.githubusercontent.com/1785727/75554606-f5ffb380-5a3a-11ea-8dbd-e6b6e185e957.png)

This is starting to sound like I have gotten a 5.0 beta version of the FTL, where you are supposed to have a database rather than a list.
But I have not done anything to get a beta, I have just done a normal `docker-compose pull`.

Tested doing `pihole checkout ftl master` but that did not help. It didn't even change version number displayed in GUI, so I'm not sure it worked.

Tested changing `docker-compose.yml` so that instead of getting `pihole/pihole:latest` it would get `pihole/pihole:release-v4.3.4`, and doing `docker-compose pull` but that didn't really help, it did downgrade the Pi-hole version, but not the FTL version.

## Expected Behavior
Ads blocked.

## Actual Behavior
No ads blocked.

## Possible Fix

Somehow getting the correct FTL version, maybe?

## Steps to Reproduce and debugging done

1. `docker-compose pull`
2. `docker-compose up -d`

## Debug steps I have tried

These things did not help:

1. I restarted the pi-hole. 
2. I have restarted the docker host. 
3. I have done a update gravity through the web gui, it reported no problems.
4. I have checked the contents of `/etc/pihole`, and it looks normal. The `list.*.domains` files are there and are normal size.
5. I have flushed the logs

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

Debug log:
https://tricorder.pi-hole.net/y9e5xygthd

I can't think of any workaround, so pi-hole has completely stopped working for me.

## Your Environment 

* Docker Host Operating System and OS Version:  Raspbian 4.19.97-v8+
* Docker Version: 19.03.6, build 369ce74
* Hardware architecture:  aarch64

**Comment by ryand11** [comment]
I  am having the same issue on the same build

**Comment by loguerto** [comment]
Same issue here.

**Comment by nathang21** [comment]
Has anyone successfully upgraded without this issue?

I'm a little concerned about upgrading.

**Comment by PromoFaux** [comment]
I have just updated my container running 4.3.2 to use the `:v4.4` tagged image (taken me a while to get around to it!), and am not seeing any issues.

`:latest` should be at 4.4, too.

I guess I will leave it running a few days to see if any of this is reproducible.

You definitely should _not_ be seeing that version of FTL in this container.

What does your compose file look like?

**Comment by RadiusK** [comment]
Same issue here ever since Watchtower automatically upgraded my pihole, was using `latest` tag at the time. Tried downgrading to `release-v4.3.4` just like @Mellbourn , without luck. Directly using `v4.4` doesn't fix it either. Have played around by removing some of the persisted data in `/etc/pihole/`, and even started over by removing all data+container and starting a fresh container. Not sure what determines the version of FTL, but it doesn't seem to be affected by the different images or even presence of pre-existing data or custom block & blacklists.

My compose file is pretty straight forward. Thing worth mentioning might be that I'm using host as network-mode and using pihole for DHCP. It worked perfectly for a couple of days (only got into last week), but now it interestingly shows `-2` items on my blocklist and doesn't block anything.

**pihole -v output**
```
Pi-hole version is v4.4 (Latest: v4.4)
AdminLTE version is v4.3.3 (Latest: v4.3.3)
FTL version is vDev-7dea0f0 (Latest: v4.3.1)
```

**docker-compose.yml**
```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:v4.4
    network_mode: host
    environment:
      - TZ=UTC
      - WEBPASSWORD=<my_password>
      - ServerIP=<my_host_ip_address>
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

Don't see anything strange in the logs when starting the container. The number of unique trapped domains is a lot higher than minus two though :P 

```
pihole    |
  [✓] Consolidating blocklists
  [✓] Extracting domains from blocklists
pihole    |   [i] Number of domains being pulled in by gravity: 147707
  [✓] Removing duplicate domains
pihole    |   [i] Number of unique domains trapped in the Event Horizon: 125377
```

**Comment by Mellbourn** [comment]
This is my `docker-compose.yml`
```
version: "3.6"

 # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
 services:
   pihole:
     container_name: pihole
     image: pihole/pihole:latest
     ports:
       - "53:53/tcp"
       - "53:53/udp"
       - "67:67/udp"
       - "80:80/tcp"
       - "443:443/tcp"
     environment:
       TZ: 'Europe/Stockholm'
       WEBPASSWORD: 'the password'
       # this is still needed to get pi.hole to work
       ServerIP: '192.168.0.9'
     # this makes the name of the docker image not be a random hash. This name is recognized only in the docker host environment
     hostname: 'pi-hole-in-docker'
     # Volumes store your data between container upgrades
     volumes:
       - './pi-hole/etc-pihole/:/etc/pihole/'
       - './pi-hole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
     # these are supposedly needed, otherwise you will get 127.0.0.11 problems https://github.com/pi-hole/docker-pi-hole/issues/410#issuecomment-460515706 - s till doesn't work
     dns:
       - 127.0.0.1
       - 1.1.1.1
     # Recommended but not required (DHCP needs NET_ADMIN)
     #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
     cap_add:
       - NET_ADMIN
     restart: unless-stopped
```
