### ISSUE TITLE
Chosen upstream DNS servers not saved

### ISSUE THREAD

**Issue by ElleshaHackett** [pi-hole/docker-pi-hole#604]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**

1: Change the Upstream DNS on the `/admin/settings.php?tab=dns` page. When docker was restarted or recreated (with persistent volume mounted) the chosen Upstream Servers in the list (left side) were not saved and back at Google DNS. I switched them several times to Cloudflare, saved. After a restart of container it was back at Google. 

**Actual behaviour:**

Selection not saved.

**Troubleshooting undertaken, and/or other relevant information:**

Tried several Docker container restarts and recreated. Did not work. I fixed it now by setting the CloudFlare DNS IPs as a custom DNS server on the right side.

**Comment by NeutralAlice** [comment]
It's not very clear in the documentation, but you need to set it as an environment variable. Default is set to google on container creation. Change the environment to the servers you would like to use before creating the container.

Example:

`services: 
  pihole: 
    deploy:
    dns: 
      - "127.0.0.1"
      - "9.9.9.9"
    environment:
      - TZ=America/Los_Angeles
      - DNS1=9.9.9.9
      - DNS2=149.112.112.112`

**Comment by ahuffman** [comment]
@NeutralAlice It would save if you've mounted persistent storage to /etc/pihole when launching the container.

**Comment by NeutralAlice** [comment]
> It would save if you've mounted persistent storage to /etc/pihole when launching the container. Also any customizations to the dnsmasq configs in /etc/dnsmasq.d would require a persistent volume to persist settings beyond a container relaunch.

I found that even with persistant storage I had to set the environment variable, otherwise it would reset this specific part. All other changes would remain on container relaunch

```  
    volumes: 
      - "etc-pihole:/etc/pihole"
      - "etc-dnsmasq.d:/etc/dnsmasq.d" 
volumes: 
  etc-dnsmasq.d: ~
  etc-pihole: ~
```

**Comment by casperklein** [comment]
BTW: Configuring DNS servers in addition to the two default Google DNS servers does work. But as soon as you remove the two Google ones, it defaults back to only two Google DNS.

**Comment by Haarolean** [comment]
I'm not sure that it's 100% relevant issue, but I got my DNS servers replaced by google servers somehow, probably during the upgrade to 5.0. I switched them back in UI and they were kept this time upon the restart.

**Comment by Haarolean** [comment]
Happens to me as well.
I had my cloudflare dns replaced by google already twice (in 01-pihole.conf).
My docker-compose.yml file:
```
version: '3'
services:
  pihole:
...
    volumes:
       - '/opt/pihole/etc-pihole/:/etc/pihole/'
       - '/opt/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
```
