### ISSUE TITLE
pihole won't start after Fedora 32 upgrade

### ISSUE THREAD

**Issue by pvnovarese** [pi-hole/docker-pi-hole#605]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
I updated my host to fedora 32 today, and after rebooting, I found that pihole wouldn't start up. 

```
> docker logs --follow pihole
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole
WARNING Misconfigured DNS in /etc/resolv.conf: Two DNS servers are recommended, 127.0.0.1 and any backup server
WARNING Misconfigured DNS in /etc/resolv.conf: Primary DNS should be 127.0.0.1 (found 127.0.0.11)

nameserver 127.0.0.11
options ndots:0
Assigning random password: 2xwR7zLx
  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u7

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
::: Pre existing WEBPASSWORD found
Using default DNS servers: 8.8.8.8 & 8.8.4.4
DNSMasq binding to default interface: eth0
Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "192.168.0.111",
			"VIRTUAL_HOST" => "192.168.0.111",
Using IPv4 and IPv6
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
http://sysctl.org/cameleon/hosts
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://hosts-file.net/ad_servers.txt
::: Testing pihole-FTL DNS: FTL started!
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
 ::: Docker start setup complete
  [i] Pi-hole blocking is enabled
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [i] Target: raw.githubusercontent.com (hosts)
  [✗] Status: Connection Refused
  [✗] List download failed: using previously cached list

  [i] Target: mirror1.malwaredomains.com (justdomains)
  [✗] Status: Connection Refused
  [✗] List download failed: using previously cached list

  [i] Target: sysctl.org (hosts)
  [✗] Status: Connection Refused
  [✗] List download failed: using previously cached list

  [i] Target: zeustracker.abuse.ch (blocklist.php?download=domainblocklist)
  [✗] Status: Connection Refused
  [✗] List download failed: using previously cached list

  [i] Target: s3.amazonaws.com (simple_tracking.txt)
  [✗] Status: Connection Refused
  [✗] List download failed: using previously cached list

  [i] Target: s3.amazonaws.com (simple_ad.txt)
  [✗] Status: Connection Refused
  [✗] List download failed: using previously cached list

  [i] Target: hosts-file.net (ad_servers.txt)
  [✗] Status: Connection Refused
  [✗] List download failed: using previously cached list

  [✓] Consolidating blocklists
  [✓] Extracting domains from blocklists
  [i] Number of domains being pulled in by gravity: 151055
  [✓] Removing duplicate domains
  [i] Number of unique domains trapped in the Event Horizon: 128874
  [i] Number of whitelisted domains: 0
  [i] Number of blacklisted domains: 0
  [i] Number of regex filters: 0
  [✓] Parsing domains into hosts format
  [✓] Cleaning up stray matter

  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting lighttpd
Starting pihole-FTL (no-daemon) as root
Starting crond
[services.d] done.


```

There is a pause of about 1 minute or so at each blocklist source it tries to pull.  The container shows unhealthy during this time, but I can exec in and see that FTL is running:

```
> docker ps
CONTAINER ID        IMAGE                          COMMAND               CREATED             STATUS                     PORTS                                                                                                  NAMES
64254f5519d9        pihole/pihole:latest           "/s6-init"            2 minutes ago       Up 2 minutes (unhealthy)   0.0.0.0:53->53/udp, 0.0.0.0:53->53/tcp, 0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:67->67/udp   pihole

> docker exec -it pihole /bin/bash
root@64254f5519d9:/# ps x | grep FTL
    569 ?        S      0:00 s6-supervise pihole-FTL
    586 ?        Sl     0:00 pihole-FTL no-daemon
    627 pts/0    S+     0:00 grep FTL

```

Anyway, once it fails to download the blocklists, it finishes the startup and the webinterface is up.  

I can access the web interface from the host itself, or from other hosts on my home network.  

However, I still can't get any queries resolved.

```
> dig @192.168.0.111 cnn.com

; <<>> DiG 9.11.18-RedHat-9.11.18-1.fc32 <<>> @192.168.0.111 cnn.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```
Since the webinterface is up, I generated a debug log, but it couldn't upload it.

```[✗]  There was an error uploading your debug log.```

when this didn't work, I tried whacking my etc-pihole and etc-dnsmasq.d directory/volumes and starting clean.

```
> docker logs --follow pihole
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole
WARNING Misconfigured DNS in /etc/resolv.conf: Two DNS servers are recommended, 127.0.0.1 and any backup server
WARNING Misconfigured DNS in /etc/resolv.conf: Primary DNS should be 127.0.0.1 (found 127.0.0.11)

nameserver 127.0.0.11
options ndots:0
Assigning random password: lW5FZjCh
  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u7

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
chown: cannot access '': No such file or directory
chmod: cannot access '': No such file or directory
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
::: Pre existing WEBPASSWORD found
Docker DNS variables not used
Existing DNS servers used (8.8.8.8 & 8.8.4.4)
DNSMasq binding to default interface: eth0
Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "192.168.0.111",
			"VIRTUAL_HOST" => "192.168.0.111",
Using IPv4 and IPv6
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
::: Testing pihole-FTL DNS: FTL started!
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
 ::: Docker start setup complete
  [✗] DNS resolution is currently unavailable
  [✗] DNS resolution is not available
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

There is a LONG pause after ' [✗] DNS resolution is currently unavailable'

Obviously since I have unless-stopped specified, the container restarts and the cycle continues.

My compose file is mostly standard:

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
#    image: pihole/pihole:beta-v5.0
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      ServerIP: '192.168.0.111'
      DNS1: '8.8.8.8'
      DNS2: '8.8.4.4' 
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 8.8.8.8
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1.
2. 
3. 
4. 

## Debug steps I have tried

- [yes] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [yes] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [yes] I have tried running without my volume data mounts to eliminate volumes as the cause
- [yes] I have searched this repository for existing issues and pull requests that look similar 

I whacked the etc-dnsmasq.d and etc-pihole directories with no change

I can exec into the container before it gives up, I can see that FTL is running:

```
> docker exec -it pihole /bin/bash
root@8d85fbb9bb19:/# ps x | grep -i ftl
    341 ?        S      0:00 pihole-FTL test
    704 pts/0    S+     0:00 grep -i ftl
```

## Your Environment 

* Docker Host Operating System and OS Version:  Fedora 32
* Docker Version: docker EE Docker version 19.03.5, build 2ee0c57608
* Hardware architecture: Intel x86_64

**Comment by pvnovarese** [comment]
Firewall issue.  I issued a 'sudo firewall-cmd --set-default-zone=trusted' and the container started up with zero issues.

Here's the weird thing, though, my default zone in firewalld still looked the same as it did before.
```
pvn@gyarados /home/pvn/compose/pihole> sudo firewall-cmd --zone=FedoraWorkstation --list-all
FedoraWorkstation (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp5s0
  sources:
  services: dhcpv6-client dns http ipp ipp-client mdns nfs samba-client ssh
  ports: 1025-65535/udp 1025-65535/tcp
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```
