### ISSUE TITLE
Can't access Pi-hole via pi.hole/admin

### ISSUE THREAD

**Issue by simphide** [pi-hole/docker-pi-hole#637]
This is a: Run Issue

## Details

If I run the pi-hole docker image I can perfectly access it via "192.168.178.45/admin" but pi.hole/admin does not work...

![image](https://user-images.githubusercontent.com/8183517/83963896-66736780-a8a9-11ea-8469-26e409c17e0a.png)

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu 20.04 
  * Hardware: PC
  * Kernel Architecture: amd64 
  * Docker Install Info and version: 
    - Software source: official docker
    - Supplimentary Software: docker compose 
  * Hardware architecture: x86

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    # hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'XXXX'
      DNS1: 1.1.1.1
      DNS2: 8.8.8.8
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [X] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by simphide** [comment]
Sorry... Should have read the documentation properly...

**Comment by shaomeng** [comment]
Hey @simphide ,  I run into the same issue. What part of the documentation did you find addressing this issue? Thanks!

**Comment by simphide** [comment]
You have to set the server-ip in the compose file:
``` 
   environment:
      TZ: 'Europe/Berlin'
      DNS1: 1.1.1.1
      DNS2: 8.8.8.8
      ServerIP: 192.168.178.45
```
