### ISSUE TITLE
Pi-hole/DockerCompose/JWilder-Nginx-Proxy

### ISSUE THREAD

**Issue by TheDuckMann** [pi-hole/docker-pi-hole#641]
This is a: Build Issue 

## Details

Hello, I'm trying to run Pi-hole behind the JWilder Nginx Proxy on my Server. As in the following Links _(Related Issues)_ provided, I set this up as the DEFAULT_HOST. Also I did the "spezial Treatment" for Ubuntu, written in the second Link _(Related Issues)_. But never the less I'm getting a portconflict. 
After using the command _sudo docker-compose up_ on the Pi-hole I am getting the following output:
```
Removing pihole
Recreating d09f715ad0ee_pihole ...
Recreating d09f715ad0ee_pihole ... error

ERROR: for d09f715ad0ee_pihole  Cannot start service pihole: driver failed programming external connectivity on endpoint pihole (f99813b9aca1b4dce45dfc05fc7c52ca6685ea7e0d981e2d557786e3e258a529): Bind for 0.0.0.0:443 failed: port is already allocated

ERROR: for pihole  Cannot start service pihole: driver failed programming external connectivity on endpoint pihole (f99813b9aca1b4dce45dfc05fc7c52ca6685ea7e0d981e2d557786e3e258a529): Bind for 0.0.0.0:443 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```
I would appreciate any help!

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose-jwilder-proxy.yml
https://github.com/pi-hole/docker-pi-hole#tips-and-tricks

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu Server 20.04 
  * Hardware: PC
  * Kernel Architecture: x86_64
  * Docker Install Info and version: 
    - Software source: GitHub
    - Supplimentary Software: Docker Compose
  * Hardware architecture: x86_64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

**Reverse Proxy with JWilders Nginx:**
```
version: '3'
services:
  reverseproxy-nginx:
    image: nginx
    container_name: reverseproxy-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    environment:
      - TZ=Europe/Berlin
    restart: always

  reverseproxy-dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup reverseproxy-nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: reverseproxy-dockergen
    depends_on:
      - reverseproxy-nginx
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    environment:
      - TZ=Europe/Berlin
      - DEFAULT_HOST=pihole.myadress.com
    restart: always

  reverseproxy-letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: reverseproxy-letsencrypt-companion
    depends_on:
      - reverseproxy-nginx
      - reverseproxy-dockergen
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/Berlin
    restart: always

volumes:
  conf:
  vhost:
  html:
  certs:

networks:
  default:
    external:
      name: nginx-reverseproxy
```

**Pi-hole:**
```
version: '3'

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - TZ=Europe/Berlin
      - WEBPASSWORD=ReallySecurePasswordForPiHole
      - ServerIP=10.10.10.50
      - VIRTUAL_HOST=pihole.myadress.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=pihole.myadress.com
      - LETSENCRYPT_EMAIL=me@myadress.com
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN
    restart: always

networks:
  default:
    external:
      name: nginx-reverseproxy
```

3. any additional info to help reproduce

This also happens with port 80 if I "deactivate" port 443 in the docker-compose.yml

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
