### ISSUE TITLE
Changes to WEBPASSWORD are ignored

### ISSUE THREAD

**Issue by chr1st1ank** [pi-hole/docker-pi-hole#643]
Setting the password for the web interface as documented only works once. E.g. this setting in a docker-compose file works:
```
version: "2.3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ...
    environment:
      WEBPASSWORD: my_complicated_password
      ...
    volumes:
       - './etc/pihole:/etc/pihole/'
       - './etc/dnsmasq.d:/etc/dnsmasq.d/'
```

But changes to this evironment variable are not picked up. Not when restarting the docker container nor even when recreating it. The reason is that the settings are stored in a volume and survive container recreations.
This line in the bash functions running on startup prevents changes to the password because it returns if there is already a password in `setupVars.conf`:
https://github.com/pi-hole/docker-pi-hole/blob/3b8227c29da6424c1e443ac71380e39be5dd41c9/bash_functions.sh#L266

This is probably also the reason behind the behaviour reported in #538 

I think the line in the bash function can simply be removed safely. Only drawback is that the same password is set again when a container is restartet.
