### ISSUE TITLE
Whitelist and adlists is empy in the web interface but not in the start log

### ISSUE THREAD

**Issue by Noiden** [pi-hole/docker-pi-hole#666]
When I start pi-hole with docker-compose it reads in all my adlists and also says,

`[i] Number of exact whitelisted domains: 197`

But when I log in to the web interface it's all empy and I can't add new.

This is a: **Bug**

## Details
I don't get any errors in the docker log and I am running the container with the default "DNSMASQ_USER=root".

Could this be some kind of permission error for lighthttpd? Because I see some weird things on the local folders and the ones in the container.

In the container the /etc/pihole is owned by user "pihole" but on the host the user is "systemd-coredump"

**ID in container**
uid=999(pihole) gid=999(pihole) groups=999(pihole)

**ID on host**
uid=999(systemd-coredump) gid=999(systemd-coredump) groups=999(systemd-coredump)

The statistic on the web interface doesn't refreh, on the dashboard the client activity and query types just spinning around and the ones in the top Queries blocked and Percent blocked doesn't refresh, it just says "---". Don't know it this is because of the other things with the whitelist and adlists.

## How to reproduce the issue

1. Environment data
  * Operating System: **Ubuntu 20.04**
  * Hardware: PC
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version:
    - Software source: offical docker-repo
    - Supplimentary Software: Portainer
  * Hardware architecture: x86/64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

**docker-compose.yml**

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: pihole.local
    ports:
      - "53:53/tcp"
      - "53:53/udp"
#      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/xxxxxxx'
      WEBPASSWORD: 'xxxxxxxxxxxxxxxx'
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
      DNS_BOGUS_PRIV: 'True'
      DNS_FQDN_REQUIRED: 'True'
      CONDITIONAL_FORWARDING: 'True'
      CONDITIONAL_FORWARDING_IP: 192.168.1.28
      CONDITIONAL_FORWARDING_DOMAIN: local
      CONDITIONAL_FORWARDING_REVERSE: 1.168.192.in-addr.arpa
      ServerIP: 192.168.1.26
      VIRTUAL_HOST: pihole.vsk
      IPV6: 'False'
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 192.168.1.28
      - 127.0.0.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
      - CAP_SYS_NICE
    restart: unless-stopped
```
3. any additional info to help reproduce

## These common fixes didn't work for my issue
- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [X] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
