### ISSUE TITLE
Teleporter failing silently in web GUI, throws error when run from command line.

### ISSUE THREAD

**Issue by dglinder** [pi-hole/docker-pi-hole#667]
This is a: Run Issue (running Pi-hole container failing)

## Details

Recently started running Pi-Hole as a Docker container with the `/etc/pihole/` and `/etc/dnsmasq.d/` as volumes on my Synology NAS.  This works well and rebuilding the container (nightly via crontab) is working quite well.

I like to use Teleporter to backup my configuration, but when the link in the web GUI is used, a new page to `http://pihole8080/admin/scripts/pi-hole/php/teleporter.php` opens, but no output is ever provided.

When I use `docker exec -it $DOCKER_ID /bin/bash" and run the php command directly (`php /var/www/html/admin/scripts/pi-hole/php/teleporter.php > /etc/pihole/test_tele.tar.gz`), it produces this error output:

```
root@pihole:/etc/pihole# php /var/www/html/admin/scripts/pi-hole/php/teleporter.php > /etc/pihole/test_tele.tar.gz
PHP Fatal error:  Uncaught UnexpectedValueException: Cannot create phar '/tmp/pi-hole-pihole.lab.linder.org-teleporter_2020-07-25_16-43-48.tar', file extension (or combination) not recognised or the directory does not exist in /var/www/html/admin/scripts/pi-hole/php/teleporter.php:547
Stack trace:
#0 /var/www/html/admin/scripts/pi-hole/php/teleporter.php(547): PharData->__construct('/tmp/pi-hole-pi...')
#1 {main}
  thrown in /var/www/html/admin/scripts/pi-hole/php/teleporter.php on line 547
root@pihole:/etc/pihole#
```

## Related Issues
- [/] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

None are similar

## How to reproduce the issue 

1. Environment data
  * Operating System: Docker container running on Synolgy NAS with latest OS
  * Hardware: Synology DS-412+
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: 
    - Software source: `image: pihole/pihole:latest`
    - Supplimentary Software: n/a
  * Hardware architecture: x86

```
admin@nas:~/NASContainers$ uname -a
Linux nas 3.10.105 #25426 SMP Wed Jul 8 03:19:33 CST 2020 x86_64 GNU/Linux synology_avoton_415+
```

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

## docker-compose.yml 
```
# Based on file from: https://blog.wapnet.nl/2020/05/install-pihole-on-synology-with-docker/
# vim: tabstop=2 shiftwidth=2 expandtab

version: '2'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: REDACTED.com
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    networks:
      pihole_network:
        ipv4_address: 192.168.123.111
    dns:
      - 1.1.1.3
      - 1.0.0.3
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - pihole-configs:/etc/pihole/
      - pihole-dnsmasq:/etc/dnsmasq.d/
    environment:
      ServerIP: 192.168.123.123
      VIRTUAL_HOST: pihole.REDACTED.com
      WEBPASSWORD: "REDACTED"
      WEB_PORT: 8080
    restart: unless-stopped

volumes:
  pihole-configs:
    # /etc/pihole/
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/services/homes/admin/NASContainers/pihole/pihole-configs
  pihole-dnsmasq:
    # /etc/dnsmasq.d/
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/services/homes/admin/NASContainers/pihole/pihole-dnsmasq

networks:
  pihole_network:
```

## docker run shell command

`sudo docker-compose -f pihole-docker-compose.yml up --detach`

then run `sudo docker exec -it pihole/bin/bash` (where `pihole` is the name of the docker container running.

3. any additional info to help reproduce

Once logged in using `docker exec` (above), run this command:

```
root@pihole:/etc/pihole# php /var/www/html/admin/scripts/pi-hole/php/teleporter.php > /etc/pihole/test_tele.tar.gz
PHP Fatal error:  Uncaught UnexpectedValueException: Cannot create phar '/tmp/pi-hole-pihole.lab.linder.org-teleporter_2020-07-25_16-43-48.tar', fi
le extension (or combination) not recognised or the directory does not exist in /var/www/html/admin/scripts/pi-hole/php/teleporter.php:547
Stack trace:
#0 /var/www/html/admin/scripts/pi-hole/php/teleporter.php(547): PharData->__construct('/tmp/pi-hole-pi...')
#1 {main}
  thrown in /var/www/html/admin/scripts/pi-hole/php/teleporter.php on line 547
root@pihole:/etc/pihole# 
```

## These common fixes didn't work for my issue

- [/] I have tried removing/destroying my container, and re-creating a new container
- [/] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

I will attempt to run the stripped-down Docker container when time (and family/users) permit.
