### ISSUE TITLE
Settings not being persistet across restarts

### ISSUE THREAD

**Issue by AuspeXeu** [pi-hole/docker-pi-hole#668]
This is a: Run Issue

## Details
When setting custom upstream DNS servers, these settings reset every time I restart the container or do an update with docker-compose.

## How to reproduce the issue 

1. Environment data
  * Operating System: CentOS7
  * Hardware: PC
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: 
    - Software source: official docker-ce
  * Hardware architecture: x86

2. docker-compose.yml contents
```
version: '2.2'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'xxxxxxxxxxxxxxxx'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 192.168.0.1
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped
```

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause
