### ISSUE TITLE
Long-term data not displayed

### ISSUE THREAD

**Issue by Hertex** [pi-hole/docker-pi-hole#673]
### Versions

- Pi-hole:  v5.1.2 (Latest: v5.1.2)
- AdminLTE:  v5.1.1 (Latest: v5.1.1)
- FTL:  v5.2 (Latest: v5.2)

### Platform

- OS and version:  Raspbian GNU/Linux 9 (stretch)

- Platform:  Raspberry Pi 3 Model B Rev 1.2

### Expected behavior

By pressing on one of the options of the "Long-term data" the informations from the Pi-hole query database should be displayed.

### Actual behavior / bug

It doesn't display any information at all. All graphs/tables are empty.

### Steps to reproduce

1. Run Pi-hole with following 'docker-compose.yml' file (except for minimal changes it's the one from the README.md of this repository).

```
version: "3"
# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'S0meEand0mPa55w0rd'
      VIRTUAL_HOST: 'pi.hole'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

2. Wait some time while surfing to generate some data.

3. Log into Pi-hole and open any of the "Long-term data" views.

## Debug Token

- URL:  https://tricorder.pi-hole.net/t420mgmgod

### Screenshots

![Long-term data - Graphics](https://imgur.com/rXhvnT4.png)

![Long-term data - Query Log](https://imgur.com/vUs3oAt.png)

![Long-term data - Top Lists](https://imgur.com/KYY6v42.png)

### Additional context

Starting a new container after deleting everything from the first one (docker images, local data from the volumes, ...) did not help.

Edit (15.08.2020 07:04 MESZ): Fixed the screenshots.
