### ISSUE TITLE
Docker Compose Stop & Docker Compose Start Cause Blocklists To Be Redownloaded

### ISSUE THREAD

**Issue by bonedaddy** [pi-hole/docker-pi-hole#692]
I'm using the following docker-compose file which when calling `docker-compose stop && docker-compose up -d` on will cause blocklists to be redownloaded. It appears that only blocklist information is lost, as all other settings are persisted.

```yaml
version: "3.5"
services:
    pihole:
        image: pihole/pihole
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "5354:53/tcp"
            - "5354:53/udp"
            - "67:67/udp"
            - "80:80/tcp"
            - "443:443/tcp"
        environment:
          TZ: 'America/Vancouver'
          WEBPASSWORD: admin
          DNSSEC: "true"
          ServerIP: <omitted>
          PIHOLE_BASE: /opt/pihole-storage
        volumes:
            - /ext-hdd/pihole-base:/opt/pihole-storage
            - /ext-hdd/pihole-etc/:/etc/pihole
            - /ext-hdd/pihole-dnsmasq.d/:/etc/dnsmasq.d/
          # WEBPASSWORD: 'set a secure password here or it will be random'
        # Volumes store your data between container upgrades
        # Recommended but not required (DHCP needs NET_ADMIN)
        #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
        cap_add:
          - NET_ADMIN
        restart: unless-stopped
```
