### ISSUE TITLE
Providing Two Customer DNS Servers, or "no", Results in "DNS resolution is currently unavailable"

### ISSUE THREAD

**Issue by jaredlander** [pi-hole/docker-pi-hole#695]
### Versions

- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.2

### Platform

- OS and version:  Ubuntu 16.04

- Platform:  WSL2

### Expected behavior

When using the following docker-compose file I expect pihole to start with one DNS pointing at the cloudflared container.

```
pihole:
    depends_on: [cloudflared]
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    ports:
      # for web interface
      - "80:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "443:443/tcp"
    dns:
      - 127.0.0.1
    environment:
      TZ: "America/New_York"
      WEBPASSWORD: "genericpassword" # Blank password - Can be whatever you want.
      ServerIP: 127.0.0.1 # Internal IP of pihole
      DNS1: 10.2.0.200#5053 # cloudflared container
      DNS2: "no"
    # Volumes store your data between container upgrades
    volumes:
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    # network_mode: host
    networks:
        private_network:
            ipv4_address: 10.2.0.100
    cloudflared:
        container_name: cloudflared
        image: visibilityspots/cloudflared
        restart: unless-stopped
        networks:
              private_network:
                  ipv4_address: 10.2.0.200
```

### Actual behavior / bug

The pihole container starts though the admin page is unavailable. Running `docker logs pihole` reveals that DNS resolution is not available.

```
[✗] DNS resolution is currently unavailable
```

### Steps to reproduce

1. Set `DNS1` to a custom domain like `10.2.0.200#5053`.
2. Set `DNS2` to `"no"`, or a different custom like `10.2.0.201#5053` or anything other than a standard DNS resolver such as `1.1.1.1`, `1.0.0.1` or `8.8.8.8`.
3. Run `docker-compose up -d`.
4. Wait for container's health to be deemed "healthy."
5. Check the logs with `docker logs pihole` or visit 127.0.0.1/admin.
6. See error

## Debug Token

- URL:  https://tricorder.pi-hole.net/4nj9qao9pd

Though this was on a working container.

### Additional context

I have tested this by permuting DNS1 and DNS2. Leaving out DNS2 results in Google being an upstream DNS Server. Using `1.1.1.1` or `1.0.0.1` or `8.8.8.8` for `DNS2` also works. But `"no"` or a custom server does not.

**Comment by dschaper** [comment]
Can you run `cloudflared` container with the daemon listening on port 53? Does it need to be on 5053?

**Comment by dschaper** [comment]
And I'm assuming the incorrect indentation for the `cloudflared` container is just a copy/paste error and the yaml is not actually indented too much.

**Comment by jaredlander** [comment]
@dschaper Happy to try running `cloudflared` on port 53, but not sure what to change in the docker-compose file to make it so.

And yeah, the indentation is a copy/paste thing.

**Comment by jaredlander** [comment]
Oh yeah, should also mention, this happens with both `pihole/pihole:latest` and `pihole/pihole:dev`.

**Comment by jaredlander** [comment]
Sorry, one more thing, if I just provide the customer DNS for `DNS1` and don't have anything for `DNS2`, the container works, but it gives me Google as an upstream.

```
environment:
      TZ: "America/New_York"
      WEBPASSWORD: "genericpassword" # Blank password - Can be whatever you want.
      ServerIP: 127.0.0.1 # Internal IP of pihole
      DNS1: 10.2.0.200#5053 # cloudflared container
```

works (but with Google) as a second DNS upstream while 

```
environment:
      TZ: "America/New_York"
      WEBPASSWORD: "genericpassword" # Blank password - Can be whatever you want.
      ServerIP: 127.0.0.1 # Internal IP of pihole
      DNS1: 10.2.0.200#5053 # cloudflared container
      DNS2: "no"
```

does not work.
