### ISSUE TITLE
DNS service not running status error

### ISSUE THREAD

**Issue by solidus1983** [pi-hole/docker-pi-hole#708]
- Pi-hole:  v5.2
- AdminLTE:  v5.2
- FTL:  v5.3.1

Platform:  Docker / Portainer

## Debug Token

- URL:  https://tricorder.pi-hole.net/6xpyh41r9t

Issue: After updating the docker image and recreating i am getting constant DNS service not running Status, This is with a clean installer or with the original config setup.
no matter what is done i get the same DNS service not running status error, even after clicking enable or restarting the container the issue remains.

Expect: DNS service should be shown in green and is running.

![piholeissue](https://user-images.githubusercontent.com/8018745/100557919-dd5f4b00-32a3-11eb-8929-fa2120b2d377.png)

**Comment by solidus1983** [comment]
Portainer is a WebGUI for docker, so what ever the start command is for docker is whats used for portainer.

The issue only happened with the latest update, its been working fine before FTL 5.3.1 update.

**Comment by dschaper** [comment]
> Portainer is a WebGUI for docker, so what ever the start command is for docker is whats used for portainer.

That doesn't provide me any information that I can use to try to help you.

**Comment by solidus1983** [comment]
Well good new is not sure what was causing the issue however it seems to of sorted itself out.

I am not sure totally what you mean by docker run however this is the files portainer uses to parse to docker-run

```
services.yaml
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    env_file:
      - ./services/pihole/pihole.env
    volumes:
       - /home/docker/pihole/pihole/:/etc/pihole/
       - /home/docker/pihole/dnsmasq.d/:/etc/dnsmasq.d/
       - /home/docker/pihole/root/:/root/scripts
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

```
pihole.env
ADMIN_EMAIL=<BLANKED>
TZ=Europe/London
WEBPASSWORD=<BLANKED>
DNS1=127.0.0.1
DNS2=1.0.0.1
DNSSEC=true
DNS_BOGUS_PRIV=true
DNS_FQDN_REQUIRED=true
CONDITIONAL_FORWARDING=true
CONDITIONAL_FORWARDING_IP=192.168.1.3
CONDITIONAL_FORWARDING_DOMAIN=lan
CONDITIONAL_FORWARDING_REVERSE=192.168.1.3/24
ServerIP=192.168.1.212
VIRTUAL_HOST=pihole
IPv6=false
DNSMASQ_LISTENING=all
DNSMASQ_USER=pihole
TEMPERATUREUNIT=C
WEBUIBOXEDLAYOUT=traditional
```
