### ISSUE TITLE
unable to spin up pihole:latest, pihole:5.1.2 with same compose works

### ISSUE THREAD

**Issue by hugalafutro** [pi-hole/docker-pi-hole#709]
Hi, my `docker-compose.yml` is:
```
services:
  pihole:
    container_name: pihole3
    environment:
      CONDITIONAL_FORWARDING: "true"
      CONDITIONAL_FORWARDING_DOMAIN: lan
      CONDITIONAL_FORWARDING_IP: 192.168.1.1
      CONDITIONAL_FORWARDING_REVERSE: 1.168.192.in-addr.arpa
      DNS1: 192.168.1.1
      DNS2: "no"
      ServerIP: 192.168.1.212
      TZ: Europe/London
      VIRTUAL_HOST: fr24
      WEBPASSWORD: <redacted>
    hostname: pihole3-docker
    image: pihole/pihole:latest
    ports:
    - 53:53/tcp
    - 53:53/udp
    - 67:67/udp
    - 7070:80/tcp
    restart: unless-stopped
    volumes:
    - /home/pi/docker/pi-hole/etc-pihole:/etc/pihole:rw
    - /home/pi/docker/pi-hole/etc-dnsmasq.d:/etc/dnsmasq.d:rw
version: '3.0'
```
the image got updated few hours ago so I wanted to test upgrade, however it fails with:
```
Creating network "pi-hole_default" with the default driver
Creating pihole3 ... done
Attaching to pihole3
pihole3   | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
pihole3   | [s6-init] ensuring user provided files have correct perms...exited 0.
pihole3   | [fix-attrs.d] applying ownership & permissions fixes...
pihole3   | [fix-attrs.d] 01-resolver-resolv: applying...
pihole3   | [fix-attrs.d] 01-resolver-resolv: exited 0.
pihole3   | [fix-attrs.d] done.
pihole3   | [cont-init.d] executing container initialization scripts...
pihole3   | [cont-init.d] 20-start.sh: executing...
pihole3   |  ::: Starting docker specific checks & setup for docker pihole/pihole
  [✓] Update local cache of available packages
pihole3   |   [i] Existing PHP installation detected : PHP version 7.3.19-1~deb10u1
pihole3   |
pihole3   |   [i] Installing configs from /etc/.pihole...
pihole3   |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
pihole3   | chown: cannot access '': No such file or directory
pihole3   | chmod: cannot access '': No such file or directory
pihole3   | chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
pihole3   | ::: Pre existing WEBPASSWORD found
pihole3   | Using custom DNS servers: 192.168.1.1 & no
pihole3   | DNSMasq binding to default interface: eth0
pihole3   | Added ENV to php:
pihole3   |                     "PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
pihole3   |                     "ServerIP" => "192.168.1.212",
pihole3   |                     "VIRTUAL_HOST" => "fr24",
pihole3   | Using IPv4 and IPv6
pihole3   | ::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
pihole3   | https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
pihole3   | https://mirror1.malwaredomains.com/files/justdomains
pihole3   |
pihole3   | dnsmasq: error at line 42 of /etc/dnsmasq.d/01-pihole.conf
pihole3   | ::: Testing pihole-FTL DNS: [cont-init.d] 20-start.sh: exited 1.
pihole3   | [cont-finish.d] executing container finish scripts...
pihole3   | [cont-finish.d] done.
pihole3   | [s6-finish] waiting for services.
pihole3   | [s6-finish] sending all processes the TERM signal.
pihole3   | [s6-finish] sending all processes the KILL signal and exiting.
```
changing tag to 5.1.2 and recreating the container spins it up no problem.

this is the offending file `cat etc-dnsmasq.d/01-pihole.conf`:
```
# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Dnsmasq config for Pi-hole's FTLDNS
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.

###############################################################################
#      FILE AUTOMATICALLY POPULATED BY PI-HOLE INSTALL/UPDATE PROCEDURE.      #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#        IF YOU WISH TO CHANGE THE UPSTREAM SERVERS, CHANGE THEM IN:          #
#                      /etc/pihole/setupVars.conf                             #
#                                                                             #
#        ANY OTHER CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE           #
#                    WITHIN /etc/dnsmasq.d/yourname.conf                      #
###############################################################################

addn-hosts=/etc/pihole/local.list
addn-hosts=/etc/pihole/custom.list


localise-queries


no-resolv



cache-size=10000

log-queries
log-facility=/var/log/pihole.log

local-ttl=2

log-async
server=192.168.1.1
interface=eth0
rev-server=1.168.192.in-addr.arpa,192.168.1.1
server=/lan/192.168.1.1
server=/use-application-dns.net/
```

Any help appreciated, thanks!
