### ISSUE TITLE
[v5.2] dnsmasq: error at line 48 of /etc/dnsmasq.d/01-pihole.conf

### ISSUE THREAD

**Issue by screendriver** [pi-hole/docker-pi-hole#710]
### Versions

Latest v5.2 docker image

### Platform

- OS and version:  

- Platform: Raspberry Pi with Docker v19.03.13

### Expected behavior

With the previous v5.1.2 everything works.

### Actual behavior / bug

With the latest v5.2 release I am not able to start a pi-hole anymore. I also tried it in a fresh directory and deleted everything. I'm always getting

```sh
pihole    | dnsmasq: error at line 48 of /etc/dnsmasq.d/01-pihole.conf
pihole    | ::: Testing pihole-FTL DNS: [cont-init.d] 20-start.sh: exited 1.
pihole    | [cont-finish.d] executing container finish scripts...
pihole    | [cont-finish.d] done.
pihole    | [s6-finish] waiting for services.
pihole    | [s6-finish] sending all processes the TERM signal.
pihole    | [s6-finish] sending all processes the KILL signal and exiting.
```

### Steps to reproduce

Try to start following `docker-compose.yml`:

```yml
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "999:999/tcp"
      # - "80:80/tcp"
      # - "443:443/tcp"
    environment:
      TZ: "Europe/Berlin"
      ServerIP: 192.168.1.2
      WEBPASSWORD: "foobar"
      DNS1: 84.200.69.80
      DNS2: 84.200.70.40
      DNSSEC: "true"
      DNS_FQDN_REQUIRED: "true"
      CONDITIONAL_FORWARDING: "true"
      CONDITIONAL_FORWARDING_IP: 192.168.1.1
      CONDITIONAL_FORWARDING_DOMAIN: fritz.box
      CONDITIONAL_FORWARDING_REVERSE: 1.168.192.in-addr.arpa
      WEB_PORT: 999
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 84.200.69.80
    cap_add:
      - NET_ADMIN
    # network_mode: host
    restart: unless-stopped
```

## Debug Token

I can't because the container does not start
