### ISSUE TITLE
[MegaThread] Settings not persisting between updates / docker-compose down then up etc

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/docker-pi-hole#720]
Going to merge a few threads and pin this one, to hopefully prevent duplicate reports:

It is something we are aware of - the advice I can give at the moment is to use [environment variables](https://github.com/pi-hole/docker-pi-hole#environment-variables) in your `docker run`/`docker-compose.yml` (or however one manages their containers.

Obviously that doesn't cover cases such as saving more than 2 upstream DNS servers, and a few other things. Personally I agree that there could be some persistence in user-changes to `setupVars.conf` and/or from the web interface. but digging through the comments on all the below issues I found this comment by @diginc : in #643 

> I have a [rewrite for config management in the works](https://github.com/pi-hole/docker-pi-hole/blob/beta-v5.0-refactor/docker/bash_functions.sh#L18-L24) (that I stalled out on) for better allowing both of these use cases to exist simultaneously but it's a pretty big breaking change to the environment variable schema and requires lots of people change their ENVs and re-writing/testing alot of the startup code.

And he makes a very good point.

In the mean time: Environment variables are your friend

## Existing threads:
- No Save Settings | No Files #198
- Feature Request: support DNS3 and DNS4 items for IPv6 upstream DNS servers #262
- Environment vars forcing use changes to reset #283
- Pi-hole settings lost at docker reboot #441
- PiHole Docker doenst use correct DNS Servers (always defaults to googles) #505
- Chosen upstream DNS servers not saved #604
- Changes to WEBPASSWORD are ignored #643
- Settings not being persistet across restarts #668
- Some DNS settings being lost on docker restart #687
- Serious issue with setupVars.conf file #719

**Comment by PromoFaux** [comment]
Comment from @xBellaDonna in #718 

> I can confirm I also have this issue, affecting more than just conditional forwarding. I first noticed this when watchtower pulled a new image and restarted my container, disabling both DNSSEC and conditional forwarding, and preventing me from accessing several local services by hostname.
> 
> It appears this is by design in the `start.sh` script which is run whenever the container starts (or restarts). The script first exports all the environment variables designed to set these settings and then calls function `change_setting` from `webpage.sh` (in the base pi-hole repo) which edits `setupVars.conf` to reflect the values of the exported environment variables, regardless of whether they are defined or not. The behaviour I'm referring to starts [here](https://github.com/pi-hole/docker-pi-hole/blob/89972b3ce546606e9e87eb8e7c4d0155e75f9692/start.sh#L57).
> Thus, even if `setupVars.conf` had these values set, they will all be unset by the startup script and written to `setupVars.conf` effectively erasing any configuration set using the web interface.
> 
> At first glance, it seems like a simple check before calling `change_setting` to see if these environment variables are undefined (i.e. `[ ! -z ${VARIABLE+x} ]`) would solve the problem but something tells me it would have already been implemented if it was that simple. There is a TODO [here](https://github.com/pi-hole/docker-pi-hole/blob/89972b3ce546606e9e87eb8e7c4d0155e75f9692/start.sh#L45) that would prevent these functions being called if it's not the container's first time starting however this would still cause problems in my case as watchtower routinely re-creates containers when pulling new images, leading to sudden and unexpected resetting of all my config unless I set the environment variables.
> 
> I'm currently working around the issue by modifying `start.sh` to include the check I mentioned and mounting it into the container, replacing the existing script (changes can be seen [here](https://github.com/xBelladonna/docker-pi-hole/commit/d70b3e371244e523fab7b1ea39e8f246519b0b30)). This check explicitly looks for undefined variables and returns true if the variable is set to an empty string, so the environment variables can be explicitly set to empty strings to override the existing config and only get ignored if they aren't defined in the first place. If this would be a viable fix then let me know and I can easily PR.

**Comment by PromoFaux** [comment]
> At first glance, it seems like a simple check before calling `change_setting` to see if these environment variables are undefined (i.e. `[ ! -z ${VARIABLE+x} ]`) would solve the problem but something tells me it would have already been implemented if it was that simple.

Funnily enough I had the same thought when I was looking over the code yesterday. My feeling is that it is a good idea to do this - as it would say "Only change this particular setting _if_ the environment variable is set" - seems sane to me, but maybe @diginc has some thought as to why this is a bad idea?

**Comment by xBelladonna** [comment]
If you change `testValue` to an empty string it will not report that the variable is set even though it is set, just to nothing.

**Comment by PromoFaux** [comment]
Thanks for the explanation, that makes sense.

![image](https://user-images.githubusercontent.com/1998970/101156273-40dcd600-3620-11eb-86f3-17a5144703a9.png)

**Comment by FrancisHG** [comment]
Cannot get my whitelist to load because the volume is not loading for me to /etc/pihole. Also no settings are persisting. I am using a docker volume mounted to /etc/pihole, but it seems a default /etc/pihole for the docker image is being used [my volume is not persisting nor mounting/overriding the container's directory]

**Comment by PromoFaux** [comment]
Testing `:dev` after the merge of #721 - I realised that upstream DNS servers can sometimes be overwritten (depending on config), #727 has been opened to address this

**Comment by PromoFaux** [comment]
Could anyone following this thread please test the changes introduces in #721 and #727, these have now both been merged to `:dev`

**Comment by quantenschaum** [comment]
I removed the inquestioned env vars from the `docker-compose.yml` like so

```yml
  pihole:
    image: pihole/pihole:dev
    restart: unless-stopped
    network_mode: host
    environment:
      ADMIN_EMAIL: *******
      TZ: Europe/Berlin
#      DNS1: 192.168.222.1
#      DNS2: fd99:2078:476a:*******
#      DNS_BOGUS_PRIV: 'true'
#      DNS_FQDN_REQUIRED: 'true'
#      REV_SERVER: 'true'
#      REV_SERVER_CIDR: 192.168.222.0/24
#      REV_SERVER_TARGET: 192.168.222.1
#      REV_SERVER_DOMAIN: fritz.box
      ServerIP: 192.168.222.10
      ServerIPv6: fd99:2078:476a:222:******
#      DNSMASQ_LISTENING: all
      WEB_PORT: '5380'
      SKIPGRAVITYONBOOT: '1'
    volumes:
       - ./pihole/pihole/:/etc/pihole/
       - ./pihole/dnsmasq.d/:/etc/dnsmasq.d/
    dns:
       - 127.0.0.1
       - 192.168.222.1
       - 1.1.1.1
```

The I issued `docker-compose restart pihole` or `stop` and `start` or `down` and `up`  and found that the settings are kept. Dockerimage id `7e490bf18941`.

When reverting to the no-dev-image (`52e72f4b6a61`), the settings were lost.
