### ISSUE TITLE
Pi-hole blocks access to its own landing page

### ISSUE THREAD

**Issue by bioxz** [pi-hole/docker-pi-hole#733]
### Versions
- Pi-hole version is v5.2.1 (Latest: v5.2.1)
- AdminLTE version is v5.2.1 (Latest: v5.2.1)
- FTL version is v5.3.2 (Latest: v5.3.2)

### Platform
- OS and version: Pi OS 10.7
- Platform:  Docker

### Expected behavior

I can visit the Pi-hole landing page using the PQDN or the IP address:

![image](https://user-images.githubusercontent.com/1084262/102761889-d645cd00-4377-11eb-9db4-4024386efca1.png)

### Actual behavior / bug

While access via IPv4 and IPv6 is working, The Pi-hole blocks access to its own landing page using PQDN (apalapucia:80) for a weird reason:

![image](https://user-images.githubusercontent.com/1084262/102762090-1311c400-4378-11eb-9250-74d311117239.png)

In which apalapucia is the PQDN of the system running the Pi-hole docker instance and the reason is that it was not found in any blacklist.

### Steps to reproduce

Fresh setup based on this docker-compose file:

```
version: '3'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 10080:80/tcp
      - 10443:443/tcp
    volumes:
      - /home/service/pihole:/etc/pihole
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
      - DNSSEC=true
    restart: unless-stopped
```

### Additional context

The admin panel is working both via PQDN and IP addresses, but still the warning page looks like it shouldn't be there. I followed the  [example](https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose.yml.example) and removed the settings that are documented as only required for DHCP.
