### ISSUE TITLE
Dashboard header reports an incorrect status when running on docker

### ISSUE THREAD

**Issue by scara** [pi-hole/docker-pi-hole#734]
### Versions
Running docker tag image `v5.2.1`, `$ docker exec -it pihole pihole -v`:
- Pi-hole version is v5.2.1 (Latest: v5.2.1)
- AdminLTE version is v5.2.1 (Latest: v5.2.1)
- FTL version is v5.3.2 (Latest: v5.3.2)

### Platform
Running using docker tag image `v5.2.1`,
- OS and version: Debian `10.5`
- Platform: Docker on Raspberry Pi

### Expected behavior
Status in the dashboard should show: "Active"

### Actual behavior / bug
Status in the dashboard shows: "DNS service not running"

### Steps to reproduce
1. Run the default image without adding any additional cap - no DHCP required
1. Point the browser to the web interface

Asking for the `pihole status` shows:
```bash
$ docker exec -it pihole pihole status
  [✗] DNS service is NOT listening
```
while if you add the following argument to the `docker run` command, `--cap-add=SYS_PTRACE`, you'll get:
```bash
$ docker exec -it pihole pihole status
  [✓] DNS service is listening
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
```
This is a regression added w/ https://github.com/pi-hole/pi-hole/commit/6009e869471f7f1da0593d91d82855340c8643b1 since `lsof` requires to read `/proc/*/stat`. See [ptrace(2)](https://man7.org/linux/man-pages/man2/ptrace.2.html).
When the cap is there:
```bash
$ docker exec -it pihole lsof -Pni:53
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
pihole-FT 835 pihole    4u  IPv4 121563      0t0  UDP *:53
pihole-FT 835 pihole    5u  IPv4 121564      0t0  TCP *:53 (LISTEN)
pihole-FT 835 pihole    6u  IPv6 121565      0t0  UDP *:53
pihole-FT 835 pihole    7u  IPv6 121566      0t0  TCP *:53 (LISTEN)
```
Shortly: `lsof` is not Docker friendly unless using `CAP_SYS_PTRACE`.
I'm not sure if the fix here is just to make a clear mention of the new cap requirement in the README or to find another way to provide that beautiful report.

HTH,
Matteo

**Comment by PromoFaux** [comment]
Thanks for the report. I'm not 100% this is reproducible - but I'm a bit green when it comes to docker.

But, short story - I don't have `CAP_SYS_PTRACE`  added in my compose file, but the two commands run fine:

![image](https://user-images.githubusercontent.com/1998970/102801513-3c991280-43ad-11eb-97cd-7ec77780c58e.png)

I'm currently running the `:dev` tag, but I don't think anything that would affect this has been added into that since we released the `:v5.2.1` tag

**Comment by scara** [comment]
Hi @PromoFaux,
thanks for the quick reply.
> but I'm a bit green when it comes to docker

Me too 😉.
I'm using docker on a Pi4:
```bash
$ docker -v
Docker version 20.10.1, build 831ebea
```
and I'm running _pihole_ not via a _docker compose_ but a simple _run_:
```bash
$ docker run -d \
             --name pihole \
             --restart=unless-stopped \
             --hostname=pihole-container \
             --dns=127.0.0.1 --dns=8.8.8.8 \
             --add-host="pi401 pi401.scaramuccia.home:127.0.0.1" \
             --cap-add=NET_BIND_SERVICE \
             --cap-add=SYS_NICE \
             --cap-add=SYS_PTRACE \
             --cap-drop=NET_RAW \
             -p 53:53/udp -p 53:53/tcp \
             -p 80:80/tcp \
             -p 443:443/tcp \
             -v /srv/pihole/etc/pihole:/etc/pihole \
             -v /srv/pihole/etc/dnsmasq.d:/etc/dnsmasq.d \
             -e ServerIP=192.168.0.5 \
             -e IPv6=False \
             -e DNS1=8.8.8.8 \
             -e DNS2=8.8.4.4 \
             -e DNSMASQ_USER=pihole \
             -e TZ=Europe/Rome \
             -e WEBPASSWORD=pippero \
             -e VIRTUAL_HOST=pi401.scaramuccia.home \
             pihole/pihole:v5.2.1
```
If I remove the `--cap-add=SYS_PTRACE \` above, I get the issue - the cap has been added just an hour ago before opening this issue.

HTH,
Matteo

**Comment by PromoFaux** [comment]
Hmm, I'm on a Synology Nas with `docker` at `v18.09.8`, not sure how much of a difference that makes.
`compose` file as follows (n.b, i'm using `macvlan` for the network layer, so don't need to do anything with `port` variables

```yml
version: '3.5'
services:

  pihole:
    container_name: pihole
    hostname: pihole-docker
    depends_on:
      - unbound
    image: pihole/pihole:dev
    environment:
      - TZ=Europe/London
      - ServerIP=192.168.1.253
      #- DNS1=8.8.8.8 #not needed in dev image
      #- DNS2=8.8.4.4 #not needed in dev image
      - PIHOLE_DNS_=8.8.8.8;8.8.4.4;127.0.0.1#5353 #new in dev image
      - REV_SERVER=true
      - REV_SERVER_DOMAIN=lan
      - REV_SERVER_TARGET=192.168.0.1
      - REV_SERVER_CIDR=192.168.0.0/16
      - SKIPGRAVITYONBOOT=1
    volumes:
      - ./pihole/configs/pihole/:/etc/pihole/
      - ./pihole/configs/dnsmasq.d:/etc/dnsmasq.d/
    mac_address: d0:ca:ab:cd:ef:fe
    networks:
      home:
        ipv4_address: 192.168.1.253
    restart: always
```

Paging @diginc  for thoughts
