### ISSUE TITLE
WEBPASS set, not working

### ISSUE THREAD

**Issue by ShlomiRex** [pi-hole/docker-pi-hole#781]
### Versions

- Pi-hole version is v5.2.4 (Latest: v5.2.4)
- AdminLTE version is v5.3.2 (Latest: v5.3.2)
- FTL version is v5.6 (Latest: v5.6)

### Platform

- OS and version:  Ubuntu Debian GNU/Linux 9.13 (stretch) x86_64

- Platform:  docker

### Expected behavior

Set admin panel password to `test`

### Actual behavior / bug

Password authentication incorrect

### Steps to reproduce

1. Set `docker-compose.yml` to: 

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "81:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'test'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

```

NOTE: I use port 81, not 80 (already binded, using diffirent service. If you want to know, it's OpenMediaVault admin panel).

2. Run `docker-compose up`
3. Connect to admin panel and try to connect with password `test`
4. Not working, auth failed
