### ISSUE TITLE
Container can't use Pihole's DNS

### ISSUE THREAD

**Issue by schklom** [pi-hole/docker-pi-hole#811]
This is a: **Run Issue**  

## Details

Container in same network cannot use Pihole's DNS, although they can ping and curl Pihole.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

https://github.com/pi-hole/docker-pi-hole/issues/230

## How to reproduce the issue 

1. Environment data
  * Operating System: **Debian Buster**
  * Hardware: RasPi 4B
  * Kernel Architecture:
```
$ uname -srvmpio
Linux 5.9.0-0.bpo.5-arm64 #1 SMP Debian 5.9.15-1~bpo10+1 (2020-12-31) aarch64 unknown unknown GNU/Linux
```
  * Docker Install Info and version: 
    - Software source: official rootless docker
    - Supplimentary Software: none, just docker commands
  * Hardware architecture: ARMv7, x64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
version: "3.8"

services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    hostname: duckdns
    dns:
      - 172.80.17.2
    environment:
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
    depends_on:
      - pihole
    networks:
      pihole-duckdns:
    
  pihole:
    image: pihole/pihole
    container_name: pihole
    hostname: pihole
    ports:
       - "53:53/tcp"
       - "53:53/udp"
      - "8888:80/tcp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      TZ: ${TZ}
      WEBPASSWORD_FILE: /run/secrets/pihole_password
      PIHOLE_DNS_: 1.1.1.1
    secrets:
      - pihole_password
    networks:
      pihole-duckdns:
        ipv4_address: 172.80.17.2
```
3. any additional info to help reproduce
Pihole can be pinged and even curl from Duckdns. But for some reason, connection to the DNS port is not working.
Pihole can look at the network and see Duckdns' IP

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
