### ISSUE TITLE
DNS doesn't work when using unbound

### ISSUE THREAD

**Issue by schklom** [pi-hole/docker-pi-hole#812]
This is a: **Run Issue**  

## Details

When using https://gitlab.com/klutchell/unbound/, Pihole receives all DNS requests, but the reply never reaches the sender.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Debian Buster**
  * Hardware: RasPi 4B
  * Kernel Architecture:
```
$ uname -srvmpio
Linux 5.9.0-0.bpo.5-arm64 #1 SMP Debian 5.9.15-1~bpo10+1 (2020-12-31) aarch64 unknown unknown GNU/Linux
```
  * Docker Install Info and version: 
    - Software source: official rootless docker
    - Supplimentary Software: none, just docker commands
  * Hardware architecture: ARMv7, x64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
version: "3.8"

services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    hostname: pihole
    ports:
       - "53:53/tcp"
       - "53:53/udp"
      - "8888:80/tcp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      TZ: ${TZ}
      WEBPASSWORD_FILE: /run/secrets/pihole_password
      PIHOLE_DNS_: 172.80.2.2#5053
      SKIPGRAVITYONBOOT: 1
    secrets:
      - pihole_password
    networks:
      pihole-unbound:

  unbound:
    image: klutchell/unbound
    container_name: unbound
    networks:
      pihole-unbound:
        ipv4_address: 172.80.2.2

networks:
  pihole-unbound:
    ipam:
      config:
        - subnet: "172.80.2.0/24"
```
3. any additional info to help reproduce

Wherever I make `curl` or `nslookup` requests from, Pihole receives them, but answer never comes back.
The only way I'm connected on Internet now is because I use a regular 2ndary DNS in my router.

This happens when using unbound: specifying usual upstream DNS servers instead of `unbound` solves the problem, but I would rather avoid it.

I have checked `unbound` and the default configuration works fine:
```
$ docker exec unbound drill -p 5053 facebook.com @127.0.0.1
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 45643
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; facebook.com.        IN      A

;; ANSWER SECTION:
facebook.com.   300     IN      A       31.13.72.36

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 168 msec
;; SERVER: 127.0.0.1
;; WHEN: Thu Mar  4 17:29:15 2021
;; MSG SIZE  rcvd: 46
```
which leads me to think the problem comes from `Pihole`, but I don't know why.

Do you have any idea ? ^^

I will be very grateful to whoever can help :)

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

### EDIT
not using `SKIPGRAVITYONBOOT: 1` makes pihole unable to start
```
::: All config checks passed, cleared for startup ...
::: Enabling Query Logging
  [i] Enabling logging...
  [✓] Logging has been enabled!
 ::: Docker start setup complete
  [✗] DNS resolution is currently unavailable
```
I should point out (if it makes a difference) that I'm using Rootless Docker.
I should also say that I had the same issue when using regular Docker.
