### ISSUE TITLE
CACHE_SIZE is not a supported Docker environmental variable, despite being supported in setupVars.conf

### ISSUE THREAD

**Issue by Veduco** [pi-hole/docker-pi-hole#813]
A user who installs pihole natively on a server is expected to utilize the setupVars.conf file to set basic environmental variables, for consumption when executing "pihole -r", populating several config files with values set.
A user who runs pihole in a docker container has no ability to set the "cache-size" as defined by the CACHE_SIZE found in setupVars.conf, nor a suitable environmental variable.

This is a: Bug

## Details

I have submitted this as a bug because anything that is capable of being set in setupVars.conf should be able to be defined and respected in a docker environment. Currently, this is not the case.

On docker container start, no matter what
```
[✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
```
which overrides any manual customizations a user has done to this file to compensate for the lack of a supported environmental variable, including resetting the cache-size to 10000.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

https://github.com/pi-hole/docker-pi-hole/issues/526

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu 20.04.2 LTS (Focal Fossa) 
  * Hardware: x86 ESXi
  * Kernel Architecture: x86/amd64 
  * Docker Install Info and version: 
    - Software source: official docker-ce
    - Supplimentary Software: None required to reproduce this issue
  * Hardware architecture: x86 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

```
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      dns_net:
        ipv4_address: 192.0.2.3
    restart: unless-stopped
    ports:
      - "10.10.3.14:53:53/tcp"
      - "10.10.3.14:53:53/udp"
      - "10.10.3.14:80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: ''
      DNS1: "192.0.2.4#53"
      DNS2: "10.10.3.14#953"
      CACHE_SIZE: 0
    volumes:
       - ./etc-pihole:/etc/pihole
       - ./etc-pihole/php_cgi.ini:/etc/php/7.3/cgi/php.ini:ro
    dns:
      - 127.0.0.1
      - 9.9.9.9
    depends_on:
      - dnscrypt
```

3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
