### ISSUE TITLE
Changes to lighttpd's external.conf do not persist 

### ISSUE THREAD

**Issue by mrjones-plip** [pi-hole/docker-pi-hole#817]
This is a:  Run Issue

## Details
Because the `docker-compose.yml` file does not have a `volume:` for the `/etc/lighttpd`  directory, any changes made to `/etc/lighttpd/external.conf` are easily lost.  This is where Pi-hole FAQs recommend you make local changes, [like serving the admin interface over TLS](https://discourse.pi-hole.net/t/enabling-https-for-your-pi-hole-web-interface/5771).  As such, it should persist across the container being destroyed like we do with `etc-pihole` and `etc-dnsmasq.d` volumes.

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

Yup! I only [see two issues](https://github.com/pi-hole/docker-pi-hole/search?q=external.conf&state=open&type=issues) that mention `external.conf`. This ticket is not a dupe as far as I can tell - the two existing tickets would both benefit from this bugfix though!

## How to reproduce the issue 

1. Environment data
  * Operating System: `Ubuntu 20.04`
  * Hardware: `PC`
  * Kernel Architecture: `amd64`
  * Docker Install Info and version: 
    - Software source: official docker image `pihole/pihole:latest` with:
    
          ```
          pihole -v
          Pi-hole version is v5.2.4 (Latest: v5.2.4)
          AdminLTE version is v5.4 (Latest: v5.4)
          FTL version is v5.7 (Latest: v5.7)
          ```

    - Supplimentary Software:  `Docker version 20.10.5, build 55c4c88` and `docker-compose version 1.28.5, build c4eb3a1f`
  * Hardware architecture: `x86`

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

     ```
     services:
     pihole:
     container_name: pihole
     image: pihole/pihole:latest
     network_mode: "host"
     environment:
          TZ: 'America/Chicago'
          WEBPASSWORD: 'NOT REALLY THIS'
     volumes:
          - './etc-pihole/:/etc/pihole/'
          - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
     cap_add:
          - NET_ADMIN
     restart: unless-stopped
     ```

3. any additional info to help reproduce
   1. create `docker-compose.yml` file per above
   2. `docker-compose up -d` 
   3. `docker exec -it pihole bash` 
   4. edit `/etc/lighttpd/external.conf`, even to just put a `#commment here` line
   5. `docker-compose down`  && `docker-compose up -d` 
   6. `docker exec -it pihole cat /etc/lighttpd/external.conf` and note file is empty when it shouldn't be

It should be noted we [explicitly tell users they can customize](https://github.com/pi-hole/docker-pi-hole/blob/master/README.md#customizations) their Docker Pi-Hole install:

> Similarly for the webserver you can customize configs in /etc/lighttpd

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container _(Yes! this is precisely how I found it)_
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- ~~[ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)~~ NA
- ~~[ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)~~ NA
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause
