### ISSUE TITLE
RPi Docker with macvlan and ServerIP set, but not used ServerIP

### ISSUE THREAD

**Issue by linuxdep** [pi-hole/docker-pi-hole#819]
This is a: **Bug ?**  

## Related Issues
- [yes ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Rasbian Buster** 
  * Hardware: RasPi 3B  
  * Kernel Architecture: ArmV7l 
  * Docker Install Info and version: 
    - Software source: Docker Engine 20.10.5  go1.13.15  
    - Supplimentary Software: 
  * Hardware architecture: ARMv7l 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
3. any additional info to help reproduce

docker-compose.yml
```
Version: "3.9"

services:
  pihole:
    container_name: pihole
    image: "pihole/pihole:latest"
    hostname: pihole
    domainname: hostname.ddnss.de
    restart: unless-stopped

    environment:
      TZ: 'Europe/Berlin' # Put your own timezone here.
      WEBPASSWORD: pihole123
      ServerIP: 192.168.123.123
      VIRTUAL_HOST: pihole.hostname.ddnss.de
      PIHOLE_DNS_: 127.0.0.1;192.168.123.1
    
    # We'll use host networking simply because it is way easier to setup.
    # network_mode: host
    network_mode: rpiauto_120

    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    
    # Volumes store your data between container upgrades
    volumes:
      - './dockerFS/pi-hole/etc-pihole/:/etc/pihole/'
      - './dockerFS/pi-hole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    
    # Required for the DHCP server
    cap_add:
      - NET_ADMIN

```
```
Recreating pihole ... done
Attaching to pihole
pihole    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
pihole    | [s6-init] ensuring user provided files have correct perms...exited 0.
pihole    | [fix-attrs.d] applying ownership & permissions fixes...
pihole    | [fix-attrs.d] 01-resolver-resolv: applying... 
pihole    | [fix-attrs.d] 01-resolver-resolv: exited 0.
pihole    | [fix-attrs.d] done.
pihole    | [cont-init.d] executing container initialization scripts...
pihole    | [cont-init.d] 20-start.sh: executing... 
pihole    |  ::: Starting docker specific checks & setup for docker pihole/pihole
pihole    | 
pihole    |   [i] Installing configs from /etc/.pihole...
pihole    |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
pihole    | Setting DNS servers based on PIHOLE_DNS_ variable
pihole    | ::: Pre existing WEBPASSWORD found
pihole    | DNSMasq binding to default interface: eth0
pihole    | Added ENV to php:
pihole    | 			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
pihole    | 			"ServerIP" => "192.168.123.123",
pihole    | 			"VIRTUAL_HOST" => "pihole.hostname.ddnss.de",
pihole    | Using IPv4 and IPv6
pihole    | ::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
pihole    | https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
pihole    | https://mirror1.malwaredomains.com/files/justdomains
pihole    | ::: Testing pihole-FTL DNS: FTL started!
pihole    | ::: Testing lighttpd config: Syntax OK
pihole    | ::: All config checks passed, cleared for startup ...
pihole    | ::: Enabling Query Logging
pihole    |   [i] Enabling logging...
  [✓] Logging has been enabled!
pihole    |  ::: Docker start setup complete
pihole    |   [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range
pihole    | 
  [✓] Preparing new gravity database
pihole    |   [i] Using libz compression
pihole    | 
pihole    |   [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
pihole    |   [i] Received 77608 domains
pihole    | 
  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
pihole    |   [i] Number of gravity domains: 77608 (77608 unique domains)
pihole    |   [i] Number of exact blacklisted domains: 0
pihole    |   [i] Number of regex blacklist filters: 0
pihole    |   [i] Number of exact whitelisted domains: 0
pihole    |   [i] Number of regex whitelist filters: 0
  [✓] Cleaning up stray matter
pihole    | 
pihole    |   [✓] DNS service is listening
pihole    |      [✓] UDP (IPv4)
pihole    |      [✓] TCP (IPv4)
pihole    |      [✓] UDP (IPv6)
pihole    |      [✓] TCP (IPv6)
pihole    | 
pihole    |   [✓] Pi-hole blocking is enabled
pihole    |   Pi-hole version is v5.2.4 (Latest: v5.2.4)
pihole    |   AdminLTE version is v5.4 (Latest: v5.4)
pihole    |   FTL version is v5.7 (Latest: v5.7)
pihole    | [cont-init.d] 20-start.sh: exited 0.
pihole    | [cont-init.d] done.
pihole    | [services.d] starting services
pihole    | Starting crond
pihole    | Starting lighttpd
pihole    | Starting pihole-FTL (no-daemon) as root
pihole    | [services.d] done.
```

IP at pihole container:
```
$ docker exec pihole ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
11: eth0@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:c0:a8:7b:78 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.123.120/24 brd 192.168.123.255 scope global eth0
       valid_lft forever preferred_lft forever
```

but i web-gui from pihole i see
```
Pi-hole Ethernet Interface: | eth0
Pi-hole IPv4 address: | 192.168.123.123
```

My macvlan is:
```
docker network inspect rpiauto_120
[
    {
        "Name": "rpiauto_120",
        "Id": "ec68fffbdf0ccd16f409400f2e0c81621db9b6cd7c44fa4207341ffabbe3470a",
        "Created": "2021-04-04T00:20:19.365202752+02:00",
        "Scope": "local",
        "Driver": "macvlan",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "192.168.123.0/24",
                    "IPRange": "192.168.123.120/29",
                    "Gateway": "192.168.123.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "7cdeb24d51899af702d5bf628766f46b105d72644c1327a805a2df16db3c9bbd": {
                "Name": "pihole",
                "EndpointID": "d8158eeefcfcc47236a4f2b927a751d442b469929624c1691309993c755b5084",
                "MacAddress": "02:42:c0:a8:7b:78",
                "IPv4Address": "192.168.123.120/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "parent": "eth0"
        },
        "Labels": {}
    }
]
```

## These common fixes didn't work for my issue

- [ yes] I have tried removing/destroying my container, and re-creating a new container
- [yes ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [no ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [no ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by buckaroogeek** [comment]
As an fyi - my docker compose (v 2.4) is below. My docker macvlan is `macvlan1`. Since there is no portforwarding with a macvlan the ports list just defines the ports exposed on the container.

```
  pihole:     # Pi Hole dns server for local network
    container_name: SageCreek-Pi-Hole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: lan             
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    networks:
      macvlan1:
        ipv4_address: 192.168.110.201   #  <-- Match ServerIP
    volumes:
      - '/volume1/docker/pihole/pihole-configs:/etc/pihole/'
      - '/volume1/docker/pihole/dnsmasq.d-configs:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      ServerIP: 192.168.110.201       # <-- match ipv4_address
      VIRTUAL_HOST: pihole.lan     
      WEBPASSWORD: "xxxxxxxx" 
    restart: unless-stopped

```

**Comment by linuxdep** [comment]
I have found, this was my issue. The docs from docker-compose.yml file was not easy to find, but i have it under github.... 
hep for other with the same:

external macvlan define with 
`docker create network...`

docker-compose.yml
```
version: "3.8"

networks:
  macvlan:
    external:
      name: macvlan120

services:

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: hostname.ddnss.de
    restart: unless-stopped

    environment:
      TZ: 'Europe/Berlin' # Put your own timezone here.
      WEBPASSWORD: 'pihole123' # Put a strong password here.
      ServerIP: '192.168.123.123'
      VIRTUAL_HOST: 'pihole.hostname.ddnss.de'
      PIHOLE_DNS_: '127.0.0.1;192.168.123.1'
    networks: 
      macvlan:
        ipv4_address: 192.168.123.123

    # Volumes store your data between container upgrades
    volumes:
      - './dockerFS/pi-hole/etc-pihole:/etc/pihole'
      - './dockerFS/pi-hole/etc-dnsmasq.d:/etc/dnsmasq.d'
```
or docker-compose.yml with network insight:
```
 version: "3.8"

networks:
  macvlan120:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.123.0/24
          gateway: 192.168.123.1
          ip_range: 192.168.123.120/29

services:

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: hostname.ddnss.de
    restart: unless-stopped

    environment:
      TZ: 'Europe/Berlin' # Put your own timezone here.
      WEBPASSWORD: 'pihole123' # Put a strong password here.
      ServerIP: '192.168.123.123'
      VIRTUAL_HOST: 'pihole.hostname.ddnss.de'
      PIHOLE_DNS_: '127.0.0.1;192.168.123.1'
    networks: 
      macvlan120:
        ipv4_address: 192.168.123.123

    # Volumes store your data between container upgrades
    volumes:
      - './dockerFS/pi-hole/etc-pihole/:/etc/pihole/'
      - './dockerFS/pi-hole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
```
this is working for me
