### ISSUE TITLE
Container starts, web error: "[ERROR] File not found: /etc/pihole/setupVars.conf"

### ISSUE THREAD

**Issue by devopsleigh** [pi-hole/docker-pi-hole#827]
This is a: Bug

## Details

The container starts just fine, but the webpage errors with "[ERROR] File not found: /etc/pihole/setupVars.conf".

Within the container, permissions for the setupVars.conf is as follows:
`-rw-rw----+ 1 root   pihole`

Debug:
https://tricorder.pi-hole.net/negtavfdl1

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Raspberry Pi OS
  * Hardware: Raspberry Pi 4
  * Kernel Architecture: ArmV7
  * Docker Install Info and version: 
    - Software source: official docker-ce
    - Supplimentary Software: OpenMediaVault, LetsEncrypt (hence changing port 80 in Pi-Hole)
  * Hardware architecture: ARMv7

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
3.
```
version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "2052:80/tcp"
      - "2053:443/tcp"
    #environment:
    #  - DNS1=127.0.0.1
    #  - DNS2=1.1.1.1
    volumes:
      - ${CONFIG}:/etc/pihole/
      - ${DNSMASQ}:/etc/dnsmasq.d/
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
```
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

I was running P-Hole over a year ago, using a docker local network.
