### ISSUE TITLE
pi.hole and pihole not correctly set to local IP

### ISSUE THREAD

**Issue by tmo1** [pi-hole/docker-pi-hole#829]
Contrary to the documentation, `http://pi.hole/admin` does not work.

Bug

## Details

The documentation states:

> A good way to test things are working right is by loading this page: http://pi.hole/admin/

But this does not actually work properly. In multiple docker pi-hole configurations, `pi.hole` (and `pihole`) are set (in `local.list`) to `0.0.0.0 ` rather than to the local IP address, and so the admin page, while reachable via `ip_address/admin`, is not reachable via `http://pi.hole/admin`, as stated in the documentation.

## Related Issues
- [x ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

https://www.reddit.com/r/pihole/comments/iscg7p/cant_get_httppiholeadmin_to_resolve_on_firefox_or/
https://www.reddit.com/r/pihole/comments/gczq4d/httppiholeadmin_does_not_resolve/
https://old.reddit.com/r/pihole/comments/mq8578/pihole_is_set_to_0000_in_etcpiholelocallist/

## How to reproduce the issue 

1. Environment data
  * Operating System: Debian 
  * Hardware: PC 
  * Kernel Architecture: x86/amd64 
  * Docker Install Info and version: 
    - Software source: official docker-ce 
    - Supplimentary Software: 
  * Hardware architecture: x86 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
version: '3'

networks:
  dns_net:
    driver: bridge
    ipam:
        config:
        - subnet: 172.20.0.0/16

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    networks:
      dns_net:
        ipv4_address: 172.20.0.6
    ports:
    - "192.168.0.9:53:53/tcp"
    - "192.168.0.9:53:53/udp"
    # we can't just do '53:53/tcp' and '53:53/udp' because of libvirt's dnsmasq  
    - "80:80/tcp"
    - "443:443/tcp"
    environment:
    - 'TZ=America/New_York'
    - 'WEBPASSWORD=xxxxxxxx'
    - 'DNS1=172.20.0.7#5053'
    - 'DNS2=no'
    volumes:
    - '/root/docker/dns_net/pihole/etc-pihole/:/etc/pihole/'
    - '/root/docker/dns_net/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
```

3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x ] I have tried removing/destroying my container, and re-creating a new container
- [ x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

 - Adding `'ServerIP=192.168.0.9'` (as per [here](https://old.reddit.com/r/pihole/comments/mq8578/pihole_is_set_to_0000_in_etcpiholelocallist/guh8k33/)) solves the problem, but if this is necessary, it contradicts the documentation's claim that
 > ServerIP no longer a required environment variable unless you run network 'host' mode! Feel free to remove it unless you need it to customize lighttpd
