### ISSUE TITLE
All LAN requests logs have the same Docker IP instead of real IP

### ISSUE THREAD

**Issue by schklom** [pi-hole/docker-pi-hole#854]
This is a: **Run Issue**  

## Details

Yesterday I updated my **Rootless** [Docker](https://docs.docker.com/engine/security/rootless/) to the latest version 20.10.6.

Since then, all my LAN devices (IPs 10.0.0.0/16) register on Docker as Pi-hole's Docker IP address (a random network, but always the same) 192.168.10.1.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

https://github.com/pi-hole/docker-pi-hole/issues/718

## How to reproduce the issue 

1. Environment data
  * Operating System: **Debian 10** 
  * Hardware: RasPi 4B 
  * Kernel Architecture: aarch64 
```
$ uname -srvmpio
Linux 5.10.0-0.bpo.5-arm64 #1 SMP Debian 5.10.24-1~bpo10+1 (2021-03-29) aarch64 unknown unknown GNU/Linux
```
  * Docker Install Info and version: 
    - Software source: [**Rootless** Docker](https://docs.docker.com/engine/security/rootless/) 20.10.6
    - Supplimentary Software: 
  * Hardware architecture: aarch64 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
  pihole:
    image: pihole/pihole
    container_name: pihole
    hostname: pihole
    logging:
      driver: local
      options:
        max-size: 5m
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8888:80/tcp
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      TZ: ${TZ}
      WEBPASSWORD_FILE: /run/secrets/pihole_password
      DNSSEC: "false"
      REV_SERVER: "true"
      REV_SERVER_DOMAIN: home
      REV_SERVER_TARGET: 10.0.0.138
      REV_SERVER_CIDR: 10.0.0.0/24
      DNSMASQ_LISTENING: all
    secrets:
      - pihole_password
    networks:
      pi_unb:
      pi_aut:
        ipv4_address: 192.168.10.5

networks: # There are a lot more, but it would be messy to display
  pi_unb:
    ipam:
      config:
        - subnet: 192.168.13.0/24
  pi_aut:
    ipam:
      config:
        - subnet: 192.168.10.0/24
```
3. any additional info to help reproduce
Pi-hole v5.3.1
Web Interface v5.5
FTL v5.8.1 

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

My `$HOME/.config/docker/daemon.json` contains
```
{
  "storage-driver": "fuse-overlayfs",
  "data-root": "<redacted>/docker_data_root",
  "default-address-pools": [
    {
      "base": "192.168.0.0/16",
      "size": 24
    }
  ]
}
```
if it matters.

Sorry for the long post, I tried to be detailed :P

Many thanks to whoever can help 👍
