### ISSUE TITLE
Lighttpd starts on all available IP addresses despite server.bind configured IP is present

### ISSUE THREAD

**Issue by Slaviusz** [pi-hole/docker-pi-hole#858]
Using docker's `network_mode: host` in combination with environment variable `ServerIP: x.x.x.x` still makes pi-hole docker container to listen on all available IP addresses of the host.

This is a: Bug  

## Details

After starting the container lighttpd starts listening on all interfaces available to the host.
Starting e.g. a netcat on one of the IP/port before starting the container makes lighttpd skip that IP address unless it is the IP address specified by `ServerIP:` env variable.

Starting netcat on IP/port configured by `ServerIP:` env variable makes docker image to produce errors about unable to bind to socket on start.

Example with netcat started on `192.168.255.239:80` but still binding to all local IP addresses on all available interfaces:
```
ss -nptl
State  Recv-Q Send-Q      Local Address:Port Peer Address:PortProcess
LISTEN 0      0               127.0.0.1:80        0.0.0.0:*    users:(("lighttpd",pid=232432,fd=5))
LISTEN 0      0         192.168.255.254:80        0.0.0.0:*    users:(("lighttpd",pid=232432,fd=4))
LISTEN 0      0         192.168.255.239:80        0.0.0.0:*    users:(("nc",pid=224752,fd=3))
LISTEN 0      0                       *:80              *:*    users:(("lighttpd",pid=232432,fd=6))
LISTEN 0      0               127.0.0.1:4711      0.0.0.0:*    users:(("pihole-FTL",pid=232439,fd=12))
LISTEN 0      0               127.0.0.1:53        0.0.0.0:*    users:(("pihole-FTL",pid=232439,fd=7))
LISTEN 0      0         192.168.255.254:53        0.0.0.0:*    users:(("pihole-FTL",pid=232439,fd=5))
LISTEN 0      0                   [::1]:4711            *:*    users:(("pihole-FTL",pid=232439,fd=13))
LISTEN 0      0                   [::1]:53              *:*    users:(("pihole-FTL",pid=232439,fd=9))
```

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Arch 
  * Hardware: PC 
  * Kernel Architecture: 64bit 
  * Docker Install Info and version: 
    - Software source: OS provided package 
    - Supplimentary Software: 
  * Hardware architecture: x86 

docker-compose.yml:
```
version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/Bratislava'
      WEBPASSWORD: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      ServerIP: 192.168.255.254
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
    network_mode: host
```

docker image:
```
docker image ls
REPOSITORY                       TAG                      IMAGE ID       CREATED        SIZE
pihole/pihole                    latest                   257fd58747c5   4 weeks ago    335MB
```

docker info:
```
Server:
 Containers: 5
  Running: 3
  Paused: 0
  Stopped: 2
 Images: 15
 Server Version: 20.10.6
 Storage Driver: btrfs
  Build Version: Btrfs v5.11.1
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 12dca9790f4cb6b18a6a7a027ce420145cb98ee7.m
 runc version: 2c7861bc5e1b3e756392236553ec14a78a09f8bf
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.12.3-155-tkg-cfs
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.57GiB
 Name: server
 ID: F343:FI4U:4TOU:3T5H:NQFD:NGAL:Y4FS:INBY:EKXF:KL4L:CPPP:GENF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/ Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

ip addr:
```
ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp6s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether a8:a1:59:32:0e:f2 brd ff:ff:ff:ff:ff:ff
    inet 192.168.255.239/24 brd 192.168.255.255 scope global enp6s0
       valid_lft forever preferred_lft forever
    inet 192.168.255.254/24 brd 192.168.255.255 scope global secondary enp6s0
       valid_lft forever preferred_lft forever
    inet6 fe80::aaa1:59ff:fe32:ef2/64 scope link
       valid_lft forever preferred_lft forever
```

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by shaderecker** [comment]
This issue is still present on the latest `2021.09` image.

The new REPLY_ADDR4 & REPLY_ADDR4 are not applied globally / to all services:
```
tcp        0      0 192.168.178.10:80       0.0.0.0:*               LISTEN      0          6457364    23139/lighttpd      
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      0          6456664    23145/pihole-FTL    
tcp6       0      0 :::80                   :::*                    LISTEN      0          6457366    23139/lighttpd      
tcp6       0      0 :::53                   :::*                    LISTEN      0          6456666    23145/pihole-FTL    
udp        0      0 0.0.0.0:53              0.0.0.0:*                           0          6456663    23145/pihole-FTL    
udp6       0      0 :::53                   :::*                                0          6456665    23145/pihole-FTL    
```
As you can see the actual ServerIP is only used in the first entry (tcp/ipv4/port 80). For all other things(ipv6/port 80, ipv4/6 port 53 & udp port 53) it is still globally listening to 0.0.0.0/::
Can this behaviour be more consistent so that the listen IPs are limited to the ServerIP/ServerIPv6 addresses.

**Comment by dschaper** [comment]
Are you using IPv6? Do you have IPv6 disabled with the environment variable config flag?

**Comment by dschaper** [comment]
```plain
$ cat docker-compose.yml
version: "3.6"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2021.09
    ports:
      - "192.168.88.20:53:53/tcp"
      - "192.168.88.20:53:53/udp"
      - "192.168.88.20:80:80"
    volumes:
      - "./etc/pihole:/etc/pihole"
      - "./etc/dnsmasq.d:/etc/dnsmasq.d"
    environment:
      - WEBPASSWORD=1234
      - PIHOLE_DNS_=192.168.88.2#5335
      - TZ=America/Los_Angeles
      - DNSSEC=true
      - ServerIP=192.168.88.20
      - IPv6=false
    restart: unless-stopped
```

```bash
$ ss -tlpn | grep 53
LISTEN 0      4096   192.168.88.20:53        0.0.0.0:*

$ ss -tlpn | grep 80
LISTEN 0      4096   192.168.88.20:80        0.0.0.0:*
```

**Comment by shaderecker** [comment]
Yes, I'm using IPv6.
And I also have `network_mode: host`.
Container created with Ansible:
```
- name: Start/Update pihole container
  docker_container:
    name: pihole
    image: "pihole/pihole:2021.09-armhf-buster"
    pull: yes
    restart_policy: unless-stopped
    env:
      TZ: "Europe/Berlin"
      ServerIP: "192.168.178.10"
      ServerIPv6: "fd00::10"
      WEBPASSWORD: "blabla"
      PIHOLE_DNS_: "1.1.1.1;2606:4700:4700::1111"
      DNSMASQ_LISTENING: "local"
    dns_servers:
      - 127.0.0.1
      - "1.1.1.1"
    network_mode: host
    volumes:
      - "/home/{{ ansible_user }}/pihole/pihole/:/etc/pihole/"
      - "/home/{{ ansible_user }}/pihole/dnsmasq.d/:/etc/dnsmasq.d/"
```
