### ISSUE TITLE
PiHole not answering DNS queries

### ISSUE THREAD

**Issue by Slyke** [pi-hole/docker-pi-hole#862]
This is a: Run Issue

## Details
Does not resolve lookups addresses outside of pod.

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar:
https://github.com/pi-hole/pi-hole/issues/4187
https://github.com/k3s-io/k3s/issues/3384

## How to reproduce the issue 
Install MetalLB and use the deployment specified here on K3s: https://github.com/k3s-io/k3s/issues/3384

1. Environment data
  * Operating System: Linux pihole-675d74d56f-b9r5p 5.10.17-v7l+ #1414 SMP Fri Apr 30 13:20:47 BST 2021 armv7l GNU/Linux
  * Hardware: Raspberry Pi 4 (8GB)
  * Kernel Architecture: ArmV7
  * Docker Install Info and version: (Docker is not installed, this is running on K3s)
    - Software source: k3s version v1.20.7+k3s1 (aa768cbd) go version go1.15.12
    - Supplimentary Software: K3s, MetalLB
  * Hardware architecture: ARMv7

2.

pihole-deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole
  namespace: home
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: pihole
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pihole
    spec:
      containers:
      - env:
        - name: ServerIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pihole-webpassword
        image: pihole/pihole:latest
        imagePullPolicy: IfNotPresent
        name: pihole
        ports:
        - containerPort: 80
          name: pihole-http
          protocol: TCP
        - containerPort: 53
          name: pihole-dns-tcp
          protocol: TCP
        - containerPort: 53
          name: pihole-dns-udp
          protocol: UDP
        - containerPort: 443
          name: pihole-ssl
          protocol: TCP
        - containerPort: 67
          name: client-udp
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/pihole
          name: config
        - mountPath: /etc/dnsmasq.d/02-custom.conf
          name: custom-dnsmasq
          subPath: 02-custom.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: pihole-config
      - configMap:
          defaultMode: 420
          name: pihole-custom-dnsmasq
        name: custom-dnsmasq
status: {}
```

MetalLB service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole-tcp
  namespace: home
spec:
  externalTrafficPolicy: Local
  ports:
  - name: pihole-dns-tcp
    protocol: TCP
    port: 53
    targetPort: pihole-dns-tcp
  - name: pihole-http
    protocol: TCP
    port: 80
    targetPort: pihole-http
  selector:
    app: pihole
  loadBalancerIP: 10.7.7.245
  type: LoadBalancer
```

3. any additional info to help reproduce
Dig/netcat on Windows (WSL2)
```
[2021-05-31T21:46:47-0700] [slyke@WSL2] k3s $ dig @10.7.7.245 google.com

; <<>> DiG 9.16.1-Ubuntu <<>> @10.7.7.245 google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

[2021-05-31T21:54:32-0700] [slyke@WSL2] k3s $ while ! nc -w 1 10.7.7.245 53 ; do echo "Attemptign to contact Service"; sleep 1; done; echo "Contacted Service"
Contacted Service
```
nslookup on Windows:
```
C:\Users\Slyke>nslookup google.com 10.7.7.245
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  10.7.7.245

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to UnKnown timed-out
```
Dig from Kubernetes Master:
```
[2021-06-01T05:54:10+0100] [pi@k-m-001] k3s_config $ dig @10.7.7.245 google.com

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Raspbian <<>> @10.7.7.245 google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```
Dig from inside the Pihole Pod:
```
[2021-06-01T03:00:25+0100] [pi@k-m-001] k3s_config $ kubectl exec --stdin --tty pihole-64c4755945-2hlzv -n home -- /bin/bash
root@pihole-64c4755945-2hlzv:/# dig @localhost google.com

; <<>> DiG 9.11.5-P4-5.1+deb10u3-Debian <<>> @localhost google.com
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32906
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             268     IN      A       142.250.217.78

;; Query time: 32 msec
;; SERVER: ::1#53(::1)
;; WHEN: Tue Jun 01 02:01:09 UTC 2021
;; MSG SIZE  rcvd: 55

root@pihole-64c4755945-2hlzv:/# exit
exit
```

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
https://tricorder.pi-hole.net/lngjarlaep
```
*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the eth0 interface:
   10.42.3.25/24 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)
   ...
*** [ DIAGNOSING ]: Setup variables
    INSTALL_WEB_SERVER=true
    INSTALL_WEB_INTERFACE=true
    IPV4_ADDRESS=10.42.3.25
    PIHOLE_INTERFACE=eth0
    QUERY_LOGGING=true
    BLOCKING_ENABLED=true
    DNSMASQ_LISTENING=all
    PIHOLE_DNS_1=8.8.8.8
    PIHOLE_DNS_2=8.8.4.4
    DNS_FQDN_REQUIRED=true
    DNS_BOGUS_PRIV=true
    DNSSEC=false
    REV_SERVER=false
    ADMIN_EMAIL=
    WEBUIBOXEDLAYOUT=boxed
    WEBTHEME=default-darker
```

**Comment by Slyke** [comment]
After like 5 days and endless hunting, I finally found the solution:
For both protocols to work, you need to specify them in different services. On MetalLB each service must have a unique IP address.
This can be fixed by setting the following annotation in both services for PiHole:
```
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
```
UDP Service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole-udp
  namespace: home
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  externalTrafficPolicy: Local
  ports:
  - name: pihole-dns-udp
    protocol: UDP
    port: 53
    targetPort: pihole-dns-udp
  - name: client-udp
    protocol: UDP
    port: 67
    targetPort: client-udp
  selector:
    app: pihole
  loadBalancerIP: 10.7.7.245
  type: LoadBalancer
```
TCP Service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole-tcp
  namespace: home
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  externalTrafficPolicy: Local
  ports:
  - name: pihole-dns-tcp
    protocol: TCP
    port: 53
    targetPort: pihole-dns-tcp
  - name: pihole-http
    protocol: TCP
    port: 80
    targetPort: pihole-http
  - name: pihole-ssl
    protocol: TCP
    port: 443
    targetPort: pihole-ssl
  selector:
    app: pihole
  loadBalancerIP: 10.7.7.245
  type: LoadBalancer
```
