### ISSUE TITLE
Docker Pihole and Unbound not working

### ISSUE THREAD

**Issue by grasuoare** [pi-hole/docker-pi-hole#868]
Hi all,

I have an issue after i have installed unbound after the official guide from https://docs.pi-hole.net/guides/dns/unbound/. Problem is that add blocker is not working anymore and i have issues in connecting to other dockers. I have searched all internet for solutions, related to dhcpd, resolv.conf, etc.

Below you can find the docker compose part of the pihole:
```

  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
#      - '67:67/udp'
      - '8182:80'
      - '8183:443'
    restart: unless-stopped
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.8
    volumes:
      - $DOCKERDIR/pihole/resolv.conf:/etc/resolv.conf:ro
      - $DOCKERDIR/pihole/pihole:/etc/pihole
      - $DOCKERDIR/pihole/dnsmasq.d:/etc/dnsmasq.d
      - $DOCKERDIR/pihole/hosts:/etc/hosts:ro
#    cap_add:
#      - NET_ADMIN
    environment:
      - ServerIP=${SERVER_IP}
      - TZ=${TZ}
      - WEBPASSWORD=$PI_HOLE_PASS
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=pihole.${DOMAINNAME}
      - VIRTUAL_PORT=80
      - DNS1=127.0.0.1#5335
      - DNS2=no
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.pihole-rtr.entrypoints=https"
      - "traefik.http.routers.pihole-rtr.rule=Host(`pihole.$DOMAINNAME`)"
      - "traefik.http.routers.pihole-rtr.tls.certresolver=dns-cloudflare"
      ## Middlewares
      - "traefik.http.routers.pihole-rtr.middlewares=chain-oauth@file" 
      ## HTTP Services
      - "traefik.http.routers.pihole-rtr.service=pihole-svc"
      - "traefik.http.services.pihole-svc.loadbalancer.server.port=80"
```

Could you please help me?

Thanks in advance
