### ISSUE TITLE
With a fresh container/volumes, dashboard is dead if SKIPGRAVITYONBOOT is set

### ISSUE THREAD

**Issue by DistractionRectangle** [pi-hole/docker-pi-hole#878]
This is a: Run Issue

## Details

The Web Interface shows a completely blank dashboard if gravity isn't initialized.
On bringing up a fresh container with empty volumes and `SKIPGRAVITYONBOOT` set, the dashboard fails to show any data. Upon updating gravity under `Tools -> Update Gravity` and navigating back to the dashboard, it becomes populated with data.

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

I have not found an relevant issues in this repo, adminlte, main pihole repository or the forums; though I specifically searched for `SKIPGRAVITYONBOOT` as the keyword since it seems to be at the root of the issue.

## How to reproduce the issue 

1. Environment data
  * Operating System: **Ubuntu 20.04 LTS** 
  * Hardware: PC; AMD 3100, b550m itx
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: 
    - Software source: official docker-ce installed using their instructions
    - Supplimentary Software: NA
  * Hardware architecture: x86/amd64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

<details><summary><b>Erroneous docker-compose.yml</b></summary>
<p>

Command used to test docker-compose.yml changes
`docker-compose down && sudo rm -rf .docker-volumes/ && docker-compose up -d`

```YAML
services:
  pihole:
    cap_add:
    - NET_ADMIN
    environment:
      SKIPGRAVITYONBOOT: '1'
      ServerIP: 192.168.1.14
      WEBPASSWORD: password
    image: pihole/pihole:latest
    ports:
    - mode: host
      protocol: tcp
      published: 8080
      target: 80
    restart: unless-stopped
    volumes:
      - ./.docker-volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d:rw
      - ./.docker-volumes/pihole/etc-pihole:/etc/pihole:rw
version: '3.7'
```

</p>
</details>

3. any additional info to help reproduce

## These common fixes ~~didn't~~ do work for my issue as detailed below. This is an edge case that can only be reached under specific circumstances, and more likely to be reached by new users since they'll have empty//uninitialized volumes.

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [X] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [X] I have tried running without my volume data mounts to eliminate volumes as the cause

This is a minor issue, as manually initializing gravity does fix the issue, or not setting `SKIPGRAVITYONBOOT` on first run with a fresh instance//volume. 

The issue requires both that mounted volumes be empty//uninitialized and `SKIPGRAVITYONBOOT` set. Bringing up a container without persistent volumes but with `SKIPGRAVITYONBOOT` set functions as expected. Bringing up a container with empty persistence volumes but `SKIPGRAVITYONBOOT` not set also functions as intended. See these examples of functional configs that skirt the issue:

<details><summary><b>Working without volumes</b></summary>
<p>

```yaml
services:
  pihole:
    cap_add:
    - NET_ADMIN
    environment:
      SKIPGRAVITYONBOOT: '1'
      ServerIP: 192.168.1.14
      WEBPASSWORD: password
    image: pihole/pihole:latest
    ports:
    - mode: host
      protocol: tcp
      published: 8080
      target: 80
    restart: unless-stopped
#    volumes:
#      - ./.docker-volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d:rw
#      - ./.docker-volumes/pihole/etc-pihole:/etc/pihole:rw
version: '3.7'
```

</p>
</details>

<details><summary><b>Working with out skipping gravity</b></summary>
<p>

```yaml
services:
  pihole:
    cap_add:
    - NET_ADMIN
    environment:
#      SKIPGRAVITYONBOOT: '1'
      ServerIP: 192.168.1.14
      WEBPASSWORD: password
    image: pihole/pihole:latest
    ports:
    - mode: host
      protocol: tcp
      published: 8080
      target: 80
    restart: unless-stopped
    volumes:
      - ./.docker-volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d:rw
      - ./.docker-volumes/pihole/etc-pihole:/etc/pihole:rw
version: '3.7'
```

</p>
</details>

Edit: cut down the reproduction docker-compose files.
