### ISSUE TITLE
REV_SERVER Env variables not passed through

### ISSUE THREAD

**Issue by modem7** [pi-hole/docker-pi-hole#904]
I'm running pihole in an Ubuntu Docker container, and for some reason the REV_SERVER and WEBPASSWORD values are not passed through. 

My docker-compose file:
```
 #Pihole - Network wide adblocker, DNS cache and DHCP server
  pihole:
    image: pihole/pihole:latest
    container_name: Pihole
    hostname: PiHole
    environment:
      INTERFACE: $INTERFACE
      DNSMASQ_LISTENING: $DNSMASQ_LISTENING
      ServerIP: $ServerIP
      DNS1: $PH_DNS1
      DNS2: $PH_DNS2
      VIRTUAL_HOST: $VIRTUAL_HOST
      TZ: $TZ
      SKIPGRAVITYONBOOT: $SKIPGRAVITYONBOOT
      DNSSEC: $DNSSEC
      DNS_BOGUS_PRIV: $DNS_BOGUS_PRIV
      DNS_FQDN_REQUIRED: $DNS_FQDN_REQUIRED
      REV_SERVER: $REV_SERVER
      REV_SERVER_TARGET: $REV_SERVER_TARGET
      REV_SERVER_CIDR: $REV_SERVER_CIDR
      REV_SERVER_DOMAIN: $REV_SERVER_DOMAIN
    cap_add:
      - NET_ADMIN
    networks:
      docker-macvlan:
        ipv4_address: '192.168.0.2'
      pihole:
        ipv4_address: '172.22.0.100'
    dns:
      - "127.0.0.1"
      - "9.9.9.9"
    expose:
      - "53"
      - "67"
      - "80"
      - "443"
    volumes:
      - Pihole:/etc/pihole/
      - Dnsmasq:/etc/dnsmasq.d/
    restart: always
    mem_limit: 500m
    mem_reservation: 250m
```

My .env file:
```
REV_SERVER=true
REV_SERVER=192.168.0.200
REV_SERVER_TARGET=192.168.0.200
REV_SERVER_CIDR=192.168.0.0/16
REV_SERVER_DOMAIN=home.lan
```

In fact, it seems that even if I type in the values manually, they aren't persisting. 

I have tried creating brand new volumes and a new image, but still no go.
