### ISSUE TITLE
WEBTHEME not pickedup using Docker Compose

### ISSUE THREAD

**Issue by johnsoga** [pi-hole/docker-pi-hole#913]
This is a: **Bug**  

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Debian** 
  * Hardware: Intel NUC i7
  * Kernel Architecture: x86/amd64 
  * Docker Install Info and version: 
    - Software source: 
      - Docker version 20.10.8, build 3967b7d
      - docker-compose version 1.26.2, build eefe0d31
    - Supplimentary Software: 
  * Hardware architecture: x86

2.
Docker Compose
```
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    #user: 1000:1000
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "9090:80/tcp"
    environment:
      TZ: "America/NewYork"
      WEBPASSWORD: "test"
      #      ServerIP: "192.168.40.10"
      PIHOLE_DNS_: "1.1.1.1;8.8.8.8"
      DHCP_ACTIVE: "false"
      WEBTHEME: "default-dark"
    volumes:
      - "/apps/pihole/etc-pihole/:/etc/pihole/"
      - "/apps/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    restart: unless-stopped
```

setupVars.conf
```
WEBPASSWORD=7b3d979ca8330a94fa7e9e1b466d8b99e0bcdea1ec90596c0dcc8d7ef6b4300c
BLOCKING_ENABLED=true
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
IPV4_ADDRESS=0.0.0.0
PIHOLE_DNS_1=1.1.1.1
PIHOLE_DNS_2=8.8.8.8
PIHOLE_INTERFACE=eth0
QUERY_LOGGING=true
```

Startup Command
```
docker-compose up -d
```
3. any additional info to help reproduce

Update: tried removing using persistent volumes; did not fix issue
Update: from Release Notes WEBTHEME only added in v5.8.1 which should be tag: latest

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
