### ISSUE TITLE
Last update broke the pi.hole DNS resolution

### ISSUE THREAD

**Issue by schklom** [pi-hole/docker-pi-hole#918]
This is a: Bug

## Details
On my home WiFi (configured to only use Pi-hole's DNS), since the update `pi.hole` doesn't resolve anymore despite being on my DNS records. I didn't add it to a blacklist, and it worked fine before the update. Deleting the DNS record doesn't make `pi.hole` resolve.
```
$ nslookup pi.hole
Server:  one_of_my_subdomains
Address:  10.0.0.3

Name:    pi.hole
Addresses:  ::
          0.0.0.0
```

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

I don't think it's the same issue, but I'm not sure: #910

## How to reproduce the issue 

1. Environment data
  * Operating System: Debian Bullseye
  * Hardware: RasPi 4B
  * Kernel Architecture: arm64
  * Docker Install Info and version: 
    - Software source: official rootless docker 20.10.8
    - Supplimentary Software: pi-hole
  * Hardware architecture: armv7

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
services:
  pihole:
    image: pihole/pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8888:80/tcp
    dns:
      - 127.0.0.1
      - 9.9.9.9
    environment:
      TZ: ${TZ}
      WEBPASSWORD: 1234
      PIHOLE_DNS_: 192.168.13.5#5053
      REV_SERVER: "true"
      REV_SERVER_DOMAIN: home
      REV_SERVER_TARGET: 10.0.0.138
      REV_SERVER_CIDR: 10.0.0.0/24
      DNSMASQ_LISTENING: all
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./pihole/etc-pihole/:/etc/pihole/
      - ./pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    networks:
      pi_unb:
    depends_on:
      - unbound

  unbound:
    image: klutchell/unbound
    networks:
      pi_unb:
        ipv4_address: 192.168.13.5

networks:
  pi_unb:
    ipam:
      config:
        - subnet: 192.168.13.0/24
```
3. any additional info to help reproduce
Switching to DNS server 9.9.9.9 exclusively in the admin page didn't help, so `unbound` isn't the issue.

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

`pi.hole` resolves well when using `image: pihole/pihole:master-stretch`.
