### ISSUE TITLE
How to use HTTPS? Problem running "docker-compose-nginx-proxy.yml" ...

### ISSUE THREAD

**Issue by xanoni** [pi-hole/docker-pi-hole#926]
This is a: Run Issue

## Details

I'm trying to expose the web interface via HTTPS by running "docker-compose-nginx-proxy.yml" instead of the "docker-compose.yml.example".

```bash
$ curl -vk https://127.0.0.1:443
*   Trying 127.0.0.1:443...
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:443
```

Unfortunately that doesn't work, I can only connect to Port 80. Is any extra configuration required beyond what's mentioned in the .yml?

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Bullseye
  * Hardware: RPi4B
  * Kernel Architecture: arm64
  * Docker Install Info and version: 
    - Software source: official docker-ce,
    - Supplimentary Software: 
  * Hardware architecture: arm64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

```bash
docker-compose up -d
```

```yml
version: "3"
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - '80:80'
    environment:
      DEFAULT_HOST: servername.lan
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    restart: always

  pihole:
    image: pihole/pihole:2021.10
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '8053:80/tcp'
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Lisbon'
      WEBPASSWORD: 'xyz'
      ServerIP: 192.168.13.37
      ADMIN_EMAIL: 'foo@bar.com'
      PIHOLE_DOMAIN: 'lan'
      DNSSEC: 'true'
      DHCP_ACTIVE: 'false'
      ServerIPv6: fe80::xxxx:xxxx:xxxx:xxx
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: servername.lan
      VIRTUAL_PORT: 80
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - './var-log/pihole.log:/var/log/pihole.log'
    cap_add:
      - NET_ADMIN
    restart: always
```

3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
