### ISSUE TITLE
DHCP server does not respect ServerIP variable

### ISSUE THREAD

**Issue by jennydaman** [pi-hole/docker-pi-hole#932]
This is a: **Bug.**  

## Details

My router was configured to use 192.168.99.241 as the DHCP relay.

The DHCP server provided by `pihole/pihole:2021.10.1` does not respect the `ServerIP` environment variable. Instead, the DNS server is being set to the IP address of the container inside of the Docker bridge network, which is undefined on the LAN.

Here is my `docker-compose.yml`

```yaml
version: "3.9"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2021.10.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      TZ: 'America/New_York'
      ServerIP: '192.168.99.241'
      VIRTUAL_HOST: 'pi.hole'
    env_file:
      - secrets.env
    volumes:
      - pihole:/etc/pihole/
      - dnsmasq:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - caddy

volumes:
  pihole:
  dnsmasq:

networks:
  caddy:
    external: true
    name: caddy_caddy
```

<details><summary>The `caddy` network is an external bridge network. (click to expand details)</summary>

I am using [Caddy](https://caddyserver.com/docs/) as a reverse-proxy for accessing the pi-hole WebUI at `http://pi.hole/`. `caddy:2.4.5-alpine` is running as a container in the `caddy_caddy` network.

Here is `docker network inspect caddy_caddy`

```json
[
    {
        "Name": "caddy_caddy",
        "Id": "949ffc5171285b3cb7bb3a73bde16dfa11c8c66d11c593cd129ee9551450cdcc",
        "Created": "2021-10-24T13:32:58.113966977-04:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "270872113b16087d5c9f649ad304813a14cc0ab866b7788efe6edf7b38ad537c": {
                "Name": "caddy",
                "EndpointID": "477d710ed03c5f49df056e1a9d4f69e5b277e9f8a652bb518fae5a5e1166eadc",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "4ad1c78ec7adc4c1ad0be3c19c878c02c707df9615cb05792d1cee07d869ae2a": {
                "Name": "ackee-ackee-1",
                "EndpointID": "e6b5ae5be1e4d6ea3577370b82f9f91f2fe424601cec0608dcf03b48a254b72c",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            },
            "d3db5e3834dd96090ac3e6579eb864804793e57b7bfb44cd375abbd34c8d8603": {
                "Name": "pihole",
                "EndpointID": "65b9d2d61979d97ab1bf220b613c0ea10d9f58b7807615b457f11ad2b5ca4d0e",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "caddy",
            "com.docker.compose.project": "caddy",
            "com.docker.compose.version": "2.0.1"
        }
    }
]
```

</details>

Using `docker inspect pihole` I can confirm that the environment variable `ServerIP` is correctly set. Also, here is the excerpt regarding network settings:

```json
"Networks": {
"caddy_caddy": {
  "IPAMConfig": null,
  "Links": null,
  "Aliases": [
    "pihole",
    "pihole",
    "d3db5e3834dd"
  ],
  "NetworkID": "949ffc5171285b3cb7bb3a73bde16dfa11c8c66d11c593cd129ee9551450cdcc",
  "EndpointID": "65b9d2d61979d97ab1bf220b613c0ea10d9f58b7807615b457f11ad2b5ca4d0e",
  "Gateway": "172.18.0.1",
  "IPAddress": "172.18.0.2",
  "IPPrefixLen": 16,
  "IPv6Gateway": "",
  "GlobalIPv6Address": "",
  "GlobalIPv6PrefixLen": 0,
  "MacAddress": "02:42:ac:12:00:02",
  "DriverOpts": null
}
```

I connected a DHCP client (an Android 10 smartphone) and the DHCP server correctly assigns it an IPv4 address, so that much is working. However, the assigned DNS server is `172.18.0.2`. The expected behavior is for the assigned DNS server to be `192.168.99.241`.

## Related Issues

- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

https://github.com/pi-hole/docker-pi-hole/issues/871

## How to reproduce the issue 

1. Environment data

Host information doesn't matter but here it is anyways.

  * Operating System: Arch Linux
  * Hardware: PC
  * Kernel Architecture: amd64
  * Docker Install Info and version: Docker version 20.10.9, build c2ea9bc90b
    - Software source: OS provided package
    - Supplimentary Software: N/A
  * Hardware architecture: x86_64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

A minimal `docker-compose.yml` is provided below.

```yaml
version: "3.9"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2021.10.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      ServerIP: '192.168.99.241'
      WEBPASSWORD: 'mypassword'
    cap_add:
      - NET_ADMIN
    networks:
      - my_network

networks:
  my_network:
```

3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

(I didn't try most of the common fixes, this particular pihole instance is brand new, and it is evident that the DHCP server works correctly.)
