### ISSUE TITLE
Crashing on Raspberry Pi 3B+

### ISSUE THREAD

**Issue by LoSunny** [pi-hole/docker-pi-hole#935]
After running the container for some hours, I won't be able to SSH or view the screen of the pi. Everything is dead and I need to unplug the power and power the pi back on in order to get access to the pi.

This is a: Bug

## Details

Here are the logs for pi-hole and syslog: https://gofile.io/d/NuNe0d
The crash happens around 22.00 to 24.00

## Related Issues
- [*] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

But sadly none

## How to reproduce the issue 

1. Environment data
  * Operating System: Rasbian 
  * Hardware: 3B+
  * Kernel Architecture: ArmV7 32bit
  * Docker Install Info and version: 
    - Software source: official docker-ce
    - Supplimentary Software: NIL
  * Hardware architecture: ARMv7

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "30000:80/tcp"
      - "30001:443/tcp"
    environment:
      TZ: 'Asia/Hong_Kong'
      WEBPASSWORD: '2January2003'
      VIRTUAL_HOST: 'pihole.sunnylo.tk'
      DNS1: '172.18.0.3#5054'
    volumes:
      - '/home/pi/Documents/pi-hole/pihole/pihole/:/etc/pihole/'
      - '/home/pi/Documents/pi-hole/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      pihole:
        ipv4_address: 172.18.0.2

  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:alpine-3.12
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      pihole:
        ipv4_address: 172.18.0.3

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Hong_Kong
      - SERVERURL=wireguard.sunnylo.tk
      - SERVERPORT=51820
      - PEERS=SunnyiPhone,SunnyiPad,SunnyMBA,SamiPhone,SamWin
      - PEERDNS=172.18.0.2
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - /home/pi/Documents/pi-hole/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      pihole:
        ipv4_address: 172.18.0.4

networks:
  pihole:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
```

## These common fixes didn't work for my issue

- [*] I have tried removing/destroying my container, and re-creating a new container
- [*] I have tried fresh volume data by backing up and moving/removing the old volume data
- [*] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [*] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
