### ISSUE TITLE
DNSMASQ missing cap NET_ADMIN, even though it's added in the config

### ISSUE THREAD

**Issue by RonaldPhilipsen** [pi-hole/docker-pi-hole#938]
This is a:  Run Issue

## Details

Running the pihole/pihole:latest container with the DHCP-server enabled fails on a docker swarm host. dnsmasq complains that the capability NET_ADMIN is missing even though this is explicitly configured in the docker compose file. 
The container is added to a macvlan network.
Changing setupVars.conf to disable DHCP will allow the container to run

## Related Issues
- [* ] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

https://github.com/pi-hole/docker-pi-hole/issues/814
https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
https://www.reddit.com/r/pihole/comments/adlu8n/pihole_docker_wont_survive_container_restart/
https://discourse.pi-hole.net/t/net-admin-in-docker-swarm/19488

## How to reproduce the issue 

1. Environment data
  * Operating System: RHEL7 
  * Hardware:  PC 
  * Kernel Architecture:   x86/amd64 
  * Docker Install Info and version: 
    - Software source: official docker-ce 
    - Supplimentary Software: portainer 
  * Hardware architecture: x86-64 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    cap_add:
      - NET_ADMIN

    networks:
      swarm-vlan_net:
        ipv4_address: 10.2.0.2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/containers/pihole/resolv.conf:/etc/resolv.conf
      - /storage/containers/pihole/configs/pihole:/etc/pihole/
      - /storage/containers/pihole/configs/dnsmasq.d:/etc/dnsmasq.d/
    ports:
      - 53:53/tcp
      - 67:67/udp
      - 53:53/udp
    expose:
       - 80
    environment:
      - ServerIP= 10.2.0.2
      - HOST_IP=10.2.0.2
      - VIRTUAL_HOST= pihole.domain.tld
      - TZ= Europe/amsterdam
      - WEBPASSWORD= some_web_password
      - FTL_CMD=debug
      - DNSMASQ_LISTENING=all

    restart: unless-stopped
networks:
  swarm-vlan_net:
    external: true
```

## These common fixes didn't work for my issue

 - [*] I have tried removing/destroying my container, and re-creating a new container
 - [*] I have tried fresh volume data by backing up and moving/removing the old volume data
 - [*] I have tried running the stock docker run example(s) in the readme (removing any customizations I added)
 - [*]  I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
 - [*] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!

  [i] Installing /etc/dnsmasq.d/01-pihole.conf...
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf

  [i] Installing /etc/.pihole/advanced/06-rfc6761.conf...
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf

Existing DNS servers detected in setupVars.conf. Leaving them alone
::: Pre existing WEBPASSWORD found
DNSMasq binding to default interface: eth0

Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => " 10.2.0.2",
			"CORS_HOSTS" => "",
			"VIRTUAL_HOST" => " pihole.domain.tld",

Using IPv4 and IPv6
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
dnsmasq: process is missing required capability NET_ADMIN
::: Testing pihole-FTL DNS: [cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
