### ISSUE TITLE
Can't use blacklist with docker (compose)

### ISSUE THREAD

**Issue by tamis-laan** [pi-hole/docker-pi-hole#943]
Given the following docker compose file and the latest version of pihole docker container:

``` yml
  # Add blocker
  pihole:
    image: pihole/pihole:latest
    environment:
      WEBPASSWORD: pihole
      QUERY_LOGGING: 1
      PIHOLE_DNS_: 208.67.222.222;208.67.220.220;1.1.1.1
      DNSSEC: 1
      TZ: Europe/Amsterdam
    volumes:
      - ./data/pihole/data:/etc/pihole/
      - ./data/pihole/dnsmasq:/etc/dnsmasq.d/
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '3005:80/tcp' # Web interface
    networks:
      - private
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '2'
```

when adding a domain to the blacklist I get the following error:
![screenshot](https://user-images.githubusercontent.com/3178666/142410687-cbe7dd8b-2654-4707-8a4f-1e659c2de512.png)
It looks like a permission problem, do I need to set a GID and UID in my docker compose file?
