### ISSUE TITLE
Can't add domain to whitelist from blockpage (missing add.php)

### ISSUE THREAD

**Issue by alpe12** [pi-hole/docker-pi-hole#950]
This is a: Bug

## Details
/pihole/index.php blockpage (accessing via a blocked domain) has a button to add the blocked domain to whitelist.
But that button points to "/admin/scripts/pi-hole/php/add.php" which doesn't exist.
```
$ sudo docker exec -it pihole ls /var/www/html/admin/scripts/pi-hole/php/
FTL.php          debug.php       header.php     savesettings.php
api_token.php    footer.php      loginpage.php  tailLog.php
auth.php         func.php        message.php    teleporter.php
customcname.php  gravity.php     network.php    theme.php
customdns.php    gravity.sh.php  password.php   update_checker.php
database.php     groups.php      queryads.php
```

## How to reproduce the issue 

1. Environment data
  * Operating System: **Ubuntu** 
  * Hardware: Odroid N2
  * Kernel Architecture: ArmV8 64bit
  * Docker Install Info and version: 
    - Software source: OS provided package
  * Hardware architecture: ArmV8 64bit

2. 
```
version: "3.3"

services:
  dnscrypt:
    container_name: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy:latest
    networks:
      network:
        ipv4_address: 10.58.32.2
    expose:
      - "5300/udp"
      - "5300/tcp"
    environment:
      TZ: 'America/Sao_Paulo'
    volumes:
      - './etc-dnscrypt-proxy:/config'
    dns:
      - 1.1.1.1
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      network:
        ipv4_address: 10.58.32.3
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "9984:80/tcp"
      #- "443:443/tcp"
    environment:
      TZ: 'America/Sao_Paulo'
      PIHOLE_DNS_: '10.58.32.2#5300'
      ServerIP: 192.168.1.250
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 1.1.1.1
    restart: unless-stopped
    depends_on:
      - dnscrypt

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.58.32.0/24  
```
3. Access any page that is blocked by pihole
4. Click on 'Technical Info'. Fill password. Click 'Whitelist'. It says it succeeded but it didn't. The POST request is made to '/admin/scripts/pi-hole/php/add.php'. But 'add.php' don't exist. So it returns another blockpage.
