### ISSUE TITLE
[macOS] Disk shortage bug

### ISSUE THREAD

**Issue by VicSegers** [pi-hole/docker-pi-hole#951]
This is a: Bug 

## Details

When updating to "Pi-hole FTL v5.12, Web v5.9 and Core v5.7" I received this message after running:

<img width="976" alt="pi-hole disk shortage bug" src="https://user-images.githubusercontent.com/32434088/147159492-a76fd035-9614-4312-acf4-506f5a6de2ce.png">

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: macOS 12.1
  * Hardware: MacBook Pro (2016)
  * Kernel Architecture: Darwin 21.2.0
  * Docker Install Info and version: 
    - Software source: Homebrew
    - Supplimentary Software: /
  * Hardware architecture: x86_64

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

docker-compose.yml
```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Belgium/Brussels'
      WEBPASSWORD: 'foo'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

3. any additional info to help reproduce

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
