### ISSUE TITLE
Restart loop after deleting image/container

### ISSUE THREAD

**Issue by SuperMike3003** [pi-hole/docker-pi-hole#989]
I was successfully running Pihole in Docker Desktop in Windows (Thanks, BTW!) using the following command:

```
docker run --name pihole --restart=unless-stopped -p 53:53/udp -p53:53/tcp -p 67:67/udp -p 80:80/tcp -p 443:443
-e TZ=America/New_York -e dns1=1.1.1.1 -e dns2=8.8.8.8 -e DOCKER_PIHOLE_TAG=latest -e SERVERIP=[local machine ip]
-e  admin_email=[my email] -e WEBPASSWORD=[my password]
-v "f:/Containers/pihole:/etc/pihole" -v "f:/Containers/pihole:/etc/dnsmasq.d" -d pihole/pihole:latest
```

Recently I started re-tagging images instead of running latest, so I could test any new image before deploying it.
No problem there- until I stopped the container to format the drive which had the volumes in the command above mounted and tried to restart it.
Now any time I try to start the container, it goes into a restart loop.
I suspect it has something to do with the PIHOLE_DOCKER_TAG env persisting no matter what I do.
Here's what I get echod out:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 1.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole
  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf.
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf.conf...
Configuring default DNS servers: 8.8.8.8, 8.8.4.4
  [✓] New password set
DNSMasq binding to default interface: eth0
Added ENV to php:
"PIHOLE_DOCKER_TAG" => "2022.01.1",
"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
"ServerIP" => "0.0.0.0",
"CORS_HOSTS" => "",
"VIRTUAL_HOST" => "0.0.0.0",
Using IPv4 and IPv6
::: setup_blocklists now setting default blocklists up: 
::: TIP: Use a docker volume for /etc/pihole/adlists.list if you want to customize for first boot
::: Blocklists (/etc/pihole/adlists.list) now set to:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
chmod: cannot access '/etc/pihole/pihole-FTL.db': No such file or directory
dnsmasq: bad option at line 1 of /etc/dnsmasq.d/adlists.list
::: Testing pihole-FTL DNS: [cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Steps tried thus far:
-deleted the container and image
-tried using the v5.8.1 tag
-deleted the persistent storage I mounted
-searched all the config files I could find for a reference to that env value (none found)
-uninstalled docker desktop, removed all related directories and registry keys and reinstalled.

**Comment by PromoFaux** [comment]
`-e DOCKER_PIHOLE_TAG=latest`

This one isn't really supposed to be set by the user - it's there so the internal Pi-hole components know they're running in the Docker environment (i.e, the web interface will display it alongside the versions of the other components) So, changing it wont actually _do_ anything.. as far as I know!

`-v "f:/Containers/pihole:/etc/pihole" -v "f:/Containers/pihole:/etc/dnsmasq.d"`

These should really be distinct on the host side of things e.g `f:/containers/pihole/etc-pihole:/etc/pihole` and `f:/containers/pihole/etc-dnsmasq.d:/etc/dnsmasq.d`

Personally I find the docker compose syntax a lot easier to read and understand than docker run... e.g in `F:\containers\pihole\` you could create a `docker-compose.yml` with the following contents:

```yml
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'America/New_York'
      PIHOLE_DNS_: '1.1.1.1;8.8.8.8'
      WEBPASSWORD: 'set a secure password here or it will be random'
      SERVERIP: '[local machine ip]'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'    
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
    restart: unless-stopped
```

And then start it by  navigating to that directory in powershell and `docker-compose up -d`

I've just tried the above on my own Windows 11 PC and it starts/boots fine!
